classes: {
  
  
  Calendar: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Icons set 4/Time/Calendar.svg
        shape: image
        label: "Calendar"
      }
  
  
  Hourglass 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Icons set 4/Time/Hourglass 2.svg
        shape: image
        label: "Hourglass 2"
      }
  
  
  Hourglass: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Icons set 4/Time/Hourglass.svg
        shape: image
        label: "Hourglass"
      }
  
  
  Time 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Icons set 4/Time/Time 1.svg
        shape: image
        label: "Time 1"
      }
  
  
  Time 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Icons set 4/Time/Time 2.svg
        shape: image
        label: "Time 2"
      }
  
}