classes: {
  
  
  Automated check: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Automated Check.svg
        shape: image
        label: "Automated check"
      }
  
  
  Bot assistant: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Bot Assistant.svg
        shape: image
        label: "Bot assistant"
      }
  
  
  Calendar: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Calendar.svg
        shape: image
        label: "Calendar"
      }
  
  
  Certification: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Certification.svg
        shape: image
        label: "Certification"
      }
  
  
  Check 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Check 2.svg
        shape: image
        label: "Check 2"
      }
  
  
  Check list: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Check List.svg
        shape: image
        label: "Check list"
      }
  
  
  Check: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Check.svg
        shape: image
        label: "Check"
      }
  
  
  Connector: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Connector.svg
        shape: image
        label: "Connector"
      }
  
  
  Data processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Data Processing.svg
        shape: image
        label: "Data processing"
      }
  
  
  Process flow: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Process flow.svg
        shape: image
        label: "Process flow"
      }
  
  
  Processing 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Processing 1.svg
        shape: image
        label: "Processing 1"
      }
  
  
  Schedule 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Schedule 2.svg
        shape: image
        label: "Schedule 2"
      }
  
  
  Schedule: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Schedule.svg
        shape: image
        label: "Schedule"
      }
  
  
  Transformation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Other/Transformation.svg
        shape: image
        label: "Transformation"
      }
  
}