classes: {
  
  icon_service_Azure_Cosmos_DB: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Cosmos_DB.svg
        shape: image
        label: "icon_service_Azure_Cosmos_DB"
      }
  
  icon_service_Azure_Database_MariaDB_Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Database_MariaDB_Server.svg
        shape: image
        label: "icon_service_Azure_Database_MariaDB_Server"
      }
  
  icon_service_Azure_Database_Migration_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Database_Migration_Services.svg
        shape: image
        label: "icon_service_Azure_Database_Migration_Services"
      }
  
  icon_service_Azure_Database_MySQL_Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Database_MySQL_Server.svg
        shape: image
        label: "icon_service_Azure_Database_MySQL_Server"
      }
  
  icon_service_Azure_Database_PostgreSQL_Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Database_PostgreSQL_Server.svg
        shape: image
        label: "icon_service_Azure_Database_PostgreSQL_Server"
      }
  
  icon_service_Azure_Database_PostgreSQL_Server_Group: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Database_PostgreSQL_Server_Group.svg
        shape: image
        label: "icon_service_Azure_Database_PostgreSQL_Server_Group"
      }
  
  icon_service_Azure_Data_Explorer_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Data_Explorer_Clusters.svg
        shape: image
        label: "icon_service_Azure_Data_Explorer_Clusters"
      }
  
  icon_service_Azure_Purview_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Purview_Accounts.svg
        shape: image
        label: "icon_service_Azure_Purview_Accounts"
      }
  
  icon_service_Azure_SQL: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_SQL.svg
        shape: image
        label: "icon_service_Azure_SQL"
      }
  
  icon_service_Azure_SQL_Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_SQL_Edge.svg
        shape: image
        label: "icon_service_Azure_SQL_Edge"
      }
  
  icon_service_Azure_SQL_Server_Stretch_Databases: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_SQL_Server_Stretch_Databases.svg
        shape: image
        label: "icon_service_Azure_SQL_Server_Stretch_Databases"
      }
  
  icon_service_Azure_SQL_VM: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_SQL_VM.svg
        shape: image
        label: "icon_service_Azure_SQL_VM"
      }
  
  icon_service_Azure_Synapse_Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Azure_Synapse_Analytics.svg
        shape: image
        label: "icon_service_Azure_Synapse_Analytics"
      }
  
  icon_service_Cache_Redis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Cache_Redis.svg
        shape: image
        label: "icon_service_Cache_Redis"
      }
  
  icon_service_Data_Factories: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Data_Factories.svg
        shape: image
        label: "icon_service_Data_Factories"
      }
  
  icon_service_Elastic_Job_Agents: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Elastic_Job_Agents.svg
        shape: image
        label: "icon_service_Elastic_Job_Agents"
      }
  
  icon_service_Instance_Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Instance_Pools.svg
        shape: image
        label: "icon_service_Instance_Pools"
      }
  
  icon_service_Managed_Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Managed_Database.svg
        shape: image
        label: "icon_service_Managed_Database"
      }
  
  icon_service_SQL_Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SQL_Database.svg
        shape: image
        label: "icon_service_SQL_Database"
      }
  
  icon_service_SQL_Data_Warehouses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SQL_Data_Warehouses.svg
        shape: image
        label: "icon_service_SQL_Data_Warehouses"
      }
  
  icon_service_SQL_Elastic_Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SQL_Elastic_Pools.svg
        shape: image
        label: "icon_service_SQL_Elastic_Pools"
      }
  
  icon_service_SQL_Managed_Instance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SQL_Managed_Instance.svg
        shape: image
        label: "icon_service_SQL_Managed_Instance"
      }
  
  icon_service_SQL_Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SQL_Server.svg
        shape: image
        label: "icon_service_SQL_Server"
      }
  
  icon_service_SQL_Server_Registries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SQL_Server_Registries.svg
        shape: image
        label: "icon_service_SQL_Server_Registries"
      }
  
  icon_service_SSIS_Lift_And_Shift_IR: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_SSIS_Lift_And_Shift_IR.svg
        shape: image
        label: "icon_service_SSIS_Lift_And_Shift_IR"
      }
  
  icon_service_Virtual_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/icon_service_Virtual_Clusters.svg
        shape: image
        label: "icon_service_Virtual_Clusters"
      }
  
}