classes: {
  
  
  Azure Cosmos Db: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Cosmos_DB.svg
        shape: image
        label: "Azure Cosmos Db"
      }
  
  
  Azure Database Mariadb Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Database_MariaDB_Server.svg
        shape: image
        label: "Azure Database Mariadb Server"
      }
  
  
  Azure Database Migration Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Database_Migration_Services.svg
        shape: image
        label: "Azure Database Migration Services"
      }
  
  
  Azure Database Mysql Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Database_MySQL_Server.svg
        shape: image
        label: "Azure Database Mysql Server"
      }
  
  
  Azure Database Postgresql Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Database_PostgreSQL_Server.svg
        shape: image
        label: "Azure Database Postgresql Server"
      }
  
  
  Azure Database Postgresql Server Group: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Database_PostgreSQL_Server_Group.svg
        shape: image
        label: "Azure Database Postgresql Server Group"
      }
  
  
  Azure Data Explorer Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Data_Explorer_Clusters.svg
        shape: image
        label: "Azure Data Explorer Clusters"
      }
  
  
  Azure Purview Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Purview_Accounts.svg
        shape: image
        label: "Azure Purview Accounts"
      }
  
  
  Azure Sql: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_SQL.svg
        shape: image
        label: "Azure Sql"
      }
  
  
  Azure Sql Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_SQL_Edge.svg
        shape: image
        label: "Azure Sql Edge"
      }
  
  
  Azure Sql Server Stretch Databases: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_SQL_Server_Stretch_Databases.svg
        shape: image
        label: "Azure Sql Server Stretch Databases"
      }
  
  
  Azure Sql Vm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_SQL_VM.svg
        shape: image
        label: "Azure Sql Vm"
      }
  
  
  Azure Synapse Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Azure_Synapse_Analytics.svg
        shape: image
        label: "Azure Synapse Analytics"
      }
  
  
  Cache Redis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Cache_Redis.svg
        shape: image
        label: "Cache Redis"
      }
  
  
  Data Factories: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Data_Factories.svg
        shape: image
        label: "Data Factories"
      }
  
  
  Elastic Job Agents: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Elastic_Job_Agents.svg
        shape: image
        label: "Elastic Job Agents"
      }
  
  
  Instance Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Instance_Pools.svg
        shape: image
        label: "Instance Pools"
      }
  
  
  Managed Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Managed_Database.svg
        shape: image
        label: "Managed Database"
      }
  
  
  Sql Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SQL_Database.svg
        shape: image
        label: "Sql Database"
      }
  
  
  Sql Data Warehouses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SQL_Data_Warehouses.svg
        shape: image
        label: "Sql Data Warehouses"
      }
  
  
  Sql Elastic Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SQL_Elastic_Pools.svg
        shape: image
        label: "Sql Elastic Pools"
      }
  
  
  Sql Managed Instance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SQL_Managed_Instance.svg
        shape: image
        label: "Sql Managed Instance"
      }
  
  
  Sql Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SQL_Server.svg
        shape: image
        label: "Sql Server"
      }
  
  
  Sql Server Registries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SQL_Server_Registries.svg
        shape: image
        label: "Sql Server Registries"
      }
  
  
  Ssis Lift And Shift Ir: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/SSIS_Lift_And_Shift_IR.svg
        shape: image
        label: "Ssis Lift And Shift Ir"
      }
  
  
  Virtual Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/databases/Virtual_Clusters.svg
        shape: image
        label: "Virtual Clusters"
      }
  
}