classes: {
  
  
  Ecology 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Green Energy/Ecology 2.svg
        shape: image
        label: "Ecology 2"
      }
  
  
  Ecology: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Green Energy/Ecology.svg
        shape: image
        label: "Ecology"
      }
  
  
  Energy: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Green Energy/Energy.svg
        shape: image
        label: "Energy"
      }
  
  
  Forest: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Green Energy/Forest.svg
        shape: image
        label: "Forest"
      }
  
  
  Sun energy: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Green Energy/Sun Energy.svg
        shape: image
        label: "Sun energy"
      }
  
  
  Water: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Green Energy/Water.svg
        shape: image
        label: "Water"
      }
  
}