classes: {
  
  icon_service_API_Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_API_Connections.svg
        shape: image
        label: "icon_service_API_Connections"
      }
  
  icon_service_API_Management_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_API_Management_Services.svg
        shape: image
        label: "icon_service_API_Management_Services"
      }
  
  icon_service_App_Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_App_Configuration.svg
        shape: image
        label: "icon_service_App_Configuration"
      }
  
  icon_service_Azure_API_for_FHIR: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Azure_API_for_FHIR.svg
        shape: image
        label: "icon_service_Azure_API_for_FHIR"
      }
  
  icon_service_Azure_Databox_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Azure_Databox_Gateway.svg
        shape: image
        label: "icon_service_Azure_Databox_Gateway"
      }
  
  icon_service_Azure_Data_Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Azure_Data_Catalog.svg
        shape: image
        label: "icon_service_Azure_Data_Catalog"
      }
  
  icon_service_Azure_Service_Bus: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Azure_Service_Bus.svg
        shape: image
        label: "icon_service_Azure_Service_Bus"
      }
  
  icon_service_Azure_SQL_Server_Stretch_Databases: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Azure_SQL_Server_Stretch_Databases.svg
        shape: image
        label: "icon_service_Azure_SQL_Server_Stretch_Databases"
      }
  
  icon_service_Azure_Stack_Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Azure_Stack_Edge.svg
        shape: image
        label: "icon_service_Azure_Stack_Edge"
      }
  
  icon_service_Data_Factories: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Data_Factories.svg
        shape: image
        label: "icon_service_Data_Factories"
      }
  
  icon_service_Event_Grid_Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Event_Grid_Domains.svg
        shape: image
        label: "icon_service_Event_Grid_Domains"
      }
  
  icon_service_Event_Grid_Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Event_Grid_Subscriptions.svg
        shape: image
        label: "icon_service_Event_Grid_Subscriptions"
      }
  
  icon_service_Event_Grid_Topics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Event_Grid_Topics.svg
        shape: image
        label: "icon_service_Event_Grid_Topics"
      }
  
  icon_service_Integration_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Integration_Accounts.svg
        shape: image
        label: "icon_service_Integration_Accounts"
      }
  
  icon_service_Integration_Service_Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Integration_Service_Environments.svg
        shape: image
        label: "icon_service_Integration_Service_Environments"
      }
  
  icon_service_Logic_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Logic_Apps.svg
        shape: image
        label: "icon_service_Logic_Apps"
      }
  
  icon_service_Logic_Apps_Custom_Connector: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Logic_Apps_Custom_Connector.svg
        shape: image
        label: "icon_service_Logic_Apps_Custom_Connector"
      }
  
  icon_service_Partner_Namespace: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Partner_Namespace.svg
        shape: image
        label: "icon_service_Partner_Namespace"
      }
  
  icon_service_Partner_Registration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Partner_Registration.svg
        shape: image
        label: "icon_service_Partner_Registration"
      }
  
  icon_service_Partner_Topic: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Partner_Topic.svg
        shape: image
        label: "icon_service_Partner_Topic"
      }
  
  icon_service_Power_Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Power_Platform.svg
        shape: image
        label: "icon_service_Power_Platform"
      }
  
  icon_service_Relays: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Relays.svg
        shape: image
        label: "icon_service_Relays"
      }
  
  icon_service_SendGrid_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_SendGrid_Accounts.svg
        shape: image
        label: "icon_service_SendGrid_Accounts"
      }
  
  icon_service_Software_as_a_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_Software_as_a_Service.svg
        shape: image
        label: "icon_service_Software_as_a_Service"
      }
  
  icon_service_SQL_Data_Warehouses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_SQL_Data_Warehouses.svg
        shape: image
        label: "icon_service_SQL_Data_Warehouses"
      }
  
  icon_service_StorSimple_Device_Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_StorSimple_Device_Managers.svg
        shape: image
        label: "icon_service_StorSimple_Device_Managers"
      }
  
  icon_service_System_Topic: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/icon_service_System_Topic.svg
        shape: image
        label: "icon_service_System_Topic"
      }
  
}