classes: {
  
  
  Api Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/API_Connections.svg
        shape: image
        label: "Api Connections"
      }
  
  
  Api Management Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/API_Management_Services.svg
        shape: image
        label: "Api Management Services"
      }
  
  
  App Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/App_Configuration.svg
        shape: image
        label: "App Configuration"
      }
  
  
  Azure Api For Fhir: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Azure_API_for_FHIR.svg
        shape: image
        label: "Azure Api For Fhir"
      }
  
  
  Azure Databox Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Azure_Databox_Gateway.svg
        shape: image
        label: "Azure Databox Gateway"
      }
  
  
  Azure Data Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Azure_Data_Catalog.svg
        shape: image
        label: "Azure Data Catalog"
      }
  
  
  Azure Service Bus: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Azure_Service_Bus.svg
        shape: image
        label: "Azure Service Bus"
      }
  
  
  Azure Sql Server Stretch Databases: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Azure_SQL_Server_Stretch_Databases.svg
        shape: image
        label: "Azure Sql Server Stretch Databases"
      }
  
  
  Azure Stack Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Azure_Stack_Edge.svg
        shape: image
        label: "Azure Stack Edge"
      }
  
  
  Data Factories: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Data_Factories.svg
        shape: image
        label: "Data Factories"
      }
  
  
  Event Grid Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Event_Grid_Domains.svg
        shape: image
        label: "Event Grid Domains"
      }
  
  
  Event Grid Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Event_Grid_Subscriptions.svg
        shape: image
        label: "Event Grid Subscriptions"
      }
  
  
  Event Grid Topics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Event_Grid_Topics.svg
        shape: image
        label: "Event Grid Topics"
      }
  
  
  Integration Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Integration_Accounts.svg
        shape: image
        label: "Integration Accounts"
      }
  
  
  Integration Service Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Integration_Service_Environments.svg
        shape: image
        label: "Integration Service Environments"
      }
  
  
  Logic Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Logic_Apps.svg
        shape: image
        label: "Logic Apps"
      }
  
  
  Logic Apps Custom Connector: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Logic_Apps_Custom_Connector.svg
        shape: image
        label: "Logic Apps Custom Connector"
      }
  
  
  Partner Namespace: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Partner_Namespace.svg
        shape: image
        label: "Partner Namespace"
      }
  
  
  Partner Registration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Partner_Registration.svg
        shape: image
        label: "Partner Registration"
      }
  
  
  Partner Topic: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Partner_Topic.svg
        shape: image
        label: "Partner Topic"
      }
  
  
  Power Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Power_Platform.svg
        shape: image
        label: "Power Platform"
      }
  
  
  Relays: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Relays.svg
        shape: image
        label: "Relays"
      }
  
  
  Sendgrid Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/SendGrid_Accounts.svg
        shape: image
        label: "Sendgrid Accounts"
      }
  
  
  Software As A Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/Software_as_a_Service.svg
        shape: image
        label: "Software As A Service"
      }
  
  
  Sql Data Warehouses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/SQL_Data_Warehouses.svg
        shape: image
        label: "Sql Data Warehouses"
      }
  
  
  Storsimple Device Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/StorSimple_Device_Managers.svg
        shape: image
        label: "Storsimple Device Managers"
      }
  
  
  System Topic: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/integration/System_Topic.svg
        shape: image
        label: "System Topic"
      }
  
}