classes: {
  
  
  Api Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/API_Connections.svg
        shape: image
        label: "Api Connections"
      }
  
  
  Api Management Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/API_Management_Services.svg
        shape: image
        label: "Api Management Services"
      }
  
  
  App Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/App_Services.svg
        shape: image
        label: "App Services"
      }
  
  
  App Service Certificates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/App_Service_Certificates.svg
        shape: image
        label: "App Service Certificates"
      }
  
  
  App Service Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/App_Service_Domains.svg
        shape: image
        label: "App Service Domains"
      }
  
  
  App Service Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/App_Service_Environments.svg
        shape: image
        label: "App Service Environments"
      }
  
  
  App Service Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/App_Service_Plans.svg
        shape: image
        label: "App Service Plans"
      }
  
  
  Azure Media Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Azure_Media_Service.svg
        shape: image
        label: "Azure Media Service"
      }
  
  
  Azure Spring Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Azure_Spring_Apps.svg
        shape: image
        label: "Azure Spring Apps"
      }
  
  
  Cognitive Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Cognitive_Search.svg
        shape: image
        label: "Cognitive Search"
      }
  
  
  Cognitive Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Cognitive_Services.svg
        shape: image
        label: "Cognitive Services"
      }
  
  
  Front Door And Cdn Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Front_Door_and_CDN_Profiles.svg
        shape: image
        label: "Front Door And Cdn Profiles"
      }
  
  
  Notification Hub Namespaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Notification_Hub_Namespaces.svg
        shape: image
        label: "Notification Hub Namespaces"
      }
  
  
  Power Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Power_Platform.svg
        shape: image
        label: "Power Platform"
      }
  
  
  Signalr: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/SignalR.svg
        shape: image
        label: "Signalr"
      }
  
  
  Static Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/Static_Apps.svg
        shape: image
        label: "Static Apps"
      }
  
}