classes: {
  
  icon_service_API_Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_API_Connections.svg
        shape: image
        label: "icon_service_API_Connections"
      }
  
  icon_service_API_Management_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_API_Management_Services.svg
        shape: image
        label: "icon_service_API_Management_Services"
      }
  
  icon_service_App_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_App_Services.svg
        shape: image
        label: "icon_service_App_Services"
      }
  
  icon_service_App_Service_Certificates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_App_Service_Certificates.svg
        shape: image
        label: "icon_service_App_Service_Certificates"
      }
  
  icon_service_App_Service_Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_App_Service_Domains.svg
        shape: image
        label: "icon_service_App_Service_Domains"
      }
  
  icon_service_App_Service_Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_App_Service_Environments.svg
        shape: image
        label: "icon_service_App_Service_Environments"
      }
  
  icon_service_App_Service_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_App_Service_Plans.svg
        shape: image
        label: "icon_service_App_Service_Plans"
      }
  
  icon_service_Azure_Media_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Azure_Media_Service.svg
        shape: image
        label: "icon_service_Azure_Media_Service"
      }
  
  icon_service_Azure_Spring_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Azure_Spring_Apps.svg
        shape: image
        label: "icon_service_Azure_Spring_Apps"
      }
  
  icon_service_Cognitive_Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Cognitive_Search.svg
        shape: image
        label: "icon_service_Cognitive_Search"
      }
  
  icon_service_Cognitive_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Cognitive_Services.svg
        shape: image
        label: "icon_service_Cognitive_Services"
      }
  
  icon_service_Front_Door_and_CDN_Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Front_Door_and_CDN_Profiles.svg
        shape: image
        label: "icon_service_Front_Door_and_CDN_Profiles"
      }
  
  icon_service_Notification_Hub_Namespaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Notification_Hub_Namespaces.svg
        shape: image
        label: "icon_service_Notification_Hub_Namespaces"
      }
  
  icon_service_Power_Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Power_Platform.svg
        shape: image
        label: "icon_service_Power_Platform"
      }
  
  icon_service_SignalR: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_SignalR.svg
        shape: image
        label: "icon_service_SignalR"
      }
  
  icon_service_Static_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/web/icon_service_Static_Apps.svg
        shape: image
        label: "icon_service_Static_Apps"
      }
  
}