classes: {
  
  
  Hand 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 1.svg
        shape: image
        label: "Hand 1"
      }
  
  
  Hand 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 2.svg
        shape: image
        label: "Hand 2"
      }
  
  
  Hand 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 3.svg
        shape: image
        label: "Hand 3"
      }
  
  
  Hand 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 4.svg
        shape: image
        label: "Hand 4"
      }
  
  
  Hand 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 5.svg
        shape: image
        label: "Hand 5"
      }
  
  
  Hand 6: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 6.svg
        shape: image
        label: "Hand 6"
      }
  
  
  Hand 7: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 7.svg
        shape: image
        label: "Hand 7"
      }
  
  
  Hand 8: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 8.svg
        shape: image
        label: "Hand 8"
      }
  
  
  Hand 9: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Hands/Hand 9.svg
        shape: image
        label: "Hand 9"
      }
  
}