classes: {
  
  access_context_manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./access_context_manager.svg
        shape: image
        label: "access_context_manager"
      }
  
  administration: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./administration.svg
        shape: image
        label: "administration"
      }
  
  advanced_agent_modeling: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./advanced_agent_modeling.svg
        shape: image
        label: "advanced_agent_modeling"
      }
  
  advanced_solutions_lab: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./advanced_solutions_lab.svg
        shape: image
        label: "advanced_solutions_lab"
      }
  
  agent_assist: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./agent_assist.svg
        shape: image
        label: "agent_assist"
      }
  
  ai_hub: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./ai_hub.svg
        shape: image
        label: "ai_hub"
      }
  
  ai_platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./ai_platform.svg
        shape: image
        label: "ai_platform"
      }
  
  ai_platform_unified: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./ai_platform_unified.svg
        shape: image
        label: "ai_platform_unified"
      }
  
  analytics_hub: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./analytics_hub.svg
        shape: image
        label: "analytics_hub"
      }
  
  anthos: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./anthos.svg
        shape: image
        label: "anthos"
      }
  
  anthos_config_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./anthos_config_management.svg
        shape: image
        label: "anthos_config_management"
      }
  
  anthos_service_mesh: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./anthos_service_mesh.svg
        shape: image
        label: "anthos_service_mesh"
      }
  
  api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./api.svg
        shape: image
        label: "api"
      }
  
  apigee_api_platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./apigee_api_platform.svg
        shape: image
        label: "apigee_api_platform"
      }
  
  apigee_sense: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./apigee_sense.svg
        shape: image
        label: "apigee_sense"
      }
  
  api_analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./api_analytics.svg
        shape: image
        label: "api_analytics"
      }
  
  api_monetization: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./api_monetization.svg
        shape: image
        label: "api_monetization"
      }
  
  app_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./app_engine.svg
        shape: image
        label: "app_engine"
      }
  
  artifact_registry: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./artifact_registry.svg
        shape: image
        label: "artifact_registry"
      }
  
  asset_inventory: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./asset_inventory.svg
        shape: image
        label: "asset_inventory"
      }
  
  assured_workloads: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./assured_workloads.svg
        shape: image
        label: "assured_workloads"
      }
  
  automl: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./automl.svg
        shape: image
        label: "automl"
      }
  
  automl_natural_language: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./automl_natural_language.svg
        shape: image
        label: "automl_natural_language"
      }
  
  automl_tables: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./automl_tables.svg
        shape: image
        label: "automl_tables"
      }
  
  automl_translation: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./automl_translation.svg
        shape: image
        label: "automl_translation"
      }
  
  automl_video_intelligence: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./automl_video_intelligence.svg
        shape: image
        label: "automl_video_intelligence"
      }
  
  automl_vision: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./automl_vision.svg
        shape: image
        label: "automl_vision"
      }
  
  bare_metal_solutions: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./bare_metal_solutions.svg
        shape: image
        label: "bare_metal_solutions"
      }
  
  batch: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./batch.svg
        shape: image
        label: "batch"
      }
  
  beyondcorp: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./beyondcorp.svg
        shape: image
        label: "beyondcorp"
      }
  
  bigquery: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./bigquery.svg
        shape: image
        label: "bigquery"
      }
  
  bigtable: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./bigtable.svg
        shape: image
        label: "bigtable"
      }
  
  billing: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./billing.svg
        shape: image
        label: "billing"
      }
  
  binary_authorization: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./binary_authorization.svg
        shape: image
        label: "binary_authorization"
      }
  
  catalog: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./catalog.svg
        shape: image
        label: "catalog"
      }
  
  certificate_authority_service: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./certificate_authority_service.svg
        shape: image
        label: "certificate_authority_service"
      }
  
  certificate_manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./certificate_manager.svg
        shape: image
        label: "certificate_manager"
      }
  
  cloud_apis: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_apis.svg
        shape: image
        label: "cloud_apis"
      }
  
  cloud_api_gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_api_gateway.svg
        shape: image
        label: "cloud_api_gateway"
      }
  
  cloud_armor: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_armor.svg
        shape: image
        label: "cloud_armor"
      }
  
  cloud_asset_inventory: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_asset_inventory.svg
        shape: image
        label: "cloud_asset_inventory"
      }
  
  cloud_audit_logs: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_audit_logs.svg
        shape: image
        label: "cloud_audit_logs"
      }
  
  cloud_build: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_build.svg
        shape: image
        label: "cloud_build"
      }
  
  cloud_cdn: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_cdn.svg
        shape: image
        label: "cloud_cdn"
      }
  
  cloud_code: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_code.svg
        shape: image
        label: "cloud_code"
      }
  
  cloud_composer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_composer.svg
        shape: image
        label: "cloud_composer"
      }
  
  cloud_data_fusion: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_data_fusion.svg
        shape: image
        label: "cloud_data_fusion"
      }
  
  cloud_deploy: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_deploy.svg
        shape: image
        label: "cloud_deploy"
      }
  
  cloud_deployment_manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_deployment_manager.svg
        shape: image
        label: "cloud_deployment_manager"
      }
  
  cloud_dns: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_dns.svg
        shape: image
        label: "cloud_dns"
      }
  
  cloud_domains: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_domains.svg
        shape: image
        label: "cloud_domains"
      }
  
  cloud_ekm: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_ekm.svg
        shape: image
        label: "cloud_ekm"
      }
  
  cloud_endpoints: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_endpoints.svg
        shape: image
        label: "cloud_endpoints"
      }
  
  cloud_external_ip_addresses: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_external_ip_addresses.svg
        shape: image
        label: "cloud_external_ip_addresses"
      }
  
  cloud_firewall_rules: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_firewall_rules.svg
        shape: image
        label: "cloud_firewall_rules"
      }
  
  cloud_for_marketing: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_for_marketing.svg
        shape: image
        label: "cloud_for_marketing"
      }
  
  cloud_functions: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_functions.svg
        shape: image
        label: "cloud_functions"
      }
  
  cloud_generic: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_generic.svg
        shape: image
        label: "cloud_generic"
      }
  
  cloud_gpu: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_gpu.svg
        shape: image
        label: "cloud_gpu"
      }
  
  cloud_healthcare_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_healthcare_api.svg
        shape: image
        label: "cloud_healthcare_api"
      }
  
  cloud_healthcare_marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_healthcare_marketplace.svg
        shape: image
        label: "cloud_healthcare_marketplace"
      }
  
  cloud_hsm: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_hsm.svg
        shape: image
        label: "cloud_hsm"
      }
  
  cloud_ids: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_ids.svg
        shape: image
        label: "cloud_ids"
      }
  
  cloud_inference_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_inference_api.svg
        shape: image
        label: "cloud_inference_api"
      }
  
  cloud_interconnect: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_interconnect.svg
        shape: image
        label: "cloud_interconnect"
      }
  
  cloud_jobs_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_jobs_api.svg
        shape: image
        label: "cloud_jobs_api"
      }
  
  cloud_load_balancing: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_load_balancing.svg
        shape: image
        label: "cloud_load_balancing"
      }
  
  cloud_logging: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_logging.svg
        shape: image
        label: "cloud_logging"
      }
  
  cloud_media_edge: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_media_edge.svg
        shape: image
        label: "cloud_media_edge"
      }
  
  cloud_monitoring: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_monitoring.svg
        shape: image
        label: "cloud_monitoring"
      }
  
  cloud_nat: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_nat.svg
        shape: image
        label: "cloud_nat"
      }
  
  cloud_natural_language_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_natural_language_api.svg
        shape: image
        label: "cloud_natural_language_api"
      }
  
  cloud_network: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_network.svg
        shape: image
        label: "cloud_network"
      }
  
  cloud_ops: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_ops.svg
        shape: image
        label: "cloud_ops"
      }
  
  cloud_optimization_ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_optimization_ai.svg
        shape: image
        label: "cloud_optimization_ai"
      }
  
  cloud_optimization_ai___fleet_routing_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_optimization_ai___fleet_routing_api.svg
        shape: image
        label: "cloud_optimization_ai___fleet_routing_api"
      }
  
  cloud_router: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_router.svg
        shape: image
        label: "cloud_router"
      }
  
  cloud_routes: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_routes.svg
        shape: image
        label: "cloud_routes"
      }
  
  cloud_run: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_run.svg
        shape: image
        label: "cloud_run"
      }
  
  cloud_run_for_anthos: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_run_for_anthos.svg
        shape: image
        label: "cloud_run_for_anthos"
      }
  
  cloud_scheduler: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_scheduler.svg
        shape: image
        label: "cloud_scheduler"
      }
  
  cloud_security_scanner: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_security_scanner.svg
        shape: image
        label: "cloud_security_scanner"
      }
  
  cloud_shell: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_shell.svg
        shape: image
        label: "cloud_shell"
      }
  
  cloud_spanner: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_spanner.svg
        shape: image
        label: "cloud_spanner"
      }
  
  cloud_sql: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_sql.svg
        shape: image
        label: "cloud_sql"
      }
  
  cloud_storage: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_storage.svg
        shape: image
        label: "cloud_storage"
      }
  
  cloud_tasks: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_tasks.svg
        shape: image
        label: "cloud_tasks"
      }
  
  cloud_test_lab: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_test_lab.svg
        shape: image
        label: "cloud_test_lab"
      }
  
  cloud_tpu: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_tpu.svg
        shape: image
        label: "cloud_tpu"
      }
  
  cloud_translation_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_translation_api.svg
        shape: image
        label: "cloud_translation_api"
      }
  
  cloud_vision_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_vision_api.svg
        shape: image
        label: "cloud_vision_api"
      }
  
  cloud_vpn: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./cloud_vpn.svg
        shape: image
        label: "cloud_vpn"
      }
  
  compute_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./compute_engine.svg
        shape: image
        label: "compute_engine"
      }
  
  configuration_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./configuration_management.svg
        shape: image
        label: "configuration_management"
      }
  
  connectivity_test: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./connectivity_test.svg
        shape: image
        label: "connectivity_test"
      }
  
  connectors: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./connectors.svg
        shape: image
        label: "connectors"
      }
  
  contact_center_ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./contact_center_ai.svg
        shape: image
        label: "contact_center_ai"
      }
  
  container_optimized_os: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./container_optimized_os.svg
        shape: image
        label: "container_optimized_os"
      }
  
  container_registry: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./container_registry.svg
        shape: image
        label: "container_registry"
      }
  
  database_migration_service: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./database_migration_service.svg
        shape: image
        label: "database_migration_service"
      }
  
  dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dataflow.svg
        shape: image
        label: "dataflow"
      }
  
  datalab: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./datalab.svg
        shape: image
        label: "datalab"
      }
  
  dataplex: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dataplex.svg
        shape: image
        label: "dataplex"
      }
  
  datapol: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./datapol.svg
        shape: image
        label: "datapol"
      }
  
  dataprep: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dataprep.svg
        shape: image
        label: "dataprep"
      }
  
  dataproc: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dataproc.svg
        shape: image
        label: "dataproc"
      }
  
  dataproc_metastore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dataproc_metastore.svg
        shape: image
        label: "dataproc_metastore"
      }
  
  datashare: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./datashare.svg
        shape: image
        label: "datashare"
      }
  
  datastore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./datastore.svg
        shape: image
        label: "datastore"
      }
  
  datastream: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./datastream.svg
        shape: image
        label: "datastream"
      }
  
  data_catalog: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_catalog.svg
        shape: image
        label: "data_catalog"
      }
  
  data_labeling: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_labeling.svg
        shape: image
        label: "data_labeling"
      }
  
  data_layers: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_layers.svg
        shape: image
        label: "data_layers"
      }
  
  data_loss_prevention_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_loss_prevention_api.svg
        shape: image
        label: "data_loss_prevention_api"
      }
  
  data_qna: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_qna.svg
        shape: image
        label: "data_qna"
      }
  
  data_studio: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_studio.svg
        shape: image
        label: "data_studio"
      }
  
  data_transfer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./data_transfer.svg
        shape: image
        label: "data_transfer"
      }
  
  debugger: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./debugger.svg
        shape: image
        label: "debugger"
      }
  
  developer_portal: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./developer_portal.svg
        shape: image
        label: "developer_portal"
      }
  
  dialogflow: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dialogflow.svg
        shape: image
        label: "dialogflow"
      }
  
  dialogflow_cx: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dialogflow_cx.svg
        shape: image
        label: "dialogflow_cx"
      }
  
  dialogflow_insights: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./dialogflow_insights.svg
        shape: image
        label: "dialogflow_insights"
      }
  
  document_ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./document_ai.svg
        shape: image
        label: "document_ai"
      }
  
  early_access_center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./early_access_center.svg
        shape: image
        label: "early_access_center"
      }
  
  error_reporting: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./error_reporting.svg
        shape: image
        label: "error_reporting"
      }
  
  eventarc: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./eventarc.svg
        shape: image
        label: "eventarc"
      }
  
  filestore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./filestore.svg
        shape: image
        label: "filestore"
      }
  
  financial_services_marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./financial_services_marketplace.svg
        shape: image
        label: "financial_services_marketplace"
      }
  
  firestore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./firestore.svg
        shape: image
        label: "firestore"
      }
  
  fleet_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./fleet_engine.svg
        shape: image
        label: "fleet_engine"
      }
  
  free_trial: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./free_trial.svg
        shape: image
        label: "free_trial"
      }
  
  game_servers: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./game_servers.svg
        shape: image
        label: "game_servers"
      }
  
  gce_systems_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./gce_systems_management.svg
        shape: image
        label: "gce_systems_management"
      }
  
  genomics: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./genomics.svg
        shape: image
        label: "genomics"
      }
  
  gke_on_prem: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./gke_on_prem.svg
        shape: image
        label: "gke_on_prem"
      }
  
  google_cloud_marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./google_cloud_marketplace.svg
        shape: image
        label: "google_cloud_marketplace"
      }
  
  google_kubernetes_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./google_kubernetes_engine.svg
        shape: image
        label: "google_kubernetes_engine"
      }
  
  google_maps_platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./google_maps_platform.svg
        shape: image
        label: "google_maps_platform"
      }
  
  healthcare_nlp_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./healthcare_nlp_api.svg
        shape: image
        label: "healthcare_nlp_api"
      }
  
  home: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./home.svg
        shape: image
        label: "home"
      }
  
  identity_and_access_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./identity_and_access_management.svg
        shape: image
        label: "identity_and_access_management"
      }
  
  identity_aware_proxy: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./identity_aware_proxy.svg
        shape: image
        label: "identity_aware_proxy"
      }
  
  identity_platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./identity_platform.svg
        shape: image
        label: "identity_platform"
      }
  
  iot_core: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./iot_core.svg
        shape: image
        label: "iot_core"
      }
  
  iot_edge: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./iot_edge.svg
        shape: image
        label: "iot_edge"
      }
  
  key_access_justifications: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./key_access_justifications.svg
        shape: image
        label: "key_access_justifications"
      }
  
  key_management_service: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./key_management_service.svg
        shape: image
        label: "key_management_service"
      }
  
  kuberun: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./kuberun.svg
        shape: image
        label: "kuberun"
      }
  
  launcher: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./launcher.svg
        shape: image
        label: "launcher"
      }
  
  local_ssd: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./local_ssd.svg
        shape: image
        label: "local_ssd"
      }
  
  looker: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./looker.svg
        shape: image
        label: "looker"
      }
  
  managed_service_for_microsoft_active_directory: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./managed_service_for_microsoft_active_directory.svg
        shape: image
        label: "managed_service_for_microsoft_active_directory"
      }
  
  media_translation_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./media_translation_api.svg
        shape: image
        label: "media_translation_api"
      }
  
  memorystore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./memorystore.svg
        shape: image
        label: "memorystore"
      }
  
  migrate_for_anthos: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./migrate_for_anthos.svg
        shape: image
        label: "migrate_for_anthos"
      }
  
  migrate_for_compute_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./migrate_for_compute_engine.svg
        shape: image
        label: "migrate_for_compute_engine"
      }
  
  my_cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./my_cloud.svg
        shape: image
        label: "my_cloud"
      }
  
  network_connectivity_center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./network_connectivity_center.svg
        shape: image
        label: "network_connectivity_center"
      }
  
  network_intelligence_center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./network_intelligence_center.svg
        shape: image
        label: "network_intelligence_center"
      }
  
  network_security: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./network_security.svg
        shape: image
        label: "network_security"
      }
  
  network_tiers: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./network_tiers.svg
        shape: image
        label: "network_tiers"
      }
  
  network_topology: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./network_topology.svg
        shape: image
        label: "network_topology"
      }
  
  onboarding: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./onboarding.svg
        shape: image
        label: "onboarding"
      }
  
  os_configuration_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./os_configuration_management.svg
        shape: image
        label: "os_configuration_management"
      }
  
  os_inventory_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./os_inventory_management.svg
        shape: image
        label: "os_inventory_management"
      }
  
  os_patch_management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./os_patch_management.svg
        shape: image
        label: "os_patch_management"
      }
  
  partner_interconnect: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./partner_interconnect.svg
        shape: image
        label: "partner_interconnect"
      }
  
  partner_portal: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./partner_portal.svg
        shape: image
        label: "partner_portal"
      }
  
  performance_dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./performance_dashboard.svg
        shape: image
        label: "performance_dashboard"
      }
  
  permissions: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./permissions.svg
        shape: image
        label: "permissions"
      }
  
  persistent_disk: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./persistent_disk.svg
        shape: image
        label: "persistent_disk"
      }
  
  phishing_protection: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./phishing_protection.svg
        shape: image
        label: "phishing_protection"
      }
  
  policy_analyzer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./policy_analyzer.svg
        shape: image
        label: "policy_analyzer"
      }
  
  premium_network_tier: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./premium_network_tier.svg
        shape: image
        label: "premium_network_tier"
      }
  
  private_connectivity: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./private_connectivity.svg
        shape: image
        label: "private_connectivity"
      }
  
  private_service_connect: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./private_service_connect.svg
        shape: image
        label: "private_service_connect"
      }
  
  producer_portal: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./producer_portal.svg
        shape: image
        label: "producer_portal"
      }
  
  profiler: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./profiler.svg
        shape: image
        label: "profiler"
      }
  
  project: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./project.svg
        shape: image
        label: "project"
      }
  
  pubsub: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./pubsub.svg
        shape: image
        label: "pubsub"
      }
  
  quantum_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./quantum_engine.svg
        shape: image
        label: "quantum_engine"
      }
  
  quotas: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./quotas.svg
        shape: image
        label: "quotas"
      }
  
  real_world_insights: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./real_world_insights.svg
        shape: image
        label: "real_world_insights"
      }
  
  recommendations_ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./recommendations_ai.svg
        shape: image
        label: "recommendations_ai"
      }
  
  release_notes: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./release_notes.svg
        shape: image
        label: "release_notes"
      }
  
  retail_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./retail_api.svg
        shape: image
        label: "retail_api"
      }
  
  risk_manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./risk_manager.svg
        shape: image
        label: "risk_manager"
      }
  
  runtime_config: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./runtime_config.svg
        shape: image
        label: "runtime_config"
      }
  
  secret_manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./secret_manager.svg
        shape: image
        label: "secret_manager"
      }
  
  security: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./security.svg
        shape: image
        label: "security"
      }
  
  security_command_center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./security_command_center.svg
        shape: image
        label: "security_command_center"
      }
  
  security_health_advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./security_health_advisor.svg
        shape: image
        label: "security_health_advisor"
      }
  
  security_key_enforcement: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./security_key_enforcement.svg
        shape: image
        label: "security_key_enforcement"
      }
  
  service_discovery: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./service_discovery.svg
        shape: image
        label: "service_discovery"
      }
  
  speech_to_text: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./speech_to_text.svg
        shape: image
        label: "speech_to_text"
      }
  
  stackdriver: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./stackdriver.svg
        shape: image
        label: "stackdriver"
      }
  
  standard_network_tier: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./standard_network_tier.svg
        shape: image
        label: "standard_network_tier"
      }
  
  stream_suite: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./stream_suite.svg
        shape: image
        label: "stream_suite"
      }
  
  support: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./support.svg
        shape: image
        label: "support"
      }
  
  tensorflow_enterprise: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./tensorflow_enterprise.svg
        shape: image
        label: "tensorflow_enterprise"
      }
  
  text_to_speech: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./text_to_speech.svg
        shape: image
        label: "text_to_speech"
      }
  
  tools_for_powershell: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./tools_for_powershell.svg
        shape: image
        label: "tools_for_powershell"
      }
  
  trace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./trace.svg
        shape: image
        label: "trace"
      }
  
  traffic_director: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./traffic_director.svg
        shape: image
        label: "traffic_director"
      }
  
  transfer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./transfer.svg
        shape: image
        label: "transfer"
      }
  
  transfer_appliance: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./transfer_appliance.svg
        shape: image
        label: "transfer_appliance"
      }
  
  user_preferences: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./user_preferences.svg
        shape: image
        label: "user_preferences"
      }
  
  vertexai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./vertexai.svg
        shape: image
        label: "vertexai"
      }
  
  video_intelligence_api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./video_intelligence_api.svg
        shape: image
        label: "video_intelligence_api"
      }
  
  virtual_private_cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./virtual_private_cloud.svg
        shape: image
        label: "virtual_private_cloud"
      }
  
  visual_inspection: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./visual_inspection.svg
        shape: image
        label: "visual_inspection"
      }
  
  vmware_engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./vmware_engine.svg
        shape: image
        label: "vmware_engine"
      }
  
  web_risk: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./web_risk.svg
        shape: image
        label: "web_risk"
      }
  
  web_security_scanner: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./web_security_scanner.svg
        shape: image
        label: "web_security_scanner"
      }
  
  workflows: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./workflows.svg
        shape: image
        label: "workflows"
      }
  
  workload_identity_pool: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/./workload_identity_pool.svg
        shape: image
        label: "workload_identity_pool"
      }
  
}