classes: {
  
  
  Res Amazon Managed Blockchain Blockchain: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Blockchain/Res_Amazon_Managed_Blockchain_Blockchain.svg
        shape: image
        label: "Res Amazon Managed Blockchain Blockchain"
      }
  
}