classes: {
  
  
  Activity Log: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Activity_Log.svg
        shape: image
        label: "Activity Log"
      }
  
  
  Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Advisor.svg
        shape: image
        label: "Advisor"
      }
  
  
  Alerts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Alerts.svg
        shape: image
        label: "Alerts"
      }
  
  
  Application Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Application_Insights.svg
        shape: image
        label: "Application Insights"
      }
  
  
  Arc Machines: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Arc_Machines.svg
        shape: image
        label: "Arc Machines"
      }
  
  
  Automation Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Automation_Accounts.svg
        shape: image
        label: "Automation Accounts"
      }
  
  
  Azure Arc: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Azure_Arc.svg
        shape: image
        label: "Azure Arc"
      }
  
  
  Azure Lighthouse: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Azure_Lighthouse.svg
        shape: image
        label: "Azure Lighthouse"
      }
  
  
  Blueprints: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Blueprints.svg
        shape: image
        label: "Blueprints"
      }
  
  
  Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Compliance.svg
        shape: image
        label: "Compliance"
      }
  
  
  Cost Management And Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Cost_Management_and_Billing.svg
        shape: image
        label: "Cost Management And Billing"
      }
  
  
  Customer Lockbox For Microsoft Azure: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Customer_Lockbox_for_Microsoft_Azure.svg
        shape: image
        label: "Customer Lockbox For Microsoft Azure"
      }
  
  
  Diagnostics Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Diagnostics_Settings.svg
        shape: image
        label: "Diagnostics Settings"
      }
  
  
  Education: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Education.svg
        shape: image
        label: "Education"
      }
  
  
  Intune Trends: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Intune_Trends.svg
        shape: image
        label: "Intune Trends"
      }
  
  
  Log Analytics Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Log_Analytics_Workspaces.svg
        shape: image
        label: "Log Analytics Workspaces"
      }
  
  
  Machinesazurearc: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/MachinesAzureArc.svg
        shape: image
        label: "Machinesazurearc"
      }
  
  
  Managed Applications Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Managed_Applications_Center.svg
        shape: image
        label: "Managed Applications Center"
      }
  
  
  Managed Desktop: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Managed_Desktop.svg
        shape: image
        label: "Managed Desktop"
      }
  
  
  Metrics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Metrics.svg
        shape: image
        label: "Metrics"
      }
  
  
  Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Monitor.svg
        shape: image
        label: "Monitor"
      }
  
  
  My Customers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/My_Customers.svg
        shape: image
        label: "My Customers"
      }
  
  
  Operation Log (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Operation_Log_(Classic).svg
        shape: image
        label: "Operation Log (classic)"
      }
  
  
  Policy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Policy.svg
        shape: image
        label: "Policy"
      }
  
  
  Recovery Services Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Recovery_Services_Vaults.svg
        shape: image
        label: "Recovery Services Vaults"
      }
  
  
  Resource Graph Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Resource_Graph_Explorer.svg
        shape: image
        label: "Resource Graph Explorer"
      }
  
  
  Scheduler Job Collections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Scheduler_Job_Collections.svg
        shape: image
        label: "Scheduler Job Collections"
      }
  
  
  Service Catalog Mad: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Service_Catalog_MAD.svg
        shape: image
        label: "Service Catalog Mad"
      }
  
  
  Service Providers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Service_Providers.svg
        shape: image
        label: "Service Providers"
      }
  
  
  Solutions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Solutions.svg
        shape: image
        label: "Solutions"
      }
  
  
  Universal Print: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/Universal_Print.svg
        shape: image
        label: "Universal Print"
      }
  
  
  User Privacy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/User_Privacy.svg
        shape: image
        label: "User Privacy"
      }
  
}