classes: {
  
  icon_service_Activity_Log: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Activity_Log.svg
        shape: image
        label: "icon_service_Activity_Log"
      }
  
  icon_service_Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Advisor.svg
        shape: image
        label: "icon_service_Advisor"
      }
  
  icon_service_Alerts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Alerts.svg
        shape: image
        label: "icon_service_Alerts"
      }
  
  icon_service_Application_Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Application_Insights.svg
        shape: image
        label: "icon_service_Application_Insights"
      }
  
  icon_service_Arc_Machines: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Arc_Machines.svg
        shape: image
        label: "icon_service_Arc_Machines"
      }
  
  icon_service_Automation_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Automation_Accounts.svg
        shape: image
        label: "icon_service_Automation_Accounts"
      }
  
  icon_service_Azure_Arc: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Azure_Arc.svg
        shape: image
        label: "icon_service_Azure_Arc"
      }
  
  icon_service_Azure_Lighthouse: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Azure_Lighthouse.svg
        shape: image
        label: "icon_service_Azure_Lighthouse"
      }
  
  icon_service_Blueprints: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Blueprints.svg
        shape: image
        label: "icon_service_Blueprints"
      }
  
  icon_service_Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Compliance.svg
        shape: image
        label: "icon_service_Compliance"
      }
  
  icon_service_Cost_Management_and_Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Cost_Management_and_Billing.svg
        shape: image
        label: "icon_service_Cost_Management_and_Billing"
      }
  
  icon_service_Customer_Lockbox_for_Microsoft_Azure: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Customer_Lockbox_for_Microsoft_Azure.svg
        shape: image
        label: "icon_service_Customer_Lockbox_for_Microsoft_Azure"
      }
  
  icon_service_Diagnostics_Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Diagnostics_Settings.svg
        shape: image
        label: "icon_service_Diagnostics_Settings"
      }
  
  icon_service_Education: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Education.svg
        shape: image
        label: "icon_service_Education"
      }
  
  icon_service_Intune_Trends: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Intune_Trends.svg
        shape: image
        label: "icon_service_Intune_Trends"
      }
  
  icon_service_Log_Analytics_Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Log_Analytics_Workspaces.svg
        shape: image
        label: "icon_service_Log_Analytics_Workspaces"
      }
  
  icon_service_MachinesAzureArc: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_MachinesAzureArc.svg
        shape: image
        label: "icon_service_MachinesAzureArc"
      }
  
  icon_service_Managed_Applications_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Managed_Applications_Center.svg
        shape: image
        label: "icon_service_Managed_Applications_Center"
      }
  
  icon_service_Managed_Desktop: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Managed_Desktop.svg
        shape: image
        label: "icon_service_Managed_Desktop"
      }
  
  icon_service_Metrics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Metrics.svg
        shape: image
        label: "icon_service_Metrics"
      }
  
  icon_service_Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Monitor.svg
        shape: image
        label: "icon_service_Monitor"
      }
  
  icon_service_My_Customers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_My_Customers.svg
        shape: image
        label: "icon_service_My_Customers"
      }
  
  icon_service_Operation_Log_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Operation_Log_(Classic).svg
        shape: image
        label: "icon_service_Operation_Log_(Classic)"
      }
  
  icon_service_Policy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Policy.svg
        shape: image
        label: "icon_service_Policy"
      }
  
  icon_service_Recovery_Services_Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Recovery_Services_Vaults.svg
        shape: image
        label: "icon_service_Recovery_Services_Vaults"
      }
  
  icon_service_Resource_Graph_Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Resource_Graph_Explorer.svg
        shape: image
        label: "icon_service_Resource_Graph_Explorer"
      }
  
  icon_service_Scheduler_Job_Collections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Scheduler_Job_Collections.svg
        shape: image
        label: "icon_service_Scheduler_Job_Collections"
      }
  
  icon_service_Service_Catalog_MAD: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Service_Catalog_MAD.svg
        shape: image
        label: "icon_service_Service_Catalog_MAD"
      }
  
  icon_service_Service_Providers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Service_Providers.svg
        shape: image
        label: "icon_service_Service_Providers"
      }
  
  icon_service_Solutions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Solutions.svg
        shape: image
        label: "icon_service_Solutions"
      }
  
  icon_service_Universal_Print: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_Universal_Print.svg
        shape: image
        label: "icon_service_Universal_Print"
      }
  
  icon_service_User_Privacy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/management + governance/icon_service_User_Privacy.svg
        shape: image
        label: "icon_service_User_Privacy"
      }
  
}