classes: {
  
  icon_service_Application_Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Application_Gateways.svg
        shape: image
        label: "icon_service_Application_Gateways"
      }
  
  icon_service_Azure_Firewall_Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Azure_Firewall_Manager.svg
        shape: image
        label: "icon_service_Azure_Firewall_Manager"
      }
  
  icon_service_Azure_Firewall_Policy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Azure_Firewall_Policy.svg
        shape: image
        label: "icon_service_Azure_Firewall_Policy"
      }
  
  icon_service_Bastions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Bastions.svg
        shape: image
        label: "icon_service_Bastions"
      }
  
  icon_service_CDN_Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_CDN_Profiles.svg
        shape: image
        label: "icon_service_CDN_Profiles"
      }
  
  icon_service_Connected_Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Connected_Cache.svg
        shape: image
        label: "icon_service_Connected_Cache"
      }
  
  icon_service_Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Connections.svg
        shape: image
        label: "icon_service_Connections"
      }
  
  icon_service_DDoS_Protection_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_DDoS_Protection_Plans.svg
        shape: image
        label: "icon_service_DDoS_Protection_Plans"
      }
  
  icon_service_DNS_Private_Resolver: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_DNS_Private_Resolver.svg
        shape: image
        label: "icon_service_DNS_Private_Resolver"
      }
  
  icon_service_DNS_Zones: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_DNS_Zones.svg
        shape: image
        label: "icon_service_DNS_Zones"
      }
  
  icon_service_ExpressRoute_Circuits: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_ExpressRoute_Circuits.svg
        shape: image
        label: "icon_service_ExpressRoute_Circuits"
      }
  
  icon_service_Firewalls: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Firewalls.svg
        shape: image
        label: "icon_service_Firewalls"
      }
  
  icon_service_Front_Door_and_CDN_Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Front_Door_and_CDN_Profiles.svg
        shape: image
        label: "icon_service_Front_Door_and_CDN_Profiles"
      }
  
  icon_service_IP_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_IP_Groups.svg
        shape: image
        label: "icon_service_IP_Groups"
      }
  
  icon_service_Load_Balancers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Load_Balancers.svg
        shape: image
        label: "icon_service_Load_Balancers"
      }
  
  icon_service_Load_Balancer_Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Load_Balancer_Hub.svg
        shape: image
        label: "icon_service_Load_Balancer_Hub"
      }
  
  icon_service_Local_Network_Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Local_Network_Gateways.svg
        shape: image
        label: "icon_service_Local_Network_Gateways"
      }
  
  icon_service_NAT: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_NAT.svg
        shape: image
        label: "icon_service_NAT"
      }
  
  icon_service_Network_Interfaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Network_Interfaces.svg
        shape: image
        label: "icon_service_Network_Interfaces"
      }
  
  icon_service_Network_Security_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Network_Security_Groups.svg
        shape: image
        label: "icon_service_Network_Security_Groups"
      }
  
  icon_service_Network_Watcher: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Network_Watcher.svg
        shape: image
        label: "icon_service_Network_Watcher"
      }
  
  icon_service_On_Premises_Data_Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_On_Premises_Data_Gateways.svg
        shape: image
        label: "icon_service_On_Premises_Data_Gateways"
      }
  
  icon_service_Private_Link: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Private_Link.svg
        shape: image
        label: "icon_service_Private_Link"
      }
  
  icon_service_Private_Link_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Private_Link_Service.svg
        shape: image
        label: "icon_service_Private_Link_Service"
      }
  
  icon_service_Private_Link_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Private_Link_Services.svg
        shape: image
        label: "icon_service_Private_Link_Services"
      }
  
  icon_service_Proximity_Placement_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Proximity_Placement_Groups.svg
        shape: image
        label: "icon_service_Proximity_Placement_Groups"
      }
  
  icon_service_Public_IP_Addresses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Public_IP_Addresses.svg
        shape: image
        label: "icon_service_Public_IP_Addresses"
      }
  
  icon_service_Public_IP_Addresses_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Public_IP_Addresses_(Classic).svg
        shape: image
        label: "icon_service_Public_IP_Addresses_(Classic)"
      }
  
  icon_service_Public_IP_Prefixes: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Public_IP_Prefixes.svg
        shape: image
        label: "icon_service_Public_IP_Prefixes"
      }
  
  icon_service_Reserved_IP_Addresses_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Reserved_IP_Addresses_(Classic).svg
        shape: image
        label: "icon_service_Reserved_IP_Addresses_(Classic)"
      }
  
  icon_service_Resource_Management_Private_Link: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Resource_Management_Private_Link.svg
        shape: image
        label: "icon_service_Resource_Management_Private_Link"
      }
  
  icon_service_Route_Filters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Route_Filters.svg
        shape: image
        label: "icon_service_Route_Filters"
      }
  
  icon_service_Route_Tables: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Route_Tables.svg
        shape: image
        label: "icon_service_Route_Tables"
      }
  
  icon_service_Service_Endpoint_Policies: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Service_Endpoint_Policies.svg
        shape: image
        label: "icon_service_Service_Endpoint_Policies"
      }
  
  icon_service_Spot_VM: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Spot_VM.svg
        shape: image
        label: "icon_service_Spot_VM"
      }
  
  icon_service_Spot_VMSS: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Spot_VMSS.svg
        shape: image
        label: "icon_service_Spot_VMSS"
      }
  
  icon_service_Subnet: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Subnet.svg
        shape: image
        label: "icon_service_Subnet"
      }
  
  icon_service_Traffic_Manager_Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Traffic_Manager_Profiles.svg
        shape: image
        label: "icon_service_Traffic_Manager_Profiles"
      }
  
  icon_service_Virtual_Networks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Virtual_Networks.svg
        shape: image
        label: "icon_service_Virtual_Networks"
      }
  
  icon_service_Virtual_Networks_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Virtual_Networks_(Classic).svg
        shape: image
        label: "icon_service_Virtual_Networks_(Classic)"
      }
  
  icon_service_Virtual_Network_Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Virtual_Network_Gateways.svg
        shape: image
        label: "icon_service_Virtual_Network_Gateways"
      }
  
  icon_service_Virtual_Router: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Virtual_Router.svg
        shape: image
        label: "icon_service_Virtual_Router"
      }
  
  icon_service_Virtual_WANs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Virtual_WANs.svg
        shape: image
        label: "icon_service_Virtual_WANs"
      }
  
  icon_service_Virtual_WAN_Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Virtual_WAN_Hub.svg
        shape: image
        label: "icon_service_Virtual_WAN_Hub"
      }
  
  icon_service_Web_Application_Firewall_Policies(WAF): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/icon_service_Web_Application_Firewall_Policies(WAF).svg
        shape: image
        label: "icon_service_Web_Application_Firewall_Policies(WAF)"
      }
  
}