classes: {
  
  
  Application Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Application_Gateways.svg
        shape: image
        label: "Application Gateways"
      }
  
  
  Azure Firewall Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Azure_Firewall_Manager.svg
        shape: image
        label: "Azure Firewall Manager"
      }
  
  
  Azure Firewall Policy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Azure_Firewall_Policy.svg
        shape: image
        label: "Azure Firewall Policy"
      }
  
  
  Bastions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Bastions.svg
        shape: image
        label: "Bastions"
      }
  
  
  Cdn Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/CDN_Profiles.svg
        shape: image
        label: "Cdn Profiles"
      }
  
  
  Connected Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Connected_Cache.svg
        shape: image
        label: "Connected Cache"
      }
  
  
  Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Connections.svg
        shape: image
        label: "Connections"
      }
  
  
  Ddos Protection Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/DDoS_Protection_Plans.svg
        shape: image
        label: "Ddos Protection Plans"
      }
  
  
  Dns Private Resolver: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/DNS_Private_Resolver.svg
        shape: image
        label: "Dns Private Resolver"
      }
  
  
  Dns Zones: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/DNS_Zones.svg
        shape: image
        label: "Dns Zones"
      }
  
  
  Expressroute Circuits: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/ExpressRoute_Circuits.svg
        shape: image
        label: "Expressroute Circuits"
      }
  
  
  Firewalls: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Firewalls.svg
        shape: image
        label: "Firewalls"
      }
  
  
  Front Door And Cdn Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Front_Door_and_CDN_Profiles.svg
        shape: image
        label: "Front Door And Cdn Profiles"
      }
  
  
  Ip Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/IP_Groups.svg
        shape: image
        label: "Ip Groups"
      }
  
  
  Load Balancers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Load_Balancers.svg
        shape: image
        label: "Load Balancers"
      }
  
  
  Load Balancer Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Load_Balancer_Hub.svg
        shape: image
        label: "Load Balancer Hub"
      }
  
  
  Local Network Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Local_Network_Gateways.svg
        shape: image
        label: "Local Network Gateways"
      }
  
  
  Nat: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/NAT.svg
        shape: image
        label: "Nat"
      }
  
  
  Network Interfaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Network_Interfaces.svg
        shape: image
        label: "Network Interfaces"
      }
  
  
  Network Security Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Network_Security_Groups.svg
        shape: image
        label: "Network Security Groups"
      }
  
  
  Network Watcher: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Network_Watcher.svg
        shape: image
        label: "Network Watcher"
      }
  
  
  On Premises Data Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/On_Premises_Data_Gateways.svg
        shape: image
        label: "On Premises Data Gateways"
      }
  
  
  Private Link: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Private_Link.svg
        shape: image
        label: "Private Link"
      }
  
  
  Private Link Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Private_Link_Service.svg
        shape: image
        label: "Private Link Service"
      }
  
  
  Private Link Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Private_Link_Services.svg
        shape: image
        label: "Private Link Services"
      }
  
  
  Proximity Placement Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Proximity_Placement_Groups.svg
        shape: image
        label: "Proximity Placement Groups"
      }
  
  
  Public Ip Addresses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Public_IP_Addresses.svg
        shape: image
        label: "Public Ip Addresses"
      }
  
  
  Public Ip Addresses (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Public_IP_Addresses_(Classic).svg
        shape: image
        label: "Public Ip Addresses (classic)"
      }
  
  
  Public Ip Prefixes: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Public_IP_Prefixes.svg
        shape: image
        label: "Public Ip Prefixes"
      }
  
  
  Reserved Ip Addresses (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Reserved_IP_Addresses_(Classic).svg
        shape: image
        label: "Reserved Ip Addresses (classic)"
      }
  
  
  Resource Management Private Link: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Resource_Management_Private_Link.svg
        shape: image
        label: "Resource Management Private Link"
      }
  
  
  Route Filters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Route_Filters.svg
        shape: image
        label: "Route Filters"
      }
  
  
  Route Tables: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Route_Tables.svg
        shape: image
        label: "Route Tables"
      }
  
  
  Service Endpoint Policies: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Service_Endpoint_Policies.svg
        shape: image
        label: "Service Endpoint Policies"
      }
  
  
  Spot Vm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Spot_VM.svg
        shape: image
        label: "Spot Vm"
      }
  
  
  Spot Vmss: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Spot_VMSS.svg
        shape: image
        label: "Spot Vmss"
      }
  
  
  Subnet: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Subnet.svg
        shape: image
        label: "Subnet"
      }
  
  
  Traffic Manager Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Traffic_Manager_Profiles.svg
        shape: image
        label: "Traffic Manager Profiles"
      }
  
  
  Virtual Networks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Virtual_Networks.svg
        shape: image
        label: "Virtual Networks"
      }
  
  
  Virtual Networks (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Virtual_Networks_(Classic).svg
        shape: image
        label: "Virtual Networks (classic)"
      }
  
  
  Virtual Network Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Virtual_Network_Gateways.svg
        shape: image
        label: "Virtual Network Gateways"
      }
  
  
  Virtual Router: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Virtual_Router.svg
        shape: image
        label: "Virtual Router"
      }
  
  
  Virtual Wans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Virtual_WANs.svg
        shape: image
        label: "Virtual Wans"
      }
  
  
  Virtual Wan Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Virtual_WAN_Hub.svg
        shape: image
        label: "Virtual Wan Hub"
      }
  
  
  Web Application Firewall Policies(waf): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/networking/Web_Application_Firewall_Policies(WAF).svg
        shape: image
        label: "Web Application Firewall Policies(waf)"
      }
  
}