classes: {
  
  
  Aws Activate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_Activate.svg
        shape: image
        label: "Aws Activate"
      }
  
  
  Aws Iq: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_IQ.svg
        shape: image
        label: "Aws Iq"
      }
  
  
  Aws Managed Services: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_Managed_Services.svg
        shape: image
        label: "Aws Managed Services"
      }
  
  
  Aws Professional Services: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_Professional_Services.svg
        shape: image
        label: "Aws Professional Services"
      }
  
  
  Aws Re Post: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_re_Post.svg
        shape: image
        label: "Aws Re Post"
      }
  
  
  Aws Support: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_Support.svg
        shape: image
        label: "Aws Support"
      }
  
  
  Aws Training Certification: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Customer-Enablement/AWS_Training_Certification.svg
        shape: image
        label: "Aws Training Certification"
      }
  
}