classes: {
  
  icon_service_App_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mobile/icon_service_App_Services.svg
        shape: image
        label: "icon_service_App_Services"
      }
  
  icon_service_Notification_Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mobile/icon_service_Notification_Hubs.svg
        shape: image
        label: "icon_service_Notification_Hubs"
      }
  
  icon_service_Power_Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mobile/icon_service_Power_Platform.svg
        shape: image
        label: "icon_service_Power_Platform"
      }
  
}