classes: {
  
  
  App Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mobile/App_Services.svg
        shape: image
        label: "App Services"
      }
  
  
  Notification Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mobile/Notification_Hubs.svg
        shape: image
        label: "Notification Hubs"
      }
  
  
  Power Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mobile/Power_Platform.svg
        shape: image
        label: "Power Platform"
      }
  
}