classes: {
  
  
  Res Amazon Location Service Geofence: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Front-End-Web-Mobile/Res_Amazon_Location_Service_Geofence.svg
        shape: image
        label: "Res Amazon Location Service Geofence"
      }
  
  
  Res Amazon Location Service Map : {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Front-End-Web-Mobile/Res_Amazon_Location_Service_Map .svg
        shape: image
        label: "Res Amazon Location Service Map "
      }
  
  
  Res Amazon Location Service Place: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Front-End-Web-Mobile/Res_Amazon_Location_Service_Place.svg
        shape: image
        label: "Res Amazon Location Service Place"
      }
  
  
  Res Amazon Location Service Routes: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Front-End-Web-Mobile/Res_Amazon_Location_Service_Routes.svg
        shape: image
        label: "Res Amazon Location Service Routes"
      }
  
  
  Res Amazon Location Service Track : {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Front-End-Web-Mobile/Res_Amazon_Location_Service_Track .svg
        shape: image
        label: "Res Amazon Location Service Track "
      }
  
  
  Res Aws Amplify Aws Amplify Studio: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Front-End-Web-Mobile/Res_AWS_Amplify_AWS_Amplify_Studio.svg
        shape: image
        label: "Res Aws Amplify Aws Amplify Studio"
      }
  
}