classes: {
  
  
  Res Amazon Aurora Amazon Aurora Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Amazon_Aurora_Instance_alternate.svg
        shape: image
        label: "Res Amazon Aurora Amazon Aurora Instance Alternate"
      }
  
  
  Res Amazon Aurora Amazon Rds Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Amazon_RDS_Instance.svg
        shape: image
        label: "Res Amazon Aurora Amazon Rds Instance"
      }
  
  
  Res Amazon Aurora Amazon Rds Instance Aternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Amazon_RDS_Instance_Aternate.svg
        shape: image
        label: "Res Amazon Aurora Amazon Rds Instance Aternate"
      }
  
  
  Res Amazon Aurora Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Instance.svg
        shape: image
        label: "Res Amazon Aurora Instance"
      }
  
  
  Res Amazon Aurora Mariadb Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_MariaDB_Instance.svg
        shape: image
        label: "Res Amazon Aurora Mariadb Instance"
      }
  
  
  Res Amazon Aurora Mariadb Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_MariaDB_Instance_Alternate.svg
        shape: image
        label: "Res Amazon Aurora Mariadb Instance Alternate"
      }
  
  
  Res Amazon Aurora Mysql Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_MySQL_Instance.svg
        shape: image
        label: "Res Amazon Aurora Mysql Instance"
      }
  
  
  Res Amazon Aurora Mysql Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_MySQL_Instance_Alternate.svg
        shape: image
        label: "Res Amazon Aurora Mysql Instance Alternate"
      }
  
  
  Res Amazon Aurora Oracle Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Oracle_Instance.svg
        shape: image
        label: "Res Amazon Aurora Oracle Instance"
      }
  
  
  Res Amazon Aurora Oracle Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Oracle_Instance_Alternate.svg
        shape: image
        label: "Res Amazon Aurora Oracle Instance Alternate"
      }
  
  
  Res Amazon Aurora Piops Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_PIOPS_Instance.svg
        shape: image
        label: "Res Amazon Aurora Piops Instance"
      }
  
  
  Res Amazon Aurora Postgresql Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_PostgreSQL_Instance.svg
        shape: image
        label: "Res Amazon Aurora Postgresql Instance"
      }
  
  
  Res Amazon Aurora Postgresql Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_PostgreSQL_Instance_Alternate.svg
        shape: image
        label: "Res Amazon Aurora Postgresql Instance Alternate"
      }
  
  
  Res Amazon Aurora Sql Server Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_SQL_Server_Instance.svg
        shape: image
        label: "Res Amazon Aurora Sql Server Instance"
      }
  
  
  Res Amazon Aurora Sql Server Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_SQL_Server_Instance_Alternate.svg
        shape: image
        label: "Res Amazon Aurora Sql Server Instance Alternate"
      }
  
  
  Res Amazon Aurora Trusted Language Extensions For Postgresql: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_Aurora_Trusted_Language_Extensions_for_PostgreSQL.svg
        shape: image
        label: "Res Amazon Aurora Trusted Language Extensions For Postgresql"
      }
  
  
  Res Amazon Documentdb Elastic Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DocumentDB_Elastic_Clusters.svg
        shape: image
        label: "Res Amazon Documentdb Elastic Clusters"
      }
  
  
  Res Amazon Dynamodb Amazon Dynamodb Accelerator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Amazon_DynamoDB_Accelerator.svg
        shape: image
        label: "Res Amazon Dynamodb Amazon Dynamodb Accelerator"
      }
  
  
  Res Amazon Dynamodb Attribute: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Attribute.svg
        shape: image
        label: "Res Amazon Dynamodb Attribute"
      }
  
  
  Res Amazon Dynamodb Attributes: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Attributes.svg
        shape: image
        label: "Res Amazon Dynamodb Attributes"
      }
  
  
  Res Amazon Dynamodb Global Secondary Index: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Global_secondary_index.svg
        shape: image
        label: "Res Amazon Dynamodb Global Secondary Index"
      }
  
  
  Res Amazon Dynamodb Item: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Item.svg
        shape: image
        label: "Res Amazon Dynamodb Item"
      }
  
  
  Res Amazon Dynamodb Items: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Items.svg
        shape: image
        label: "Res Amazon Dynamodb Items"
      }
  
  
  Res Amazon Dynamodb Standard Access Table Class: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Standard_Access_Table_Class.svg
        shape: image
        label: "Res Amazon Dynamodb Standard Access Table Class"
      }
  
  
  Res Amazon Dynamodb Standard Infrequent Access Table Class: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Standard_Infrequent_Access_Table_Class.svg
        shape: image
        label: "Res Amazon Dynamodb Standard Infrequent Access Table Class"
      }
  
  
  Res Amazon Dynamodb Stream: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Stream.svg
        shape: image
        label: "Res Amazon Dynamodb Stream"
      }
  
  
  Res Amazon Dynamodb Table: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_DynamoDB_Table.svg
        shape: image
        label: "Res Amazon Dynamodb Table"
      }
  
  
  Res Amazon Elasticache Cache Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_ElastiCache_Cache_Node.svg
        shape: image
        label: "Res Amazon Elasticache Cache Node"
      }
  
  
  Res Amazon Elasticache Elasticache For Memcached: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_ElastiCache_ElastiCache_for_Memcached.svg
        shape: image
        label: "Res Amazon Elasticache Elasticache For Memcached"
      }
  
  
  Res Amazon Elasticache Elasticache For Redis: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_ElastiCache_ElastiCache_for_Redis.svg
        shape: image
        label: "Res Amazon Elasticache Elasticache For Redis"
      }
  
  
  Res Amazon Rds Blue Green Deployments: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Blue_Green_Deployments.svg
        shape: image
        label: "Res Amazon Rds Blue Green Deployments"
      }
  
  
  Res Amazon Rds Multi Az: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Multi_AZ.svg
        shape: image
        label: "Res Amazon Rds Multi Az"
      }
  
  
  Res Amazon Rds Multi Az Db Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Multi_AZ_DB_Cluster.svg
        shape: image
        label: "Res Amazon Rds Multi Az Db Cluster"
      }
  
  
  Res Amazon Rds Optimized Writes: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Optimized_Writes.svg
        shape: image
        label: "Res Amazon Rds Optimized Writes"
      }
  
  
  Res Amazon Rds Proxy Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Proxy_Instance.svg
        shape: image
        label: "Res Amazon Rds Proxy Instance"
      }
  
  
  Res Amazon Rds Proxy Instance Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Proxy_Instance_Alternate.svg
        shape: image
        label: "Res Amazon Rds Proxy Instance Alternate"
      }
  
  
  Res Amazon Rds Trusted Language Extensions For Postgresql: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_Amazon_RDS_Trusted_Language_Extensions_for_PostgreSQL.svg
        shape: image
        label: "Res Amazon Rds Trusted Language Extensions For Postgresql"
      }
  
  
  Res Aws Database Migration Service Database Migration Workflow Or Job: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Database/Res_AWS_Database_Migration_Service_Database_migration_workflow_or_job.svg
        shape: image
        label: "Res Aws Database Migration Service Database Migration Workflow Or Job"
      }
  
}