classes: {
  
  access_control: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/access_control.svg
        shape: image
        label: "access_control"
      }
  
  aggregation_process: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/aggregation_process.svg
        shape: image
        label: "aggregation_process"
      }
  
  agile_scrum: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/agile_scrum.svg
        shape: image
        label: "agile_scrum"
      }
  
  alerts: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/alerts.svg
        shape: image
        label: "alerts"
      }
  
  application: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/application.svg
        shape: image
        label: "application"
      }
  
  application_caching: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/application_caching.svg
        shape: image
        label: "application_caching"
      }
  
  architecture: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/architecture.svg
        shape: image
        label: "architecture"
      }
  
  authentication: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/authentication.svg
        shape: image
        label: "authentication"
      }
  
  authorization: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/authorization.svg
        shape: image
        label: "authorization"
      }
  
  automatic_configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/automatic_configuration.svg
        shape: image
        label: "automatic_configuration"
      }
  
  availability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/availability.svg
        shape: image
        label: "availability"
      }
  
  available: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/available.svg
        shape: image
        label: "available"
      }
  
  balancing_act: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/balancing_act.svg
        shape: image
        label: "balancing_act"
      }
  
  big_data: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/big_data.svg
        shape: image
        label: "big_data"
      }
  
  Blacklist_Whitelist: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Blacklist_Whitelist.svg
        shape: image
        label: "Blacklist_Whitelist"
      }
  
  blazing_speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/blazing_speed.svg
        shape: image
        label: "blazing_speed"
      }
  
  break_time: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/break_time.svg
        shape: image
        label: "break_time"
      }
  
  bug_fixes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/bug_fixes.svg
        shape: image
        label: "bug_fixes"
      }
  
  business_logic_changes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/business_logic_changes.svg
        shape: image
        label: "business_logic_changes"
      }
  
  cache_as_service: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cache_as_service.svg
        shape: image
        label: "cache_as_service"
      }
  
  centralized_management_API: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/centralized_management_API.svg
        shape: image
        label: "centralized_management_API"
      }
  
  centralized_monitoring: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/centralized_monitoring.svg
        shape: image
        label: "centralized_monitoring"
      }
  
  checkpointing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/checkpointing.svg
        shape: image
        label: "checkpointing"
      }
  
  chicago: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/chicago.svg
        shape: image
        label: "chicago"
      }
  
  client_rolling_upgrade: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/client_rolling_upgrade.svg
        shape: image
        label: "client_rolling_upgrade"
      }
  
  cloud-applications: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud-applications.svg
        shape: image
        label: "cloud-applications"
      }
  
  cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud.svg
        shape: image
        label: "cloud"
      }
  
  cloud_dedicated: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_dedicated.svg
        shape: image
        label: "cloud_dedicated"
      }
  
  cloud_discovery: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_discovery.svg
        shape: image
        label: "cloud_discovery"
      }
  
  cloud_enterprise: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_enterprise.svg
        shape: image
        label: "cloud_enterprise"
      }
  
  cloud_free: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_free.svg
        shape: image
        label: "cloud_free"
      }
  
  cloud_native_dev: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_native_dev.svg
        shape: image
        label: "cloud_native_dev"
      }
  
  cloud_on_prem: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_on_prem.svg
        shape: image
        label: "cloud_on_prem"
      }
  
  Cloud_Paas: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Cloud_Paas.svg
        shape: image
        label: "Cloud_Paas"
      }
  
  cluster_configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cluster_configuration.svg
        shape: image
        label: "cluster_configuration"
      }
  
  cluster_stats: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cluster_stats.svg
        shape: image
        label: "cluster_stats"
      }
  
  collect: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/collect.svg
        shape: image
        label: "collect"
      }
  
  community: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/community.svg
        shape: image
        label: "community"
      }
  
  comprehensive: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/comprehensive.svg
        shape: image
        label: "comprehensive"
      }
  
  configuration_changes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/configuration_changes.svg
        shape: image
        label: "configuration_changes"
      }
  
  config_client_behavior: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/config_client_behavior.svg
        shape: image
        label: "config_client_behavior"
      }
  
  confused: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/confused.svg
        shape: image
        label: "confused"
      }
  
  connector: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/connector.svg
        shape: image
        label: "connector"
      }
  
  cons: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cons.svg
        shape: image
        label: "cons"
      }
  
  continuous_processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/continuous_processing.svg
        shape: image
        label: "continuous_processing"
      }
  
  contribute: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/contribute.svg
        shape: image
        label: "contribute"
      }
  
  custom-sources: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/custom-sources.svg
        shape: image
        label: "custom-sources"
      }
  
  database: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/database.svg
        shape: image
        label: "database"
      }
  
  data_persistence: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/data_persistence.svg
        shape: image
        label: "data_persistence"
      }
  
  data_privacy: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/data_privacy.svg
        shape: image
        label: "data_privacy"
      }
  
  data_structure_stats: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/data_structure_stats.svg
        shape: image
        label: "data_structure_stats"
      }
  
  deep_expertise: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/deep_expertise.svg
        shape: image
        label: "deep_expertise"
      }
  
  deploy_anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/deploy_anywhere.svg
        shape: image
        label: "deploy_anywhere"
      }
  
  development_costs: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/development_costs.svg
        shape: image
        label: "development_costs"
      }
  
  disaster_recovery: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/disaster_recovery.svg
        shape: image
        label: "disaster_recovery"
      }
  
  docker: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/docker.svg
        shape: image
        label: "docker"
      }
  
  domain_control: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/domain_control.svg
        shape: image
        label: "domain_control"
      }
  
  easy_scale_out: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/easy_scale_out.svg
        shape: image
        label: "easy_scale_out"
      }
  
  ecommerce: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/ecommerce.svg
        shape: image
        label: "ecommerce"
      }
  
  elastic: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/elastic.svg
        shape: image
        label: "elastic"
      }
  
  elastic_clustering: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/elastic_clustering.svg
        shape: image
        label: "elastic_clustering"
      }
  
  elastic_scalability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/elastic_scalability.svg
        shape: image
        label: "elastic_scalability"
      }
  
  end-to-end_pipeline_security: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/end-to-end_pipeline_security.svg
        shape: image
        label: "end-to-end_pipeline_security"
      }
  
  end_user_customers: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/end_user_customers.svg
        shape: image
        label: "end_user_customers"
      }
  
  eng_requires_new_level_speed_scale: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/eng_requires_new_level_speed_scale.svg
        shape: image
        label: "eng_requires_new_level_speed_scale"
      }
  
  enterprise-applications: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise-applications.svg
        shape: image
        label: "enterprise-applications"
      }
  
  enterprise: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise.svg
        shape: image
        label: "enterprise"
      }
  
  enterprise_deplyment: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_deplyment.svg
        shape: image
        label: "enterprise_deplyment"
      }
  
  enterprise_grade_storyage: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_grade_storyage.svg
        shape: image
        label: "enterprise_grade_storyage"
      }
  
  enterprise_ready_white: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_ready_white.svg
        shape: image
        label: "enterprise_ready_white"
      }
  
  enterprise_security: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_security.svg
        shape: image
        label: "enterprise_security"
      }
  
  entry_processor: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/entry_processor.svg
        shape: image
        label: "entry_processor"
      }
  
  exceed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/exceed.svg
        shape: image
        label: "exceed"
      }
  
  expert 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/expert 2.svg
        shape: image
        label: "expert 2"
      }
  
  expert: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/expert.svg
        shape: image
        label: "expert"
      }
  
  expiration_eviction: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/expiration_eviction.svg
        shape: image
        label: "expiration_eviction"
      }
  
  exploit_hardware_memory: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/exploit_hardware_memory.svg
        shape: image
        label: "exploit_hardware_memory"
      }
  
  faster_is_better: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/faster_is_better.svg
        shape: image
        label: "faster_is_better"
      }
  
  fast_cache: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fast_cache.svg
        shape: image
        label: "fast_cache"
      }
  
  fast_session_access: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fast_session_access.svg
        shape: image
        label: "fast_session_access"
      }
  
  fault_tolerance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fault_tolerance.svg
        shape: image
        label: "fault_tolerance"
      }
  
  fence_lock: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fence_lock.svg
        shape: image
        label: "fence_lock"
      }
  
  file: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/file.svg
        shape: image
        label: "file"
      }
  
  file1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/file1.svg
        shape: image
        label: "file1"
      }
  
  filter-1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/filter-1.svg
        shape: image
        label: "filter-1"
      }
  
  filter: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/filter.svg
        shape: image
        label: "filter"
      }
  
  finance_banking: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/finance_banking.svg
        shape: image
        label: "finance_banking"
      }
  
  financial-services: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/financial-services.svg
        shape: image
        label: "financial-services"
      }
  
  flexibility 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexibility 2.svg
        shape: image
        label: "flexibility 2"
      }
  
  flexibility: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexibility.svg
        shape: image
        label: "flexibility"
      }
  
  flexibility_2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexibility_2.svg
        shape: image
        label: "flexibility_2"
      }
  
  flexible_integration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexible_integration.svg
        shape: image
        label: "flexible_integration"
      }
  
  frankfurt: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/frankfurt.svg
        shape: image
        label: "frankfurt"
      }
  
  fully_use_resources: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fully_use_resources.svg
        shape: image
        label: "fully_use_resources"
      }
  
  gaming: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/gaming.svg
        shape: image
        label: "gaming"
      }
  
  gear: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/gear.svg
        shape: image
        label: "gear"
      }
  
  generic_WAN: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/generic_WAN.svg
        shape: image
        label: "generic_WAN"
      }
  
  github: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/github.svg
        shape: image
        label: "github"
      }
  
  google: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/google.svg
        shape: image
        label: "google"
      }
  
  government 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/government 2.svg
        shape: image
        label: "government 2"
      }
  
  government: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/government.svg
        shape: image
        label: "government"
      }
  
  green: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/green.svg
        shape: image
        label: "green"
      }
  
  handshake_integrator: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_integrator.svg
        shape: image
        label: "handshake_integrator"
      }
  
  handshake_OEM: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_OEM.svg
        shape: image
        label: "handshake_OEM"
      }
  
  handshake_reseller: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_reseller.svg
        shape: image
        label: "handshake_reseller"
      }
  
  handshake_technology: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_technology.svg
        shape: image
        label: "handshake_technology"
      }
  
  hands_on_assistance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hands_on_assistance.svg
        shape: image
        label: "hands_on_assistance"
      }
  
  hazelcast_cluster: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hazelcast_cluster.svg
        shape: image
        label: "hazelcast_cluster"
      }
  
  healthcare: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/healthcare.svg
        shape: image
        label: "healthcare"
      }
  
  Helm: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Helm.svg
        shape: image
        label: "Helm"
      }
  
  Hibernate: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Hibernate.svg
        shape: image
        label: "Hibernate"
      }
  
  high_density_caching: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_density_caching.svg
        shape: image
        label: "high_density_caching"
      }
  
  high_density_memory1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_density_memory1.svg
        shape: image
        label: "high_density_memory1"
      }
  
  high_performance_no_app_altercation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_performance_no_app_altercation.svg
        shape: image
        label: "high_performance_no_app_altercation"
      }
  
  high_productivity: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_productivity.svg
        shape: image
        label: "high_productivity"
      }
  
  hot_restart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hot_restart.svg
        shape: image
        label: "hot_restart"
      }
  
  hot_restart_store: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hot_restart_store.svg
        shape: image
        label: "hot_restart_store"
      }
  
  in-memory-cache: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in-memory-cache.svg
        shape: image
        label: "in-memory-cache"
      }
  
  in-memory: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in-memory.svg
        shape: image
        label: "in-memory"
      }
  
  in-memory_better_approach: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in-memory_better_approach.svg
        shape: image
        label: "in-memory_better_approach"
      }
  
  inform: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/inform.svg
        shape: image
        label: "inform"
      }
  
  innovation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/innovation.svg
        shape: image
        label: "innovation"
      }
  
  integration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/integration.svg
        shape: image
        label: "integration"
      }
  
  interactive-analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/interactive-analytics.svg
        shape: image
        label: "interactive-analytics"
      }
  
  internet-of-things: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/internet-of-things.svg
        shape: image
        label: "internet-of-things"
      }
  
  in_memory_nosql-1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in_memory_nosql-1.svg
        shape: image
        label: "in_memory_nosql-1"
      }
  
  Istanbul: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Istanbul.svg
        shape: image
        label: "Istanbul"
      }
  
  Java: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Java.svg
        shape: image
        label: "Java"
      }
  
  kafka: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/kafka.svg
        shape: image
        label: "kafka"
      }
  
  languages: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/languages.svg
        shape: image
        label: "languages"
      }
  
  latency_and_stability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/latency_and_stability.svg
        shape: image
        label: "latency_and_stability"
      }
  
  leverage_change_data_capture: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/leverage_change_data_capture.svg
        shape: image
        label: "leverage_change_data_capture"
      }
  
  linear_scaling_clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/linear_scaling_clusters.svg
        shape: image
        label: "linear_scaling_clusters"
      }
  
  list: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/list.svg
        shape: image
        label: "list"
      }
  
  listeners_interceptors: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/listeners_interceptors.svg
        shape: image
        label: "listeners_interceptors"
      }
  
  lock: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/lock.svg
        shape: image
        label: "lock"
      }
  
  logistics: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/logistics.svg
        shape: image
        label: "logistics"
      }
  
  logo_Hazelcast_JET_v2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/logo_Hazelcast_JET_v2.svg
        shape: image
        label: "logo_Hazelcast_JET_v2"
      }
  
  London: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/London.svg
        shape: image
        label: "London"
      }
  
  manageability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/manageability.svg
        shape: image
        label: "manageability"
      }
  
  management_center: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/management_center.svg
        shape: image
        label: "management_center"
      }
  
  map: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/map.svg
        shape: image
        label: "map"
      }
  
  massively_parallel_processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/massively_parallel_processing.svg
        shape: image
        label: "massively_parallel_processing"
      }
  
  maximum_service_isolation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/maximum_service_isolation.svg
        shape: image
        label: "maximum_service_isolation"
      }
  
  max_service_non-Java-_clients: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/max_service_non-Java-_clients.svg
        shape: image
        label: "max_service_non-Java-_clients"
      }
  
  media: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/media.svg
        shape: image
        label: "media"
      }
  
  member_rolling_upgrade: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/member_rolling_upgrade.svg
        shape: image
        label: "member_rolling_upgrade"
      }
  
  Memcached: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Memcached.svg
        shape: image
        label: "Memcached"
      }
  
  messaging-queue: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/messaging-queue.svg
        shape: image
        label: "messaging-queue"
      }
  
  messaging: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/messaging.svg
        shape: image
        label: "messaging"
      }
  
  microservices: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/microservices.svg
        shape: image
        label: "microservices"
      }
  
  milan: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/milan.svg
        shape: image
        label: "milan"
      }
  
  multicast: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/multicast.svg
        shape: image
        label: "multicast"
      }
  
  multiple_config_features: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/multiple_config_features.svg
        shape: image
        label: "multiple_config_features"
      }
  
  multiple_data_structures: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/multiple_data_structures.svg
        shape: image
        label: "multiple_data_structures"
      }
  
  native_memory_storage: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/native_memory_storage.svg
        shape: image
        label: "native_memory_storage"
      }
  
  new_york: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/new_york.svg
        shape: image
        label: "new_york"
      }
  
  noticeable_speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/noticeable_speed.svg
        shape: image
        label: "noticeable_speed"
      }
  
  object_relational_config: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/object_relational_config.svg
        shape: image
        label: "object_relational_config"
      }
  
  offered_existing_cluster: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/offered_existing_cluster.svg
        shape: image
        label: "offered_existing_cluster"
      }
  
  on-demand_sync_target_cluster: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/on-demand_sync_target_cluster.svg
        shape: image
        label: "on-demand_sync_target_cluster"
      }
  
  OPex: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/OPex.svg
        shape: image
        label: "OPex"
      }
  
  pdf: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pdf.svg
        shape: image
        label: "pdf"
      }
  
  peak-tower: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/peak-tower.svg
        shape: image
        label: "peak-tower"
      }
  
  persistent_state: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/persistent_state.svg
        shape: image
        label: "persistent_state"
      }
  
  phone: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/phone.svg
        shape: image
        label: "phone"
      }
  
  pipeline: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pipeline.svg
        shape: image
        label: "pipeline"
      }
  
  pn_counter: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pn_counter.svg
        shape: image
        label: "pn_counter"
      }
  
  predictable_results: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/predictable_results.svg
        shape: image
        label: "predictable_results"
      }
  
  prioritize_clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/prioritize_clusters.svg
        shape: image
        label: "prioritize_clusters"
      }
  
  process: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/process.svg
        shape: image
        label: "process"
      }
  
  processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/processing.svg
        shape: image
        label: "processing"
      }
  
  programmer: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/programmer.svg
        shape: image
        label: "programmer"
      }
  
  promote: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/promote.svg
        shape: image
        label: "promote"
      }
  
  pros: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pros.svg
        shape: image
        label: "pros"
      }
  
  query: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/query.svg
        shape: image
        label: "query"
      }
  
  query_results: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/query_results.svg
        shape: image
        label: "query_results"
      }
  
  queue: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/queue.svg
        shape: image
        label: "queue"
      }
  
  real-time-decisions: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/real-time-decisions.svg
        shape: image
        label: "real-time-decisions"
      }
  
  real_time_processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/real_time_processing.svg
        shape: image
        label: "real_time_processing"
      }
  
  real_time_push: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/real_time_push.svg
        shape: image
        label: "real_time_push"
      }
  
  reduce_fraud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/reduce_fraud.svg
        shape: image
        label: "reduce_fraud"
      }
  
  replicated_storage: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/replicated_storage.svg
        shape: image
        label: "replicated_storage"
      }
  
  reporting_requirements: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/reporting_requirements.svg
        shape: image
        label: "reporting_requirements"
      }
  
  restrooms: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/restrooms.svg
        shape: image
        label: "restrooms"
      }
  
  rewindable: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rewindable.svg
        shape: image
        label: "rewindable"
      }
  
  ringbuffer: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/ringbuffer.svg
        shape: image
        label: "ringbuffer"
      }
  
  risk-mitigation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/risk-mitigation.svg
        shape: image
        label: "risk-mitigation"
      }
  
  rolling_restart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rolling_restart.svg
        shape: image
        label: "rolling_restart"
      }
  
  rolling_upgrade 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rolling_upgrade 2.svg
        shape: image
        label: "rolling_upgrade 2"
      }
  
  rolling_upgrade: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rolling_upgrade.svg
        shape: image
        label: "rolling_upgrade"
      }
  
  run_anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/run_anywhere.svg
        shape: image
        label: "run_anywhere"
      }
  
  sales_force: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/sales_force.svg
        shape: image
        label: "sales_force"
      }
  
  scalability_2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_2.svg
        shape: image
        label: "scalability_2"
      }
  
  scalability_3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_3.svg
        shape: image
        label: "scalability_3"
      }
  
  scalability_4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_4.svg
        shape: image
        label: "scalability_4"
      }
  
  scalability_5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_5.svg
        shape: image
        label: "scalability_5"
      }
  
  search: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/search.svg
        shape: image
        label: "search"
      }
  
  secured_wifi: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/secured_wifi.svg
        shape: image
        label: "secured_wifi"
      }
  
  secure_cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/secure_cloud.svg
        shape: image
        label: "secure_cloud"
      }
  
  security: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security.svg
        shape: image
        label: "security"
      }
  
  security_2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_2.svg
        shape: image
        label: "security_2"
      }
  
  security_3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_3.svg
        shape: image
        label: "security_3"
      }
  
  security_4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_4.svg
        shape: image
        label: "security_4"
      }
  
  security_5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_5.svg
        shape: image
        label: "security_5"
      }
  
  security_suite: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_suite.svg
        shape: image
        label: "security_suite"
      }
  
  semaphore: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/semaphore.svg
        shape: image
        label: "semaphore"
      }
  
  separate_on-heap_and_high_density: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/separate_on-heap_and_high_density.svg
        shape: image
        label: "separate_on-heap_and_high_density"
      }
  
  server: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/server.svg
        shape: image
        label: "server"
      }
  
  shutdown_restart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/shutdown_restart.svg
        shape: image
        label: "shutdown_restart"
      }
  
  simple: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/simple.svg
        shape: image
        label: "simple"
      }
  
  Singapore: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Singapore.svg
        shape: image
        label: "Singapore"
      }
  
  single_source_truth: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/single_source_truth.svg
        shape: image
        label: "single_source_truth"
      }
  
  smart-clients: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/smart-clients.svg
        shape: image
        label: "smart-clients"
      }
  
  speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed.svg
        shape: image
        label: "speed"
      }
  
  speed_2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_2.svg
        shape: image
        label: "speed_2"
      }
  
  speed_3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_3.svg
        shape: image
        label: "speed_3"
      }
  
  speed_4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_4.svg
        shape: image
        label: "speed_4"
      }
  
  speed_performance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_performance.svg
        shape: image
        label: "speed_performance"
      }
  
  Spring_Boot: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Spring_Boot.svg
        shape: image
        label: "Spring_Boot"
      }
  
  stability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability.svg
        shape: image
        label: "stability"
      }
  
  stability_2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability_2.svg
        shape: image
        label: "stability_2"
      }
  
  stability_3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability_3.svg
        shape: image
        label: "stability_3"
      }
  
  stability_4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability_4.svg
        shape: image
        label: "stability_4"
      }
  
  supports_CNAME: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/supports_CNAME.svg
        shape: image
        label: "supports_CNAME"
      }
  
  support_multiple_discovery_mechanisms: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/support_multiple_discovery_mechanisms.svg
        shape: image
        label: "support_multiple_discovery_mechanisms"
      }
  
  telecom 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/telecom 2.svg
        shape: image
        label: "telecom 2"
      }
  
  telecom: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/telecom.svg
        shape: image
        label: "telecom"
      }
  
  time_expired: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/time_expired.svg
        shape: image
        label: "time_expired"
      }
  
  tokyo: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/tokyo.svg
        shape: image
        label: "tokyo"
      }
  
  topic: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/topic.svg
        shape: image
        label: "topic"
      }
  
  transaction-processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/transaction-processing.svg
        shape: image
        label: "transaction-processing"
      }
  
  transition_to_microservices: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/transition_to_microservices.svg
        shape: image
        label: "transition_to_microservices"
      }
  
  USA: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/USA.svg
        shape: image
        label: "USA"
      }
  
  user-experience: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/user-experience.svg
        shape: image
        label: "user-experience"
      }
  
  VPC_Peering-2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/VPC_Peering-2.svg
        shape: image
        label: "VPC_Peering-2"
      }
  
  WAN_replication: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/WAN_replication.svg
        shape: image
        label: "WAN_replication"
      }
  
  web_sessions_clustering-: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/web_sessions_clustering-.svg
        shape: image
        label: "web_sessions_clustering-"
      }
  
  web_session_clustering: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/web_session_clustering.svg
        shape: image
        label: "web_session_clustering"
      }
  
  world_class_service: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/world_class_service.svg
        shape: image
        label: "world_class_service"
      }
  
  zendesk: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/zendesk.svg
        shape: image
        label: "zendesk"
      }
  
}