classes: {
  
  
  Access Control: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/access_control.svg
        shape: image
        label: "Access Control"
      }
  
  
  Aggregation Process: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/aggregation_process.svg
        shape: image
        label: "Aggregation Process"
      }
  
  
  Agile Scrum: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/agile_scrum.svg
        shape: image
        label: "Agile Scrum"
      }
  
  
  Alerts: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/alerts.svg
        shape: image
        label: "Alerts"
      }
  
  
  Application: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/application.svg
        shape: image
        label: "Application"
      }
  
  
  Application Caching: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/application_caching.svg
        shape: image
        label: "Application Caching"
      }
  
  
  Architecture: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/architecture.svg
        shape: image
        label: "Architecture"
      }
  
  
  Authentication: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/authentication.svg
        shape: image
        label: "Authentication"
      }
  
  
  Authorization: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/authorization.svg
        shape: image
        label: "Authorization"
      }
  
  
  Automatic Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/automatic_configuration.svg
        shape: image
        label: "Automatic Configuration"
      }
  
  
  Availability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/availability.svg
        shape: image
        label: "Availability"
      }
  
  
  Available: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/available.svg
        shape: image
        label: "Available"
      }
  
  
  Balancing Act: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/balancing_act.svg
        shape: image
        label: "Balancing Act"
      }
  
  
  Big Data: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/big_data.svg
        shape: image
        label: "Big Data"
      }
  
  
  Blacklist Whitelist: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Blacklist_Whitelist.svg
        shape: image
        label: "Blacklist Whitelist"
      }
  
  
  Blazing Speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/blazing_speed.svg
        shape: image
        label: "Blazing Speed"
      }
  
  
  Break Time: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/break_time.svg
        shape: image
        label: "Break Time"
      }
  
  
  Bug Fixes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/bug_fixes.svg
        shape: image
        label: "Bug Fixes"
      }
  
  
  Business Logic Changes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/business_logic_changes.svg
        shape: image
        label: "Business Logic Changes"
      }
  
  
  Cache As Service: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cache_as_service.svg
        shape: image
        label: "Cache As Service"
      }
  
  
  Centralized Management Api: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/centralized_management_API.svg
        shape: image
        label: "Centralized Management Api"
      }
  
  
  Centralized Monitoring: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/centralized_monitoring.svg
        shape: image
        label: "Centralized Monitoring"
      }
  
  
  Checkpointing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/checkpointing.svg
        shape: image
        label: "Checkpointing"
      }
  
  
  Chicago: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/chicago.svg
        shape: image
        label: "Chicago"
      }
  
  
  Client Rolling Upgrade: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/client_rolling_upgrade.svg
        shape: image
        label: "Client Rolling Upgrade"
      }
  
  
  Cloud-applications: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud-applications.svg
        shape: image
        label: "Cloud-applications"
      }
  
  
  Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud.svg
        shape: image
        label: "Cloud"
      }
  
  
  Cloud Dedicated: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_dedicated.svg
        shape: image
        label: "Cloud Dedicated"
      }
  
  
  Cloud Discovery: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_discovery.svg
        shape: image
        label: "Cloud Discovery"
      }
  
  
  Cloud Enterprise: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_enterprise.svg
        shape: image
        label: "Cloud Enterprise"
      }
  
  
  Cloud Free: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_free.svg
        shape: image
        label: "Cloud Free"
      }
  
  
  Cloud Native Dev: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_native_dev.svg
        shape: image
        label: "Cloud Native Dev"
      }
  
  
  Cloud On Prem: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cloud_on_prem.svg
        shape: image
        label: "Cloud On Prem"
      }
  
  
  Cloud Paas: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Cloud_Paas.svg
        shape: image
        label: "Cloud Paas"
      }
  
  
  Cluster Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cluster_configuration.svg
        shape: image
        label: "Cluster Configuration"
      }
  
  
  Cluster Stats: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cluster_stats.svg
        shape: image
        label: "Cluster Stats"
      }
  
  
  Collect: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/collect.svg
        shape: image
        label: "Collect"
      }
  
  
  Community: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/community.svg
        shape: image
        label: "Community"
      }
  
  
  Comprehensive: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/comprehensive.svg
        shape: image
        label: "Comprehensive"
      }
  
  
  Configuration Changes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/configuration_changes.svg
        shape: image
        label: "Configuration Changes"
      }
  
  
  Config Client Behavior: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/config_client_behavior.svg
        shape: image
        label: "Config Client Behavior"
      }
  
  
  Confused: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/confused.svg
        shape: image
        label: "Confused"
      }
  
  
  Connector: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/connector.svg
        shape: image
        label: "Connector"
      }
  
  
  Cons: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/cons.svg
        shape: image
        label: "Cons"
      }
  
  
  Continuous Processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/continuous_processing.svg
        shape: image
        label: "Continuous Processing"
      }
  
  
  Contribute: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/contribute.svg
        shape: image
        label: "Contribute"
      }
  
  
  Custom-sources: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/custom-sources.svg
        shape: image
        label: "Custom-sources"
      }
  
  
  Data pipeline: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Data Pipeline.svg
        shape: image
        label: "Data pipeline"
      }
  
  
  Database: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/database.svg
        shape: image
        label: "Database"
      }
  
  
  Data Persistence: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/data_persistence.svg
        shape: image
        label: "Data Persistence"
      }
  
  
  Data Privacy: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/data_privacy.svg
        shape: image
        label: "Data Privacy"
      }
  
  
  Data Structure Stats: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/data_structure_stats.svg
        shape: image
        label: "Data Structure Stats"
      }
  
  
  Deep Expertise: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/deep_expertise.svg
        shape: image
        label: "Deep Expertise"
      }
  
  
  Deploy Anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/deploy_anywhere.svg
        shape: image
        label: "Deploy Anywhere"
      }
  
  
  Development Costs: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/development_costs.svg
        shape: image
        label: "Development Costs"
      }
  
  
  Disaster Recovery: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/disaster_recovery.svg
        shape: image
        label: "Disaster Recovery"
      }
  
  
  Docker: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/docker.svg
        shape: image
        label: "Docker"
      }
  
  
  Domain Control: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/domain_control.svg
        shape: image
        label: "Domain Control"
      }
  
  
  Easy Scale Out: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/easy_scale_out.svg
        shape: image
        label: "Easy Scale Out"
      }
  
  
  Ecommerce: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/ecommerce.svg
        shape: image
        label: "Ecommerce"
      }
  
  
  Elastic: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/elastic.svg
        shape: image
        label: "Elastic"
      }
  
  
  Elastic Clustering: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/elastic_clustering.svg
        shape: image
        label: "Elastic Clustering"
      }
  
  
  Elastic Scalability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/elastic_scalability.svg
        shape: image
        label: "Elastic Scalability"
      }
  
  
  End-to-end Pipeline Security: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/end-to-end_pipeline_security.svg
        shape: image
        label: "End-to-end Pipeline Security"
      }
  
  
  End User Customers: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/end_user_customers.svg
        shape: image
        label: "End User Customers"
      }
  
  
  Eng Requires New Level Speed Scale: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/eng_requires_new_level_speed_scale.svg
        shape: image
        label: "Eng Requires New Level Speed Scale"
      }
  
  
  Enterprise-applications: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise-applications.svg
        shape: image
        label: "Enterprise-applications"
      }
  
  
  Enterprise: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise.svg
        shape: image
        label: "Enterprise"
      }
  
  
  Enterprise Deplyment: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_deplyment.svg
        shape: image
        label: "Enterprise Deplyment"
      }
  
  
  Enterprise Grade Storyage: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_grade_storyage.svg
        shape: image
        label: "Enterprise Grade Storyage"
      }
  
  
  Enterprise Ready White: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_ready_white.svg
        shape: image
        label: "Enterprise Ready White"
      }
  
  
  Enterprise Security: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/enterprise_security.svg
        shape: image
        label: "Enterprise Security"
      }
  
  
  Entry Processor: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/entry_processor.svg
        shape: image
        label: "Entry Processor"
      }
  
  
  Exceed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/exceed.svg
        shape: image
        label: "Exceed"
      }
  
  
  Expert 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/expert 2.svg
        shape: image
        label: "Expert 2"
      }
  
  
  Expert: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/expert.svg
        shape: image
        label: "Expert"
      }
  
  
  Expiration Eviction: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/expiration_eviction.svg
        shape: image
        label: "Expiration Eviction"
      }
  
  
  Exploit Hardware Memory: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/exploit_hardware_memory.svg
        shape: image
        label: "Exploit Hardware Memory"
      }
  
  
  Faster Is Better: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/faster_is_better.svg
        shape: image
        label: "Faster Is Better"
      }
  
  
  Fast Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fast_cache.svg
        shape: image
        label: "Fast Cache"
      }
  
  
  Fast Session Access: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fast_session_access.svg
        shape: image
        label: "Fast Session Access"
      }
  
  
  Fault Tolerance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fault_tolerance.svg
        shape: image
        label: "Fault Tolerance"
      }
  
  
  Fence Lock: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fence_lock.svg
        shape: image
        label: "Fence Lock"
      }
  
  
  File: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/file.svg
        shape: image
        label: "File"
      }
  
  
  File1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/file1.svg
        shape: image
        label: "File1"
      }
  
  
  Filter-1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/filter-1.svg
        shape: image
        label: "Filter-1"
      }
  
  
  Filter: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/filter.svg
        shape: image
        label: "Filter"
      }
  
  
  Finance Banking: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/finance_banking.svg
        shape: image
        label: "Finance Banking"
      }
  
  
  Financial-services: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/financial-services.svg
        shape: image
        label: "Financial-services"
      }
  
  
  Flexibility 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexibility 2.svg
        shape: image
        label: "Flexibility 2"
      }
  
  
  Flexibility: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexibility.svg
        shape: image
        label: "Flexibility"
      }
  
  
  Flexibility 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexibility_2.svg
        shape: image
        label: "Flexibility 2"
      }
  
  
  Flexible Integration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/flexible_integration.svg
        shape: image
        label: "Flexible Integration"
      }
  
  
  Frankfurt: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/frankfurt.svg
        shape: image
        label: "Frankfurt"
      }
  
  
  Fully Use Resources: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/fully_use_resources.svg
        shape: image
        label: "Fully Use Resources"
      }
  
  
  Gaming: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/gaming.svg
        shape: image
        label: "Gaming"
      }
  
  
  Gear: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/gear.svg
        shape: image
        label: "Gear"
      }
  
  
  Generic Wan: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/generic_WAN.svg
        shape: image
        label: "Generic Wan"
      }
  
  
  Github: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/github.svg
        shape: image
        label: "Github"
      }
  
  
  Google: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/google.svg
        shape: image
        label: "Google"
      }
  
  
  Government 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/government 2.svg
        shape: image
        label: "Government 2"
      }
  
  
  Government: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/government.svg
        shape: image
        label: "Government"
      }
  
  
  Green: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/green.svg
        shape: image
        label: "Green"
      }
  
  
  Handshake Integrator: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_integrator.svg
        shape: image
        label: "Handshake Integrator"
      }
  
  
  Handshake Oem: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_OEM.svg
        shape: image
        label: "Handshake Oem"
      }
  
  
  Handshake Reseller: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_reseller.svg
        shape: image
        label: "Handshake Reseller"
      }
  
  
  Handshake Technology: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/handshake_technology.svg
        shape: image
        label: "Handshake Technology"
      }
  
  
  Hands On Assistance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hands_on_assistance.svg
        shape: image
        label: "Hands On Assistance"
      }
  
  
  Hazelcast Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hazelcast_cluster.svg
        shape: image
        label: "Hazelcast Cluster"
      }
  
  
  Healthcare: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/healthcare.svg
        shape: image
        label: "Healthcare"
      }
  
  
  Helm: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Helm.svg
        shape: image
        label: "Helm"
      }
  
  
  Hibernate: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Hibernate.svg
        shape: image
        label: "Hibernate"
      }
  
  
  High Density Caching: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_density_caching.svg
        shape: image
        label: "High Density Caching"
      }
  
  
  High Density Memory1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_density_memory1.svg
        shape: image
        label: "High Density Memory1"
      }
  
  
  High Performance No App Altercation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_performance_no_app_altercation.svg
        shape: image
        label: "High Performance No App Altercation"
      }
  
  
  High Productivity: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/high_productivity.svg
        shape: image
        label: "High Productivity"
      }
  
  
  Hot Restart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hot_restart.svg
        shape: image
        label: "Hot Restart"
      }
  
  
  Hot Restart Store: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/hot_restart_store.svg
        shape: image
        label: "Hot Restart Store"
      }
  
  
  In-memory-cache: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in-memory-cache.svg
        shape: image
        label: "In-memory-cache"
      }
  
  
  In-memory: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in-memory.svg
        shape: image
        label: "In-memory"
      }
  
  
  In-memory Better Approach: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in-memory_better_approach.svg
        shape: image
        label: "In-memory Better Approach"
      }
  
  
  Inform: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/inform.svg
        shape: image
        label: "Inform"
      }
  
  
  Innovation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/innovation.svg
        shape: image
        label: "Innovation"
      }
  
  
  Integration: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/integration.svg
        shape: image
        label: "Integration"
      }
  
  
  Interactive-analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/interactive-analytics.svg
        shape: image
        label: "Interactive-analytics"
      }
  
  
  Internet-of-things: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/internet-of-things.svg
        shape: image
        label: "Internet-of-things"
      }
  
  
  In Memory Nosql-1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/in_memory_nosql-1.svg
        shape: image
        label: "In Memory Nosql-1"
      }
  
  
  Istanbul: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Istanbul.svg
        shape: image
        label: "Istanbul"
      }
  
  
  Java: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Java.svg
        shape: image
        label: "Java"
      }
  
  
  Kafka: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/kafka.svg
        shape: image
        label: "Kafka"
      }
  
  
  Languages: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/languages.svg
        shape: image
        label: "Languages"
      }
  
  
  Latency And Stability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/latency_and_stability.svg
        shape: image
        label: "Latency And Stability"
      }
  
  
  Leverage Change Data Capture: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/leverage_change_data_capture.svg
        shape: image
        label: "Leverage Change Data Capture"
      }
  
  
  Linear Scaling Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/linear_scaling_clusters.svg
        shape: image
        label: "Linear Scaling Clusters"
      }
  
  
  List: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/list.svg
        shape: image
        label: "List"
      }
  
  
  Listeners Interceptors: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/listeners_interceptors.svg
        shape: image
        label: "Listeners Interceptors"
      }
  
  
  Lock: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/lock.svg
        shape: image
        label: "Lock"
      }
  
  
  Logistics: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/logistics.svg
        shape: image
        label: "Logistics"
      }
  
  
  Logo Hazelcast Jet V2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/logo_Hazelcast_JET_v2.svg
        shape: image
        label: "Logo Hazelcast Jet V2"
      }
  
  
  London: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/London.svg
        shape: image
        label: "London"
      }
  
  
  Manageability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/manageability.svg
        shape: image
        label: "Manageability"
      }
  
  
  Management Center: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/management_center.svg
        shape: image
        label: "Management Center"
      }
  
  
  Map: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/map.svg
        shape: image
        label: "Map"
      }
  
  
  Massively Parallel Processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/massively_parallel_processing.svg
        shape: image
        label: "Massively Parallel Processing"
      }
  
  
  Maximum Service Isolation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/maximum_service_isolation.svg
        shape: image
        label: "Maximum Service Isolation"
      }
  
  
  Max Service Non-java- Clients: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/max_service_non-Java-_clients.svg
        shape: image
        label: "Max Service Non-java- Clients"
      }
  
  
  Media: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/media.svg
        shape: image
        label: "Media"
      }
  
  
  Member Rolling Upgrade: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/member_rolling_upgrade.svg
        shape: image
        label: "Member Rolling Upgrade"
      }
  
  
  Memcached: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Memcached.svg
        shape: image
        label: "Memcached"
      }
  
  
  Messaging-queue: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/messaging-queue.svg
        shape: image
        label: "Messaging-queue"
      }
  
  
  Messaging: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/messaging.svg
        shape: image
        label: "Messaging"
      }
  
  
  Microservices: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/microservices.svg
        shape: image
        label: "Microservices"
      }
  
  
  Milan: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/milan.svg
        shape: image
        label: "Milan"
      }
  
  
  Multicast: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/multicast.svg
        shape: image
        label: "Multicast"
      }
  
  
  Multiple Config Features: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/multiple_config_features.svg
        shape: image
        label: "Multiple Config Features"
      }
  
  
  Multiple Data Structures: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/multiple_data_structures.svg
        shape: image
        label: "Multiple Data Structures"
      }
  
  
  Native Memory Storage: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/native_memory_storage.svg
        shape: image
        label: "Native Memory Storage"
      }
  
  
  New York: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/new_york.svg
        shape: image
        label: "New York"
      }
  
  
  Noticeable Speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/noticeable_speed.svg
        shape: image
        label: "Noticeable Speed"
      }
  
  
  Object Relational Config: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/object_relational_config.svg
        shape: image
        label: "Object Relational Config"
      }
  
  
  Offered Existing Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/offered_existing_cluster.svg
        shape: image
        label: "Offered Existing Cluster"
      }
  
  
  On-demand Sync Target Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/on-demand_sync_target_cluster.svg
        shape: image
        label: "On-demand Sync Target Cluster"
      }
  
  
  Opex: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/OPex.svg
        shape: image
        label: "Opex"
      }
  
  
  Pdf: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pdf.svg
        shape: image
        label: "Pdf"
      }
  
  
  Peak-tower: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/peak-tower.svg
        shape: image
        label: "Peak-tower"
      }
  
  
  Persistent State: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/persistent_state.svg
        shape: image
        label: "Persistent State"
      }
  
  
  Phone: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/phone.svg
        shape: image
        label: "Phone"
      }
  
  
  Pipeline: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pipeline.svg
        shape: image
        label: "Pipeline"
      }
  
  
  Pn Counter: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pn_counter.svg
        shape: image
        label: "Pn Counter"
      }
  
  
  Predictable Results: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/predictable_results.svg
        shape: image
        label: "Predictable Results"
      }
  
  
  Prioritize Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/prioritize_clusters.svg
        shape: image
        label: "Prioritize Clusters"
      }
  
  
  Process: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/process.svg
        shape: image
        label: "Process"
      }
  
  
  Processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/processing.svg
        shape: image
        label: "Processing"
      }
  
  
  Programmer: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/programmer.svg
        shape: image
        label: "Programmer"
      }
  
  
  Promote: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/promote.svg
        shape: image
        label: "Promote"
      }
  
  
  Pros: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/pros.svg
        shape: image
        label: "Pros"
      }
  
  
  Query: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/query.svg
        shape: image
        label: "Query"
      }
  
  
  Query Results: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/query_results.svg
        shape: image
        label: "Query Results"
      }
  
  
  Queue: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/queue.svg
        shape: image
        label: "Queue"
      }
  
  
  Real-time-decisions: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/real-time-decisions.svg
        shape: image
        label: "Real-time-decisions"
      }
  
  
  Real Time Processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/real_time_processing.svg
        shape: image
        label: "Real Time Processing"
      }
  
  
  Real Time Push: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/real_time_push.svg
        shape: image
        label: "Real Time Push"
      }
  
  
  Reduce Fraud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/reduce_fraud.svg
        shape: image
        label: "Reduce Fraud"
      }
  
  
  Replicated Storage: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/replicated_storage.svg
        shape: image
        label: "Replicated Storage"
      }
  
  
  Reporting Requirements: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/reporting_requirements.svg
        shape: image
        label: "Reporting Requirements"
      }
  
  
  Restrooms: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/restrooms.svg
        shape: image
        label: "Restrooms"
      }
  
  
  Rewindable: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rewindable.svg
        shape: image
        label: "Rewindable"
      }
  
  
  Ringbuffer: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/ringbuffer.svg
        shape: image
        label: "Ringbuffer"
      }
  
  
  Risk-mitigation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/risk-mitigation.svg
        shape: image
        label: "Risk-mitigation"
      }
  
  
  Rolling Restart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rolling_restart.svg
        shape: image
        label: "Rolling Restart"
      }
  
  
  Rolling Upgrade 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rolling_upgrade 2.svg
        shape: image
        label: "Rolling Upgrade 2"
      }
  
  
  Rolling Upgrade: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/rolling_upgrade.svg
        shape: image
        label: "Rolling Upgrade"
      }
  
  
  Run Anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/run_anywhere.svg
        shape: image
        label: "Run Anywhere"
      }
  
  
  Sales Force: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/sales_force.svg
        shape: image
        label: "Sales Force"
      }
  
  
  Scalability 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_2.svg
        shape: image
        label: "Scalability 2"
      }
  
  
  Scalability 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_3.svg
        shape: image
        label: "Scalability 3"
      }
  
  
  Scalability 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_4.svg
        shape: image
        label: "Scalability 4"
      }
  
  
  Scalability 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/scalability_5.svg
        shape: image
        label: "Scalability 5"
      }
  
  
  Search: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/search.svg
        shape: image
        label: "Search"
      }
  
  
  Secured Wifi: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/secured_wifi.svg
        shape: image
        label: "Secured Wifi"
      }
  
  
  Secure Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/secure_cloud.svg
        shape: image
        label: "Secure Cloud"
      }
  
  
  Security: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security.svg
        shape: image
        label: "Security"
      }
  
  
  Security 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_2.svg
        shape: image
        label: "Security 2"
      }
  
  
  Security 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_3.svg
        shape: image
        label: "Security 3"
      }
  
  
  Security 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_4.svg
        shape: image
        label: "Security 4"
      }
  
  
  Security 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_5.svg
        shape: image
        label: "Security 5"
      }
  
  
  Security Suite: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/security_suite.svg
        shape: image
        label: "Security Suite"
      }
  
  
  Semaphore: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/semaphore.svg
        shape: image
        label: "Semaphore"
      }
  
  
  Separate On-heap And High Density: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/separate_on-heap_and_high_density.svg
        shape: image
        label: "Separate On-heap And High Density"
      }
  
  
  Server: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/server.svg
        shape: image
        label: "Server"
      }
  
  
  Shutdown Restart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/shutdown_restart.svg
        shape: image
        label: "Shutdown Restart"
      }
  
  
  Simple: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/simple.svg
        shape: image
        label: "Simple"
      }
  
  
  Singapore: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Singapore.svg
        shape: image
        label: "Singapore"
      }
  
  
  Single Source Truth: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/single_source_truth.svg
        shape: image
        label: "Single Source Truth"
      }
  
  
  Smart-clients: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/smart-clients.svg
        shape: image
        label: "Smart-clients"
      }
  
  
  Speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed.svg
        shape: image
        label: "Speed"
      }
  
  
  Speed 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_2.svg
        shape: image
        label: "Speed 2"
      }
  
  
  Speed 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_3.svg
        shape: image
        label: "Speed 3"
      }
  
  
  Speed 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_4.svg
        shape: image
        label: "Speed 4"
      }
  
  
  Speed Performance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/speed_performance.svg
        shape: image
        label: "Speed Performance"
      }
  
  
  Spring Boot: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/Spring_Boot.svg
        shape: image
        label: "Spring Boot"
      }
  
  
  Stability: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability.svg
        shape: image
        label: "Stability"
      }
  
  
  Stability 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability_2.svg
        shape: image
        label: "Stability 2"
      }
  
  
  Stability 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability_3.svg
        shape: image
        label: "Stability 3"
      }
  
  
  Stability 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/stability_4.svg
        shape: image
        label: "Stability 4"
      }
  
  
  Supports Cname: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/supports_CNAME.svg
        shape: image
        label: "Supports Cname"
      }
  
  
  Support Multiple Discovery Mechanisms: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/support_multiple_discovery_mechanisms.svg
        shape: image
        label: "Support Multiple Discovery Mechanisms"
      }
  
  
  Telecom 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/telecom 2.svg
        shape: image
        label: "Telecom 2"
      }
  
  
  Telecom: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/telecom.svg
        shape: image
        label: "Telecom"
      }
  
  
  Time Expired: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/time_expired.svg
        shape: image
        label: "Time Expired"
      }
  
  
  Tokyo: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/tokyo.svg
        shape: image
        label: "Tokyo"
      }
  
  
  Topic: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/topic.svg
        shape: image
        label: "Topic"
      }
  
  
  Transaction-processing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/transaction-processing.svg
        shape: image
        label: "Transaction-processing"
      }
  
  
  Transition To Microservices: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/transition_to_microservices.svg
        shape: image
        label: "Transition To Microservices"
      }
  
  
  Usa: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/USA.svg
        shape: image
        label: "Usa"
      }
  
  
  User-experience: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/user-experience.svg
        shape: image
        label: "User-experience"
      }
  
  
  Vpc Peering-2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/VPC_Peering-2.svg
        shape: image
        label: "Vpc Peering-2"
      }
  
  
  Wan Replication: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/WAN_replication.svg
        shape: image
        label: "Wan Replication"
      }
  
  
  Web Sessions Clustering-: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/web_sessions_clustering-.svg
        shape: image
        label: "Web Sessions Clustering-"
      }
  
  
  Web Session Clustering: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/web_session_clustering.svg
        shape: image
        label: "Web Session Clustering"
      }
  
  
  World Class Service: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/world_class_service.svg
        shape: image
        label: "World Class Service"
      }
  
  
  Zendesk: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/generic/zendesk.svg
        shape: image
        label: "Zendesk"
      }
  
}