classes: {
  
  
  Res Amazon Cloudwatch Alarm: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Alarm.svg
        shape: image
        label: "Res Amazon Cloudwatch Alarm"
      }
  
  
  Res Amazon Cloudwatch Cross Account Observability: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Cross_account_Observability.svg
        shape: image
        label: "Res Amazon Cloudwatch Cross Account Observability"
      }
  
  
  Res Amazon Cloudwatch Data Protection: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Data_Protection.svg
        shape: image
        label: "Res Amazon Cloudwatch Data Protection"
      }
  
  
  Res Amazon Cloudwatch Event Event Based: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Event_Event_Based.svg
        shape: image
        label: "Res Amazon Cloudwatch Event Event Based"
      }
  
  
  Res Amazon Cloudwatch Event Time Based: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Event_Time_Based.svg
        shape: image
        label: "Res Amazon Cloudwatch Event Time Based"
      }
  
  
  Res Amazon Cloudwatch Evidently: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Evidently.svg
        shape: image
        label: "Res Amazon Cloudwatch Evidently"
      }
  
  
  Res Amazon Cloudwatch Logs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Logs.svg
        shape: image
        label: "Res Amazon Cloudwatch Logs"
      }
  
  
  Res Amazon Cloudwatch Metrics Insights: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Metrics_Insights.svg
        shape: image
        label: "Res Amazon Cloudwatch Metrics Insights"
      }
  
  
  Res Amazon Cloudwatch Rule: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Rule.svg
        shape: image
        label: "Res Amazon Cloudwatch Rule"
      }
  
  
  Res Amazon Cloudwatch Rum: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_RUM.svg
        shape: image
        label: "Res Amazon Cloudwatch Rum"
      }
  
  
  Res Amazon Cloudwatch Synthetics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_Amazon_CloudWatch_Synthetics.svg
        shape: image
        label: "Res Amazon Cloudwatch Synthetics"
      }
  
  
  Res Aws Cloudformation Change Set: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_CloudFormation_Change_Set.svg
        shape: image
        label: "Res Aws Cloudformation Change Set"
      }
  
  
  Res Aws Cloudformation Stack: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_CloudFormation_Stack.svg
        shape: image
        label: "Res Aws Cloudformation Stack"
      }
  
  
  Res Aws Cloudformation Template: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_CloudFormation_Template.svg
        shape: image
        label: "Res Aws Cloudformation Template"
      }
  
  
  Res Aws Cloudtrail Cloudtrail Lake: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_CloudTrail_CloudTrail_Lake.svg
        shape: image
        label: "Res Aws Cloudtrail Cloudtrail Lake"
      }
  
  
  Res Aws License Manager Application Discovery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_License_Manager_Application_Discovery.svg
        shape: image
        label: "Res Aws License Manager Application Discovery"
      }
  
  
  Res Aws License Manager License Blending: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_License_Manager_License_Blending.svg
        shape: image
        label: "Res Aws License Manager License Blending"
      }
  
  
  Res Aws Opsworks Apps: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Apps.svg
        shape: image
        label: "Res Aws Opsworks Apps"
      }
  
  
  Res Aws Opsworks Deployments: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Deployments.svg
        shape: image
        label: "Res Aws Opsworks Deployments"
      }
  
  
  Res Aws Opsworks Instances: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Instances.svg
        shape: image
        label: "Res Aws Opsworks Instances"
      }
  
  
  Res Aws Opsworks Layers: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Layers.svg
        shape: image
        label: "Res Aws Opsworks Layers"
      }
  
  
  Res Aws Opsworks Monitoring: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Monitoring.svg
        shape: image
        label: "Res Aws Opsworks Monitoring"
      }
  
  
  Res Aws Opsworks Permissions: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Permissions.svg
        shape: image
        label: "Res Aws Opsworks Permissions"
      }
  
  
  Res Aws Opsworks Resources: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Resources.svg
        shape: image
        label: "Res Aws Opsworks Resources"
      }
  
  
  Res Aws Opsworks Stack: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_OpsWorks_Stack.svg
        shape: image
        label: "Res Aws Opsworks Stack"
      }
  
  
  Res Aws Organizations Account: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Organizations_Account.svg
        shape: image
        label: "Res Aws Organizations Account"
      }
  
  
  Res Aws Organizations Management Account: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Organizations_Management_Account.svg
        shape: image
        label: "Res Aws Organizations Management Account"
      }
  
  
  Res Aws Organizations Organizational Unit: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Organizations_Organizational_Unit.svg
        shape: image
        label: "Res Aws Organizations Organizational Unit"
      }
  
  
  Res Aws Systems Manager Application Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Application_Manager.svg
        shape: image
        label: "Res Aws Systems Manager Application Manager"
      }
  
  
  Res Aws Systems Manager Automation: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Automation.svg
        shape: image
        label: "Res Aws Systems Manager Automation"
      }
  
  
  Res Aws Systems Manager Change Calendar: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Change_Calendar.svg
        shape: image
        label: "Res Aws Systems Manager Change Calendar"
      }
  
  
  Res Aws Systems Manager Change Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Change_Manager.svg
        shape: image
        label: "Res Aws Systems Manager Change Manager"
      }
  
  
  Res Aws Systems Manager Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Compliance.svg
        shape: image
        label: "Res Aws Systems Manager Compliance"
      }
  
  
  Res Aws Systems Manager Distributor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Distributor.svg
        shape: image
        label: "Res Aws Systems Manager Distributor"
      }
  
  
  Res Aws Systems Manager Documents: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Documents.svg
        shape: image
        label: "Res Aws Systems Manager Documents"
      }
  
  
  Res Aws Systems Manager Incident Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Incident_Manager.svg
        shape: image
        label: "Res Aws Systems Manager Incident Manager"
      }
  
  
  Res Aws Systems Manager Inventory: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Inventory.svg
        shape: image
        label: "Res Aws Systems Manager Inventory"
      }
  
  
  Res Aws Systems Manager Maintenance Windows: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Maintenance_Windows.svg
        shape: image
        label: "Res Aws Systems Manager Maintenance Windows"
      }
  
  
  Res Aws Systems Manager Opscenter: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_OpsCenter.svg
        shape: image
        label: "Res Aws Systems Manager Opscenter"
      }
  
  
  Res Aws Systems Manager Parameter Store: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Parameter_Store.svg
        shape: image
        label: "Res Aws Systems Manager Parameter Store"
      }
  
  
  Res Aws Systems Manager Patch Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Patch_Manager.svg
        shape: image
        label: "Res Aws Systems Manager Patch Manager"
      }
  
  
  Res Aws Systems Manager Run Command: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Run_Command.svg
        shape: image
        label: "Res Aws Systems Manager Run Command"
      }
  
  
  Res Aws Systems Manager Session Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_Session_Manager.svg
        shape: image
        label: "Res Aws Systems Manager Session Manager"
      }
  
  
  Res Aws Systems Manager State Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Systems_Manager_State_Manager.svg
        shape: image
        label: "Res Aws Systems Manager State Manager"
      }
  
  
  Res Aws Trusted Advisor Checklist: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Trusted_Advisor_Checklist.svg
        shape: image
        label: "Res Aws Trusted Advisor Checklist"
      }
  
  
  Res Aws Trusted Advisor Checklist Cost: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Trusted_Advisor_Checklist_Cost.svg
        shape: image
        label: "Res Aws Trusted Advisor Checklist Cost"
      }
  
  
  Res Aws Trusted Advisor Checklist Fault Tolerant: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Trusted_Advisor_Checklist_Fault_Tolerant.svg
        shape: image
        label: "Res Aws Trusted Advisor Checklist Fault Tolerant"
      }
  
  
  Res Aws Trusted Advisor Checklist Performance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Trusted_Advisor_Checklist_Performance.svg
        shape: image
        label: "Res Aws Trusted Advisor Checklist Performance"
      }
  
  
  Res Aws Trusted Advisor Checklist Security: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Management-Governance/Res_AWS_Trusted_Advisor_Checklist_Security.svg
        shape: image
        label: "Res Aws Trusted Advisor Checklist Security"
      }
  
}