Cloud Composer: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_composer.svg
    shape: image
    label: "Cloud Composer"
  }

  Dataflow: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataflow.svg
    shape: image
    label: "Dataflow"
  }

  Dataplex: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataplex.svg
    shape: image
    label: "Dataplex"
  }

  Datashare: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datashare.svg
    shape: image
    label: "Datashare"
  }

  Data Catalog: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_catalog.svg
    shape: image
    label: "Data Catalog"
  }

  Looker: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/looker.svg
    shape: image
    label: "Looker"
  }

  Cloud Sql: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_sql.svg
    shape: image
    label: "Cloud Sql"
  }


Cloud Storage: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_storage.svg
    shape: image
    label: "Cloud Storage"
  }

  Data Studio: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_studio.svg
    shape: image
    label: "Data Studio"
  }


Data Transfer: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_transfer.svg
    shape: image
    label: "Data Transfer"
  }

  Bigquery: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/bigquery.svg
    shape: image
    label: "Bigquery"
  }


Bigtable: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/bigtable.svg
    shape: image
    label: "Bigtable"
  }

BigLake: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/BigLake.svg
    shape: image
    label: "BigLake"
  }

  Cloud Apis: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_apis.svg
    shape: image
    label: "Cloud Apis"
  }

  Datapol: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datapol.svg
    shape: image
    label: "Datapol"
  }


Dataprep: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataprep.svg
    shape: image
    label: "Dataprep"
  }


Dataproc: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataproc.svg
    shape: image
    label: "Dataproc"
  }


Dataproc Metastore: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataproc_metastore.svg
    shape: image
    label: "Dataproc Metastore"
  }

  Pubsub: {
    icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/pubsub.svg
    shape: image
    label: "Pubsub"
  }