classes: {
  
  
  Aws Application Discovery Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_Application_Discovery_Service.svg
        shape: image
        label: "Aws Application Discovery Service"
      }
  
  
  Aws Application Migration Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_Application_Migration_Service.svg
        shape: image
        label: "Aws Application Migration Service"
      }
  
  
  Aws Datasync: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_DataSync.svg
        shape: image
        label: "Aws Datasync"
      }
  
  
  Aws Mainframe Modernization: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_Mainframe_Modernization.svg
        shape: image
        label: "Aws Mainframe Modernization"
      }
  
  
  Aws Migration Evaluator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_Migration_Evaluator.svg
        shape: image
        label: "Aws Migration Evaluator"
      }
  
  
  Aws Migration Hub: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_Migration_Hub.svg
        shape: image
        label: "Aws Migration Hub"
      }
  
  
  Aws Transfer Family: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Migration-Transfer/AWS_Transfer_Family.svg
        shape: image
        label: "Aws Transfer Family"
      }
  
}