classes: {
  
  
  Amazon Api Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_API_Gateway.svg
        shape: image
        label: "Amazon Api Gateway"
      }
  
  
  Amazon Appflow: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_AppFlow.svg
        shape: image
        label: "Amazon Appflow"
      }
  
  
  Amazon Eventbridge: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_EventBridge.svg
        shape: image
        label: "Amazon Eventbridge"
      }
  
  
  Amazon Managed Workflows For Apache Airflow: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_Managed_Workflows_for_Apache_Airflow.svg
        shape: image
        label: "Amazon Managed Workflows For Apache Airflow"
      }
  
  
  Amazon Mq: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_MQ.svg
        shape: image
        label: "Amazon Mq"
      }
  
  
  Amazon Simple Notification Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_Simple_Notification_Service.svg
        shape: image
        label: "Amazon Simple Notification Service"
      }
  
  
  Amazon Simple Queue Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/Amazon_Simple_Queue_Service.svg
        shape: image
        label: "Amazon Simple Queue Service"
      }
  
  
  Aws Appsync: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/AWS_AppSync.svg
        shape: image
        label: "Aws Appsync"
      }
  
  
  Aws Console Mobile Application: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/AWS_Console_Mobile_Application.svg
        shape: image
        label: "Aws Console Mobile Application"
      }
  
  
  Aws Express Workflows: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/AWS_Express_Workflows.svg
        shape: image
        label: "Aws Express Workflows"
      }
  
  
  Aws Step Functions: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/App-Integration/AWS_Step_Functions.svg
        shape: image
        label: "Aws Step Functions"
      }
  
}