classes: {
  
  icon_service_Applens: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure ecosystem/icon_service_Applens.svg
        shape: image
        label: "icon_service_Applens"
      }
  
  icon_service_Azure_Hybrid_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure ecosystem/icon_service_Azure_Hybrid_Center.svg
        shape: image
        label: "icon_service_Azure_Hybrid_Center"
      }
  
  icon_service_Collaborative_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure ecosystem/icon_service_Collaborative_Service.svg
        shape: image
        label: "icon_service_Collaborative_Service"
      }
  
}