classes: {
  
  
  Applens: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure ecosystem/Applens.svg
        shape: image
        label: "Applens"
      }
  
  
  Azure Hybrid Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure ecosystem/Azure_Hybrid_Center.svg
        shape: image
        label: "Azure Hybrid Center"
      }
  
  
  Collaborative Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure ecosystem/Collaborative_Service.svg
        shape: image
        label: "Collaborative Service"
      }
  
}