classes: {
  
  
  Ai 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/AI 2.svg
        shape: image
        label: "Ai 2"
      }
  
  
  Ai: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/AI.svg
        shape: image
        label: "Ai"
      }
  
  
  Chart 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Chart 2.svg
        shape: image
        label: "Chart 2"
      }
  
  
  Chart 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Chart 3.svg
        shape: image
        label: "Chart 3"
      }
  
  
  Chart 3 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Chart 3_1.svg
        shape: image
        label: "Chart 3 1"
      }
  
  
  Cloud 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Cloud 1.svg
        shape: image
        label: "Cloud 1"
      }
  
  
  Cloud 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Cloud 2.svg
        shape: image
        label: "Cloud 2"
      }
  
  
  Cloud 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Cloud 3.svg
        shape: image
        label: "Cloud 3"
      }
  
  
  Cloud 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Cloud 4.svg
        shape: image
        label: "Cloud 4"
      }
  
  
  Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Connections.svg
        shape: image
        label: "Connections"
      }
  
  
  Data lake: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Data Lake.svg
        shape: image
        label: "Data lake"
      }
  
  
  Database: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Database.svg
        shape: image
        label: "Database"
      }
  
  
  Decrease 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Decrease 2.svg
        shape: image
        label: "Decrease 2"
      }
  
  
  Decrease: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Decrease.svg
        shape: image
        label: "Decrease"
      }
  
  
  File management: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/File Management.svg
        shape: image
        label: "File management"
      }
  
  
  Increase 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Increase 2.svg
        shape: image
        label: "Increase 2"
      }
  
  
  Increase 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Increase 4.svg
        shape: image
        label: "Increase 4"
      }
  
  
  Increase: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Increase.svg
        shape: image
        label: "Increase"
      }
  
  
  Lakehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Lakehouse.svg
        shape: image
        label: "Lakehouse"
      }
  
  
  Magnifier: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Magnifier.svg
        shape: image
        label: "Magnifier"
      }
  
  
  Model: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Model.svg
        shape: image
        label: "Model"
      }
  
  
  Repair 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Repair 2.svg
        shape: image
        label: "Repair 2"
      }
  
  
  Repair 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Repair 3.svg
        shape: image
        label: "Repair 3"
      }
  
  
  Repair: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Repair.svg
        shape: image
        label: "Repair"
      }
  
  
  Research: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Research.svg
        shape: image
        label: "Research"
      }
  
  
  Search 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Search 2.svg
        shape: image
        label: "Search 2"
      }
  
  
  Search 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Data Analysis Charts/Search 3.svg
        shape: image
        label: "Search 3"
      }
  
}