vars: {
    Data Lake: Lakehouse
    Data Platform: Fabric
    Data Warehouse: Data Warehouse
    Data Mart: DataMart
    Data Science: Data Science
    Data Engineering: Data Engineering
    Data Pipeline: Data Factory  Regular
    Pipeline: Pipelines
    Data Ingestion: Data Ingestion
    Workspace: Workspace
    Data Catalog: Purview
    #Data Lake.class: Lakehouse
  }

