classes: {
  
  
  Analyze: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Analyze.svg
        shape: image
        label: "Analyze"
      }
  
  
  Bank account 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Bank Account 2.svg
        shape: image
        label: "Bank account 2"
      }
  
  
  Bank account: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Bank Account.svg
        shape: image
        label: "Bank account"
      }
  
  
  Calculations: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Calculations.svg
        shape: image
        label: "Calculations"
      }
  
  
  Databases: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Databases.svg
        shape: image
        label: "Databases"
      }
  
  
  Decrease 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Decrease 3.svg
        shape: image
        label: "Decrease 3"
      }
  
  
  Network: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Network.svg
        shape: image
        label: "Network"
      }
  
  
  Savings phone 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Savings Phone 2.svg
        shape: image
        label: "Savings phone 2"
      }
  
  
  Savings phone: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Savings Phone.svg
        shape: image
        label: "Savings phone"
      }
  
  
  Text message: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Mobile phones/Text Message.svg
        shape: image
        label: "Text message"
      }
  
}