classes: {
  
  
  Alexa For Business: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Alexa_For_Business.svg
        shape: image
        label: "Alexa For Business"
      }
  
  
  Amazon Chime: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Chime.svg
        shape: image
        label: "Amazon Chime"
      }
  
  
  Amazon Chime Sdk: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Chime_SDK.svg
        shape: image
        label: "Amazon Chime Sdk"
      }
  
  
  Amazon Connect: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Connect.svg
        shape: image
        label: "Amazon Connect"
      }
  
  
  Amazon Honeycode: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Honeycode.svg
        shape: image
        label: "Amazon Honeycode"
      }
  
  
  Amazon Pinpoint: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Pinpoint.svg
        shape: image
        label: "Amazon Pinpoint"
      }
  
  
  Amazon Pinpoint Apis: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Pinpoint_APIs.svg
        shape: image
        label: "Amazon Pinpoint Apis"
      }
  
  
  Amazon Simple Email Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_Simple_Email_Service.svg
        shape: image
        label: "Amazon Simple Email Service"
      }
  
  
  Amazon Workdocs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_WorkDocs.svg
        shape: image
        label: "Amazon Workdocs"
      }
  
  
  Amazon Workdocs Sdk: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_WorkDocs_SDK.svg
        shape: image
        label: "Amazon Workdocs Sdk"
      }
  
  
  Amazon Workmail: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/Amazon_WorkMail.svg
        shape: image
        label: "Amazon Workmail"
      }
  
  
  Aws Supply Chain: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/AWS_Supply_Chain.svg
        shape: image
        label: "Aws Supply Chain"
      }
  
  
  Aws Wickr: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Business-Applications/AWS_Wickr.svg
        shape: image
        label: "Aws Wickr"
      }
  
}