classes: {
  
  
  Azure Database Migration Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migration/Azure_Database_Migration_Services.svg
        shape: image
        label: "Azure Database Migration Services"
      }
  
}