classes: {
  
  00400-icon-service-Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/00400-icon-service-Workspaces.svg
        shape: image
        label: "00400-icon-service-Workspaces"
      }
  
  icon_service_Application_Group: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Application_Group.svg
        shape: image
        label: "icon_service_Application_Group"
      }
  
  icon_service_App_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_App_Services.svg
        shape: image
        label: "icon_service_App_Services"
      }
  
  icon_service_Automanaged_VM: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Automanaged_VM.svg
        shape: image
        label: "icon_service_Automanaged_VM"
      }
  
  icon_service_Availability_Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Availability_Sets.svg
        shape: image
        label: "icon_service_Availability_Sets"
      }
  
  icon_service_Azure_Compute_Galleries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Azure_Compute_Galleries.svg
        shape: image
        label: "icon_service_Azure_Compute_Galleries"
      }
  
  icon_service_Azure_Spring_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Azure_Spring_Apps.svg
        shape: image
        label: "icon_service_Azure_Spring_Apps"
      }
  
  icon_service_Batch_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Batch_Accounts.svg
        shape: image
        label: "icon_service_Batch_Accounts"
      }
  
  icon_service_Cloud_Services_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Cloud_Services_(Classic).svg
        shape: image
        label: "icon_service_Cloud_Services_(Classic)"
      }
  
  icon_service_Container_Instances: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Container_Instances.svg
        shape: image
        label: "icon_service_Container_Instances"
      }
  
  icon_service_Container_Services_(Deprecated): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Container_Services_(Deprecated).svg
        shape: image
        label: "icon_service_Container_Services_(Deprecated)"
      }
  
  icon_service_Disks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Disks.svg
        shape: image
        label: "icon_service_Disks"
      }
  
  icon_service_Disks_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Disks_(Classic).svg
        shape: image
        label: "icon_service_Disks_(Classic)"
      }
  
  icon_service_Disks_Snapshots: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Disks_Snapshots.svg
        shape: image
        label: "icon_service_Disks_Snapshots"
      }
  
  icon_service_Disk_Encryption_Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Disk_Encryption_Sets.svg
        shape: image
        label: "icon_service_Disk_Encryption_Sets"
      }
  
  icon_service_Function_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Function_Apps.svg
        shape: image
        label: "icon_service_Function_Apps"
      }
  
  icon_service_Hosts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Hosts.svg
        shape: image
        label: "icon_service_Hosts"
      }
  
  icon_service_Host_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Host_Groups.svg
        shape: image
        label: "icon_service_Host_Groups"
      }
  
  icon_service_Host_Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Host_Pools.svg
        shape: image
        label: "icon_service_Host_Pools"
      }
  
  icon_service_Images: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Images.svg
        shape: image
        label: "icon_service_Images"
      }
  
  icon_service_Image_Definitions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Image_Definitions.svg
        shape: image
        label: "icon_service_Image_Definitions"
      }
  
  icon_service_Image_Templates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Image_Templates.svg
        shape: image
        label: "icon_service_Image_Templates"
      }
  
  icon_service_Image_Versions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Image_Versions.svg
        shape: image
        label: "icon_service_Image_Versions"
      }
  
  icon_service_Kubernetes_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Kubernetes_Services.svg
        shape: image
        label: "icon_service_Kubernetes_Services"
      }
  
  icon_service_Maintenance_Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Maintenance_Configuration.svg
        shape: image
        label: "icon_service_Maintenance_Configuration"
      }
  
  icon_service_Managed_Service_Fabric: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Managed_Service_Fabric.svg
        shape: image
        label: "icon_service_Managed_Service_Fabric"
      }
  
  icon_service_Mesh_Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Mesh_Applications.svg
        shape: image
        label: "icon_service_Mesh_Applications"
      }
  
  icon_service_Metrics_Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Metrics_Advisor.svg
        shape: image
        label: "icon_service_Metrics_Advisor"
      }
  
  icon_service_OS_Images_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_OS_Images_(Classic).svg
        shape: image
        label: "icon_service_OS_Images_(Classic)"
      }
  
  icon_service_Restore_Points: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Restore_Points.svg
        shape: image
        label: "icon_service_Restore_Points"
      }
  
  icon_service_Restore_Points_Collections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Restore_Points_Collections.svg
        shape: image
        label: "icon_service_Restore_Points_Collections"
      }
  
  icon_service_Service_Fabric_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Service_Fabric_Clusters.svg
        shape: image
        label: "icon_service_Service_Fabric_Clusters"
      }
  
  icon_service_Shared_Image_Galleries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Shared_Image_Galleries.svg
        shape: image
        label: "icon_service_Shared_Image_Galleries"
      }
  
  icon_service_Virtual_Machine: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Virtual_Machine.svg
        shape: image
        label: "icon_service_Virtual_Machine"
      }
  
  icon_service_Virtual_Machines_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Virtual_Machines_(Classic).svg
        shape: image
        label: "icon_service_Virtual_Machines_(Classic)"
      }
  
  icon_service_VM_Images_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_VM_Images_(Classic).svg
        shape: image
        label: "icon_service_VM_Images_(Classic)"
      }
  
  icon_service_VM_Scale_Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_VM_Scale_Sets.svg
        shape: image
        label: "icon_service_VM_Scale_Sets"
      }
  
  icon_service_Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Workspaces.svg
        shape: image
        label: "icon_service_Workspaces"
      }
  
}