classes: {
  
  
  Application Group: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Application_Group.svg
        shape: image
        label: "Application Group"
      }
  
  
  App Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/App_Services.svg
        shape: image
        label: "App Services"
      }
  
  
  Automanaged Vm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Automanaged_VM.svg
        shape: image
        label: "Automanaged Vm"
      }
  
  
  Availability Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Availability_Sets.svg
        shape: image
        label: "Availability Sets"
      }
  
  
  Azure Compute Galleries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Azure_Compute_Galleries.svg
        shape: image
        label: "Azure Compute Galleries"
      }
  
  
  Azure Spring Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Azure_Spring_Apps.svg
        shape: image
        label: "Azure Spring Apps"
      }
  
  
  Batch Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Batch_Accounts.svg
        shape: image
        label: "Batch Accounts"
      }
  
  
  Cloud Services (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Cloud_Services_(Classic).svg
        shape: image
        label: "Cloud Services (classic)"
      }
  
  
  Container Instances: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Container_Instances.svg
        shape: image
        label: "Container Instances"
      }
  
  
  Container Services (deprecated): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Container_Services_(Deprecated).svg
        shape: image
        label: "Container Services (deprecated)"
      }
  
  
  Disks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Disks.svg
        shape: image
        label: "Disks"
      }
  
  
  Disks (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Disks_(Classic).svg
        shape: image
        label: "Disks (classic)"
      }
  
  
  Disks Snapshots: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Disks_Snapshots.svg
        shape: image
        label: "Disks Snapshots"
      }
  
  
  Disk Encryption Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Disk_Encryption_Sets.svg
        shape: image
        label: "Disk Encryption Sets"
      }
  
  
  Function Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Function_Apps.svg
        shape: image
        label: "Function Apps"
      }
  
  
  Hosts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Hosts.svg
        shape: image
        label: "Hosts"
      }
  
  
  Host Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Host_Groups.svg
        shape: image
        label: "Host Groups"
      }
  
  
  Host Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Host_Pools.svg
        shape: image
        label: "Host Pools"
      }
  
  
  Icon Service Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/icon_service_Workspaces.svg
        shape: image
        label: "Icon Service Workspaces"
      }
  
  
  Images: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Images.svg
        shape: image
        label: "Images"
      }
  
  
  Image Definitions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Image_Definitions.svg
        shape: image
        label: "Image Definitions"
      }
  
  
  Image Templates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Image_Templates.svg
        shape: image
        label: "Image Templates"
      }
  
  
  Image Versions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Image_Versions.svg
        shape: image
        label: "Image Versions"
      }
  
  
  Kubernetes Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Kubernetes_Services.svg
        shape: image
        label: "Kubernetes Services"
      }
  
  
  Maintenance Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Maintenance_Configuration.svg
        shape: image
        label: "Maintenance Configuration"
      }
  
  
  Managed Service Fabric: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Managed_Service_Fabric.svg
        shape: image
        label: "Managed Service Fabric"
      }
  
  
  Mesh Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Mesh_Applications.svg
        shape: image
        label: "Mesh Applications"
      }
  
  
  Metrics Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Metrics_Advisor.svg
        shape: image
        label: "Metrics Advisor"
      }
  
  
  Os Images (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/OS_Images_(Classic).svg
        shape: image
        label: "Os Images (classic)"
      }
  
  
  Restore Points: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Restore_Points.svg
        shape: image
        label: "Restore Points"
      }
  
  
  Restore Points Collections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Restore_Points_Collections.svg
        shape: image
        label: "Restore Points Collections"
      }
  
  
  Service Fabric Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Service_Fabric_Clusters.svg
        shape: image
        label: "Service Fabric Clusters"
      }
  
  
  Shared Image Galleries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Shared_Image_Galleries.svg
        shape: image
        label: "Shared Image Galleries"
      }
  
  
  Virtual Machine: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Virtual_Machine.svg
        shape: image
        label: "Virtual Machine"
      }
  
  
  Virtual Machines (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Virtual_Machines_(Classic).svg
        shape: image
        label: "Virtual Machines (classic)"
      }
  
  
  Vm Images (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/VM_Images_(Classic).svg
        shape: image
        label: "Vm Images (classic)"
      }
  
  
  Vm Scale Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/VM_Scale_Sets.svg
        shape: image
        label: "Vm Scale Sets"
      }
  
  
  Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/compute/Workspaces.svg
        shape: image
        label: "Workspaces"
      }
  
}