classes: {
  
  
  Amazon Location Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Front-End-Web-Mobile/Amazon_Location_Service.svg
        shape: image
        label: "Amazon Location Service"
      }
  
  
  Aws Amplify: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Front-End-Web-Mobile/AWS_Amplify.svg
        shape: image
        label: "Aws Amplify"
      }
  
  
  Aws Device Farm: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Front-End-Web-Mobile/AWS_Device_Farm.svg
        shape: image
        label: "Aws Device Farm"
      }
  
}