classes: {
  
  
  Analysis Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Analysis_Services.svg
        shape: image
        label: "Analysis Services"
      }
  
  
  Azure Databricks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Azure_Databricks.svg
        shape: image
        label: "Azure Databricks"
      }
  
  
  Azure Data Explorer Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Azure_Data_Explorer_Clusters.svg
        shape: image
        label: "Azure Data Explorer Clusters"
      }
  
  
  Azure Synapse Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Azure_Synapse_Analytics.svg
        shape: image
        label: "Azure Synapse Analytics"
      }
  
  
  Azure Workbooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Azure_Workbooks.svg
        shape: image
        label: "Azure Workbooks"
      }
  
  
  Data Factories: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Data_Factories.svg
        shape: image
        label: "Data Factories"
      }
  
  
  Data Lake Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Data_Lake_Analytics.svg
        shape: image
        label: "Data Lake Analytics"
      }
  
  
  Data Lake Store Gen: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Data_Lake_Store_Gen.svg
        shape: image
        label: "Data Lake Store Gen"
      }
  
  
  Endpoint Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Endpoint_Analytics.svg
        shape: image
        label: "Endpoint Analytics"
      }
  
  
  Event Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Event_Hubs.svg
        shape: image
        label: "Event Hubs"
      }
  
  
  Event Hub Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Event_Hub_Clusters.svg
        shape: image
        label: "Event Hub Clusters"
      }
  
  
  Hd Insight Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/HD_Insight_Clusters.svg
        shape: image
        label: "Hd Insight Clusters"
      }
  
  
  Log Analytics Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Log_Analytics_Workspaces.svg
        shape: image
        label: "Log Analytics Workspaces"
      }
  
  
  Power Bi Embedded: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Power_BI_Embedded.svg
        shape: image
        label: "Power Bi Embedded"
      }
  
  
  Power Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Power_Platform.svg
        shape: image
        label: "Power Platform"
      }
  
  
  Private Link Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Private_Link_Services.svg
        shape: image
        label: "Private Link Services"
      }
  
  
  Stream Analytics Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/Stream_Analytics_Jobs.svg
        shape: image
        label: "Stream Analytics Jobs"
      }
  
}