classes: {
  
  icon_service_Analysis_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Analysis_Services.svg
        shape: image
        label: "icon_service_Analysis_Services"
      }
  
  icon_service_Azure_Databricks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Azure_Databricks.svg
        shape: image
        label: "icon_service_Azure_Databricks"
      }
  
  icon_service_Azure_Data_Explorer_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Azure_Data_Explorer_Clusters.svg
        shape: image
        label: "icon_service_Azure_Data_Explorer_Clusters"
      }
  
  icon_service_Azure_Synapse_Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Azure_Synapse_Analytics.svg
        shape: image
        label: "icon_service_Azure_Synapse_Analytics"
      }
  
  icon_service_Azure_Workbooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Azure_Workbooks.svg
        shape: image
        label: "icon_service_Azure_Workbooks"
      }
  
  icon_service_Data_Factories: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Data_Factories.svg
        shape: image
        label: "icon_service_Data_Factories"
      }
  
  icon_service_Data_Lake_Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Data_Lake_Analytics.svg
        shape: image
        label: "icon_service_Data_Lake_Analytics"
      }
  
  icon_service_Data_Lake_Store_Gen: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Data_Lake_Store_Gen.svg
        shape: image
        label: "icon_service_Data_Lake_Store_Gen"
      }
  
  icon_service_Endpoint_Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Endpoint_Analytics.svg
        shape: image
        label: "icon_service_Endpoint_Analytics"
      }
  
  icon_service_Event_Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Event_Hubs.svg
        shape: image
        label: "icon_service_Event_Hubs"
      }
  
  icon_service_Event_Hub_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Event_Hub_Clusters.svg
        shape: image
        label: "icon_service_Event_Hub_Clusters"
      }
  
  icon_service_HD_Insight_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_HD_Insight_Clusters.svg
        shape: image
        label: "icon_service_HD_Insight_Clusters"
      }
  
  icon_service_Log_Analytics_Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Log_Analytics_Workspaces.svg
        shape: image
        label: "icon_service_Log_Analytics_Workspaces"
      }
  
  icon_service_Power_BI_Embedded: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Power_BI_Embedded.svg
        shape: image
        label: "icon_service_Power_BI_Embedded"
      }
  
  icon_service_Power_Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Power_Platform.svg
        shape: image
        label: "icon_service_Power_Platform"
      }
  
  icon_service_Private_Link_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Private_Link_Services.svg
        shape: image
        label: "icon_service_Private_Link_Services"
      }
  
  icon_service_Stream_Analytics_Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/analytics/icon_service_Stream_Analytics_Jobs.svg
        shape: image
        label: "icon_service_Stream_Analytics_Jobs"
      }
  
}