classes: {
  
  
  Amazon Ecs Anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_ECS_Anywhere.svg
        shape: image
        label: "Amazon Ecs Anywhere"
      }
  
  
  Amazon Eks Anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_EKS_Anywhere.svg
        shape: image
        label: "Amazon Eks Anywhere"
      }
  
  
  Amazon Eks Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_EKS_Cloud.svg
        shape: image
        label: "Amazon Eks Cloud"
      }
  
  
  Amazon Eks Distro: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_EKS_Distro.svg
        shape: image
        label: "Amazon Eks Distro"
      }
  
  
  Amazon Elastic Container Registry: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_Elastic_Container_Registry.svg
        shape: image
        label: "Amazon Elastic Container Registry"
      }
  
  
  Amazon Elastic Container Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_Elastic_Container_Service.svg
        shape: image
        label: "Amazon Elastic Container Service"
      }
  
  
  Amazon Elastic Kubernetes Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Amazon_Elastic_Kubernetes_Service.svg
        shape: image
        label: "Amazon Elastic Kubernetes Service"
      }
  
  
  Aws Fargate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/AWS_Fargate.svg
        shape: image
        label: "Aws Fargate"
      }
  
  
  Red Hat Openshift Service On Aws: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Containers/Red_Hat_OpenShift_Service_on_AWS.svg
        shape: image
        label: "Red Hat Openshift Service On Aws"
      }
  
}