classes: {
  
  
  Amazon Braket: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Quantum-Technologies/Amazon_Braket.svg
        shape: image
        label: "Amazon Braket"
      }
  
}