classes: {
  
  
  Res Aws Cloud Digital Interface: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Media-Services/Res_AWS_Cloud_Digital_Interface.svg
        shape: image
        label: "Res Aws Cloud Digital Interface"
      }
  
}