classes: {
  
  
  Amazon Appstream: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/End-User-Computing/Amazon_AppStream.svg
        shape: image
        label: "Amazon Appstream"
      }
  
  
  Amazon Worklink: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/End-User-Computing/Amazon_WorkLink.svg
        shape: image
        label: "Amazon Worklink"
      }
  
  
  Amazon Workspaces Family: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/End-User-Computing/Amazon_WorkSpaces_Family.svg
        shape: image
        label: "Amazon Workspaces Family"
      }
  
}