classes: {
  
  
  Res Aws Robomaker Cloud Extensions Ros: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Robotics/Res_AWS_RoboMaker_Cloud_Extensions_ROS.svg
        shape: image
        label: "Res Aws Robomaker Cloud Extensions Ros"
      }
  
  
  Res Aws Robomaker Development Environment: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Robotics/Res_AWS_RoboMaker_Development_Environment.svg
        shape: image
        label: "Res Aws Robomaker Development Environment"
      }
  
  
  Res Aws Robomaker Fleet Management: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Robotics/Res_AWS_RoboMaker_Fleet_Management.svg
        shape: image
        label: "Res Aws Robomaker Fleet Management"
      }
  
  
  Res Aws Robomaker Simulation: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Robotics/Res_AWS_RoboMaker_Simulation.svg
        shape: image
        label: "Res Aws Robomaker Simulation"
      }
  
}