classes: {
  
  Res_Amazon_Elastic_Block_Store_Amazon_Data_Lifecycle_Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_Block_Store_Amazon_Data_Lifecycle_Manager.svg
        shape: image
        label: "Res_Amazon_Elastic_Block_Store_Amazon_Data_Lifecycle_Manager"
      }
  
  Res_Amazon_Elastic_Block_Store_Multiple_Volumes: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_Block_Store_Multiple_Volumes.svg
        shape: image
        label: "Res_Amazon_Elastic_Block_Store_Multiple_Volumes"
      }
  
  Res_Amazon_Elastic_Block_Store_Snapshot: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_Block_Store_Snapshot.svg
        shape: image
        label: "Res_Amazon_Elastic_Block_Store_Snapshot"
      }
  
  Res_Amazon_Elastic_Block_Store_Volume: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_Block_Store_Volume.svg
        shape: image
        label: "Res_Amazon_Elastic_Block_Store_Volume"
      }
  
  Res_Amazon_Elastic_Block_Store_Volume_gp: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_Block_Store_Volume_gp.svg
        shape: image
        label: "Res_Amazon_Elastic_Block_Store_Volume_gp"
      }
  
  Res_Amazon_Elastic_File_System_EFS_Intelligent_Tiering: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_EFS_Intelligent_Tiering.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_EFS_Intelligent_Tiering"
      }
  
  Res_Amazon_Elastic_File_System_EFS_One_Zone: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_EFS_One_Zone.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_EFS_One_Zone"
      }
  
  Res_Amazon_Elastic_File_System_EFS_One_Zone_Infrequent_Access: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_EFS_One_Zone_Infrequent_Access.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_EFS_One_Zone_Infrequent_Access"
      }
  
  Res_Amazon_Elastic_File_System_EFS_Standard: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_EFS_Standard.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_EFS_Standard"
      }
  
  Res_Amazon_Elastic_File_System_EFS_Standard_Infrequent_Access: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_EFS_Standard_Infrequent_Access.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_EFS_Standard_Infrequent_Access"
      }
  
  Res_Amazon_Elastic_File_System_Elastic_Throughput: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_Elastic_Throughput.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_Elastic_Throughput"
      }
  
  Res_Amazon_Elastic_File_System_File_System: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Elastic_File_System_File_System.svg
        shape: image
        label: "Res_Amazon_Elastic_File_System_File_System"
      }
  
  Res_Amazon_File_Cache_Hybrid_NFS_linked_datasets: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_File_Cache_Hybrid_NFS_linked_datasets.svg
        shape: image
        label: "Res_Amazon_File_Cache_Hybrid_NFS_linked_datasets"
      }
  
  Res_Amazon_File_Cache_On_premises_NFS_linked_datasets: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_File_Cache_On_premises_NFS_linked_datasets.svg
        shape: image
        label: "Res_Amazon_File_Cache_On_premises_NFS_linked_datasets"
      }
  
  Res_Amazon_File_Cache_S_linked_datasets: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_File_Cache_S_linked_datasets.svg
        shape: image
        label: "Res_Amazon_File_Cache_S_linked_datasets"
      }
  
  Res_Amazon_Simple_Storage_Service_Bucket: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_Bucket.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_Bucket"
      }
  
  Res_Amazon_Simple_Storage_Service_Bucket_With_Objects: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_Bucket_With_Objects.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_Bucket_With_Objects"
      }
  
  Res_Amazon_Simple_Storage_Service_General_Access_Points: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_General_Access_Points.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_General_Access_Points"
      }
  
  Res_Amazon_Simple_Storage_Service_Glacier_Archive: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_Glacier_Archive.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_Glacier_Archive"
      }
  
  Res_Amazon_Simple_Storage_Service_Glacier_Vault: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_Glacier_Vault.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_Glacier_Vault"
      }
  
  Res_Amazon_Simple_Storage_Service_Object: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_Object.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_Object"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Batch_Operations: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Batch_Operations.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Batch_Operations"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Glacier_Deep_Archive: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Glacier_Deep_Archive.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Glacier_Deep_Archive"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Glacier_Flexible_Retrieval: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Glacier_Flexible_Retrieval.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Glacier_Flexible_Retrieval"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Glacier_Instant_Retrieval: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Glacier_Instant_Retrieval.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Glacier_Instant_Retrieval"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Intelligent_Tiering: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Intelligent_Tiering.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Intelligent_Tiering"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Multi_Region_Access_Points: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Multi_Region_Access_Points.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Multi_Region_Access_Points"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Object_Lambda: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Object_Lambda.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Object_Lambda"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Object_Lambda_Access_Points: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Object_Lambda_Access_Points.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Object_Lambda_Access_Points"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Object_Lock: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Object_Lock.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Object_Lock"
      }
  
  Res_Amazon_Simple_Storage_Service_S_One_Zone_IA: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_One_Zone_IA.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_One_Zone_IA"
      }
  
  Res_Amazon_Simple_Storage_Service_S_On_Outposts: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_On_Outposts.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_On_Outposts"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Replication: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Replication.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Replication"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Replication_Time_Control: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Replication_Time_Control.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Replication_Time_Control"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Select: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Select.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Select"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Standard: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Standard.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Standard"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Standard_IA: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Standard_IA.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Standard_IA"
      }
  
  Res_Amazon_Simple_Storage_Service_S_Storage_Lens: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_S_Storage_Lens.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_S_Storage_Lens"
      }
  
  Res_Amazon_Simple_Storage_Service_VPC_Access_Points: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_Amazon_Simple_Storage_Service_VPC_Access_Points.svg
        shape: image
        label: "Res_Amazon_Simple_Storage_Service_VPC_Access_Points"
      }
  
  Res_AWS_Backup_Audit_Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Audit_Manager.svg
        shape: image
        label: "Res_AWS_Backup_Audit_Manager"
      }
  
  Res_AWS_Backup_AWS_Backup_for_AWS_CloudFormation: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_AWS_Backup_for_AWS_CloudFormation.svg
        shape: image
        label: "Res_AWS_Backup_AWS_Backup_for_AWS_CloudFormation"
      }
  
  Res_AWS_Backup_AWS_Backup_support_for_Amazon_FSx_for_NetApp_ONTAP: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_AWS_Backup_support_for_Amazon_FSx_for_NetApp_ONTAP.svg
        shape: image
        label: "Res_AWS_Backup_AWS_Backup_support_for_Amazon_FSx_for_NetApp_ONTAP"
      }
  
  Res_AWS_Backup_AWS_Backup_support_for_Amazon_S: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_AWS_Backup_support_for_Amazon_S.svg
        shape: image
        label: "Res_AWS_Backup_AWS_Backup_support_for_Amazon_S"
      }
  
  Res_AWS_Backup_AWS_Backup_Support_for_VMware_Workloads: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_AWS_Backup_Support_for_VMware_Workloads.svg
        shape: image
        label: "Res_AWS_Backup_AWS_Backup_Support_for_VMware_Workloads"
      }
  
  Res_AWS_Backup_Backup_Plan: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Backup_Plan.svg
        shape: image
        label: "Res_AWS_Backup_Backup_Plan"
      }
  
  Res_AWS_Backup_Backup_Restore: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Backup_Restore.svg
        shape: image
        label: "Res_AWS_Backup_Backup_Restore"
      }
  
  Res_AWS_Backup_Backup_Vault: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Backup_Vault.svg
        shape: image
        label: "Res_AWS_Backup_Backup_Vault"
      }
  
  Res_AWS_Backup_Compliance_Reporting: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Compliance_Reporting.svg
        shape: image
        label: "Res_AWS_Backup_Compliance_Reporting"
      }
  
  Res_AWS_Backup_Compute: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Compute.svg
        shape: image
        label: "Res_AWS_Backup_Compute"
      }
  
  Res_AWS_Backup_Database: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Database.svg
        shape: image
        label: "Res_AWS_Backup_Database"
      }
  
  Res_AWS_Backup_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Gateway.svg
        shape: image
        label: "Res_AWS_Backup_Gateway"
      }
  
  Res_AWS_Backup_Legal_Hold: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Legal_Hold.svg
        shape: image
        label: "Res_AWS_Backup_Legal_Hold"
      }
  
  Res_AWS_Backup_Recovery_Point_Objective: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Recovery_Point_Objective.svg
        shape: image
        label: "Res_AWS_Backup_Recovery_Point_Objective"
      }
  
  Res_AWS_Backup_Recovery_Time_Objective: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Recovery_Time_Objective.svg
        shape: image
        label: "Res_AWS_Backup_Recovery_Time_Objective"
      }
  
  Res_AWS_Backup_Storage: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Storage.svg
        shape: image
        label: "Res_AWS_Backup_Storage"
      }
  
  Res_AWS_Backup_Vault_Lock: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Vault_Lock.svg
        shape: image
        label: "Res_AWS_Backup_Vault_Lock"
      }
  
  Res_AWS_Backup_Virtual_Machine: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Virtual_Machine.svg
        shape: image
        label: "Res_AWS_Backup_Virtual_Machine"
      }
  
  Res_AWS_Backup_Virtual_Machine_Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Backup_Virtual_Machine_Monitor.svg
        shape: image
        label: "Res_AWS_Backup_Virtual_Machine_Monitor"
      }
  
  Res_AWS_Snowball_Snowball_Import_Export: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Snowball_Snowball_Import_Export.svg
        shape: image
        label: "Res_AWS_Snowball_Snowball_Import_Export"
      }
  
  Res_AWS_Storage_Gateway_Amazon_FSx_File_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Amazon_FSx_File_Gateway.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Amazon_FSx_File_Gateway"
      }
  
  Res_AWS_Storage_Gateway_Amazon_S_File_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Amazon_S_File_Gateway.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Amazon_S_File_Gateway"
      }
  
  Res_AWS_Storage_Gateway_Cached_Volume: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Cached_Volume.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Cached_Volume"
      }
  
  Res_AWS_Storage_Gateway_File_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_File_Gateway.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_File_Gateway"
      }
  
  Res_AWS_Storage_Gateway_Noncached_Volume: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Noncached_Volume.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Noncached_Volume"
      }
  
  Res_AWS_Storage_Gateway_Tape_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Tape_Gateway.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Tape_Gateway"
      }
  
  Res_AWS_Storage_Gateway_Virtual_Tape_Library: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Virtual_Tape_Library.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Virtual_Tape_Library"
      }
  
  Res_AWS_Storage_Gateway_Volume_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Resource-Icons/Res_Storage/Res_AWS_Storage_Gateway_Volume_Gateway.svg
        shape: image
        label: "Res_AWS_Storage_Gateway_Volume_Gateway"
      }
  
}