classes: {
  
  
  Amazon Augmented Ai Ai: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Augmented_AI_AI.svg
        shape: image
        label: "Amazon Augmented Ai Ai"
      }
  
  
  Amazon Codeguru: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_CodeGuru.svg
        shape: image
        label: "Amazon Codeguru"
      }
  
  
  Amazon Codewhisperer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_CodeWhisperer.svg
        shape: image
        label: "Amazon Codewhisperer"
      }
  
  
  Amazon Comprehend: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Comprehend.svg
        shape: image
        label: "Amazon Comprehend"
      }
  
  
  Amazon Comprehend Medical: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Comprehend_Medical.svg
        shape: image
        label: "Amazon Comprehend Medical"
      }
  
  
  Amazon Devops Guru: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_DevOps_Guru.svg
        shape: image
        label: "Amazon Devops Guru"
      }
  
  
  Amazon Elastic Inference: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Elastic_Inference.svg
        shape: image
        label: "Amazon Elastic Inference"
      }
  
  
  Amazon Forecast: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Forecast.svg
        shape: image
        label: "Amazon Forecast"
      }
  
  
  Amazon Fraud Detector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Fraud_Detector.svg
        shape: image
        label: "Amazon Fraud Detector"
      }
  
  
  Amazon Healthlake: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_HealthLake.svg
        shape: image
        label: "Amazon Healthlake"
      }
  
  
  Amazon Kendra: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Kendra.svg
        shape: image
        label: "Amazon Kendra"
      }
  
  
  Amazon Lex: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Lex.svg
        shape: image
        label: "Amazon Lex"
      }
  
  
  Amazon Lookout For Equipment: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Lookout_for_Equipment.svg
        shape: image
        label: "Amazon Lookout For Equipment"
      }
  
  
  Amazon Lookout For Metrics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Lookout_for_Metrics.svg
        shape: image
        label: "Amazon Lookout For Metrics"
      }
  
  
  Amazon Lookout For Vision: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Lookout_for_Vision.svg
        shape: image
        label: "Amazon Lookout For Vision"
      }
  
  
  Amazon Monitron: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Monitron.svg
        shape: image
        label: "Amazon Monitron"
      }
  
  
  Amazon Omics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Omics.svg
        shape: image
        label: "Amazon Omics"
      }
  
  
  Amazon Personalize: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Personalize.svg
        shape: image
        label: "Amazon Personalize"
      }
  
  
  Amazon Polly: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Polly.svg
        shape: image
        label: "Amazon Polly"
      }
  
  
  Amazon Rekognition: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Rekognition.svg
        shape: image
        label: "Amazon Rekognition"
      }
  
  
  Amazon Sagemaker: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_SageMaker.svg
        shape: image
        label: "Amazon Sagemaker"
      }
  
  
  Amazon Sagemaker Ground Truth: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_SageMaker_Ground_Truth.svg
        shape: image
        label: "Amazon Sagemaker Ground Truth"
      }
  
  
  Amazon Sagemaker Studio Lab: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_SageMaker_Studio_Lab.svg
        shape: image
        label: "Amazon Sagemaker Studio Lab"
      }
  
  
  Amazon Textract: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Textract.svg
        shape: image
        label: "Amazon Textract"
      }
  
  
  Amazon Transcribe: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Transcribe.svg
        shape: image
        label: "Amazon Transcribe"
      }
  
  
  Amazon Translate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Amazon_Translate.svg
        shape: image
        label: "Amazon Translate"
      }
  
  
  Apache Mxnet On Aws: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/Apache_MXNet_on_AWS.svg
        shape: image
        label: "Apache Mxnet On Aws"
      }
  
  
  Aws Deepcomposer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_DeepComposer.svg
        shape: image
        label: "Aws Deepcomposer"
      }
  
  
  Aws Deeplens: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_DeepLens.svg
        shape: image
        label: "Aws Deeplens"
      }
  
  
  Aws Deepracer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_DeepRacer.svg
        shape: image
        label: "Aws Deepracer"
      }
  
  
  Aws Deep Learning Amis: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_Deep_Learning_AMIs.svg
        shape: image
        label: "Aws Deep Learning Amis"
      }
  
  
  Aws Deep Learning Containers: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_Deep_Learning_Containers.svg
        shape: image
        label: "Aws Deep Learning Containers"
      }
  
  
  Aws Neuron: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_Neuron.svg
        shape: image
        label: "Aws Neuron"
      }
  
  
  Aws Panorama: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/AWS_Panorama.svg
        shape: image
        label: "Aws Panorama"
      }
  
  
  Tensorflow On Aws: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/TensorFlow_on_AWS.svg
        shape: image
        label: "Tensorflow On Aws"
      }
  
  
  Torchserve: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Machine-Learning/TorchServe.svg
        shape: image
        label: "Torchserve"
      }
  
}