classes: {
  
  
  Remote Rendering: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mixed reality/Remote_Rendering.svg
        shape: image
        label: "Remote Rendering"
      }
  
  
  Spatial Anchor Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mixed reality/Spatial_Anchor_Accounts.svg
        shape: image
        label: "Spatial Anchor Accounts"
      }
  
}