classes: {
  
  icon_service_Remote_Rendering: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mixed reality/icon_service_Remote_Rendering.svg
        shape: image
        label: "icon_service_Remote_Rendering"
      }
  
  icon_service_Spatial_Anchor_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/mixed reality/icon_service_Spatial_Anchor_Accounts.svg
        shape: image
        label: "icon_service_Spatial_Anchor_Accounts"
      }
  
}