classes: {
  
  
  Res Amazon Api Gateway Endpoint: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_API_Gateway_Endpoint.svg
        shape: image
        label: "Res Amazon Api Gateway Endpoint"
      }
  
  
  Res Amazon Eventbridge Custom Event Bus: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Custom_Event_Bus.svg
        shape: image
        label: "Res Amazon Eventbridge Custom Event Bus"
      }
  
  
  Res Amazon Eventbridge Default Event Bus: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Default_Event_Bus.svg
        shape: image
        label: "Res Amazon Eventbridge Default Event Bus"
      }
  
  
  Res Amazon Eventbridge Event: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Event.svg
        shape: image
        label: "Res Amazon Eventbridge Event"
      }
  
  
  Res Amazon Eventbridge Pipes: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Pipes.svg
        shape: image
        label: "Res Amazon Eventbridge Pipes"
      }
  
  
  Res Amazon Eventbridge Rule: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Rule.svg
        shape: image
        label: "Res Amazon Eventbridge Rule"
      }
  
  
  Res Amazon Eventbridge Saas Partner Event: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Saas_Partner_Event.svg
        shape: image
        label: "Res Amazon Eventbridge Saas Partner Event"
      }
  
  
  Res Amazon Eventbridge Scheduler: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Scheduler.svg
        shape: image
        label: "Res Amazon Eventbridge Scheduler"
      }
  
  
  Res Amazon Eventbridge Schema: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Schema.svg
        shape: image
        label: "Res Amazon Eventbridge Schema"
      }
  
  
  Res Amazon Eventbridge Schema Registry: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_EventBridge_Schema_Registry.svg
        shape: image
        label: "Res Amazon Eventbridge Schema Registry"
      }
  
  
  Res Amazon Mq Broker: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_MQ_Broker.svg
        shape: image
        label: "Res Amazon Mq Broker"
      }
  
  
  Res Amazon Simple Notification Service Email Notification: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_Simple_Notification_Service_Email_Notification.svg
        shape: image
        label: "Res Amazon Simple Notification Service Email Notification"
      }
  
  
  Res Amazon Simple Notification Service Http Notification: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_Simple_Notification_Service_HTTP_Notification.svg
        shape: image
        label: "Res Amazon Simple Notification Service Http Notification"
      }
  
  
  Res Amazon Simple Notification Service Topic: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_Simple_Notification_Service_Topic.svg
        shape: image
        label: "Res Amazon Simple Notification Service Topic"
      }
  
  
  Res Amazon Simple Queue Service Message: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_Simple_Queue_Service_Message.svg
        shape: image
        label: "Res Amazon Simple Queue Service Message"
      }
  
  
  Res Amazon Simple Queue Service Queue: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Application-Integration/Res_Amazon_Simple_Queue_Service_Queue.svg
        shape: image
        label: "Res Amazon Simple Queue Service Queue"
      }
  
}