classes: {
  
  
  Defense: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Defense.svg
        shape: image
        label: "Defense"
      }
  
  
  Fingerprint 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Fingerprint 2.svg
        shape: image
        label: "Fingerprint 2"
      }
  
  
  Fingerprint: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Fingerprint.svg
        shape: image
        label: "Fingerprint"
      }
  
  
  Key: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Key.svg
        shape: image
        label: "Key"
      }
  
  
  Safety 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Safety 2.svg
        shape: image
        label: "Safety 2"
      }
  
  
  Safety 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Safety 3.svg
        shape: image
        label: "Safety 3"
      }
  
  
  Safety 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Safety 4.svg
        shape: image
        label: "Safety 4"
      }
  
  
  Safety 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Safety 5.svg
        shape: image
        label: "Safety 5"
      }
  
  
  Safety: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Safety/Safety.svg
        shape: image
        label: "Safety"
      }
  
}