classes: {...@../classes/other/terrastruct/azure.d2.classes}

Batch: {
    blob.class: Data Lake Storage
    Legacy SQL Database.class: Azure SQL Database
    blob.label: Data Lake Storage
}

Stream : {
    API Connections.class: API Connections
}