classes: {...@../classes/lingaro/sa/shapes.d2.classes}
classes: {...@../classes/other/terrastruct/gcp.d2.classes}
x.icon2.class: gml
*.class: gcpShape

x -> y -> z

x.description: |md
  # Ingest
  ## App Engine
  Streaming changes
|

y.description: |md
  # Ingest
  ## App Engine
  Streaming changes
|

z.description: |md
  # Ingest
  ## App Engine
  Streaming changes
|