classes: {...@../classes/lingaro/sa/shapes.d2.classes}

gcpShape: {
  grid-rows: 3
  icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAI%20and%20Machine%20Learning%2FAI%20Platform.svg
  label: "Label"
}

gcpShape.documentation: |md
  # Documentation
  ## App Engine
  Streaming changes



gml_2.description: |md
    # Purpose
    ## Name
    short desc
  |

  gml_1 -> gml_2 -> z

 gml_1.description: |md
    # Ingest
    ## App Engine
    Streaming changes
  |

  gml*.icon2.icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAI%20and%20Machine%20Learning%2FAI%20Platform.svg
  gml*.icon2.shape: image
  gml*.icon2.label: "gml"