classes: {...@../classes/lingaro/sa/shapes.d2.classes}

  *.icon2.icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FAI%20and%20Machine%20Learning%2FAI%20Platform.svg
  *.icon2.shape: image
  *.icon2.label: ""

  *.description: |md
    # Purpose
    ## Name
    short desc
  |

  x -> y -> z

  x.description: |md
    # Ingest
    ## App Engine
    Streaming changes
  |
