classes: {
  
  Data_Activator__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/Data_Activator__color.svg
        shape: image
        label: "Data_Activator__color"
      }
  
  Data_Activator__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/Data_Activator__regular.svg
        shape: image
        label: "Data_Activator__regular"
      }
  
  data_factory__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/data_factory__color.svg
        shape: image
        label: "data_factory__color"
      }
  
  data_factory__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/data_factory__regular.svg
        shape: image
        label: "data_factory__regular"
      }
  
  onelake__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/onelake__color.svg
        shape: image
        label: "onelake__color"
      }
  
  onelake__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/onelake__regular.svg
        shape: image
        label: "onelake__regular"
      }
  
  powerbi__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/powerbi__regular.svg
        shape: image
        label: "powerbi__regular"
      }
  
  power_bi__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/power_bi__color.svg
        shape: image
        label: "power_bi__color"
      }
  
  synapse_data_engineering__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_engineering__color.svg
        shape: image
        label: "synapse_data_engineering__color"
      }
  
  synapse_data_engineering__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_engineering__regular.svg
        shape: image
        label: "synapse_data_engineering__regular"
      }
  
  synapse_data_science__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_science__color.svg
        shape: image
        label: "synapse_data_science__color"
      }
  
  synapse_data_science__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_science__regular.svg
        shape: image
        label: "synapse_data_science__regular"
      }
  
  synapse_data_warehouse__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_warehouse__color.svg
        shape: image
        label: "synapse_data_warehouse__color"
      }
  
  synapse_data_warehouse__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_warehouse__regular.svg
        shape: image
        label: "synapse_data_warehouse__regular"
      }
  
  synapse_real_time_analytics__color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_real_time_analytics__color.svg
        shape: image
        label: "synapse_real_time_analytics__color"
      }
  
  synapse_real_time_analytics__regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_real_time_analytics__regular.svg
        shape: image
        label: "synapse_real_time_analytics__regular"
      }
  
}