classes: {
  
  
  Data Activator  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/Data_Activator__color.svg
        shape: image
        label: "Data Activator  Color"
      }
  
  
  Data Activator  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/Data_Activator__regular.svg
        shape: image
        label: "Data Activator  Regular"
      }
  
  
  Data Factory  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/data_factory__color.svg
        shape: image
        label: "Data Factory  Color"
      }
  
  
  Data Factory  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/data_factory__regular.svg
        shape: image
        label: "Data Factory  Regular"
      }
  
  
  Onelake  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/onelake__color.svg
        shape: image
        label: "Onelake  Color"
      }
  
  
  Onelake  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/onelake__regular.svg
        shape: image
        label: "Onelake  Regular"
      }
  
  
  Powerbi  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/powerbi__regular.svg
        shape: image
        label: "Powerbi  Regular"
      }
  
  
  Power Bi  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/power_bi__color.svg
        shape: image
        label: "Power Bi  Color"
      }
  
  
  Synapse Data Engineering  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_engineering__color.svg
        shape: image
        label: "Synapse Data Engineering  Color"
      }
  
  
  Synapse Data Engineering  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_engineering__regular.svg
        shape: image
        label: "Synapse Data Engineering  Regular"
      }
  
  
  Synapse Data Science  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_science__color.svg
        shape: image
        label: "Synapse Data Science  Color"
      }
  
  
  Synapse Data Science  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_science__regular.svg
        shape: image
        label: "Synapse Data Science  Regular"
      }
  
  
  Synapse Data Warehouse  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_warehouse__color.svg
        shape: image
        label: "Synapse Data Warehouse  Color"
      }
  
  
  Synapse Data Warehouse  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_data_warehouse__regular.svg
        shape: image
        label: "Synapse Data Warehouse  Regular"
      }
  
  
  Synapse Real Time Analytics  Color: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_real_time_analytics__color.svg
        shape: image
        label: "Synapse Real Time Analytics  Color"
      }
  
  
  Synapse Real Time Analytics  Regular: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Experiences/synapse_real_time_analytics__regular.svg
        shape: image
        label: "Synapse Real Time Analytics  Regular"
      }
  
}