classes: {
  
  
  Res Amazon Pinpoint Journey: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Business-Applications/Res_Amazon_Pinpoint_Journey.svg
        shape: image
        label: "Res Amazon Pinpoint Journey"
      }
  
  
  Res Amazon Simple Email Service Email: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Business-Applications/Res_Amazon_Simple_Email_Service_Email.svg
        shape: image
        label: "Res Amazon Simple Email Service Email"
      }
  
}