classes: {
  
  
  Amazon Elastic Transcoder: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/Amazon_Elastic_Transcoder.svg
        shape: image
        label: "Amazon Elastic Transcoder"
      }
  
  
  Amazon Interactive Video Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/Amazon_Interactive_Video_Service.svg
        shape: image
        label: "Amazon Interactive Video Service"
      }
  
  
  Amazon Kinesis Video Streams: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/Amazon_Kinesis_Video_Streams.svg
        shape: image
        label: "Amazon Kinesis Video Streams"
      }
  
  
  Amazon Nimble Studio: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/Amazon_Nimble_Studio.svg
        shape: image
        label: "Amazon Nimble Studio"
      }
  
  
  Aws Elemental Appliances & Software: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_Appliances_&_Software.svg
        shape: image
        label: "Aws Elemental Appliances & Software"
      }
  
  
  Aws Elemental Conductor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_Conductor.svg
        shape: image
        label: "Aws Elemental Conductor"
      }
  
  
  Aws Elemental Delta: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_Delta.svg
        shape: image
        label: "Aws Elemental Delta"
      }
  
  
  Aws Elemental Link: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_Link.svg
        shape: image
        label: "Aws Elemental Link"
      }
  
  
  Aws Elemental Live: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_Live.svg
        shape: image
        label: "Aws Elemental Live"
      }
  
  
  Aws Elemental Mediaconnect: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_MediaConnect.svg
        shape: image
        label: "Aws Elemental Mediaconnect"
      }
  
  
  Aws Elemental Mediaconvert: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_MediaConvert.svg
        shape: image
        label: "Aws Elemental Mediaconvert"
      }
  
  
  Aws Elemental Medialive: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_MediaLive.svg
        shape: image
        label: "Aws Elemental Medialive"
      }
  
  
  Aws Elemental Mediapackage: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_MediaPackage.svg
        shape: image
        label: "Aws Elemental Mediapackage"
      }
  
  
  Aws Elemental Mediastore: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_MediaStore.svg
        shape: image
        label: "Aws Elemental Mediastore"
      }
  
  
  Aws Elemental Mediatailor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_MediaTailor.svg
        shape: image
        label: "Aws Elemental Mediatailor"
      }
  
  
  Aws Elemental Server: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Media-Services/AWS_Elemental_Server.svg
        shape: image
        label: "Aws Elemental Server"
      }
  
}