classes: {
  
  icon_service_Azure_Databox_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Azure_Databox_Gateway.svg
        shape: image
        label: "icon_service_Azure_Databox_Gateway"
      }
  
  icon_service_Azure_Fileshares: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Azure_Fileshares.svg
        shape: image
        label: "icon_service_Azure_Fileshares"
      }
  
  icon_service_Azure_HCP_Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Azure_HCP_Cache.svg
        shape: image
        label: "icon_service_Azure_HCP_Cache"
      }
  
  icon_service_Azure_NetApp_Files: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Azure_NetApp_Files.svg
        shape: image
        label: "icon_service_Azure_NetApp_Files"
      }
  
  icon_service_Azure_Stack_Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Azure_Stack_Edge.svg
        shape: image
        label: "icon_service_Azure_Stack_Edge"
      }
  
  icon_service_Data_Box: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Data_Box.svg
        shape: image
        label: "icon_service_Data_Box"
      }
  
  icon_service_Data_Lake_Storage_Gen: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Data_Lake_Storage_Gen.svg
        shape: image
        label: "icon_service_Data_Lake_Storage_Gen"
      }
  
  icon_service_Data_Shares: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Data_Shares.svg
        shape: image
        label: "icon_service_Data_Shares"
      }
  
  icon_service_Data_Share_Invitations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Data_Share_Invitations.svg
        shape: image
        label: "icon_service_Data_Share_Invitations"
      }
  
  icon_service_Import_Export_Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Import_Export_Jobs.svg
        shape: image
        label: "icon_service_Import_Export_Jobs"
      }
  
  icon_service_Recovery_Services_Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Recovery_Services_Vaults.svg
        shape: image
        label: "icon_service_Recovery_Services_Vaults"
      }
  
  icon_service_Storage_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Storage_Accounts.svg
        shape: image
        label: "icon_service_Storage_Accounts"
      }
  
  icon_service_Storage_Accounts_(Classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Storage_Accounts_(Classic).svg
        shape: image
        label: "icon_service_Storage_Accounts_(Classic)"
      }
  
  icon_service_Storage_Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Storage_Explorer.svg
        shape: image
        label: "icon_service_Storage_Explorer"
      }
  
  icon_service_Storage_Sync_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_Storage_Sync_Services.svg
        shape: image
        label: "icon_service_Storage_Sync_Services"
      }
  
  icon_service_StorSimple_Data_Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_StorSimple_Data_Managers.svg
        shape: image
        label: "icon_service_StorSimple_Data_Managers"
      }
  
  icon_service_StorSimple_Device_Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/icon_service_StorSimple_Device_Managers.svg
        shape: image
        label: "icon_service_StorSimple_Device_Managers"
      }
  
}