classes: {
  
  
  Azure Databox Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Azure_Databox_Gateway.svg
        shape: image
        label: "Azure Databox Gateway"
      }
  
  
  Azure Fileshares: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Azure_Fileshares.svg
        shape: image
        label: "Azure Fileshares"
      }
  
  
  Azure Hcp Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Azure_HCP_Cache.svg
        shape: image
        label: "Azure Hcp Cache"
      }
  
  
  Azure Netapp Files: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Azure_NetApp_Files.svg
        shape: image
        label: "Azure Netapp Files"
      }
  
  
  Azure Stack Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Azure_Stack_Edge.svg
        shape: image
        label: "Azure Stack Edge"
      }
  
  
  Data Box: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Data_Box.svg
        shape: image
        label: "Data Box"
      }
  
  
  Data Lake Storage Gen: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Data_Lake_Storage_Gen.svg
        shape: image
        label: "Data Lake Storage Gen"
      }
  
  
  Data Shares: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Data_Shares.svg
        shape: image
        label: "Data Shares"
      }
  
  
  Data Share Invitations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Data_Share_Invitations.svg
        shape: image
        label: "Data Share Invitations"
      }
  
  
  Import Export Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Import_Export_Jobs.svg
        shape: image
        label: "Import Export Jobs"
      }
  
  
  Recovery Services Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Recovery_Services_Vaults.svg
        shape: image
        label: "Recovery Services Vaults"
      }
  
  
  Storage Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Storage_Accounts.svg
        shape: image
        label: "Storage Accounts"
      }
  
  
  Storage Accounts (classic): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Storage_Accounts_(Classic).svg
        shape: image
        label: "Storage Accounts (classic)"
      }
  
  
  Storage Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Storage_Explorer.svg
        shape: image
        label: "Storage Explorer"
      }
  
  
  Storage Sync Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/Storage_Sync_Services.svg
        shape: image
        label: "Storage Sync Services"
      }
  
  
  Storsimple Data Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/StorSimple_Data_Managers.svg
        shape: image
        label: "Storsimple Data Managers"
      }
  
  
  Storsimple Device Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/storage/StorSimple_Device_Managers.svg
        shape: image
        label: "Storsimple Device Managers"
      }
  
}