classes: {
  
  
  Res Alert  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Alert__Light.svg
        shape: image
        label: "Res Alert  Light"
      }
  
  
  Res Authenticated User  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Authenticated_User__Light.svg
        shape: image
        label: "Res Authenticated User  Light"
      }
  
  
  Res Aws Management Console  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_AWS_Management_Console__Light.svg
        shape: image
        label: "Res Aws Management Console  Light"
      }
  
  
  Res Camera  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Camera__Light.svg
        shape: image
        label: "Res Camera  Light"
      }
  
  
  Res Chat  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Chat__Light.svg
        shape: image
        label: "Res Chat  Light"
      }
  
  
  Res Client  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Client__Light.svg
        shape: image
        label: "Res Client  Light"
      }
  
  
  Res Cold Storage  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Cold_Storage__Light.svg
        shape: image
        label: "Res Cold Storage  Light"
      }
  
  
  Res Credentials  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Credentials__Light.svg
        shape: image
        label: "Res Credentials  Light"
      }
  
  
  Res Database  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Database__Light.svg
        shape: image
        label: "Res Database  Light"
      }
  
  
  Res Data Stream  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Data_Stream__Light.svg
        shape: image
        label: "Res Data Stream  Light"
      }
  
  
  Res Data Table  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Data_Table__Light.svg
        shape: image
        label: "Res Data Table  Light"
      }
  
  
  Res Disk  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Disk__Light.svg
        shape: image
        label: "Res Disk  Light"
      }
  
  
  Res Documents  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Documents__Light.svg
        shape: image
        label: "Res Documents  Light"
      }
  
  
  Res Document  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Document__Light.svg
        shape: image
        label: "Res Document  Light"
      }
  
  
  Res Email  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Email__Light.svg
        shape: image
        label: "Res Email  Light"
      }
  
  
  Res Firewall  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Firewall__Light.svg
        shape: image
        label: "Res Firewall  Light"
      }
  
  
  Res Folders  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Folders__Light.svg
        shape: image
        label: "Res Folders  Light"
      }
  
  
  Res Folder  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Folder__Light.svg
        shape: image
        label: "Res Folder  Light"
      }
  
  
  Res Forums  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Forums__Light.svg
        shape: image
        label: "Res Forums  Light"
      }
  
  
  Res Gear  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Gear__Light.svg
        shape: image
        label: "Res Gear  Light"
      }
  
  
  Res Generic Application  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Generic_Application__Light.svg
        shape: image
        label: "Res Generic Application  Light"
      }
  
  
  Res Git Repository  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Git_Repository__Light.svg
        shape: image
        label: "Res Git Repository  Light"
      }
  
  
  Res Globe  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Globe__Light.svg
        shape: image
        label: "Res Globe  Light"
      }
  
  
  Res Internet-alt2 48 Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Internet-alt2_48_Light.svg
        shape: image
        label: "Res Internet-alt2 48 Light"
      }
  
  
  Res Internet Alt  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Internet_alt__Light.svg
        shape: image
        label: "Res Internet Alt  Light"
      }
  
  
  Res Internet  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Internet__Light.svg
        shape: image
        label: "Res Internet  Light"
      }
  
  
  Res Json Script  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_JSON_Script__Light.svg
        shape: image
        label: "Res Json Script  Light"
      }
  
  
  Res Logs  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Logs__Light.svg
        shape: image
        label: "Res Logs  Light"
      }
  
  
  Res Magnifying Glass  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Magnifying_Glass__Light.svg
        shape: image
        label: "Res Magnifying Glass  Light"
      }
  
  
  Res Metrics  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Metrics__Light.svg
        shape: image
        label: "Res Metrics  Light"
      }
  
  
  Res Mobile Client  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Mobile_client__Light.svg
        shape: image
        label: "Res Mobile Client  Light"
      }
  
  
  Res Multimedia  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Multimedia__Light.svg
        shape: image
        label: "Res Multimedia  Light"
      }
  
  
  Res Office Building  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Office_building__Light.svg
        shape: image
        label: "Res Office Building  Light"
      }
  
  
  Res Programming Language  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Programming_Language__Light.svg
        shape: image
        label: "Res Programming Language  Light"
      }
  
  
  Res Question  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Question__Light.svg
        shape: image
        label: "Res Question  Light"
      }
  
  
  Res Recover  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Recover__Light.svg
        shape: image
        label: "Res Recover  Light"
      }
  
  
  Res Saml Token  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_SAML_token__Light.svg
        shape: image
        label: "Res Saml Token  Light"
      }
  
  
  Res Sdk  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_SDK__Light.svg
        shape: image
        label: "Res Sdk  Light"
      }
  
  
  Res Servers  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Servers__Light.svg
        shape: image
        label: "Res Servers  Light"
      }
  
  
  Res Server  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Server__Light.svg
        shape: image
        label: "Res Server  Light"
      }
  
  
  Res Shield  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Shield__Light.svg
        shape: image
        label: "Res Shield  Light"
      }
  
  
  Res Source Code  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Source_Code__Light.svg
        shape: image
        label: "Res Source Code  Light"
      }
  
  
  Res Ssl Padlock  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_SSL_padlock__Light.svg
        shape: image
        label: "Res Ssl Padlock  Light"
      }
  
  
  Res Tape Storage  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Tape_storage__Light.svg
        shape: image
        label: "Res Tape Storage  Light"
      }
  
  
  Res Toolkit  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Toolkit__Light.svg
        shape: image
        label: "Res Toolkit  Light"
      }
  
  
  Res Users  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_Users__Light.svg
        shape: image
        label: "Res Users  Light"
      }
  
  
  Res User  Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Light/Res_User__Light.svg
        shape: image
        label: "Res User  Light"
      }
  
}