classes: {...@../../classes/lingaro/erd/domain_shapes.d2.classes}
Sales start schema: {
  fct_sales: {
    tooltip: Total abstinence is easier than perfect moderation
    order_id: STRING {constraint: primary_key}
    item_sku: STRING dim_product.product_sku
    item_name: STRING order_line_item.name
    item_category: STRING assoc_product_category.product_idcategoty_iddim_category.categoty_id
    item_qty: INT order_line_item.qty
    item_price: FLOAT order_line_item.item_price
    item_discount: FLOAT order_line_item.discount
    item_tax: FLOAT order_line_item.tax
    item_total: FLOAT order_line_item.total
    order_discount: FLOAT
    order_tax: FLOAT
    order_total: FLOAT
    store_id: STRING {constraint: foreign_key}
    store_name: STRING {constraint: foreign_key dim_store.name}
    store_url: STRING {constraint: foreign_key dim_store.url}
    store_brand: STRING {constraint: foreign_key dim_store.brand}
    store_region: STRING {constraint: foreign_key dim_store.region}
    customer_id: STRING {constraint: foreign_key}
    order_date: DATE
    shipping_method_name: STRING shipping_method.name
    shipping_cost: FLOAT
    payment_method_name: STRING payment_method.name
    payment_cost: FLOAT
    billing_address_id: STRING {constraint: foreign_key dim_address.zip_code}
    shipping_address_id: STRING {constraint: foreign_key dim_address.zip_code}

  }
  fct_sales.class: fct
  dim_address: {
    address_id: STRING {constraint: primary_key}
    city: STRING
    zip_code: STRING
    country: STRING
    state: STRING

  }

  dim_customer: {
    customer_id: STRING {constraint: primary_key}
    customer_first_name: STRING
    customer_last_name: STRING
    customer_email: STRING
    customer_phone: STRING
    shipping_address_street_name: STRING
    shipping_address_street_number: STRING
    shipping_address_city: STRING
    shipping_address_zip: STRING
    shipping_address_state: STRING
    shipping_address_country: STRING
    billing_address_street_name: STRING
    billing_address_street_number: STRING
    billing_address_city: STRING
    billing_address_zip: STRING
    billing_address_state: STRING
    billing_address_country: STRING
    acquisition_date: DATE

  }

  dim_product: {
    id: STRING {constraint: primary_key}
    product_sku: STRING
    product_name: STRING
    product_price: FLOAT
    # store_id: STRING {constraint: foreign_key}
    store_name: STRING
    # product_categories: STRING {constraint: foreign_key assoc_product_category.product_id}
    primary_product_category: STRING

  }

  dim_store: {
    id: STRING {constraint: primary_key}
    url: STRING
    name: STRING
    region: STRING
    brand: STRING

  }

  assoc_product_category: {
    product_id: STRING {constraint: foreign_key}
    category_id: STRING {constraint: foreign_key}

  }

  dim_category: {
    category_id: STRING {constraint: primary_key}
    category_name: STRING
    is_leaf: BOOLEAN
    parent_category_id: STRING {constraint: foreign_key}
    # I need to add store attributes here
    store_id: STRING {constraint: foreign_key}
    store_name: STRING {constraint: foreign_key}


  }

  fct_sales.item_sku <-> dim_product.product_sku: "is for" {class: om-1}

  fct_sales.store_id <-> dim_store.id: "belongs to" {class: om-1}

  fct_sales.customer_id <-> dim_customer.customer_id: "placed by" {class: om-1}

  #    fct_sales.shipping_method_id <-> dim_shipping_method.shipping_method_id: "uses" {
  #      source-arrowhead.shape: cf-one-required
  #      target-arrowhead.shape: cf-many
  #    }

  #    fct_sales.payment_method_id <-> dim_payment_method.payment_method_id: "paid by" {
  #      source-arrowhead.shape: cf-one-required
  #      target-arrowhead.shape: cf-many
  #    }

  fct_sales.billing_address_id <-> dim_address.address_id: "billed to" {class: om-1}

  fct_sales.shipping_address_id <-> dim_address.address_id: "shipped to" {class: om-1}

  dim_product.product_categories <-> assoc_product_category.product_id: "has" {class: om-om}

  assoc_product_category.product_id <-> dim_product.id: "belongs to" {class: om-om}

  assoc_product_category.category_id <-> dim_category.category_id: "categorized as" {class: m-o}
  *.shape: sql_table
}

