classes: {
  
  icon_service_Azure_AD_Roles_and_Administrators: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Azure_AD_Roles_and_Administrators.svg
        shape: image
        label: "icon_service_Azure_AD_Roles_and_Administrators"
      }
  
  icon_service_Client_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Client_Apps.svg
        shape: image
        label: "icon_service_Client_Apps"
      }
  
  icon_service_Devices: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Devices.svg
        shape: image
        label: "icon_service_Devices"
      }
  
  icon_service_Device_Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Device_Compliance.svg
        shape: image
        label: "icon_service_Device_Compliance"
      }
  
  icon_service_Device_Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Device_Configuration.svg
        shape: image
        label: "icon_service_Device_Configuration"
      }
  
  icon_service_Device_Enrollment: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Device_Enrollment.svg
        shape: image
        label: "icon_service_Device_Enrollment"
      }
  
  icon_service_Device_Security_Apple: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Device_Security_Apple.svg
        shape: image
        label: "icon_service_Device_Security_Apple"
      }
  
  icon_service_Device_Security_Google: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Device_Security_Google.svg
        shape: image
        label: "icon_service_Device_Security_Google"
      }
  
  icon_service_Device_Security_Windows: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Device_Security_Windows.svg
        shape: image
        label: "icon_service_Device_Security_Windows"
      }
  
  icon_service_eBooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_eBooks.svg
        shape: image
        label: "icon_service_eBooks"
      }
  
  icon_service_Exchange_Access: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Exchange_Access.svg
        shape: image
        label: "icon_service_Exchange_Access"
      }
  
  icon_service_Intune: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Intune.svg
        shape: image
        label: "icon_service_Intune"
      }
  
  icon_service_Intune_App_Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Intune_App_Protection.svg
        shape: image
        label: "icon_service_Intune_App_Protection"
      }
  
  icon_service_Intune_For_Education: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Intune_For_Education.svg
        shape: image
        label: "icon_service_Intune_For_Education"
      }
  
  icon_service_Mindaro: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Mindaro.svg
        shape: image
        label: "icon_service_Mindaro"
      }
  
  icon_service_Security_Baselines: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Security_Baselines.svg
        shape: image
        label: "icon_service_Security_Baselines"
      }
  
  icon_service_Software_Updates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Software_Updates.svg
        shape: image
        label: "icon_service_Software_Updates"
      }
  
  icon_service_Tenant_Status: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/icon_service_Tenant_Status.svg
        shape: image
        label: "icon_service_Tenant_Status"
      }
  
}