classes: {
  
  
  Azure Ad Roles And Administrators: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Azure_AD_Roles_and_Administrators.svg
        shape: image
        label: "Azure Ad Roles And Administrators"
      }
  
  
  Client Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Client_Apps.svg
        shape: image
        label: "Client Apps"
      }
  
  
  Devices: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Devices.svg
        shape: image
        label: "Devices"
      }
  
  
  Device Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Device_Compliance.svg
        shape: image
        label: "Device Compliance"
      }
  
  
  Device Configuration: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Device_Configuration.svg
        shape: image
        label: "Device Configuration"
      }
  
  
  Device Enrollment: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Device_Enrollment.svg
        shape: image
        label: "Device Enrollment"
      }
  
  
  Device Security Apple: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Device_Security_Apple.svg
        shape: image
        label: "Device Security Apple"
      }
  
  
  Device Security Google: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Device_Security_Google.svg
        shape: image
        label: "Device Security Google"
      }
  
  
  Device Security Windows: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Device_Security_Windows.svg
        shape: image
        label: "Device Security Windows"
      }
  
  
  Ebooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/eBooks.svg
        shape: image
        label: "Ebooks"
      }
  
  
  Exchange Access: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Exchange_Access.svg
        shape: image
        label: "Exchange Access"
      }
  
  
  Intune: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Intune.svg
        shape: image
        label: "Intune"
      }
  
  
  Intune App Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Intune_App_Protection.svg
        shape: image
        label: "Intune App Protection"
      }
  
  
  Intune For Education: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Intune_For_Education.svg
        shape: image
        label: "Intune For Education"
      }
  
  
  Mindaro: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Mindaro.svg
        shape: image
        label: "Mindaro"
      }
  
  
  Security Baselines: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Security_Baselines.svg
        shape: image
        label: "Security Baselines"
      }
  
  
  Software Updates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Software_Updates.svg
        shape: image
        label: "Software Updates"
      }
  
  
  Tenant Status: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/intune/Tenant_Status.svg
        shape: image
        label: "Tenant Status"
      }
  
}