classes: {
  dim: {
    style: {
      fill: "#000000"
      shadow: true
    }
  }
  fct: {
    style: {
      fill: "#5B5B5B"
      shadow: true
    }
  }
  o-om: {
    source-arrowhead.shape: cf-one
    target-arrowhead.shape: cf-many
  }
  o-o: {
    source-arrowhead.shape: cf-one
    target-arrowhead.shape: cf-one
  }
  1-1: {
    source-arrowhead.shape: cf-one-required
    target-arrowhead.shape: cf-one-required
  }
  o-om: {
    source-arrowhead.shape: cf-one
    target-arrowhead.shape: cf-many
  }
  o-m: {
    source-arrowhead.shape: cf-one
    target-arrowhead.shape: cf-many-required
  }
  1-m: {
    source-arrowhead.shape: cf-one-required
    target-arrowhead.shape: cf-many-required
  }
  1-om: {
    source-arrowhead.shape: cf-one-required
    target-arrowhead.shape: cf-many
  }
  om-o: {
    source-arrowhead.shape: cf-many
    target-arrowhead.shape: cf-one
  }
  m-o: {
    source-arrowhead.shape: cf-many-required
    target-arrowhead.shape: cf-one
  }
  m-1: {
    source-arrowhead.shape: cf-many-required
    target-arrowhead.shape: cf-one-required
  }
  om-1: {
    source-arrowhead.shape: cf-many
    target-arrowhead.shape: cf-one-required
  }
  om-m: {
    source-arrowhead.shape: cf-many
    target-arrowhead.shape: cf-many-required
  }
  m-om: {
    source-arrowhead.shape: cf-many-required
    target-arrowhead.shape: cf-many
  }
  om-om: {
    source-arrowhead.shape: cf-many
    target-arrowhead.shape: cf-many
  }
  m-m: {
    source-arrowhead.shape: cf-many-required
    target-arrowhead.shape: cf-many-required
  }
}
