classes: {
  
  icon_service_App_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_App_Services.svg
        shape: image
        label: "icon_service_App_Services"
      }
  
  icon_service_App_Service_Certificates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_App_Service_Certificates.svg
        shape: image
        label: "icon_service_App_Service_Certificates"
      }
  
  icon_service_App_Service_Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_App_Service_Domains.svg
        shape: image
        label: "icon_service_App_Service_Domains"
      }
  
  icon_service_App_Service_Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_App_Service_Environments.svg
        shape: image
        label: "icon_service_App_Service_Environments"
      }
  
  icon_service_App_Service_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_App_Service_Plans.svg
        shape: image
        label: "icon_service_App_Service_Plans"
      }
  
  icon_service_CDN_Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_CDN_Profiles.svg
        shape: image
        label: "icon_service_CDN_Profiles"
      }
  
  icon_service_Cognitive_Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_Cognitive_Search.svg
        shape: image
        label: "icon_service_Cognitive_Search"
      }
  
  icon_service_Notification_Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/icon_service_Notification_Hubs.svg
        shape: image
        label: "icon_service_Notification_Hubs"
      }
  
}