classes: {
  
  
  App Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/App_Services.svg
        shape: image
        label: "App Services"
      }
  
  
  App Service Certificates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/App_Service_Certificates.svg
        shape: image
        label: "App Service Certificates"
      }
  
  
  App Service Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/App_Service_Domains.svg
        shape: image
        label: "App Service Domains"
      }
  
  
  App Service Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/App_Service_Environments.svg
        shape: image
        label: "App Service Environments"
      }
  
  
  App Service Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/App_Service_Plans.svg
        shape: image
        label: "App Service Plans"
      }
  
  
  Cdn Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/CDN_Profiles.svg
        shape: image
        label: "Cdn Profiles"
      }
  
  
  Cognitive Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/Cognitive_Search.svg
        shape: image
        label: "Cognitive Search"
      }
  
  
  Notification Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/app services/Notification_Hubs.svg
        shape: image
        label: "Notification Hubs"
      }
  
}