classes: {
  
  
  Capacity: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/Capacity.svg
        shape: image
        label: "Capacity"
      }
  
  
  Infrastructure Backup: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/Infrastructure_Backup.svg
        shape: image
        label: "Infrastructure Backup"
      }
  
  
  Multi Tenancy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/Multi_Tenancy.svg
        shape: image
        label: "Multi Tenancy"
      }
  
  
  Offers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/Offers.svg
        shape: image
        label: "Offers"
      }
  
  
  Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/Plans.svg
        shape: image
        label: "Plans"
      }
  
  
  Updates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/Updates.svg
        shape: image
        label: "Updates"
      }
  
  
  User Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/User_Subscriptions.svg
        shape: image
        label: "User Subscriptions"
      }
  
}