classes: {
  
  icon_service_Capacity: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_Capacity.svg
        shape: image
        label: "icon_service_Capacity"
      }
  
  icon_service_Infrastructure_Backup: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_Infrastructure_Backup.svg
        shape: image
        label: "icon_service_Infrastructure_Backup"
      }
  
  icon_service_Multi_Tenancy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_Multi_Tenancy.svg
        shape: image
        label: "icon_service_Multi_Tenancy"
      }
  
  icon_service_Offers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_Offers.svg
        shape: image
        label: "icon_service_Offers"
      }
  
  icon_service_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_Plans.svg
        shape: image
        label: "icon_service_Plans"
      }
  
  icon_service_Updates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_Updates.svg
        shape: image
        label: "icon_service_Updates"
      }
  
  icon_service_User_Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/azure stack/icon_service_User_Subscriptions.svg
        shape: image
        label: "icon_service_User_Subscriptions"
      }
  
}