classes: {
  
  
  Aws Ground Station: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Satellite/AWS_Ground_Station.svg
        shape: image
        label: "Aws Ground Station"
      }
  
}