classes: {
  
  
  Aws Marketplace Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/General-Icons/AWS_Marketplace_Dark.svg
        shape: image
        label: "Aws Marketplace Dark"
      }
  
  
  Aws Marketplace Light: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/General-Icons/AWS_Marketplace_Light.svg
        shape: image
        label: "Aws Marketplace Light"
      }
  
}