classes: {
  
  
  Amazon Athena: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Athena.svg
        shape: image
        label: "Amazon Athena"
      }
  
  
  Amazon Cloudsearch: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_CloudSearch.svg
        shape: image
        label: "Amazon Cloudsearch"
      }
  
  
  Amazon Datazone: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_DataZone.svg
        shape: image
        label: "Amazon Datazone"
      }
  
  
  Amazon Emr: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_EMR.svg
        shape: image
        label: "Amazon Emr"
      }
  
  
  Amazon Finspace: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_FinSpace.svg
        shape: image
        label: "Amazon Finspace"
      }
  
  
  Amazon Kinesis: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Kinesis.svg
        shape: image
        label: "Amazon Kinesis"
      }
  
  
  Amazon Kinesis Data Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Kinesis_Data_Analytics.svg
        shape: image
        label: "Amazon Kinesis Data Analytics"
      }
  
  
  Amazon Kinesis Data Firehose: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Kinesis_Data_Firehose.svg
        shape: image
        label: "Amazon Kinesis Data Firehose"
      }
  
  
  Amazon Kinesis Data Streams: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Kinesis_Data_Streams.svg
        shape: image
        label: "Amazon Kinesis Data Streams"
      }
  
  
  Amazon Kinesis Video Streams: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Kinesis_Video_Streams.svg
        shape: image
        label: "Amazon Kinesis Video Streams"
      }
  
  
  Amazon Managed Streaming For Apache Kafka: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Managed_Streaming_for_Apache_Kafka.svg
        shape: image
        label: "Amazon Managed Streaming For Apache Kafka"
      }
  
  
  Amazon Opensearch Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_OpenSearch_Service.svg
        shape: image
        label: "Amazon Opensearch Service"
      }
  
  
  Amazon Quicksight: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_QuickSight.svg
        shape: image
        label: "Amazon Quicksight"
      }
  
  
  Amazon Redshift: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/Amazon_Redshift.svg
        shape: image
        label: "Amazon Redshift"
      }
  
  
  Aws Clean Rooms: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Clean_Rooms.svg
        shape: image
        label: "Aws Clean Rooms"
      }
  
  
  Aws Data Exchange: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Data_Exchange.svg
        shape: image
        label: "Aws Data Exchange"
      }
  
  
  Aws Data Pipeline: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Data_Pipeline.svg
        shape: image
        label: "Aws Data Pipeline"
      }
  
  
  Aws Glue: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Glue.svg
        shape: image
        label: "Aws Glue"
      }
  
  
  Aws Glue Databrew: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Glue_DataBrew.svg
        shape: image
        label: "Aws Glue Databrew"
      }
  
  
  Aws Glue Elastic Views: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Glue_Elastic_Views.svg
        shape: image
        label: "Aws Glue Elastic Views"
      }
  
  
  Aws Lake Formation: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Analytics/AWS_Lake_Formation.svg
        shape: image
        label: "Aws Lake Formation"
      }
  
}