classes: {
  
  icon_service_AAD_Licenses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_AAD_Licenses.svg
        shape: image
        label: "icon_service_AAD_Licenses"
      }
  
  icon_service_App_Compliance_Automation: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_App_Compliance_Automation.svg
        shape: image
        label: "icon_service_App_Compliance_Automation"
      }
  
  icon_service_App_Registrations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_App_Registrations.svg
        shape: image
        label: "icon_service_App_Registrations"
      }
  
  icon_service_Aquila: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Aquila.svg
        shape: image
        label: "icon_service_Aquila"
      }
  
  icon_service_Arc_Data_services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Arc_Data_services.svg
        shape: image
        label: "icon_service_Arc_Data_services"
      }
  
  icon_service_Arc_Kubernetes: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Arc_Kubernetes.svg
        shape: image
        label: "icon_service_Arc_Kubernetes"
      }
  
  icon_service_Arc_PostgreSQL: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Arc_PostgreSQL.svg
        shape: image
        label: "icon_service_Arc_PostgreSQL"
      }
  
  icon_service_Arc_SQL_Managed_Instance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Arc_SQL_Managed_Instance.svg
        shape: image
        label: "icon_service_Arc_SQL_Managed_Instance"
      }
  
  icon_service_Arc_SQL_Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Arc_SQL_Server.svg
        shape: image
        label: "icon_service_Arc_SQL_Server"
      }
  
  icon_service_AVS_VM: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_AVS_VM.svg
        shape: image
        label: "icon_service_AVS_VM"
      }
  
  icon_service_AzureAttestation: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_AzureAttestation.svg
        shape: image
        label: "icon_service_AzureAttestation"
      }
  
  icon_service_Azure_A: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_A.svg
        shape: image
        label: "icon_service_Azure_A"
      }
  
  icon_service_Azure_Backup_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Backup_Center.svg
        shape: image
        label: "icon_service_Azure_Backup_Center"
      }
  
  icon_service_Azure_Center_for_SAP: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Center_for_SAP.svg
        shape: image
        label: "icon_service_Azure_Center_for_SAP"
      }
  
  icon_service_Azure_Chaos_Studio: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Chaos_Studio.svg
        shape: image
        label: "icon_service_Azure_Chaos_Studio"
      }
  
  icon_service_Azure_Cloud_Shell: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Cloud_Shell.svg
        shape: image
        label: "icon_service_Azure_Cloud_Shell"
      }
  
  icon_service_Azure_Communication_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Communication_Services.svg
        shape: image
        label: "icon_service_Azure_Communication_Services"
      }
  
  icon_service_Azure_Compute_Galleries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Compute_Galleries.svg
        shape: image
        label: "icon_service_Azure_Compute_Galleries"
      }
  
  icon_service_Azure_Deployment_Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Deployment_Environments.svg
        shape: image
        label: "icon_service_Azure_Deployment_Environments"
      }
  
  icon_service_Azure_Edge_Hardware_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Edge_Hardware_Center.svg
        shape: image
        label: "icon_service_Azure_Edge_Hardware_Center"
      }
  
  icon_service_Azure_HPC_Workbenches: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_HPC_Workbenches.svg
        shape: image
        label: "icon_service_Azure_HPC_Workbenches"
      }
  
  icon_service_Azure_Load_Testing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Load_Testing.svg
        shape: image
        label: "icon_service_Azure_Load_Testing"
      }
  
  icon_service_Azure_Managed_Grafana: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Managed_Grafana.svg
        shape: image
        label: "icon_service_Azure_Managed_Grafana"
      }
  
  icon_service_Azure_Monitor_Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Monitor_Dashboard.svg
        shape: image
        label: "icon_service_Azure_Monitor_Dashboard"
      }
  
  icon_service_Azure_Network_Function_Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Network_Function_Manager.svg
        shape: image
        label: "icon_service_Azure_Network_Function_Manager"
      }
  
  icon_service_Azure_Network_Function_Manager_Functions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Network_Function_Manager_Functions.svg
        shape: image
        label: "icon_service_Azure_Network_Function_Manager_Functions"
      }
  
  icon_service_Azure_Orbital: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Orbital.svg
        shape: image
        label: "icon_service_Azure_Orbital"
      }
  
  icon_service_Azure_Quotas: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Quotas.svg
        shape: image
        label: "icon_service_Azure_Quotas"
      }
  
  icon_service_Azure_Sphere: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Sphere.svg
        shape: image
        label: "icon_service_Azure_Sphere"
      }
  
  icon_service_Azure_Storage_Mover: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Storage_Mover.svg
        shape: image
        label: "icon_service_Azure_Storage_Mover"
      }
  
  icon_service_Azure_Support_Center_Blue: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Support_Center_Blue.svg
        shape: image
        label: "icon_service_Azure_Support_Center_Blue"
      }
  
  icon_service_Azure_Video_Indexer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Video_Indexer.svg
        shape: image
        label: "icon_service_Azure_Video_Indexer"
      }
  
  icon_service_Azure_Virtual_Desktop: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_Virtual_Desktop.svg
        shape: image
        label: "icon_service_Azure_Virtual_Desktop"
      }
  
  icon_service_Azure_VMware_Solution: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azure_VMware_Solution.svg
        shape: image
        label: "icon_service_Azure_VMware_Solution"
      }
  
  icon_service_Azurite: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Azurite.svg
        shape: image
        label: "icon_service_Azurite"
      }
  
  icon_service_Backup_Vault: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Backup_Vault.svg
        shape: image
        label: "icon_service_Backup_Vault"
      }
  
  icon_service_Bare_Metal_Infrastructure: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Bare_Metal_Infrastructure.svg
        shape: image
        label: "icon_service_Bare_Metal_Infrastructure"
      }
  
  icon_service_Capacity_Reservation_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Capacity_Reservation_Groups.svg
        shape: image
        label: "icon_service_Capacity_Reservation_Groups"
      }
  
  icon_service_Central_Service_Instance_For_SAP: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Central_Service_Instance_For_SAP.svg
        shape: image
        label: "icon_service_Central_Service_Instance_For_SAP"
      }
  
  icon_service_Ceres: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Ceres.svg
        shape: image
        label: "icon_service_Ceres"
      }
  
  icon_service_Cloud_Services_(extended_support): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Cloud_Services_(extended_support).svg
        shape: image
        label: "icon_service_Cloud_Services_(extended_support)"
      }
  
  icon_service_Community_Images: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Community_Images.svg
        shape: image
        label: "icon_service_Community_Images"
      }
  
  icon_service_Compliance_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Compliance_Center.svg
        shape: image
        label: "icon_service_Compliance_Center"
      }
  
  icon_service_Confidential_Ledgers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Confidential_Ledgers.svg
        shape: image
        label: "icon_service_Confidential_Ledgers"
      }
  
  icon_service_Container_Apps_Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Container_Apps_Environments.svg
        shape: image
        label: "icon_service_Container_Apps_Environments"
      }
  
  icon_service_Cost_Export: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Cost_Export.svg
        shape: image
        label: "icon_service_Cost_Export"
      }
  
  icon_service_Custom_IP_Prefix: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Custom_IP_Prefix.svg
        shape: image
        label: "icon_service_Custom_IP_Prefix"
      }
  
  icon_service_Dashboard_Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Dashboard_Hub.svg
        shape: image
        label: "icon_service_Dashboard_Hub"
      }
  
  icon_service_Database_Instance_For_SAP: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Database_Instance_For_SAP.svg
        shape: image
        label: "icon_service_Database_Instance_For_SAP"
      }
  
  icon_service_Data_Collection_Rules: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Data_Collection_Rules.svg
        shape: image
        label: "icon_service_Data_Collection_Rules"
      }
  
  icon_service_Dedicated_HSM: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Dedicated_HSM.svg
        shape: image
        label: "icon_service_Dedicated_HSM"
      }
  
  icon_service_Defender_CM_Local_Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_CM_Local_Manager.svg
        shape: image
        label: "icon_service_Defender_CM_Local_Manager"
      }
  
  icon_service_Defender_DCS_Controller: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_DCS_Controller.svg
        shape: image
        label: "icon_service_Defender_DCS_Controller"
      }
  
  icon_service_Defender_Distributer_Control_System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Distributer_Control_System.svg
        shape: image
        label: "icon_service_Defender_Distributer_Control_System"
      }
  
  icon_service_Defender_Engineering_Station: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Engineering_Station.svg
        shape: image
        label: "icon_service_Defender_Engineering_Station"
      }
  
  icon_service_Defender_External_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_External_Management.svg
        shape: image
        label: "icon_service_Defender_External_Management"
      }
  
  icon_service_Defender_Freezer_Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Freezer_Monitor.svg
        shape: image
        label: "icon_service_Defender_Freezer_Monitor"
      }
  
  icon_service_Defender_Historian: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Historian.svg
        shape: image
        label: "icon_service_Defender_Historian"
      }
  
  icon_service_Defender_HMI: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_HMI.svg
        shape: image
        label: "icon_service_Defender_HMI"
      }
  
  icon_service_Defender_Industrial_Packaging_System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Industrial_Packaging_System.svg
        shape: image
        label: "icon_service_Defender_Industrial_Packaging_System"
      }
  
  icon_service_Defender_Industrial_Printer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Industrial_Printer.svg
        shape: image
        label: "icon_service_Defender_Industrial_Printer"
      }
  
  icon_service_Defender_Industrial_Robot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Industrial_Robot.svg
        shape: image
        label: "icon_service_Defender_Industrial_Robot"
      }
  
  icon_service_Defender_Industrial_Scale_System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Industrial_Scale_System.svg
        shape: image
        label: "icon_service_Defender_Industrial_Scale_System"
      }
  
  icon_service_Defender_Marquee: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Marquee.svg
        shape: image
        label: "icon_service_Defender_Marquee"
      }
  
  icon_service_Defender_Meter: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Meter.svg
        shape: image
        label: "icon_service_Defender_Meter"
      }
  
  icon_service_Defender_PLC: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_PLC.svg
        shape: image
        label: "icon_service_Defender_PLC"
      }
  
  icon_service_Defender_Pneumatic_Device: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Pneumatic_Device.svg
        shape: image
        label: "icon_service_Defender_Pneumatic_Device"
      }
  
  icon_service_Defender_Programable_Board: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Programable_Board.svg
        shape: image
        label: "icon_service_Defender_Programable_Board"
      }
  
  icon_service_Defender_Relay: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Relay.svg
        shape: image
        label: "icon_service_Defender_Relay"
      }
  
  icon_service_Defender_Robot_Controller: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Robot_Controller.svg
        shape: image
        label: "icon_service_Defender_Robot_Controller"
      }
  
  icon_service_Defender_RTU: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_RTU.svg
        shape: image
        label: "icon_service_Defender_RTU"
      }
  
  icon_service_Defender_Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Sensor.svg
        shape: image
        label: "icon_service_Defender_Sensor"
      }
  
  icon_service_Defender_Slot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Slot.svg
        shape: image
        label: "icon_service_Defender_Slot"
      }
  
  icon_service_Defender_Web_Guiding_System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Defender_Web_Guiding_System.svg
        shape: image
        label: "icon_service_Defender_Web_Guiding_System"
      }
  
  icon_service_Device_Update_IoT_Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Device_Update_IoT_Hub.svg
        shape: image
        label: "icon_service_Device_Update_IoT_Hub"
      }
  
  icon_service_Disk_Pool: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Disk_Pool.svg
        shape: image
        label: "icon_service_Disk_Pool"
      }
  
  icon_service_Edge_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Edge_Management.svg
        shape: image
        label: "icon_service_Edge_Management"
      }
  
  icon_service_Elastic_SAN: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Elastic_SAN.svg
        shape: image
        label: "icon_service_Elastic_SAN"
      }
  
  icon_service_Exchange_On_Premises_Access: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Exchange_On_Premises_Access.svg
        shape: image
        label: "icon_service_Exchange_On_Premises_Access"
      }
  
  icon_service_ExpressRoute_Direct: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_ExpressRoute_Direct.svg
        shape: image
        label: "icon_service_ExpressRoute_Direct"
      }
  
  icon_service_Express_Route_Traffic_Collector: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Express_Route_Traffic_Collector.svg
        shape: image
        label: "icon_service_Express_Route_Traffic_Collector"
      }
  
  icon_service_FHIR_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_FHIR_Service.svg
        shape: image
        label: "icon_service_FHIR_Service"
      }
  
  icon_service_Fiji: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Fiji.svg
        shape: image
        label: "icon_service_Fiji"
      }
  
  icon_service_Instance_Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Instance_Pools.svg
        shape: image
        label: "icon_service_Instance_Pools"
      }
  
  icon_service_Internet_Analyzer_Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Internet_Analyzer_Profiles.svg
        shape: image
        label: "icon_service_Internet_Analyzer_Profiles"
      }
  
  icon_service_Kubernetes_Fleet_Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Kubernetes_Fleet_Manager.svg
        shape: image
        label: "icon_service_Kubernetes_Fleet_Manager"
      }
  
  icon_service_Local_Network_Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Local_Network_Gateways.svg
        shape: image
        label: "icon_service_Local_Network_Gateways"
      }
  
  icon_service_Log_Analytics_Query_Pack: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Log_Analytics_Query_Pack.svg
        shape: image
        label: "icon_service_Log_Analytics_Query_Pack"
      }
  
  icon_service_Managed_Instance_Apache_Cassandra: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Managed_Instance_Apache_Cassandra.svg
        shape: image
        label: "icon_service_Managed_Instance_Apache_Cassandra"
      }
  
  icon_service_MedTech_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_MedTech_Service.svg
        shape: image
        label: "icon_service_MedTech_Service"
      }
  
  icon_service_Microsoft_Dev_Box: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Microsoft_Dev_Box.svg
        shape: image
        label: "icon_service_Microsoft_Dev_Box"
      }
  
  icon_service_Mission_Landing_Zone: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Mission_Landing_Zone.svg
        shape: image
        label: "icon_service_Mission_Landing_Zone"
      }
  
  icon_service_Mobile_Networks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Mobile_Networks.svg
        shape: image
        label: "icon_service_Mobile_Networks"
      }
  
  icon_service_Modular_Data_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Modular_Data_Center.svg
        shape: image
        label: "icon_service_Modular_Data_Center"
      }
  
  icon_service_Network_Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Network_Managers.svg
        shape: image
        label: "icon_service_Network_Managers"
      }
  
  icon_service_Network_Security_Perimeters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Network_Security_Perimeters.svg
        shape: image
        label: "icon_service_Network_Security_Perimeters"
      }
  
  icon_service_Open_Supply_Chain_Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Open_Supply_Chain_Platform.svg
        shape: image
        label: "icon_service_Open_Supply_Chain_Platform"
      }
  
  icon_service_Peerings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Peerings.svg
        shape: image
        label: "icon_service_Peerings"
      }
  
  icon_service_Peering_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Peering_Service.svg
        shape: image
        label: "icon_service_Peering_Service"
      }
  
  icon_service_Private_Endpoints: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Private_Endpoints.svg
        shape: image
        label: "icon_service_Private_Endpoints"
      }
  
  icon_service_Reserved_Capacity: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Reserved_Capacity.svg
        shape: image
        label: "icon_service_Reserved_Capacity"
      }
  
  icon_service_Resource_Guard: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Resource_Guard.svg
        shape: image
        label: "icon_service_Resource_Guard"
      }
  
  icon_service_Resource_Mover: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Resource_Mover.svg
        shape: image
        label: "icon_service_Resource_Mover"
      }
  
  icon_service_RTOS: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_RTOS.svg
        shape: image
        label: "icon_service_RTOS"
      }
  
  icon_service_Savings_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Savings_Plans.svg
        shape: image
        label: "icon_service_Savings_Plans"
      }
  
  icon_service_SCVMM_Management_Servers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_SCVMM_Management_Servers.svg
        shape: image
        label: "icon_service_SCVMM_Management_Servers"
      }
  
  icon_service_Sonic_Dash: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Sonic_Dash.svg
        shape: image
        label: "icon_service_Sonic_Dash"
      }
  
  icon_service_SSH_Keys: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_SSH_Keys.svg
        shape: image
        label: "icon_service_SSH_Keys"
      }
  
  icon_service_Storage_Tasks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Storage_Tasks.svg
        shape: image
        label: "icon_service_Storage_Tasks"
      }
  
  icon_service_Targets_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Targets_Management.svg
        shape: image
        label: "icon_service_Targets_Management"
      }
  
  icon_service_Template_Specs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Template_Specs.svg
        shape: image
        label: "icon_service_Template_Specs"
      }
  
  icon_service_Test_Base: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Test_Base.svg
        shape: image
        label: "icon_service_Test_Base"
      }
  
  icon_service_Update_Management_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Update_Management_Center.svg
        shape: image
        label: "icon_service_Update_Management_Center"
      }
  
  icon_service_Video_Analyzers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Video_Analyzers.svg
        shape: image
        label: "icon_service_Video_Analyzers"
      }
  
  icon_service_Virtual_Instance_for_SAP: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Virtual_Instance_for_SAP.svg
        shape: image
        label: "icon_service_Virtual_Instance_for_SAP"
      }
  
  icon_service_Virtual_Visits_Builder: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Virtual_Visits_Builder.svg
        shape: image
        label: "icon_service_Virtual_Visits_Builder"
      }
  
  icon_service_VM_App_Definitions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_VM_App_Definitions.svg
        shape: image
        label: "icon_service_VM_App_Definitions"
      }
  
  icon_service_VM_App_Versions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_VM_App_Versions.svg
        shape: image
        label: "icon_service_VM_App_Versions"
      }
  
  icon_service_VM_Image_Version: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_VM_Image_Version.svg
        shape: image
        label: "icon_service_VM_Image_Version"
      }
  
  icon_service_WAC: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_WAC.svg
        shape: image
        label: "icon_service_WAC"
      }
  
  icon_service_Web_App_+_Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Web_App_+_Database.svg
        shape: image
        label: "icon_service_Web_App_+_Database"
      }
  
  icon_service_Web_Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Web_Jobs.svg
        shape: image
        label: "icon_service_Web_Jobs"
      }
  
  icon_service_Windows_Notification_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Windows_Notification_Services.svg
        shape: image
        label: "icon_service_Windows_Notification_Services"
      }
  
  icon_service_Worker_Container_App: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/icon_service_Worker_Container_App.svg
        shape: image
        label: "icon_service_Worker_Container_App"
      }
  
}