classes: {
  
  
  Aad Licenses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/AAD_Licenses.svg
        shape: image
        label: "Aad Licenses"
      }
  
  
  App Compliance Automation: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/App_Compliance_Automation.svg
        shape: image
        label: "App Compliance Automation"
      }
  
  
  App Registrations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/App_Registrations.svg
        shape: image
        label: "App Registrations"
      }
  
  
  Aquila: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Aquila.svg
        shape: image
        label: "Aquila"
      }
  
  
  Arc Data Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Arc_Data_services.svg
        shape: image
        label: "Arc Data Services"
      }
  
  
  Arc Kubernetes: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Arc_Kubernetes.svg
        shape: image
        label: "Arc Kubernetes"
      }
  
  
  Arc Postgresql: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Arc_PostgreSQL.svg
        shape: image
        label: "Arc Postgresql"
      }
  
  
  Arc Sql Managed Instance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Arc_SQL_Managed_Instance.svg
        shape: image
        label: "Arc Sql Managed Instance"
      }
  
  
  Arc Sql Server: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Arc_SQL_Server.svg
        shape: image
        label: "Arc Sql Server"
      }
  
  
  Avs Vm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/AVS_VM.svg
        shape: image
        label: "Avs Vm"
      }
  
  
  Azureattestation: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/AzureAttestation.svg
        shape: image
        label: "Azureattestation"
      }
  
  
  Azure A: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_A.svg
        shape: image
        label: "Azure A"
      }
  
  
  Azure Backup Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Backup_Center.svg
        shape: image
        label: "Azure Backup Center"
      }
  
  
  Azure Center For Sap: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Center_for_SAP.svg
        shape: image
        label: "Azure Center For Sap"
      }
  
  
  Azure Chaos Studio: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Chaos_Studio.svg
        shape: image
        label: "Azure Chaos Studio"
      }
  
  
  Azure Cloud Shell: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Cloud_Shell.svg
        shape: image
        label: "Azure Cloud Shell"
      }
  
  
  Azure Communication Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Communication_Services.svg
        shape: image
        label: "Azure Communication Services"
      }
  
  
  Azure Compute Galleries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Compute_Galleries.svg
        shape: image
        label: "Azure Compute Galleries"
      }
  
  
  Azure Deployment Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Deployment_Environments.svg
        shape: image
        label: "Azure Deployment Environments"
      }
  
  
  Azure Edge Hardware Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Edge_Hardware_Center.svg
        shape: image
        label: "Azure Edge Hardware Center"
      }
  
  
  Azure Hpc Workbenches: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_HPC_Workbenches.svg
        shape: image
        label: "Azure Hpc Workbenches"
      }
  
  
  Azure Load Testing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Load_Testing.svg
        shape: image
        label: "Azure Load Testing"
      }
  
  
  Azure Managed Grafana: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Managed_Grafana.svg
        shape: image
        label: "Azure Managed Grafana"
      }
  
  
  Azure Monitor Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Monitor_Dashboard.svg
        shape: image
        label: "Azure Monitor Dashboard"
      }
  
  
  Azure Network Function Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Network_Function_Manager.svg
        shape: image
        label: "Azure Network Function Manager"
      }
  
  
  Azure Network Function Manager Functions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Network_Function_Manager_Functions.svg
        shape: image
        label: "Azure Network Function Manager Functions"
      }
  
  
  Azure Orbital: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Orbital.svg
        shape: image
        label: "Azure Orbital"
      }
  
  
  Azure Quotas: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Quotas.svg
        shape: image
        label: "Azure Quotas"
      }
  
  
  Azure Sphere: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Sphere.svg
        shape: image
        label: "Azure Sphere"
      }
  
  
  Azure Storage Mover: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Storage_Mover.svg
        shape: image
        label: "Azure Storage Mover"
      }
  
  
  Azure Support Center Blue: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Support_Center_Blue.svg
        shape: image
        label: "Azure Support Center Blue"
      }
  
  
  Azure Video Indexer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Video_Indexer.svg
        shape: image
        label: "Azure Video Indexer"
      }
  
  
  Azure Virtual Desktop: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_Virtual_Desktop.svg
        shape: image
        label: "Azure Virtual Desktop"
      }
  
  
  Azure Vmware Solution: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azure_VMware_Solution.svg
        shape: image
        label: "Azure Vmware Solution"
      }
  
  
  Azurite: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Azurite.svg
        shape: image
        label: "Azurite"
      }
  
  
  Backup Vault: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Backup_Vault.svg
        shape: image
        label: "Backup Vault"
      }
  
  
  Bare Metal Infrastructure: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Bare_Metal_Infrastructure.svg
        shape: image
        label: "Bare Metal Infrastructure"
      }
  
  
  Capacity Reservation Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Capacity_Reservation_Groups.svg
        shape: image
        label: "Capacity Reservation Groups"
      }
  
  
  Central Service Instance For Sap: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Central_Service_Instance_For_SAP.svg
        shape: image
        label: "Central Service Instance For Sap"
      }
  
  
  Ceres: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Ceres.svg
        shape: image
        label: "Ceres"
      }
  
  
  Cloud Services (extended Support): {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Cloud_Services_(extended_support).svg
        shape: image
        label: "Cloud Services (extended Support)"
      }
  
  
  Community Images: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Community_Images.svg
        shape: image
        label: "Community Images"
      }
  
  
  Compliance Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Compliance_Center.svg
        shape: image
        label: "Compliance Center"
      }
  
  
  Confidential Ledgers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Confidential_Ledgers.svg
        shape: image
        label: "Confidential Ledgers"
      }
  
  
  Container Apps Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Container_Apps_Environments.svg
        shape: image
        label: "Container Apps Environments"
      }
  
  
  Cost Export: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Cost_Export.svg
        shape: image
        label: "Cost Export"
      }
  
  
  Custom Ip Prefix: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Custom_IP_Prefix.svg
        shape: image
        label: "Custom Ip Prefix"
      }
  
  
  Dashboard Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Dashboard_Hub.svg
        shape: image
        label: "Dashboard Hub"
      }
  
  
  Database Instance For Sap: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Database_Instance_For_SAP.svg
        shape: image
        label: "Database Instance For Sap"
      }
  
  
  Data Collection Rules: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Data_Collection_Rules.svg
        shape: image
        label: "Data Collection Rules"
      }
  
  
  Dedicated Hsm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Dedicated_HSM.svg
        shape: image
        label: "Dedicated Hsm"
      }
  
  
  Defender Cm Local Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_CM_Local_Manager.svg
        shape: image
        label: "Defender Cm Local Manager"
      }
  
  
  Defender Dcs Controller: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_DCS_Controller.svg
        shape: image
        label: "Defender Dcs Controller"
      }
  
  
  Defender Distributer Control System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Distributer_Control_System.svg
        shape: image
        label: "Defender Distributer Control System"
      }
  
  
  Defender Engineering Station: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Engineering_Station.svg
        shape: image
        label: "Defender Engineering Station"
      }
  
  
  Defender External Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_External_Management.svg
        shape: image
        label: "Defender External Management"
      }
  
  
  Defender Freezer Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Freezer_Monitor.svg
        shape: image
        label: "Defender Freezer Monitor"
      }
  
  
  Defender Historian: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Historian.svg
        shape: image
        label: "Defender Historian"
      }
  
  
  Defender Hmi: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_HMI.svg
        shape: image
        label: "Defender Hmi"
      }
  
  
  Defender Industrial Packaging System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Industrial_Packaging_System.svg
        shape: image
        label: "Defender Industrial Packaging System"
      }
  
  
  Defender Industrial Printer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Industrial_Printer.svg
        shape: image
        label: "Defender Industrial Printer"
      }
  
  
  Defender Industrial Robot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Industrial_Robot.svg
        shape: image
        label: "Defender Industrial Robot"
      }
  
  
  Defender Industrial Scale System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Industrial_Scale_System.svg
        shape: image
        label: "Defender Industrial Scale System"
      }
  
  
  Defender Marquee: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Marquee.svg
        shape: image
        label: "Defender Marquee"
      }
  
  
  Defender Meter: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Meter.svg
        shape: image
        label: "Defender Meter"
      }
  
  
  Defender Plc: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_PLC.svg
        shape: image
        label: "Defender Plc"
      }
  
  
  Defender Pneumatic Device: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Pneumatic_Device.svg
        shape: image
        label: "Defender Pneumatic Device"
      }
  
  
  Defender Programable Board: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Programable_Board.svg
        shape: image
        label: "Defender Programable Board"
      }
  
  
  Defender Relay: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Relay.svg
        shape: image
        label: "Defender Relay"
      }
  
  
  Defender Robot Controller: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Robot_Controller.svg
        shape: image
        label: "Defender Robot Controller"
      }
  
  
  Defender Rtu: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_RTU.svg
        shape: image
        label: "Defender Rtu"
      }
  
  
  Defender Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Sensor.svg
        shape: image
        label: "Defender Sensor"
      }
  
  
  Defender Slot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Slot.svg
        shape: image
        label: "Defender Slot"
      }
  
  
  Defender Web Guiding System: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Defender_Web_Guiding_System.svg
        shape: image
        label: "Defender Web Guiding System"
      }
  
  
  Device Update Iot Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Device_Update_IoT_Hub.svg
        shape: image
        label: "Device Update Iot Hub"
      }
  
  
  Disk Pool: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Disk_Pool.svg
        shape: image
        label: "Disk Pool"
      }
  
  
  Edge Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Edge_Management.svg
        shape: image
        label: "Edge Management"
      }
  
  
  Elastic San: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Elastic_SAN.svg
        shape: image
        label: "Elastic San"
      }
  
  
  Exchange On Premises Access: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Exchange_On_Premises_Access.svg
        shape: image
        label: "Exchange On Premises Access"
      }
  
  
  Expressroute Direct: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/ExpressRoute_Direct.svg
        shape: image
        label: "Expressroute Direct"
      }
  
  
  Express Route Traffic Collector: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Express_Route_Traffic_Collector.svg
        shape: image
        label: "Express Route Traffic Collector"
      }
  
  
  Fhir Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/FHIR_Service.svg
        shape: image
        label: "Fhir Service"
      }
  
  
  Fiji: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Fiji.svg
        shape: image
        label: "Fiji"
      }
  
  
  Instance Pools: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Instance_Pools.svg
        shape: image
        label: "Instance Pools"
      }
  
  
  Internet Analyzer Profiles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Internet_Analyzer_Profiles.svg
        shape: image
        label: "Internet Analyzer Profiles"
      }
  
  
  Kubernetes Fleet Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Kubernetes_Fleet_Manager.svg
        shape: image
        label: "Kubernetes Fleet Manager"
      }
  
  
  Local Network Gateways: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Local_Network_Gateways.svg
        shape: image
        label: "Local Network Gateways"
      }
  
  
  Log Analytics Query Pack: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Log_Analytics_Query_Pack.svg
        shape: image
        label: "Log Analytics Query Pack"
      }
  
  
  Managed Instance Apache Cassandra: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Managed_Instance_Apache_Cassandra.svg
        shape: image
        label: "Managed Instance Apache Cassandra"
      }
  
  
  Medtech Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/MedTech_Service.svg
        shape: image
        label: "Medtech Service"
      }
  
  
  Microsoft Dev Box: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Microsoft_Dev_Box.svg
        shape: image
        label: "Microsoft Dev Box"
      }
  
  
  Mission Landing Zone: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Mission_Landing_Zone.svg
        shape: image
        label: "Mission Landing Zone"
      }
  
  
  Mobile Networks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Mobile_Networks.svg
        shape: image
        label: "Mobile Networks"
      }
  
  
  Modular Data Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Modular_Data_Center.svg
        shape: image
        label: "Modular Data Center"
      }
  
  
  Network Managers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Network_Managers.svg
        shape: image
        label: "Network Managers"
      }
  
  
  Network Security Perimeters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Network_Security_Perimeters.svg
        shape: image
        label: "Network Security Perimeters"
      }
  
  
  Open Supply Chain Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Open_Supply_Chain_Platform.svg
        shape: image
        label: "Open Supply Chain Platform"
      }
  
  
  Peerings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Peerings.svg
        shape: image
        label: "Peerings"
      }
  
  
  Peering Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Peering_Service.svg
        shape: image
        label: "Peering Service"
      }
  
  
  Private Endpoints: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Private_Endpoints.svg
        shape: image
        label: "Private Endpoints"
      }
  
  
  Reserved Capacity: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Reserved_Capacity.svg
        shape: image
        label: "Reserved Capacity"
      }
  
  
  Resource Guard: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Resource_Guard.svg
        shape: image
        label: "Resource Guard"
      }
  
  
  Resource Mover: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Resource_Mover.svg
        shape: image
        label: "Resource Mover"
      }
  
  
  Rtos: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/RTOS.svg
        shape: image
        label: "Rtos"
      }
  
  
  Savings Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Savings_Plans.svg
        shape: image
        label: "Savings Plans"
      }
  
  
  Scvmm Management Servers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/SCVMM_Management_Servers.svg
        shape: image
        label: "Scvmm Management Servers"
      }
  
  
  Sonic Dash: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Sonic_Dash.svg
        shape: image
        label: "Sonic Dash"
      }
  
  
  Ssh Keys: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/SSH_Keys.svg
        shape: image
        label: "Ssh Keys"
      }
  
  
  Storage Tasks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Storage_Tasks.svg
        shape: image
        label: "Storage Tasks"
      }
  
  
  Targets Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Targets_Management.svg
        shape: image
        label: "Targets Management"
      }
  
  
  Template Specs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Template_Specs.svg
        shape: image
        label: "Template Specs"
      }
  
  
  Test Base: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Test_Base.svg
        shape: image
        label: "Test Base"
      }
  
  
  Update Management Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Update_Management_Center.svg
        shape: image
        label: "Update Management Center"
      }
  
  
  Video Analyzers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Video_Analyzers.svg
        shape: image
        label: "Video Analyzers"
      }
  
  
  Virtual Instance For Sap: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Virtual_Instance_for_SAP.svg
        shape: image
        label: "Virtual Instance For Sap"
      }
  
  
  Virtual Visits Builder: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Virtual_Visits_Builder.svg
        shape: image
        label: "Virtual Visits Builder"
      }
  
  
  Vm App Definitions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/VM_App_Definitions.svg
        shape: image
        label: "Vm App Definitions"
      }
  
  
  Vm App Versions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/VM_App_Versions.svg
        shape: image
        label: "Vm App Versions"
      }
  
  
  Vm Image Version: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/VM_Image_Version.svg
        shape: image
        label: "Vm Image Version"
      }
  
  
  Wac: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/WAC.svg
        shape: image
        label: "Wac"
      }
  
  
  Web App + Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Web_App_+_Database.svg
        shape: image
        label: "Web App + Database"
      }
  
  
  Web Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Web_Jobs.svg
        shape: image
        label: "Web Jobs"
      }
  
  
  Windows Notification Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Windows_Notification_Services.svg
        shape: image
        label: "Windows Notification Services"
      }
  
  
  Worker Container App: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/other/Worker_Container_App.svg
        shape: image
        label: "Worker Container App"
      }
  
}