classes: {
  
  
  Amazon Aurora: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_Aurora.svg
        shape: image
        label: "Amazon Aurora"
      }
  
  
  Amazon Documentdb: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_DocumentDB.svg
        shape: image
        label: "Amazon Documentdb"
      }
  
  
  Amazon Dynamodb: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_DynamoDB.svg
        shape: image
        label: "Amazon Dynamodb"
      }
  
  
  Amazon Elasticache: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_ElastiCache.svg
        shape: image
        label: "Amazon Elasticache"
      }
  
  
  Amazon Keyspaces: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_Keyspaces.svg
        shape: image
        label: "Amazon Keyspaces"
      }
  
  
  Amazon Memorydb For Redis: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_MemoryDB_for_Redis.svg
        shape: image
        label: "Amazon Memorydb For Redis"
      }
  
  
  Amazon Neptune: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_Neptune.svg
        shape: image
        label: "Amazon Neptune"
      }
  
  
  Amazon Rds: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_RDS.svg
        shape: image
        label: "Amazon Rds"
      }
  
  
  Amazon Rds On Vmware: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_RDS_on_VMware.svg
        shape: image
        label: "Amazon Rds On Vmware"
      }
  
  
  Amazon Timestream: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/Amazon_Timestream.svg
        shape: image
        label: "Amazon Timestream"
      }
  
  
  Aws Database Migration Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Database/AWS_Database_Migration_Service.svg
        shape: image
        label: "Aws Database Migration Service"
      }
  
}