classes: {
  
  
  Aws Iot Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Analytics.svg
        shape: image
        label: "Aws Iot Analytics"
      }
  
  
  Aws Iot Button: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Button.svg
        shape: image
        label: "Aws Iot Button"
      }
  
  
  Aws Iot Core: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Core.svg
        shape: image
        label: "Aws Iot Core"
      }
  
  
  Aws Iot Device Defender: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Device_Defender.svg
        shape: image
        label: "Aws Iot Device Defender"
      }
  
  
  Aws Iot Device Management: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Device_Management.svg
        shape: image
        label: "Aws Iot Device Management"
      }
  
  
  Aws Iot Edukit: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_EduKit.svg
        shape: image
        label: "Aws Iot Edukit"
      }
  
  
  Aws Iot Events: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Events.svg
        shape: image
        label: "Aws Iot Events"
      }
  
  
  Aws Iot Expresslink: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_ExpressLink.svg
        shape: image
        label: "Aws Iot Expresslink"
      }
  
  
  Aws Iot Fleetwise: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_FleetWise.svg
        shape: image
        label: "Aws Iot Fleetwise"
      }
  
  
  Aws Iot Greengrass: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Greengrass.svg
        shape: image
        label: "Aws Iot Greengrass"
      }
  
  
  Aws Iot Roborunner: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_RoboRunner.svg
        shape: image
        label: "Aws Iot Roborunner"
      }
  
  
  Aws Iot Sitewise: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_SiteWise.svg
        shape: image
        label: "Aws Iot Sitewise"
      }
  
  
  Aws Iot Things Graph: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_Things_Graph.svg
        shape: image
        label: "Aws Iot Things Graph"
      }
  
  
  Aws Iot Twinmaker: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT_TwinMaker.svg
        shape: image
        label: "Aws Iot Twinmaker"
      }
  
  
  Aws Iot  Click: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/AWS_IoT__Click.svg
        shape: image
        label: "Aws Iot  Click"
      }
  
  
  Freertos: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Internet-of-Things/FreeRTOS.svg
        shape: image
        label: "Freertos"
      }
  
}