classes: {
  
  
  Dashboard  flow: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Dashboard  Flow.svg
        shape: image
        label: "Dashboard  flow"
      }
  
  
  Dashboard automated: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Dashboard Automated.svg
        shape: image
        label: "Dashboard automated"
      }
  
  
  Dashboard human: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Dashboard Human.svg
        shape: image
        label: "Dashboard human"
      }
  
  
  Flow: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Flow.svg
        shape: image
        label: "Flow"
      }
  
  
  Monitor 12: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor 12.svg
        shape: image
        label: "Monitor 12"
      }
  
  
  Monitor analysis edit: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Analysis Edit.svg
        shape: image
        label: "Monitor analysis edit"
      }
  
  
  Monitor analysis human: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Analysis Human.svg
        shape: image
        label: "Monitor analysis human"
      }
  
  
  Monitor analysis machine: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Analysis Machine.svg
        shape: image
        label: "Monitor analysis machine"
      }
  
  
  Monitor bug: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Bug.svg
        shape: image
        label: "Monitor bug"
      }
  
  
  Monitor cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Cloud.svg
        shape: image
        label: "Monitor cloud"
      }
  
  
  Monitor dashboard edit: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Dashboard Edit.svg
        shape: image
        label: "Monitor dashboard edit"
      }
  
  
  Monitor gear: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor Gear.svg
        shape: image
        label: "Monitor gear"
      }
  
  
  Monitor view: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Monitor View.svg
        shape: image
        label: "Monitor view"
      }
  
  
  Programming: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Programming.svg
        shape: image
        label: "Programming"
      }
  
  
  Tracking: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Tracking.svg
        shape: image
        label: "Tracking"
      }
  
  
  Web pages: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Web Pages.svg
        shape: image
        label: "Web pages"
      }
  
  
  Website: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Monitors/Website.svg
        shape: image
        label: "Website"
      }
  
}