classes: {
  
  
  Res Amazon Workspaces Family Amazon Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_End-User-Computing/Res_Amazon_WorkSpaces_Family_Amazon_WorkSpaces.svg
        shape: image
        label: "Res Amazon Workspaces Family Amazon Workspaces"
      }
  
  
  Res Amazon Workspaces Family Amazon Workspaces Core: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_End-User-Computing/Res_Amazon_WorkSpaces_Family_Amazon_WorkSpaces_Core.svg
        shape: image
        label: "Res Amazon Workspaces Family Amazon Workspaces Core"
      }
  
  
  Res Amazon Workspaces Family Amazon Workspaces Web: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_End-User-Computing/Res_Amazon_WorkSpaces_Family_Amazon_WorkSpaces_Web.svg
        shape: image
        label: "Res Amazon Workspaces Family Amazon Workspaces Web"
      }
  
}