classes: {
  
  
  Res Amazon Inspector Agent: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_Amazon_Inspector_Agent.svg
        shape: image
        label: "Res Amazon Inspector Agent"
      }
  
  
  Res Aws Certificate Manager Certificate Authority: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Certificate_Manager_Certificate_Authority.svg
        shape: image
        label: "Res Aws Certificate Manager Certificate Authority"
      }
  
  
  Res Aws Directory Service Ad Connector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Directory_Service_AD_Connector.svg
        shape: image
        label: "Res Aws Directory Service Ad Connector"
      }
  
  
  Res Aws Directory Service Aws Managed Microsoft Ad: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Directory_Service_AWS_Managed_Microsoft_AD.svg
        shape: image
        label: "Res Aws Directory Service Aws Managed Microsoft Ad"
      }
  
  
  Res Aws Directory Service Simple Ad: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Directory_Service_Simple_AD.svg
        shape: image
        label: "Res Aws Directory Service Simple Ad"
      }
  
  
  Res Aws Identity Access Management Add On: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Add_on.svg
        shape: image
        label: "Res Aws Identity Access Management Add On"
      }
  
  
  Res Aws Identity Access Management Aws Sts: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_AWS_STS.svg
        shape: image
        label: "Res Aws Identity Access Management Aws Sts"
      }
  
  
  Res Aws Identity Access Management Aws Sts Alternate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_AWS_STS_Alternate.svg
        shape: image
        label: "Res Aws Identity Access Management Aws Sts Alternate"
      }
  
  
  Res Aws Identity Access Management Data Encryption Key: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Data_Encryption_Key.svg
        shape: image
        label: "Res Aws Identity Access Management Data Encryption Key"
      }
  
  
  Res Aws Identity Access Management Encrypted Data: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Encrypted_Data.svg
        shape: image
        label: "Res Aws Identity Access Management Encrypted Data"
      }
  
  
  Res Aws Identity Access Management Iam Access Analyzer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_IAM_Access_Analyzer.svg
        shape: image
        label: "Res Aws Identity Access Management Iam Access Analyzer"
      }
  
  
  Res Aws Identity Access Management Iam Roles Anywhere: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_IAM_Roles_Anywhere.svg
        shape: image
        label: "Res Aws Identity Access Management Iam Roles Anywhere"
      }
  
  
  Res Aws Identity Access Management Long Term Security Credential: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Long_Term_Security_Credential.svg
        shape: image
        label: "Res Aws Identity Access Management Long Term Security Credential"
      }
  
  
  Res Aws Identity Access Management Mfa Token: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_MFA_Token.svg
        shape: image
        label: "Res Aws Identity Access Management Mfa Token"
      }
  
  
  Res Aws Identity Access Management Permissions: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Permissions.svg
        shape: image
        label: "Res Aws Identity Access Management Permissions"
      }
  
  
  Res Aws Identity Access Management Role: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Role.svg
        shape: image
        label: "Res Aws Identity Access Management Role"
      }
  
  
  Res Aws Identity Access Management Temporary Security Credential: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Identity_Access_Management_Temporary_Security_Credential.svg
        shape: image
        label: "Res Aws Identity Access Management Temporary Security Credential"
      }
  
  
  Res Aws Key Management Service External Key Store: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Key_Management_Service_External_Key_Store.svg
        shape: image
        label: "Res Aws Key Management Service External Key Store"
      }
  
  
  Res Aws Network Firewall Endpoints: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Network_Firewall_Endpoints.svg
        shape: image
        label: "Res Aws Network Firewall Endpoints"
      }
  
  
  Res Aws Security Hub Finding: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Security_Hub_Finding.svg
        shape: image
        label: "Res Aws Security Hub Finding"
      }
  
  
  Res Aws Shield Aws Shield Advanced: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_Shield_AWS_Shield_Advanced.svg
        shape: image
        label: "Res Aws Shield Aws Shield Advanced"
      }
  
  
  Res Aws Waf Bad Bot: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Bad_Bot.svg
        shape: image
        label: "Res Aws Waf Bad Bot"
      }
  
  
  Res Aws Waf Bot: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Bot.svg
        shape: image
        label: "Res Aws Waf Bot"
      }
  
  
  Res Aws Waf Bot Control: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Bot_Control.svg
        shape: image
        label: "Res Aws Waf Bot Control"
      }
  
  
  Res Aws Waf Filtering Rule: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Filtering_Rule.svg
        shape: image
        label: "Res Aws Waf Filtering Rule"
      }
  
  
  Res Aws Waf Labels: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Labels.svg
        shape: image
        label: "Res Aws Waf Labels"
      }
  
  
  Res Aws Waf Managed Rule: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Managed_Rule.svg
        shape: image
        label: "Res Aws Waf Managed Rule"
      }
  
  
  Res Aws Waf Rule: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Security-Identity-Compliance/Res_AWS_WAF_Rule.svg
        shape: image
        label: "Res Aws Waf Rule"
      }
  
}