classes: {
  
  Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Apps.svg
        shape: image
        label: "Apps"
      }
  
  Azure SQL: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Azure SQL.svg
        shape: image
        label: "Azure SQL"
      }
  
  Azure Synapse Link: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Azure Synapse Link.svg
        shape: image
        label: "Azure Synapse Link"
      }
  
  Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dashboard.svg
        shape: image
        label: "Dashboard"
      }
  
  Data Warehouse (legacy): {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Data Warehouse (legacy).svg
        shape: image
        label: "Data Warehouse (legacy)"
      }
  
  Data Warehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Data Warehouse.svg
        shape: image
        label: "Data Warehouse"
      }
  
  Dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dataflow.svg
        shape: image
        label: "Dataflow"
      }
  
  Datamart: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Datamart.svg
        shape: image
        label: "Datamart"
      }
  
  Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dataset.svg
        shape: image
        label: "Dataset"
      }
  
  Dataverse: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dataverse.svg
        shape: image
        label: "Dataverse"
      }
  
  Experiments: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Experiments.svg
        shape: image
        label: "Experiments"
      }
  
  External Dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/External Dataflow.svg
        shape: image
        label: "External Dataflow"
      }
  
  External Datamart: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/External Datamart.svg
        shape: image
        label: "External Datamart"
      }
  
  External Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/External Dataset.svg
        shape: image
        label: "External Dataset"
      }
  
  KQL Database: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/KQL Database.svg
        shape: image
        label: "KQL Database"
      }
  
  KQL Queryset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/KQL Queryset.svg
        shape: image
        label: "KQL Queryset"
      }
  
  Lakehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Lakehouse.svg
        shape: image
        label: "Lakehouse"
      }
  
  Links: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Links.svg
        shape: image
        label: "Links"
      }
  
  Models: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Models.svg
        shape: image
        label: "Models"
      }
  
  No Access Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/No Access Dataset.svg
        shape: image
        label: "No Access Dataset"
      }
  
  Notebook: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Notebook.svg
        shape: image
        label: "Notebook"
      }
  
  Paginated Reports: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Paginated Reports.svg
        shape: image
        label: "Paginated Reports"
      }
  
  Pipelines: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Pipelines.svg
        shape: image
        label: "Pipelines"
      }
  
  Purview: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Purview.svg
        shape: image
        label: "Purview"
      }
  
  Real_time Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Real_time Dashboard.svg
        shape: image
        label: "Real_time Dashboard"
      }
  
  Report: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Report.svg
        shape: image
        label: "Report"
      }
  
  Scorecard: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Scorecard.svg
        shape: image
        label: "Scorecard"
      }
  
  Shared Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Shared Dataset.svg
        shape: image
        label: "Shared Dataset"
      }
  
  Spark Job: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Spark Job.svg
        shape: image
        label: "Spark Job"
      }
  
  Streaming Dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Streaming Dataflow.svg
        shape: image
        label: "Streaming Dataflow"
      }
  
  Streaming Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Streaming Dataset.svg
        shape: image
        label: "Streaming Dataset"
      }
  
  Workbook: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Workbook.svg
        shape: image
        label: "Workbook"
      }
  
  Workspace: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Workspace.svg
        shape: image
        label: "Workspace"
      }
  
}