classes: {
  
  
  Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Apps.svg
        shape: image
        label: "Apps"
      }
  
  
  Azure sql: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Azure SQL.svg
        shape: image
        label: "Azure sql"
      }
  
  
  Azure synapse link: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Azure Synapse Link.svg
        shape: image
        label: "Azure synapse link"
      }
  
  
  Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dashboard.svg
        shape: image
        label: "Dashboard"
      }
  
  
  Data warehouse (legacy): {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Data Warehouse (legacy).svg
        shape: image
        label: "Data warehouse (legacy)"
      }
  
  
  Data warehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Data Warehouse.svg
        shape: image
        label: "Data warehouse"
      }
  
  
  Dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dataflow.svg
        shape: image
        label: "Dataflow"
      }
  
  
  Datamart: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Datamart.svg
        shape: image
        label: "Datamart"
      }
  
  
  Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dataset.svg
        shape: image
        label: "Dataset"
      }
  
  
  Dataverse: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Dataverse.svg
        shape: image
        label: "Dataverse"
      }
  
  
  Experiments: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Experiments.svg
        shape: image
        label: "Experiments"
      }
  
  
  External dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/External Dataflow.svg
        shape: image
        label: "External dataflow"
      }
  
  
  External datamart: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/External Datamart.svg
        shape: image
        label: "External datamart"
      }
  
  
  External dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/External Dataset.svg
        shape: image
        label: "External dataset"
      }
  
  
  Kql database: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/KQL Database.svg
        shape: image
        label: "Kql database"
      }
  
  
  Kql queryset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/KQL Queryset.svg
        shape: image
        label: "Kql queryset"
      }
  
  
  Lakehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Lakehouse.svg
        shape: image
        label: "Lakehouse"
      }
  
  
  Links: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Links.svg
        shape: image
        label: "Links"
      }
  
  
  Models: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Models.svg
        shape: image
        label: "Models"
      }
  
  
  No access dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/No Access Dataset.svg
        shape: image
        label: "No access dataset"
      }
  
  
  Notebook: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Notebook.svg
        shape: image
        label: "Notebook"
      }
  
  
  Paginated reports: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Paginated Reports.svg
        shape: image
        label: "Paginated reports"
      }
  
  
  Pipelines: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Pipelines.svg
        shape: image
        label: "Pipelines"
      }
  
  
  Purview: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Purview.svg
        shape: image
        label: "Purview"
      }
  
  
  Real Time dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Real_time Dashboard.svg
        shape: image
        label: "Real Time dashboard"
      }
  
  
  Report: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Report.svg
        shape: image
        label: "Report"
      }
  
  
  Scorecard: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Scorecard.svg
        shape: image
        label: "Scorecard"
      }
  
  
  Shared dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Shared Dataset.svg
        shape: image
        label: "Shared dataset"
      }
  
  
  Spark job: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Spark Job.svg
        shape: image
        label: "Spark job"
      }
  
  
  Streaming dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Streaming Dataflow.svg
        shape: image
        label: "Streaming dataflow"
      }
  
  
  Streaming dataset: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Streaming Dataset.svg
        shape: image
        label: "Streaming dataset"
      }
  
  
  Workbook: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Workbook.svg
        shape: image
        label: "Workbook"
      }
  
  
  Workspace: {
        icon: https://ppalka-lingaro.github.io/icons/Microsoft Fabric/Items/Workspace.svg
        shape: image
        label: "Workspace"
      }
  
}