classes: {
  
  
  Box: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Box.svg
        shape: image
        label: "Box"
      }
  
  
  Package: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Package.svg
        shape: image
        label: "Package"
      }
  
  
  Plane 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Plane 2.svg
        shape: image
        label: "Plane 2"
      }
  
  
  Plane: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Plane.svg
        shape: image
        label: "Plane"
      }
  
  
  Ship: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Ship.svg
        shape: image
        label: "Ship"
      }
  
  
  Transport: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Transport.svg
        shape: image
        label: "Transport"
      }
  
  
  Warehouse cart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Warehouse Cart.svg
        shape: image
        label: "Warehouse cart"
      }
  
  
  Warehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Logistic/Warehouse.svg
        shape: image
        label: "Warehouse"
      }
  
}