classes: {
  
  
  Res Amazon Athena Data Source Connectors: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Athena_Data_Source_Connectors.svg
        shape: image
        label: "Res Amazon Athena Data Source Connectors"
      }
  
  
  Res Amazon Cloudsearch Search Documents: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_CloudSearch_Search_Documents.svg
        shape: image
        label: "Res Amazon Cloudsearch Search Documents"
      }
  
  
  Res Amazon Datazone Business Data Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_DataZone_Business_Data_Catalog.svg
        shape: image
        label: "Res Amazon Datazone Business Data Catalog"
      }
  
  
  Res Amazon Datazone Data Portal: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_DataZone_Data_Portal.svg
        shape: image
        label: "Res Amazon Datazone Data Portal"
      }
  
  
  Res Amazon Datazone Data Projects: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_DataZone_Data_Projects.svg
        shape: image
        label: "Res Amazon Datazone Data Projects"
      }
  
  
  Res Amazon Emr Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_EMR_Cluster.svg
        shape: image
        label: "Res Amazon Emr Cluster"
      }
  
  
  Res Amazon Emr Emr Engine: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_EMR_EMR_Engine.svg
        shape: image
        label: "Res Amazon Emr Emr Engine"
      }
  
  
  Res Amazon Emr Hdfs Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_EMR_HDFS_Cluster.svg
        shape: image
        label: "Res Amazon Emr Hdfs Cluster"
      }
  
  
  Res Amazon Msk Amazon Msk Connect: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_MSK_Amazon_MSK_Connect.svg
        shape: image
        label: "Res Amazon Msk Amazon Msk Connect"
      }
  
  
  Res Amazon Opensearch Service Cluster Administrator Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_Cluster_Administrator_Node.svg
        shape: image
        label: "Res Amazon Opensearch Service Cluster Administrator Node"
      }
  
  
  Res Amazon Opensearch Service Data Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_Data_Node.svg
        shape: image
        label: "Res Amazon Opensearch Service Data Node"
      }
  
  
  Res Amazon Opensearch Service Index: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_Index.svg
        shape: image
        label: "Res Amazon Opensearch Service Index"
      }
  
  
  Res Amazon Opensearch Service Observability: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_Observability.svg
        shape: image
        label: "Res Amazon Opensearch Service Observability"
      }
  
  
  Res Amazon Opensearch Service Opensearch Dashboards: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_OpenSearch_Dashboards.svg
        shape: image
        label: "Res Amazon Opensearch Service Opensearch Dashboards"
      }
  
  
  Res Amazon Opensearch Service Traces: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_Traces.svg
        shape: image
        label: "Res Amazon Opensearch Service Traces"
      }
  
  
  Res Amazon Opensearch Service Ultrawarm Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_OpenSearch_Service_UltraWarm_Node.svg
        shape: image
        label: "Res Amazon Opensearch Service Ultrawarm Node"
      }
  
  
  Res Amazon Quicksight Paginated Reports: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Quicksight_Paginated_Reports.svg
        shape: image
        label: "Res Amazon Quicksight Paginated Reports"
      }
  
  
  Res Amazon Redshift Auto Copy: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_Auto_copy.svg
        shape: image
        label: "Res Amazon Redshift Auto Copy"
      }
  
  
  Res Amazon Redshift Data Sharing Governance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_Data_Sharing_Governance.svg
        shape: image
        label: "Res Amazon Redshift Data Sharing Governance"
      }
  
  
  Res Amazon Redshift Dense Compute Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_Dense_Compute_Node.svg
        shape: image
        label: "Res Amazon Redshift Dense Compute Node"
      }
  
  
  Res Amazon Redshift Dense Storage Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_Dense_Storage_Node.svg
        shape: image
        label: "Res Amazon Redshift Dense Storage Node"
      }
  
  
  Res Amazon Redshift Ml: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_ML.svg
        shape: image
        label: "Res Amazon Redshift Ml"
      }
  
  
  Res Amazon Redshift Query Editor V.: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_Query_Editor_v..svg
        shape: image
        label: "Res Amazon Redshift Query Editor V."
      }
  
  
  Res Amazon Redshift Ra: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_RA.svg
        shape: image
        label: "Res Amazon Redshift Ra"
      }
  
  
  Res Amazon Redshift Streaming Ingestion: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_Amazon_Redshift_Streaming_Ingestion.svg
        shape: image
        label: "Res Amazon Redshift Streaming Ingestion"
      }
  
  
  Res Aws Data Exchange For Apis: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_AWS_Data_Exchange_for_APIs.svg
        shape: image
        label: "Res Aws Data Exchange For Apis"
      }
  
  
  Res Aws Glue Aws Glue For Ray: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_AWS_Glue_AWS_Glue_for_Ray.svg
        shape: image
        label: "Res Aws Glue Aws Glue For Ray"
      }
  
  
  Res Aws Glue Crawler: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_AWS_Glue_Crawler.svg
        shape: image
        label: "Res Aws Glue Crawler"
      }
  
  
  Res Aws Glue Data Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_AWS_Glue_Data_Catalog.svg
        shape: image
        label: "Res Aws Glue Data Catalog"
      }
  
  
  Res Aws Glue Data Quality: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_AWS_Glue_Data_Quality.svg
        shape: image
        label: "Res Aws Glue Data Quality"
      }
  
  
  Res Aws Lake Formation Data Lake: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Analytics/Res_AWS_Lake_Formation_Data_Lake.svg
        shape: image
        label: "Res Aws Lake Formation Data Lake"
      }
  
}