classes: {
  
  
  Aws Application Cost Profiler: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/AWS_Application_Cost_Profiler.svg
        shape: image
        label: "Aws Application Cost Profiler"
      }
  
  
  Aws Billing Conductor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/AWS_Billing_Conductor.svg
        shape: image
        label: "Aws Billing Conductor"
      }
  
  
  Aws Budgets: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/AWS_Budgets.svg
        shape: image
        label: "Aws Budgets"
      }
  
  
  Aws Cost And Usage Report: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/AWS_Cost_and_Usage_Report.svg
        shape: image
        label: "Aws Cost And Usage Report"
      }
  
  
  Aws Cost Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/AWS_Cost_Explorer.svg
        shape: image
        label: "Aws Cost Explorer"
      }
  
  
  Reserved Instance Reporting: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/Reserved_Instance_Reporting.svg
        shape: image
        label: "Reserved Instance Reporting"
      }
  
  
  Savings Plans: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Cloud-Financial-Management/Savings_Plans.svg
        shape: image
        label: "Savings Plans"
      }
  
}