classes: {
  
  
  Anomaly Detector: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Anomaly_Detector.svg
        shape: image
        label: "Anomaly Detector"
      }
  
  
  Azure Applied Ai Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Azure_Applied_AI_Services.svg
        shape: image
        label: "Azure Applied Ai Services"
      }
  
  
  Azure Experimentation Studio: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Azure_Experimentation_Studio.svg
        shape: image
        label: "Azure Experimentation Studio"
      }
  
  
  Azure Object Understanding: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Azure_Object_Understanding.svg
        shape: image
        label: "Azure Object Understanding"
      }
  
  
  Batch Ai: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Batch_AI.svg
        shape: image
        label: "Batch Ai"
      }
  
  
  Bonsai: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Bonsai.svg
        shape: image
        label: "Bonsai"
      }
  
  
  Bot Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Bot_Services.svg
        shape: image
        label: "Bot Services"
      }
  
  
  Cognitive Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Cognitive_Search.svg
        shape: image
        label: "Cognitive Search"
      }
  
  
  Cognitive Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Cognitive_Services.svg
        shape: image
        label: "Cognitive Services"
      }
  
  
  Computer Vision: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Computer_Vision.svg
        shape: image
        label: "Computer Vision"
      }
  
  
  Content Moderators: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Content_Moderators.svg
        shape: image
        label: "Content Moderators"
      }
  
  
  Custom Vision: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Custom_Vision.svg
        shape: image
        label: "Custom Vision"
      }
  
  
  Face Apis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Face_APIs.svg
        shape: image
        label: "Face Apis"
      }
  
  
  Form Recognizers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Form_Recognizers.svg
        shape: image
        label: "Form Recognizers"
      }
  
  
  Genomics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Genomics.svg
        shape: image
        label: "Genomics"
      }
  
  
  Genomics Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Genomics_Accounts.svg
        shape: image
        label: "Genomics Accounts"
      }
  
  
  Immersive Readers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Immersive_Readers.svg
        shape: image
        label: "Immersive Readers"
      }
  
  
  Language: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Language.svg
        shape: image
        label: "Language"
      }
  
  
  Language Understanding: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Language_Understanding.svg
        shape: image
        label: "Language Understanding"
      }
  
  
  Machine Learning: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Machine_Learning.svg
        shape: image
        label: "Machine Learning"
      }
  
  
  Machine Learning Studio (classic) Web Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Machine_Learning_Studio_(Classic)_Web_Services.svg
        shape: image
        label: "Machine Learning Studio (classic) Web Services"
      }
  
  
  Machine Learning Studio Web Service Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Machine_Learning_Studio_Web_Service_Plans.svg
        shape: image
        label: "Machine Learning Studio Web Service Plans"
      }
  
  
  Machine Learning Studio Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Machine_Learning_Studio_Workspaces.svg
        shape: image
        label: "Machine Learning Studio Workspaces"
      }
  
  
  Metrics Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Metrics_Advisor.svg
        shape: image
        label: "Metrics Advisor"
      }
  
  
  Personalizers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Personalizers.svg
        shape: image
        label: "Personalizers"
      }
  
  
  Qna Makers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/QnA_Makers.svg
        shape: image
        label: "Qna Makers"
      }
  
  
  Speech Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Speech_Services.svg
        shape: image
        label: "Speech Services"
      }
  
  
  Translator Text: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/Translator_Text.svg
        shape: image
        label: "Translator Text"
      }
  
}