classes: {
  
  icon_service_Anomaly_Detector: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Anomaly_Detector.svg
        shape: image
        label: "icon_service_Anomaly_Detector"
      }
  
  icon_service_Azure_Applied_AI_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Azure_Applied_AI_Services.svg
        shape: image
        label: "icon_service_Azure_Applied_AI_Services"
      }
  
  icon_service_Azure_Experimentation_Studio: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Azure_Experimentation_Studio.svg
        shape: image
        label: "icon_service_Azure_Experimentation_Studio"
      }
  
  icon_service_Azure_Object_Understanding: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Azure_Object_Understanding.svg
        shape: image
        label: "icon_service_Azure_Object_Understanding"
      }
  
  icon_service_Batch_AI: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Batch_AI.svg
        shape: image
        label: "icon_service_Batch_AI"
      }
  
  icon_service_Bonsai: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Bonsai.svg
        shape: image
        label: "icon_service_Bonsai"
      }
  
  icon_service_Bot_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Bot_Services.svg
        shape: image
        label: "icon_service_Bot_Services"
      }
  
  icon_service_Cognitive_Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Cognitive_Search.svg
        shape: image
        label: "icon_service_Cognitive_Search"
      }
  
  icon_service_Cognitive_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Cognitive_Services.svg
        shape: image
        label: "icon_service_Cognitive_Services"
      }
  
  icon_service_Computer_Vision: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Computer_Vision.svg
        shape: image
        label: "icon_service_Computer_Vision"
      }
  
  icon_service_Content_Moderators: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Content_Moderators.svg
        shape: image
        label: "icon_service_Content_Moderators"
      }
  
  icon_service_Custom_Vision: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Custom_Vision.svg
        shape: image
        label: "icon_service_Custom_Vision"
      }
  
  icon_service_Face_APIs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Face_APIs.svg
        shape: image
        label: "icon_service_Face_APIs"
      }
  
  icon_service_Form_Recognizers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Form_Recognizers.svg
        shape: image
        label: "icon_service_Form_Recognizers"
      }
  
  icon_service_Genomics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Genomics.svg
        shape: image
        label: "icon_service_Genomics"
      }
  
  icon_service_Genomics_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Genomics_Accounts.svg
        shape: image
        label: "icon_service_Genomics_Accounts"
      }
  
  icon_service_Immersive_Readers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Immersive_Readers.svg
        shape: image
        label: "icon_service_Immersive_Readers"
      }
  
  icon_service_Language: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Language.svg
        shape: image
        label: "icon_service_Language"
      }
  
  icon_service_Language_Understanding: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Language_Understanding.svg
        shape: image
        label: "icon_service_Language_Understanding"
      }
  
  icon_service_Machine_Learning: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Machine_Learning.svg
        shape: image
        label: "icon_service_Machine_Learning"
      }
  
  icon_service_Machine_Learning_Studio_(Classic)_Web_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Machine_Learning_Studio_(Classic)_Web_Services.svg
        shape: image
        label: "icon_service_Machine_Learning_Studio_(Classic)_Web_Services"
      }
  
  icon_service_Machine_Learning_Studio_Web_Service_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Machine_Learning_Studio_Web_Service_Plans.svg
        shape: image
        label: "icon_service_Machine_Learning_Studio_Web_Service_Plans"
      }
  
  icon_service_Machine_Learning_Studio_Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Machine_Learning_Studio_Workspaces.svg
        shape: image
        label: "icon_service_Machine_Learning_Studio_Workspaces"
      }
  
  icon_service_Metrics_Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Metrics_Advisor.svg
        shape: image
        label: "icon_service_Metrics_Advisor"
      }
  
  icon_service_Personalizers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Personalizers.svg
        shape: image
        label: "icon_service_Personalizers"
      }
  
  icon_service_QnA_Makers: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_QnA_Makers.svg
        shape: image
        label: "icon_service_QnA_Makers"
      }
  
  icon_service_Speech_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Speech_Services.svg
        shape: image
        label: "icon_service_Speech_Services"
      }
  
  icon_service_Translator_Text: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/ai + machine learning/icon_service_Translator_Text.svg
        shape: image
        label: "icon_service_Translator_Text"
      }
  
}