classes: {
  
  Category_Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Analytics.svg
        shape: image
        label: "Category_Analytics"
      }
  
  Category_Application_Integration: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Application_Integration.svg
        shape: image
        label: "Category_Application_Integration"
      }
  
  Category_Blockchain: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Blockchain.svg
        shape: image
        label: "Category_Blockchain"
      }
  
  Category_Business_Applications: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Business_Applications.svg
        shape: image
        label: "Category_Business_Applications"
      }
  
  Category_Cloud_Financial_Management: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Cloud_Financial_Management.svg
        shape: image
        label: "Category_Cloud_Financial_Management"
      }
  
  Category_Compute: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Compute.svg
        shape: image
        label: "Category_Compute"
      }
  
  Category_Contact_Center: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Contact_Center.svg
        shape: image
        label: "Category_Contact_Center"
      }
  
  Category_Containers: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Containers.svg
        shape: image
        label: "Category_Containers"
      }
  
  Category_Customer_Enablement: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Customer_Enablement.svg
        shape: image
        label: "Category_Customer_Enablement"
      }
  
  Category_Database: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Database.svg
        shape: image
        label: "Category_Database"
      }
  
  Category_Developer_Tools: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Developer_Tools.svg
        shape: image
        label: "Category_Developer_Tools"
      }
  
  Category_End_User_Computing: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_End_User_Computing.svg
        shape: image
        label: "Category_End_User_Computing"
      }
  
  Category_Front_End_Web_Mobile: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Front_End_Web_Mobile.svg
        shape: image
        label: "Category_Front_End_Web_Mobile"
      }
  
  Category_Games: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Games.svg
        shape: image
        label: "Category_Games"
      }
  
  Category_Internet_of_Things: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Internet_of_Things.svg
        shape: image
        label: "Category_Internet_of_Things"
      }
  
  Category_Machine_Learning: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Machine_Learning.svg
        shape: image
        label: "Category_Machine_Learning"
      }
  
  Category_Management_Governance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Management_Governance.svg
        shape: image
        label: "Category_Management_Governance"
      }
  
  Category_Media_Services: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Media_Services.svg
        shape: image
        label: "Category_Media_Services"
      }
  
  Category_Migration_Transfer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Migration_Transfer.svg
        shape: image
        label: "Category_Migration_Transfer"
      }
  
  Category_Networking_Content_Delivery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Networking_Content_Delivery.svg
        shape: image
        label: "Category_Networking_Content_Delivery"
      }
  
  Category_Quantum_Technologies: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Quantum_Technologies.svg
        shape: image
        label: "Category_Quantum_Technologies"
      }
  
  Category_Robotics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Robotics.svg
        shape: image
        label: "Category_Robotics"
      }
  
  Category_Satellite: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Satellite.svg
        shape: image
        label: "Category_Satellite"
      }
  
  Category_Security_Identity_Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Security_Identity_Compliance.svg
        shape: image
        label: "Category_Security_Identity_Compliance"
      }
  
  Category_Serverless: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Serverless.svg
        shape: image
        label: "Category_Serverless"
      }
  
  Category_Storage: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Storage.svg
        shape: image
        label: "Category_Storage"
      }
  
}