classes: {
  
  
  Category Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Analytics.svg
        shape: image
        label: "Category Analytics"
      }
  
  
  Category Application Integration: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Application_Integration.svg
        shape: image
        label: "Category Application Integration"
      }
  
  
  Category Blockchain: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Blockchain.svg
        shape: image
        label: "Category Blockchain"
      }
  
  
  Category Business Applications: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Business_Applications.svg
        shape: image
        label: "Category Business Applications"
      }
  
  
  Category Cloud Financial Management: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Cloud_Financial_Management.svg
        shape: image
        label: "Category Cloud Financial Management"
      }
  
  
  Category Compute: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Compute.svg
        shape: image
        label: "Category Compute"
      }
  
  
  Category Contact Center: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Contact_Center.svg
        shape: image
        label: "Category Contact Center"
      }
  
  
  Category Containers: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Containers.svg
        shape: image
        label: "Category Containers"
      }
  
  
  Category Customer Enablement: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Customer_Enablement.svg
        shape: image
        label: "Category Customer Enablement"
      }
  
  
  Category Database: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Database.svg
        shape: image
        label: "Category Database"
      }
  
  
  Category Developer Tools: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Developer_Tools.svg
        shape: image
        label: "Category Developer Tools"
      }
  
  
  Category End User Computing: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_End_User_Computing.svg
        shape: image
        label: "Category End User Computing"
      }
  
  
  Category Front End Web Mobile: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Front_End_Web_Mobile.svg
        shape: image
        label: "Category Front End Web Mobile"
      }
  
  
  Category Games: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Games.svg
        shape: image
        label: "Category Games"
      }
  
  
  Category Internet of Things: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Internet_of_Things.svg
        shape: image
        label: "Category Internet of Things"
      }
  
  
  Category Machine Learning: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Machine_Learning.svg
        shape: image
        label: "Category Machine Learning"
      }
  
  
  Category Management Governance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Management_Governance.svg
        shape: image
        label: "Category Management Governance"
      }
  
  
  Category Media Services: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Media_Services.svg
        shape: image
        label: "Category Media Services"
      }
  
  
  Category Migration Transfer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Migration_Transfer.svg
        shape: image
        label: "Category Migration Transfer"
      }
  
  
  Category Networking Content Delivery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Networking_Content_Delivery.svg
        shape: image
        label: "Category Networking Content Delivery"
      }
  
  
  Category Quantum Technologies: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Quantum_Technologies.svg
        shape: image
        label: "Category Quantum Technologies"
      }
  
  
  Category Robotics: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Robotics.svg
        shape: image
        label: "Category Robotics"
      }
  
  
  Category Satellite: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Satellite.svg
        shape: image
        label: "Category Satellite"
      }
  
  
  Category Security Identity Compliance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Security_Identity_Compliance.svg
        shape: image
        label: "Category Security Identity Compliance"
      }
  
  
  Category Serverless: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Serverless.svg
        shape: image
        label: "Category Serverless"
      }
  
  
  Category Storage: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Category-Icons/Arch-Category/Category_Storage.svg
        shape: image
        label: "Category Storage"
      }
  
}