classes: {
  
  
  Application Security Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Application_Security_Groups.svg
        shape: image
        label: "Application Security Groups"
      }
  
  
  Azure Ad Authentication Methods: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_AD_Authentication_Methods.svg
        shape: image
        label: "Azure Ad Authentication Methods"
      }
  
  
  Azure Ad Identity Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_AD_Identity_Protection.svg
        shape: image
        label: "Azure Ad Identity Protection"
      }
  
  
  Azure Ad Privleged Identity Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_AD_Privleged_Identity_Management.svg
        shape: image
        label: "Azure Ad Privleged Identity Management"
      }
  
  
  Azure Ad Risky Signins: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_AD_Risky_Signins.svg
        shape: image
        label: "Azure Ad Risky Signins"
      }
  
  
  Azure Ad Risky Users: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_AD_Risky_Users.svg
        shape: image
        label: "Azure Ad Risky Users"
      }
  
  
  Azure Information Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_Information_Protection.svg
        shape: image
        label: "Azure Information Protection"
      }
  
  
  Azure Sentinel: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Azure_Sentinel.svg
        shape: image
        label: "Azure Sentinel"
      }
  
  
  Conditional Access: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Conditional_Access.svg
        shape: image
        label: "Conditional Access"
      }
  
  
  Detonation: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Detonation.svg
        shape: image
        label: "Detonation"
      }
  
  
  Extendedsecurityupdates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/ExtendedSecurityUpdates.svg
        shape: image
        label: "Extendedsecurityupdates"
      }
  
  
  Identity Secure Score: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Identity_Secure_Score.svg
        shape: image
        label: "Identity Secure Score"
      }
  
  
  Key Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Key_Vaults.svg
        shape: image
        label: "Key Vaults"
      }
  
  
  Microsoft Defender Easm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Microsoft_Defender_EASM.svg
        shape: image
        label: "Microsoft Defender Easm"
      }
  
  
  Microsoft Defender For Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Microsoft_Defender_for_Cloud.svg
        shape: image
        label: "Microsoft Defender For Cloud"
      }
  
  
  Microsoft Defender For Iot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Microsoft_Defender_for_IoT.svg
        shape: image
        label: "Microsoft Defender For Iot"
      }
  
  
  Multifactor Authentication: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/Multifactor_Authentication.svg
        shape: image
        label: "Multifactor Authentication"
      }
  
  
  User Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/User_Settings.svg
        shape: image
        label: "User Settings"
      }
  
}