classes: {
  
  icon_service_Application_Security_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Application_Security_Groups.svg
        shape: image
        label: "icon_service_Application_Security_Groups"
      }
  
  icon_service_Azure_AD_Authentication_Methods: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_AD_Authentication_Methods.svg
        shape: image
        label: "icon_service_Azure_AD_Authentication_Methods"
      }
  
  icon_service_Azure_AD_Identity_Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_AD_Identity_Protection.svg
        shape: image
        label: "icon_service_Azure_AD_Identity_Protection"
      }
  
  icon_service_Azure_AD_Privleged_Identity_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_AD_Privleged_Identity_Management.svg
        shape: image
        label: "icon_service_Azure_AD_Privleged_Identity_Management"
      }
  
  icon_service_Azure_AD_Risky_Signins: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_AD_Risky_Signins.svg
        shape: image
        label: "icon_service_Azure_AD_Risky_Signins"
      }
  
  icon_service_Azure_AD_Risky_Users: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_AD_Risky_Users.svg
        shape: image
        label: "icon_service_Azure_AD_Risky_Users"
      }
  
  icon_service_Azure_Information_Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_Information_Protection.svg
        shape: image
        label: "icon_service_Azure_Information_Protection"
      }
  
  icon_service_Azure_Sentinel: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Azure_Sentinel.svg
        shape: image
        label: "icon_service_Azure_Sentinel"
      }
  
  icon_service_Conditional_Access: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Conditional_Access.svg
        shape: image
        label: "icon_service_Conditional_Access"
      }
  
  icon_service_Detonation: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Detonation.svg
        shape: image
        label: "icon_service_Detonation"
      }
  
  icon_service_ExtendedSecurityUpdates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_ExtendedSecurityUpdates.svg
        shape: image
        label: "icon_service_ExtendedSecurityUpdates"
      }
  
  icon_service_Identity_Secure_Score: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Identity_Secure_Score.svg
        shape: image
        label: "icon_service_Identity_Secure_Score"
      }
  
  icon_service_Key_Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Key_Vaults.svg
        shape: image
        label: "icon_service_Key_Vaults"
      }
  
  icon_service_Microsoft_Defender_EASM: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Microsoft_Defender_EASM.svg
        shape: image
        label: "icon_service_Microsoft_Defender_EASM"
      }
  
  icon_service_Microsoft_Defender_for_Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Microsoft_Defender_for_Cloud.svg
        shape: image
        label: "icon_service_Microsoft_Defender_for_Cloud"
      }
  
  icon_service_Microsoft_Defender_for_IoT: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Microsoft_Defender_for_IoT.svg
        shape: image
        label: "icon_service_Microsoft_Defender_for_IoT"
      }
  
  icon_service_Multifactor_Authentication: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_Multifactor_Authentication.svg
        shape: image
        label: "icon_service_Multifactor_Authentication"
      }
  
  icon_service_User_Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/security/icon_service_User_Settings.svg
        shape: image
        label: "icon_service_User_Settings"
      }
  
}