classes: {
  
  
  Amazon Codecatalyst: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/Amazon_CodeCatalyst.svg
        shape: image
        label: "Amazon Codecatalyst"
      }
  
  
  Amazon Corretto: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/Amazon_Corretto.svg
        shape: image
        label: "Amazon Corretto"
      }
  
  
  Aws Application Composer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_Application_Composer.svg
        shape: image
        label: "Aws Application Composer"
      }
  
  
  Aws Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_Cloud.svg
        shape: image
        label: "Aws Cloud"
      }
  
  
  Aws Cloudshell: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CloudShell.svg
        shape: image
        label: "Aws Cloudshell"
      }
  
  
  Aws Cloud Control Api: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_Cloud_Control_API.svg
        shape: image
        label: "Aws Cloud Control Api"
      }
  
  
  Aws Cloud Development Kit: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_Cloud_Development_Kit.svg
        shape: image
        label: "Aws Cloud Development Kit"
      }
  
  
  Aws Codeartifact: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CodeArtifact.svg
        shape: image
        label: "Aws Codeartifact"
      }
  
  
  Aws Codebuild: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CodeBuild.svg
        shape: image
        label: "Aws Codebuild"
      }
  
  
  Aws Codecommit: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CodeCommit.svg
        shape: image
        label: "Aws Codecommit"
      }
  
  
  Aws Codedeploy: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CodeDeploy.svg
        shape: image
        label: "Aws Codedeploy"
      }
  
  
  Aws Codepipeline: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CodePipeline.svg
        shape: image
        label: "Aws Codepipeline"
      }
  
  
  Aws Codestar: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_CodeStar.svg
        shape: image
        label: "Aws Codestar"
      }
  
  
  Aws Command Line Interface: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_Command_Line_Interface.svg
        shape: image
        label: "Aws Command Line Interface"
      }
  
  
  Aws Tools And Sdks: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_Tools_and_SDKs.svg
        shape: image
        label: "Aws Tools And Sdks"
      }
  
  
  Aws X Ray: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Developer-Tools/AWS_X_Ray.svg
        shape: image
        label: "Aws X Ray"
      }
  
}