classes: {
  
  
  Amused: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Amused.svg
        shape: image
        label: "Amused"
      }
  
  
  Angry: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Angry.svg
        shape: image
        label: "Angry"
      }
  
  
  Bored: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Bored.svg
        shape: image
        label: "Bored"
      }
  
  
  Cycling: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Cycling.svg
        shape: image
        label: "Cycling"
      }
  
  
  Developer persona: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Developer Persona.svg
        shape: image
        label: "Developer persona"
      }
  
  
  Devops persona: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/DevOps Persona.svg
        shape: image
        label: "Devops persona"
      }
  
  
  Dissapointed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Dissapointed.svg
        shape: image
        label: "Dissapointed"
      }
  
  
  Happy 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Happy 2.svg
        shape: image
        label: "Happy 2"
      }
  
  
  Happy: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Happy.svg
        shape: image
        label: "Happy"
      }
  
  
  Head: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Head.svg
        shape: image
        label: "Head"
      }
  
  
  Human: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Human.svg
        shape: image
        label: "Human"
      }
  
  
  Ideas: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Ideas.svg
        shape: image
        label: "Ideas"
      }
  
  
  Mad: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Mad.svg
        shape: image
        label: "Mad"
      }
  
  
  Mental health: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Mental Health.svg
        shape: image
        label: "Mental health"
      }
  
  
  Nurse: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Nurse.svg
        shape: image
        label: "Nurse"
      }
  
  
  Ops persona: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Ops Persona.svg
        shape: image
        label: "Ops persona"
      }
  
  
  People 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 1.svg
        shape: image
        label: "People 1"
      }
  
  
  People 10: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 10.svg
        shape: image
        label: "People 10"
      }
  
  
  People 11: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 11.svg
        shape: image
        label: "People 11"
      }
  
  
  People 12: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 12.svg
        shape: image
        label: "People 12"
      }
  
  
  People 13: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 13.svg
        shape: image
        label: "People 13"
      }
  
  
  People 15: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 15.svg
        shape: image
        label: "People 15"
      }
  
  
  People 16: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 16.svg
        shape: image
        label: "People 16"
      }
  
  
  People 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 2.svg
        shape: image
        label: "People 2"
      }
  
  
  People 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 3.svg
        shape: image
        label: "People 3"
      }
  
  
  People 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 4.svg
        shape: image
        label: "People 4"
      }
  
  
  People 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 5.svg
        shape: image
        label: "People 5"
      }
  
  
  People 6: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 6.svg
        shape: image
        label: "People 6"
      }
  
  
  People 7: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 7.svg
        shape: image
        label: "People 7"
      }
  
  
  People 9: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People 9.svg
        shape: image
        label: "People 9"
      }
  
  
  People connections: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People Connections.svg
        shape: image
        label: "People connections"
      }
  
  
  People network: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/People Network.svg
        shape: image
        label: "People network"
      }
  
  
  Persona 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Persona 2.svg
        shape: image
        label: "Persona 2"
      }
  
  
  Programmist 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Programmist 2.svg
        shape: image
        label: "Programmist 2"
      }
  
  
  Programmist: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Programmist.svg
        shape: image
        label: "Programmist"
      }
  
  
  Sad: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Sad.svg
        shape: image
        label: "Sad"
      }
  
  
  Security persona: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Security Persona.svg
        shape: image
        label: "Security persona"
      }
  
  
  Shocked: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Shocked.svg
        shape: image
        label: "Shocked"
      }
  
  
  Speed: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Speed.svg
        shape: image
        label: "Speed"
      }
  
  
  Steward persona: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Steward Persona.svg
        shape: image
        label: "Steward persona"
      }
  
  
  Streching: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Personas/Streching.svg
        shape: image
        label: "Streching"
      }
  
}