classes: {
    0-0_M: {
      source-arrowhead.shape: cf-One
      target-arrowhead.shape: cf-Many
    }
    1-1: {
      source-arrowhead.shape: cf-One-required
      target-arrowhead.shape: cf-One-required
    }
    0-M: {
      source-arrowhead.shape: cf-One
      target-arrowhead.shape: cf-Many-required
    }
    1-M: {
      source-arrowhead.shape: cf-One-required
      target-arrowhead.shape: cf-Many-required
    }
    1-0_M: {
      source-arrowhead.shape: cf-One-required
      target-arrowhead.shape: cf-Many
    }
    0_M-0: {
      source-arrowhead.shape: cf-Many
      target-arrowhead.shape: cf-One
    }
    M-0: {
      source-arrowhead.shape: cf-Many-required
      target-arrowhead.shape: cf-One
    }
    M-1: {
      source-arrowhead.shape: cf-Many-required
      target-arrowhead.shape: cf-One-required
    }
    0_M-1: {
      source-arrowhead.shape: cf-Many
      target-arrowhead.shape: cf-One-required
    }
    0_M-M: {
      source-arrowhead.shape: cf-Many
      target-arrowhead.shape: cf-Many-required
    }
    M-0_M: {
      source-arrowhead.shape: cf-Many-required
      target-arrowhead.shape: cf-Many
    }
    0_M-0_M: {
      source-arrowhead.shape: cf-Many
      target-arrowhead.shape: cf-Many
    }
    M-M: {
      source-arrowhead.shape: cf-Many-required
      target-arrowhead.shape: cf-Many-required
    }
  }
