classes: {
  
  
  Access Context Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/access_context_manager.svg
        shape: image
        label: "Access Context Manager"
      }
  
  
  Administration: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/administration.svg
        shape: image
        label: "Administration"
      }
  
  
  Advanced Agent Modeling: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/advanced_agent_modeling.svg
        shape: image
        label: "Advanced Agent Modeling"
      }
  
  
  Advanced Solutions Lab: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/advanced_solutions_lab.svg
        shape: image
        label: "Advanced Solutions Lab"
      }
  
  
  Agent Assist: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/agent_assist.svg
        shape: image
        label: "Agent Assist"
      }
  
  
  Ai Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/ai_hub.svg
        shape: image
        label: "Ai Hub"
      }
  
  
  Ai Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/ai_platform.svg
        shape: image
        label: "Ai Platform"
      }
  
  
  Ai Platform Unified: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/ai_platform_unified.svg
        shape: image
        label: "Ai Platform Unified"
      }
  
  
  Analytics Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/analytics_hub.svg
        shape: image
        label: "Analytics Hub"
      }
  
  
  Anthos: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/anthos.svg
        shape: image
        label: "Anthos"
      }
  
  
  Anthos Config Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/anthos_config_management.svg
        shape: image
        label: "Anthos Config Management"
      }
  
  
  Anthos Service Mesh: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/anthos_service_mesh.svg
        shape: image
        label: "Anthos Service Mesh"
      }
  
  
  Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/api.svg
        shape: image
        label: "Api"
      }
  
  
  Apigee Api Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/apigee_api_platform.svg
        shape: image
        label: "Apigee Api Platform"
      }
  
  
  Apigee Sense: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/apigee_sense.svg
        shape: image
        label: "Apigee Sense"
      }
  
  
  Api Analytics: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/api_analytics.svg
        shape: image
        label: "Api Analytics"
      }
  
  
  Api Monetization: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/api_monetization.svg
        shape: image
        label: "Api Monetization"
      }
  
  
  App Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/app_engine.svg
        shape: image
        label: "App Engine"
      }
  
  
  Artifact Registry: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/artifact_registry.svg
        shape: image
        label: "Artifact Registry"
      }
  
  
  Asset Inventory: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/asset_inventory.svg
        shape: image
        label: "Asset Inventory"
      }
  
  
  Assured Workloads: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/assured_workloads.svg
        shape: image
        label: "Assured Workloads"
      }
  
  
  Automl: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/automl.svg
        shape: image
        label: "Automl"
      }
  
  
  Automl Natural Language: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/automl_natural_language.svg
        shape: image
        label: "Automl Natural Language"
      }
  
  
  Automl Tables: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/automl_tables.svg
        shape: image
        label: "Automl Tables"
      }
  
  
  Automl Translation: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/automl_translation.svg
        shape: image
        label: "Automl Translation"
      }
  
  
  Automl Video Intelligence: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/automl_video_intelligence.svg
        shape: image
        label: "Automl Video Intelligence"
      }
  
  
  Automl Vision: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/automl_vision.svg
        shape: image
        label: "Automl Vision"
      }
  
  
  Bare Metal Solutions: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/bare_metal_solutions.svg
        shape: image
        label: "Bare Metal Solutions"
      }
  
  
  Batch: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/batch.svg
        shape: image
        label: "Batch"
      }
  
  
  Beyondcorp: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/beyondcorp.svg
        shape: image
        label: "Beyondcorp"
      }
  
  
  Bigquery: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/bigquery.svg
        shape: image
        label: "Bigquery"
      }
  
  
  Bigtable: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/bigtable.svg
        shape: image
        label: "Bigtable"
      }
  
  
  Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/billing.svg
        shape: image
        label: "Billing"
      }
  
  
  Binary Authorization: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/binary_authorization.svg
        shape: image
        label: "Binary Authorization"
      }
  
  
  Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/catalog.svg
        shape: image
        label: "Catalog"
      }
  
  
  Certificate Authority Service: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/certificate_authority_service.svg
        shape: image
        label: "Certificate Authority Service"
      }
  
  
  Certificate Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/certificate_manager.svg
        shape: image
        label: "Certificate Manager"
      }
  
  
  Cloud Apis: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_apis.svg
        shape: image
        label: "Cloud Apis"
      }
  
  
  Cloud Api Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_api_gateway.svg
        shape: image
        label: "Cloud Api Gateway"
      }
  
  
  Cloud Armor: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_armor.svg
        shape: image
        label: "Cloud Armor"
      }
  
  
  Cloud Asset Inventory: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_asset_inventory.svg
        shape: image
        label: "Cloud Asset Inventory"
      }
  
  
  Cloud Audit Logs: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_audit_logs.svg
        shape: image
        label: "Cloud Audit Logs"
      }
  
  
  Cloud Build: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_build.svg
        shape: image
        label: "Cloud Build"
      }
  
  
  Cloud Cdn: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_cdn.svg
        shape: image
        label: "Cloud Cdn"
      }
  
  
  Cloud Code: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_code.svg
        shape: image
        label: "Cloud Code"
      }
  
  
  Cloud Composer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_composer.svg
        shape: image
        label: "Cloud Composer"
      }
  
  
  Cloud Data Fusion: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_data_fusion.svg
        shape: image
        label: "Cloud Data Fusion"
      }
  
  
  Cloud Deploy: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_deploy.svg
        shape: image
        label: "Cloud Deploy"
      }
  
  
  Cloud Deployment Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_deployment_manager.svg
        shape: image
        label: "Cloud Deployment Manager"
      }
  
  
  Cloud Dns: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_dns.svg
        shape: image
        label: "Cloud Dns"
      }
  
  
  Cloud Domains: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_domains.svg
        shape: image
        label: "Cloud Domains"
      }
  
  
  Cloud Ekm: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_ekm.svg
        shape: image
        label: "Cloud Ekm"
      }
  
  
  Cloud Endpoints: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_endpoints.svg
        shape: image
        label: "Cloud Endpoints"
      }
  
  
  Cloud External Ip Addresses: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_external_ip_addresses.svg
        shape: image
        label: "Cloud External Ip Addresses"
      }
  
  
  Cloud Firewall Rules: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_firewall_rules.svg
        shape: image
        label: "Cloud Firewall Rules"
      }
  
  
  Cloud For Marketing: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_for_marketing.svg
        shape: image
        label: "Cloud For Marketing"
      }
  
  
  Cloud Functions: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_functions.svg
        shape: image
        label: "Cloud Functions"
      }
  
  
  Cloud Generic: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_generic.svg
        shape: image
        label: "Cloud Generic"
      }
  
  
  Cloud Gpu: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_gpu.svg
        shape: image
        label: "Cloud Gpu"
      }
  
  
  Cloud Healthcare Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_healthcare_api.svg
        shape: image
        label: "Cloud Healthcare Api"
      }
  
  
  Cloud Healthcare Marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_healthcare_marketplace.svg
        shape: image
        label: "Cloud Healthcare Marketplace"
      }
  
  
  Cloud Hsm: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_hsm.svg
        shape: image
        label: "Cloud Hsm"
      }
  
  
  Cloud Ids: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_ids.svg
        shape: image
        label: "Cloud Ids"
      }
  
  
  Cloud Inference Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_inference_api.svg
        shape: image
        label: "Cloud Inference Api"
      }
  
  
  Cloud Interconnect: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_interconnect.svg
        shape: image
        label: "Cloud Interconnect"
      }
  
  
  Cloud Jobs Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_jobs_api.svg
        shape: image
        label: "Cloud Jobs Api"
      }
  
  
  Cloud Load Balancing: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_load_balancing.svg
        shape: image
        label: "Cloud Load Balancing"
      }
  
  
  Cloud Logging: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_logging.svg
        shape: image
        label: "Cloud Logging"
      }
  
  
  Cloud Media Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_media_edge.svg
        shape: image
        label: "Cloud Media Edge"
      }
  
  
  Cloud Monitoring: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_monitoring.svg
        shape: image
        label: "Cloud Monitoring"
      }
  
  
  Cloud Nat: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_nat.svg
        shape: image
        label: "Cloud Nat"
      }
  
  
  Cloud Natural Language Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_natural_language_api.svg
        shape: image
        label: "Cloud Natural Language Api"
      }
  
  
  Cloud Network: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_network.svg
        shape: image
        label: "Cloud Network"
      }
  
  
  Cloud Ops: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_ops.svg
        shape: image
        label: "Cloud Ops"
      }
  
  
  Cloud Optimization Ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_optimization_ai.svg
        shape: image
        label: "Cloud Optimization Ai"
      }
  
  
  Cloud Optimization Ai   Fleet Routing Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_optimization_ai___fleet_routing_api.svg
        shape: image
        label: "Cloud Optimization Ai   Fleet Routing Api"
      }
  
  
  Cloud Router: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_router.svg
        shape: image
        label: "Cloud Router"
      }
  
  
  Cloud Routes: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_routes.svg
        shape: image
        label: "Cloud Routes"
      }
  
  
  Cloud Run: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_run.svg
        shape: image
        label: "Cloud Run"
      }
  
  
  Cloud Run For Anthos: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_run_for_anthos.svg
        shape: image
        label: "Cloud Run For Anthos"
      }
  
  
  Cloud Scheduler: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_scheduler.svg
        shape: image
        label: "Cloud Scheduler"
      }
  
  
  Cloud Security Scanner: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_security_scanner.svg
        shape: image
        label: "Cloud Security Scanner"
      }
  
  
  Cloud Shell: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_shell.svg
        shape: image
        label: "Cloud Shell"
      }
  
  
  Cloud Spanner: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_spanner.svg
        shape: image
        label: "Cloud Spanner"
      }
  
  
  Cloud Sql: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_sql.svg
        shape: image
        label: "Cloud Sql"
      }
  
  
  Cloud Storage: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_storage.svg
        shape: image
        label: "Cloud Storage"
      }
  
  
  Cloud Tasks: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_tasks.svg
        shape: image
        label: "Cloud Tasks"
      }
  
  
  Cloud Test Lab: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_test_lab.svg
        shape: image
        label: "Cloud Test Lab"
      }
  
  
  Cloud Tpu: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_tpu.svg
        shape: image
        label: "Cloud Tpu"
      }
  
  
  Cloud Translation Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_translation_api.svg
        shape: image
        label: "Cloud Translation Api"
      }
  
  
  Cloud Vision Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_vision_api.svg
        shape: image
        label: "Cloud Vision Api"
      }
  
  
  Cloud Vpn: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/cloud_vpn.svg
        shape: image
        label: "Cloud Vpn"
      }
  
  
  Compute Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/compute_engine.svg
        shape: image
        label: "Compute Engine"
      }
  
  
  Configuration Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/configuration_management.svg
        shape: image
        label: "Configuration Management"
      }
  
  
  Connectivity Test: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/connectivity_test.svg
        shape: image
        label: "Connectivity Test"
      }
  
  
  Connectors: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/connectors.svg
        shape: image
        label: "Connectors"
      }
  
  
  Contact Center Ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/contact_center_ai.svg
        shape: image
        label: "Contact Center Ai"
      }
  
  
  Container Optimized Os: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/container_optimized_os.svg
        shape: image
        label: "Container Optimized Os"
      }
  
  
  Container Registry: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/container_registry.svg
        shape: image
        label: "Container Registry"
      }
  
  
  Database Migration Service: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/database_migration_service.svg
        shape: image
        label: "Database Migration Service"
      }
  
  
  Dataflow: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataflow.svg
        shape: image
        label: "Dataflow"
      }
  
  
  Datalab: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datalab.svg
        shape: image
        label: "Datalab"
      }
  
  
  Dataplex: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataplex.svg
        shape: image
        label: "Dataplex"
      }
  
  
  Datapol: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datapol.svg
        shape: image
        label: "Datapol"
      }
  
  
  Dataprep: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataprep.svg
        shape: image
        label: "Dataprep"
      }
  
  
  Dataproc: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataproc.svg
        shape: image
        label: "Dataproc"
      }
  
  
  Dataproc Metastore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dataproc_metastore.svg
        shape: image
        label: "Dataproc Metastore"
      }
  
  
  Datashare: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datashare.svg
        shape: image
        label: "Datashare"
      }
  
  
  Datastore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datastore.svg
        shape: image
        label: "Datastore"
      }
  
  
  Datastream: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/datastream.svg
        shape: image
        label: "Datastream"
      }
  
  
  Data Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_catalog.svg
        shape: image
        label: "Data Catalog"
      }
  
  
  Data Labeling: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_labeling.svg
        shape: image
        label: "Data Labeling"
      }
  
  
  Data Layers: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_layers.svg
        shape: image
        label: "Data Layers"
      }
  
  
  Data Loss Prevention Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_loss_prevention_api.svg
        shape: image
        label: "Data Loss Prevention Api"
      }
  
  
  Data Qna: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_qna.svg
        shape: image
        label: "Data Qna"
      }
  
  
  Data Studio: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_studio.svg
        shape: image
        label: "Data Studio"
      }
  
  
  Data Transfer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/data_transfer.svg
        shape: image
        label: "Data Transfer"
      }
  
  
  Debugger: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/debugger.svg
        shape: image
        label: "Debugger"
      }
  
  
  Developer Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/developer_portal.svg
        shape: image
        label: "Developer Portal"
      }
  
  
  Dialogflow: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dialogflow.svg
        shape: image
        label: "Dialogflow"
      }
  
  
  Dialogflow Cx: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dialogflow_cx.svg
        shape: image
        label: "Dialogflow Cx"
      }
  
  
  Dialogflow Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/dialogflow_insights.svg
        shape: image
        label: "Dialogflow Insights"
      }
  
  
  Document Ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/document_ai.svg
        shape: image
        label: "Document Ai"
      }
  
  
  Early Access Center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/early_access_center.svg
        shape: image
        label: "Early Access Center"
      }
  
  
  Error Reporting: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/error_reporting.svg
        shape: image
        label: "Error Reporting"
      }
  
  
  Eventarc: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/eventarc.svg
        shape: image
        label: "Eventarc"
      }
  
  
  Filestore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/filestore.svg
        shape: image
        label: "Filestore"
      }
  
  
  Financial Services Marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/financial_services_marketplace.svg
        shape: image
        label: "Financial Services Marketplace"
      }
  
  
  Firestore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/firestore.svg
        shape: image
        label: "Firestore"
      }
  
  
  Fleet Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/fleet_engine.svg
        shape: image
        label: "Fleet Engine"
      }
  
  
  Free Trial: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/free_trial.svg
        shape: image
        label: "Free Trial"
      }
  
  
  Game Servers: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/game_servers.svg
        shape: image
        label: "Game Servers"
      }
  
  
  Gce Systems Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/gce_systems_management.svg
        shape: image
        label: "Gce Systems Management"
      }
  
  
  Genomics: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/genomics.svg
        shape: image
        label: "Genomics"
      }
  
  
  Gke On Prem: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/gke_on_prem.svg
        shape: image
        label: "Gke On Prem"
      }
  
  
  Google Cloud Marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/google_cloud_marketplace.svg
        shape: image
        label: "Google Cloud Marketplace"
      }
  
  
  Google Kubernetes Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/google_kubernetes_engine.svg
        shape: image
        label: "Google Kubernetes Engine"
      }
  
  
  Google Maps Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/google_maps_platform.svg
        shape: image
        label: "Google Maps Platform"
      }
  
  
  Healthcare Nlp Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/healthcare_nlp_api.svg
        shape: image
        label: "Healthcare Nlp Api"
      }
  
  
  Home: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/home.svg
        shape: image
        label: "Home"
      }
  
  
  Identity And Access Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/identity_and_access_management.svg
        shape: image
        label: "Identity And Access Management"
      }
  
  
  Identity Aware Proxy: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/identity_aware_proxy.svg
        shape: image
        label: "Identity Aware Proxy"
      }
  
  
  Identity Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/identity_platform.svg
        shape: image
        label: "Identity Platform"
      }
  
  
  Iot Core: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/iot_core.svg
        shape: image
        label: "Iot Core"
      }
  
  
  Iot Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/iot_edge.svg
        shape: image
        label: "Iot Edge"
      }
  
  
  Key Access Justifications: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/key_access_justifications.svg
        shape: image
        label: "Key Access Justifications"
      }
  
  
  Key Management Service: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/key_management_service.svg
        shape: image
        label: "Key Management Service"
      }
  
  
  Kuberun: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/kuberun.svg
        shape: image
        label: "Kuberun"
      }
  
  
  Launcher: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/launcher.svg
        shape: image
        label: "Launcher"
      }
  
  
  Local Ssd: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/local_ssd.svg
        shape: image
        label: "Local Ssd"
      }
  
  
  Looker: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/looker.svg
        shape: image
        label: "Looker"
      }
  
  
  Managed Service For Microsoft Active Directory: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/managed_service_for_microsoft_active_directory.svg
        shape: image
        label: "Managed Service For Microsoft Active Directory"
      }
  
  
  Media Translation Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/media_translation_api.svg
        shape: image
        label: "Media Translation Api"
      }
  
  
  Memorystore: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/memorystore.svg
        shape: image
        label: "Memorystore"
      }
  
  
  Migrate For Anthos: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/migrate_for_anthos.svg
        shape: image
        label: "Migrate For Anthos"
      }
  
  
  Migrate For Compute Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/migrate_for_compute_engine.svg
        shape: image
        label: "Migrate For Compute Engine"
      }
  
  
  My Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/my_cloud.svg
        shape: image
        label: "My Cloud"
      }
  
  
  Network Connectivity Center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/network_connectivity_center.svg
        shape: image
        label: "Network Connectivity Center"
      }
  
  
  Network Intelligence Center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/network_intelligence_center.svg
        shape: image
        label: "Network Intelligence Center"
      }
  
  
  Network Security: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/network_security.svg
        shape: image
        label: "Network Security"
      }
  
  
  Network Tiers: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/network_tiers.svg
        shape: image
        label: "Network Tiers"
      }
  
  
  Network Topology: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/network_topology.svg
        shape: image
        label: "Network Topology"
      }
  
  
  Onboarding: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/onboarding.svg
        shape: image
        label: "Onboarding"
      }
  
  
  Os Configuration Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/os_configuration_management.svg
        shape: image
        label: "Os Configuration Management"
      }
  
  
  Os Inventory Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/os_inventory_management.svg
        shape: image
        label: "Os Inventory Management"
      }
  
  
  Os Patch Management: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/os_patch_management.svg
        shape: image
        label: "Os Patch Management"
      }
  
  
  Partner Interconnect: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/partner_interconnect.svg
        shape: image
        label: "Partner Interconnect"
      }
  
  
  Partner Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/partner_portal.svg
        shape: image
        label: "Partner Portal"
      }
  
  
  Performance Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/performance_dashboard.svg
        shape: image
        label: "Performance Dashboard"
      }
  
  
  Permissions: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/permissions.svg
        shape: image
        label: "Permissions"
      }
  
  
  Persistent Disk: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/persistent_disk.svg
        shape: image
        label: "Persistent Disk"
      }
  
  
  Phishing Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/phishing_protection.svg
        shape: image
        label: "Phishing Protection"
      }
  
  
  Policy Analyzer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/policy_analyzer.svg
        shape: image
        label: "Policy Analyzer"
      }
  
  
  Premium Network Tier: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/premium_network_tier.svg
        shape: image
        label: "Premium Network Tier"
      }
  
  
  Private Connectivity: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/private_connectivity.svg
        shape: image
        label: "Private Connectivity"
      }
  
  
  Private Service Connect: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/private_service_connect.svg
        shape: image
        label: "Private Service Connect"
      }
  
  
  Producer Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/producer_portal.svg
        shape: image
        label: "Producer Portal"
      }
  
  
  Profiler: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/profiler.svg
        shape: image
        label: "Profiler"
      }
  
  
  Project: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/project.svg
        shape: image
        label: "Project"
      }
  
  
  Pubsub: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/pubsub.svg
        shape: image
        label: "Pubsub"
      }
  
  
  Quantum Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/quantum_engine.svg
        shape: image
        label: "Quantum Engine"
      }
  
  
  Quotas: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/quotas.svg
        shape: image
        label: "Quotas"
      }
  
  
  Real World Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/real_world_insights.svg
        shape: image
        label: "Real World Insights"
      }
  
  
  Recommendations Ai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/recommendations_ai.svg
        shape: image
        label: "Recommendations Ai"
      }
  
  
  Release Notes: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/release_notes.svg
        shape: image
        label: "Release Notes"
      }
  
  
  Retail Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/retail_api.svg
        shape: image
        label: "Retail Api"
      }
  
  
  Risk Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/risk_manager.svg
        shape: image
        label: "Risk Manager"
      }
  
  
  Runtime Config: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/runtime_config.svg
        shape: image
        label: "Runtime Config"
      }
  
  
  Secret Manager: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/secret_manager.svg
        shape: image
        label: "Secret Manager"
      }
  
  
  Security: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/security.svg
        shape: image
        label: "Security"
      }
  
  
  Security Command Center: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/security_command_center.svg
        shape: image
        label: "Security Command Center"
      }
  
  
  Security Health Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/security_health_advisor.svg
        shape: image
        label: "Security Health Advisor"
      }
  
  
  Security Key Enforcement: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/security_key_enforcement.svg
        shape: image
        label: "Security Key Enforcement"
      }
  
  
  Service Discovery: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/service_discovery.svg
        shape: image
        label: "Service Discovery"
      }
  
  
  Speech To Text: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/speech_to_text.svg
        shape: image
        label: "Speech To Text"
      }
  
  
  Stackdriver: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/stackdriver.svg
        shape: image
        label: "Stackdriver"
      }
  
  
  Standard Network Tier: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/standard_network_tier.svg
        shape: image
        label: "Standard Network Tier"
      }
  
  
  Stream Suite: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/stream_suite.svg
        shape: image
        label: "Stream Suite"
      }
  
  
  Support: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/support.svg
        shape: image
        label: "Support"
      }
  
  
  Tensorflow Enterprise: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/tensorflow_enterprise.svg
        shape: image
        label: "Tensorflow Enterprise"
      }
  
  
  Text To Speech: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/text_to_speech.svg
        shape: image
        label: "Text To Speech"
      }
  
  
  Tools For Powershell: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/tools_for_powershell.svg
        shape: image
        label: "Tools For Powershell"
      }
  
  
  Trace: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/trace.svg
        shape: image
        label: "Trace"
      }
  
  
  Traffic Director: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/traffic_director.svg
        shape: image
        label: "Traffic Director"
      }
  
  
  Transfer: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/transfer.svg
        shape: image
        label: "Transfer"
      }
  
  
  Transfer Appliance: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/transfer_appliance.svg
        shape: image
        label: "Transfer Appliance"
      }
  
  
  User Preferences: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/user_preferences.svg
        shape: image
        label: "User Preferences"
      }
  
  
  Vertexai: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/vertexai.svg
        shape: image
        label: "Vertexai"
      }
  
  
  Video Intelligence Api: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/video_intelligence_api.svg
        shape: image
        label: "Video Intelligence Api"
      }
  
  
  Virtual Private Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/virtual_private_cloud.svg
        shape: image
        label: "Virtual Private Cloud"
      }
  
  
  Visual Inspection: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/visual_inspection.svg
        shape: image
        label: "Visual Inspection"
      }
  
  
  Vmware Engine: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/vmware_engine.svg
        shape: image
        label: "Vmware Engine"
      }
  
  
  Web Risk: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/web_risk.svg
        shape: image
        label: "Web Risk"
      }
  
  
  Web Security Scanner: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/web_security_scanner.svg
        shape: image
        label: "Web Security Scanner"
      }
  
  
  Workflows: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/workflows.svg
        shape: image
        label: "Workflows"
      }
  
  
  Workload Identity Pool: {
        icon: https://ppalka-lingaro.github.io/icons/Google cloud icons/All/workload_identity_pool.svg
        shape: image
        label: "Workload Identity Pool"
      }
  
}