classes: {
  
  
  Res Aws-iot Http Protocol 48: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS-IoT_HTTP_Protocol_48.svg
        shape: image
        label: "Res Aws-iot Http Protocol 48"
      }
  
  
  Res Aws Iot Action: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Action.svg
        shape: image
        label: "Res Aws Iot Action"
      }
  
  
  Res Aws Iot Actuator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Actuator.svg
        shape: image
        label: "Res Aws Iot Actuator"
      }
  
  
  Res Aws Iot Alexa Enabled Device: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Alexa_Enabled_Device.svg
        shape: image
        label: "Res Aws Iot Alexa Enabled Device"
      }
  
  
  Res Aws Iot Alexa Skill: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Alexa_Skill.svg
        shape: image
        label: "Res Aws Iot Alexa Skill"
      }
  
  
  Res Aws Iot Alexa Voice Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Alexa_Voice_Service.svg
        shape: image
        label: "Res Aws Iot Alexa Voice Service"
      }
  
  
  Res Aws Iot Analytics Channel: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Analytics_Channel.svg
        shape: image
        label: "Res Aws Iot Analytics Channel"
      }
  
  
  Res Aws Iot Analytics Dataset: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Analytics_Dataset.svg
        shape: image
        label: "Res Aws Iot Analytics Dataset"
      }
  
  
  Res Aws Iot Analytics Data Store: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Analytics_Data_Store.svg
        shape: image
        label: "Res Aws Iot Analytics Data Store"
      }
  
  
  Res Aws Iot Analytics Notebook: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Analytics_Notebook.svg
        shape: image
        label: "Res Aws Iot Analytics Notebook"
      }
  
  
  Res Aws Iot Analytics Pipeline: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Analytics_Pipeline.svg
        shape: image
        label: "Res Aws Iot Analytics Pipeline"
      }
  
  
  Res Aws Iot Certificate: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Certificate.svg
        shape: image
        label: "Res Aws Iot Certificate"
      }
  
  
  Res Aws Iot Core Device Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Core_Device_Advisor.svg
        shape: image
        label: "Res Aws Iot Core Device Advisor"
      }
  
  
  Res Aws Iot Core Device Location: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Core_Device_Location.svg
        shape: image
        label: "Res Aws Iot Core Device Location"
      }
  
  
  Res Aws Iot Desired State: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Desired_State.svg
        shape: image
        label: "Res Aws Iot Desired State"
      }
  
  
  Res Aws Iot Device Defender Iot Device Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Device_Defender_IoT_Device_Jobs.svg
        shape: image
        label: "Res Aws Iot Device Defender Iot Device Jobs"
      }
  
  
  Res Aws Iot Device Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Device_Gateway.svg
        shape: image
        label: "Res Aws Iot Device Gateway"
      }
  
  
  Res Aws Iot Device Management Fleet Hub: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Device_Management_Fleet_Hub.svg
        shape: image
        label: "Res Aws Iot Device Management Fleet Hub"
      }
  
  
  Res Aws Iot Device Tester: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Device_Tester.svg
        shape: image
        label: "Res Aws Iot Device Tester"
      }
  
  
  Res Aws Iot Echo: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Echo.svg
        shape: image
        label: "Res Aws Iot Echo"
      }
  
  
  Res Aws Iot Fire Tv: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Fire_TV.svg
        shape: image
        label: "Res Aws Iot Fire Tv"
      }
  
  
  Res Aws Iot Fire Tv Stick: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Fire_TV_Stick.svg
        shape: image
        label: "Res Aws Iot Fire Tv Stick"
      }
  
  
  Res Aws Iot Greengrass Artifact: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Artifact.svg
        shape: image
        label: "Res Aws Iot Greengrass Artifact"
      }
  
  
  Res Aws Iot Greengrass Component: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Component.svg
        shape: image
        label: "Res Aws Iot Greengrass Component"
      }
  
  
  Res Aws Iot Greengrass Component Machine Learning: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Component_Machine_Learning.svg
        shape: image
        label: "Res Aws Iot Greengrass Component Machine Learning"
      }
  
  
  Res Aws Iot Greengrass Component Nucleus: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Component_Nucleus.svg
        shape: image
        label: "Res Aws Iot Greengrass Component Nucleus"
      }
  
  
  Res Aws Iot Greengrass Component Private: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Component_Private.svg
        shape: image
        label: "Res Aws Iot Greengrass Component Private"
      }
  
  
  Res Aws Iot Greengrass Component Public: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Component_Public.svg
        shape: image
        label: "Res Aws Iot Greengrass Component Public"
      }
  
  
  Res Aws Iot Greengrass Connector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Connector.svg
        shape: image
        label: "Res Aws Iot Greengrass Connector"
      }
  
  
  Res Aws Iot Greengrass Interprocess Communication: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Interprocess_Communication.svg
        shape: image
        label: "Res Aws Iot Greengrass Interprocess Communication"
      }
  
  
  Res Aws Iot Greengrass Protocol: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Protocol.svg
        shape: image
        label: "Res Aws Iot Greengrass Protocol"
      }
  
  
  Res Aws Iot Greengrass Recipe: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Recipe.svg
        shape: image
        label: "Res Aws Iot Greengrass Recipe"
      }
  
  
  Res Aws Iot Greengrass Stream Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Greengrass_Stream_Manager.svg
        shape: image
        label: "Res Aws Iot Greengrass Stream Manager"
      }
  
  
  Res Aws Iot Hardware Board: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Hardware_Board.svg
        shape: image
        label: "Res Aws Iot Hardware Board"
      }
  
  
  Res Aws Iot Http Protocol: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_HTTP_Protocol.svg
        shape: image
        label: "Res Aws Iot Http Protocol"
      }
  
  
  Res Aws Iot Lambda Function: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Lambda_Function.svg
        shape: image
        label: "Res Aws Iot Lambda Function"
      }
  
  
  Res Aws Iot Lorawan Protocol: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_LoRaWAN_Protocol.svg
        shape: image
        label: "Res Aws Iot Lorawan Protocol"
      }
  
  
  Res Aws Iot Mqtt Protocol: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_MQTT_Protocol.svg
        shape: image
        label: "Res Aws Iot Mqtt Protocol"
      }
  
  
  Res Aws Iot Over Air Update: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Over_Air_Update.svg
        shape: image
        label: "Res Aws Iot Over Air Update"
      }
  
  
  Res Aws Iot Policy: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Policy.svg
        shape: image
        label: "Res Aws Iot Policy"
      }
  
  
  Res Aws Iot Reported State: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Reported_State.svg
        shape: image
        label: "Res Aws Iot Reported State"
      }
  
  
  Res Aws Iot Rule: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Rule.svg
        shape: image
        label: "Res Aws Iot Rule"
      }
  
  
  Res Aws Iot Sailboat: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Sailboat.svg
        shape: image
        label: "Res Aws Iot Sailboat"
      }
  
  
  Res Aws Iot Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Sensor.svg
        shape: image
        label: "Res Aws Iot Sensor"
      }
  
  
  Res Aws Iot Servo: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Servo.svg
        shape: image
        label: "Res Aws Iot Servo"
      }
  
  
  Res Aws Iot Shadow: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Shadow.svg
        shape: image
        label: "Res Aws Iot Shadow"
      }
  
  
  Res Aws Iot Simulator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Simulator.svg
        shape: image
        label: "Res Aws Iot Simulator"
      }
  
  
  Res Aws Iot Sitewise Asset: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_SiteWise_Asset.svg
        shape: image
        label: "Res Aws Iot Sitewise Asset"
      }
  
  
  Res Aws Iot Sitewise Asset Hierarchy: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_SiteWise_Asset_Hierarchy.svg
        shape: image
        label: "Res Aws Iot Sitewise Asset Hierarchy"
      }
  
  
  Res Aws Iot Sitewise Asset Model: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_SiteWise_Asset_Model.svg
        shape: image
        label: "Res Aws Iot Sitewise Asset Model"
      }
  
  
  Res Aws Iot Sitewise Asset Properties: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_SiteWise_Asset_Properties.svg
        shape: image
        label: "Res Aws Iot Sitewise Asset Properties"
      }
  
  
  Res Aws Iot Sitewise Data Streams: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_SiteWise_Data_Streams.svg
        shape: image
        label: "Res Aws Iot Sitewise Data Streams"
      }
  
  
  Res Aws Iot Thing Bank: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Bank.svg
        shape: image
        label: "Res Aws Iot Thing Bank"
      }
  
  
  Res Aws Iot Thing Bicycle: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Bicycle.svg
        shape: image
        label: "Res Aws Iot Thing Bicycle"
      }
  
  
  Res Aws Iot Thing Camera: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Camera.svg
        shape: image
        label: "Res Aws Iot Thing Camera"
      }
  
  
  Res Aws Iot Thing Car: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Car.svg
        shape: image
        label: "Res Aws Iot Thing Car"
      }
  
  
  Res Aws Iot Thing Cart: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Cart.svg
        shape: image
        label: "Res Aws Iot Thing Cart"
      }
  
  
  Res Aws Iot Thing Coffee Pot: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Coffee_Pot.svg
        shape: image
        label: "Res Aws Iot Thing Coffee Pot"
      }
  
  
  Res Aws Iot Thing Door Lock: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Door_Lock.svg
        shape: image
        label: "Res Aws Iot Thing Door Lock"
      }
  
  
  Res Aws Iot Thing Factory: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Factory.svg
        shape: image
        label: "Res Aws Iot Thing Factory"
      }
  
  
  Res Aws Iot Thing Freertos Device: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_FreeRTOS_Device.svg
        shape: image
        label: "Res Aws Iot Thing Freertos Device"
      }
  
  
  Res Aws Iot Thing Generic: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Generic.svg
        shape: image
        label: "Res Aws Iot Thing Generic"
      }
  
  
  Res Aws Iot Thing House: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_House.svg
        shape: image
        label: "Res Aws Iot Thing House"
      }
  
  
  Res Aws Iot Thing Humidity Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Humidity_Sensor.svg
        shape: image
        label: "Res Aws Iot Thing Humidity Sensor"
      }
  
  
  Res Aws Iot Thing Industrial Pc: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Industrial_PC.svg
        shape: image
        label: "Res Aws Iot Thing Industrial Pc"
      }
  
  
  Res Aws Iot Thing Lightbulb: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Lightbulb.svg
        shape: image
        label: "Res Aws Iot Thing Lightbulb"
      }
  
  
  Res Aws Iot Thing Medical Emergency: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Medical_Emergency.svg
        shape: image
        label: "Res Aws Iot Thing Medical Emergency"
      }
  
  
  Res Aws Iot Thing Plc: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_PLC.svg
        shape: image
        label: "Res Aws Iot Thing Plc"
      }
  
  
  Res Aws Iot Thing Police Emergency: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Police_Emergency.svg
        shape: image
        label: "Res Aws Iot Thing Police Emergency"
      }
  
  
  Res Aws Iot Thing Relay: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Relay.svg
        shape: image
        label: "Res Aws Iot Thing Relay"
      }
  
  
  Res Aws Iot Thing Stacklight: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Stacklight.svg
        shape: image
        label: "Res Aws Iot Thing Stacklight"
      }
  
  
  Res Aws Iot Thing Temperature Humidity Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Temperature_Humidity_Sensor.svg
        shape: image
        label: "Res Aws Iot Thing Temperature Humidity Sensor"
      }
  
  
  Res Aws Iot Thing Temperature Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Temperature_Sensor.svg
        shape: image
        label: "Res Aws Iot Thing Temperature Sensor"
      }
  
  
  Res Aws Iot Thing Temperature Vibration Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Temperature_Vibration_Sensor.svg
        shape: image
        label: "Res Aws Iot Thing Temperature Vibration Sensor"
      }
  
  
  Res Aws Iot Thing Thermostat: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Thermostat.svg
        shape: image
        label: "Res Aws Iot Thing Thermostat"
      }
  
  
  Res Aws Iot Thing Travel: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Travel.svg
        shape: image
        label: "Res Aws Iot Thing Travel"
      }
  
  
  Res Aws Iot Thing Utility: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Utility.svg
        shape: image
        label: "Res Aws Iot Thing Utility"
      }
  
  
  Res Aws Iot Thing Vibration Sensor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Vibration_Sensor.svg
        shape: image
        label: "Res Aws Iot Thing Vibration Sensor"
      }
  
  
  Res Aws Iot Thing Windfarm: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Thing_Windfarm.svg
        shape: image
        label: "Res Aws Iot Thing Windfarm"
      }
  
  
  Res Aws Iot Topic: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_IoT/Res_AWS_IoT_Topic.svg
        shape: image
        label: "Res Aws Iot Topic"
      }
  
}