classes: {
  
  icon_service_App_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_App_Services.svg
        shape: image
        label: "icon_service_App_Services"
      }
  
  icon_service_Azure_Red_Hat_OpenShift: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_Azure_Red_Hat_OpenShift.svg
        shape: image
        label: "icon_service_Azure_Red_Hat_OpenShift"
      }
  
  icon_service_Batch_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_Batch_Accounts.svg
        shape: image
        label: "icon_service_Batch_Accounts"
      }
  
  icon_service_Container_Instances: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_Container_Instances.svg
        shape: image
        label: "icon_service_Container_Instances"
      }
  
  icon_service_Container_Registries: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_Container_Registries.svg
        shape: image
        label: "icon_service_Container_Registries"
      }
  
  icon_service_Kubernetes_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_Kubernetes_Services.svg
        shape: image
        label: "icon_service_Kubernetes_Services"
      }
  
  icon_service_Service_Fabric_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/containers/icon_service_Service_Fabric_Clusters.svg
        shape: image
        label: "icon_service_Service_Fabric_Clusters"
      }
  
}