classes: {
  
  
  Res Amazon Cloudfront Download Distribution: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_CloudFront_Download_Distribution.svg
        shape: image
        label: "Res Amazon Cloudfront Download Distribution"
      }
  
  
  Res Amazon Cloudfront Edge Location: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_CloudFront_Edge_Location.svg
        shape: image
        label: "Res Amazon Cloudfront Edge Location"
      }
  
  
  Res Amazon Cloudfront Functions: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_CloudFront_Functions.svg
        shape: image
        label: "Res Amazon Cloudfront Functions"
      }
  
  
  Res Amazon Cloudfront Streaming Distribution: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_CloudFront_Streaming_Distribution.svg
        shape: image
        label: "Res Amazon Cloudfront Streaming Distribution"
      }
  
  
  Res Amazon Route  Hosted Zone: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Hosted_Zone.svg
        shape: image
        label: "Res Amazon Route  Hosted Zone"
      }
  
  
  Res Amazon Route  Readiness Checks: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Readiness_Checks.svg
        shape: image
        label: "Res Amazon Route  Readiness Checks"
      }
  
  
  Res Amazon Route  Resolver: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Resolver.svg
        shape: image
        label: "Res Amazon Route  Resolver"
      }
  
  
  Res Amazon Route  Resolver Dns Firewall: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Resolver_DNS_Firewall.svg
        shape: image
        label: "Res Amazon Route  Resolver Dns Firewall"
      }
  
  
  Res Amazon Route  Resolver Query Logging: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Resolver_Query_Logging.svg
        shape: image
        label: "Res Amazon Route  Resolver Query Logging"
      }
  
  
  Res Amazon Route  Route Table: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Route_Table.svg
        shape: image
        label: "Res Amazon Route  Route Table"
      }
  
  
  Res Amazon Route  Route  Application Recovery Controller: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Route__Application_Recovery_Controller.svg
        shape: image
        label: "Res Amazon Route  Route  Application Recovery Controller"
      }
  
  
  Res Amazon Route  Routing Controls: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_Route__Routing_Controls.svg
        shape: image
        label: "Res Amazon Route  Routing Controls"
      }
  
  
  Res Amazon Vpc Carrier Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Carrier_Gateway.svg
        shape: image
        label: "Res Amazon Vpc Carrier Gateway"
      }
  
  
  Res Amazon Vpc Customer Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Customer_Gateway.svg
        shape: image
        label: "Res Amazon Vpc Customer Gateway"
      }
  
  
  Res Amazon Vpc Elastic Network Adapter: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Elastic_Network_Adapter.svg
        shape: image
        label: "Res Amazon Vpc Elastic Network Adapter"
      }
  
  
  Res Amazon Vpc Elastic Network Interface: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Elastic_Network_Interface.svg
        shape: image
        label: "Res Amazon Vpc Elastic Network Interface"
      }
  
  
  Res Amazon Vpc Endpoints: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Endpoints.svg
        shape: image
        label: "Res Amazon Vpc Endpoints"
      }
  
  
  Res Amazon Vpc Flow Logs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Flow_Logs.svg
        shape: image
        label: "Res Amazon Vpc Flow Logs"
      }
  
  
  Res Amazon Vpc Internet Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Internet_Gateway.svg
        shape: image
        label: "Res Amazon Vpc Internet Gateway"
      }
  
  
  Res Amazon Vpc Nat Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_NAT_Gateway.svg
        shape: image
        label: "Res Amazon Vpc Nat Gateway"
      }
  
  
  Res Amazon Vpc Network Access Analyzer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Network_Access_Analyzer.svg
        shape: image
        label: "Res Amazon Vpc Network Access Analyzer"
      }
  
  
  Res Amazon Vpc Network Access Control List: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Network_Access_Control_List.svg
        shape: image
        label: "Res Amazon Vpc Network Access Control List"
      }
  
  
  Res Amazon Vpc Peering Connection: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Peering_Connection.svg
        shape: image
        label: "Res Amazon Vpc Peering Connection"
      }
  
  
  Res Amazon Vpc Reachability Analyzer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Reachability_Analyzer.svg
        shape: image
        label: "Res Amazon Vpc Reachability Analyzer"
      }
  
  
  Res Amazon Vpc Router: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Router.svg
        shape: image
        label: "Res Amazon Vpc Router"
      }
  
  
  Res Amazon Vpc Traffic Mirroring: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Traffic_Mirroring.svg
        shape: image
        label: "Res Amazon Vpc Traffic Mirroring"
      }
  
  
  Res Amazon Vpc Virtual Private Cloud Vpc: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_Virtual_private_cloud_VPC.svg
        shape: image
        label: "Res Amazon Vpc Virtual Private Cloud Vpc"
      }
  
  
  Res Amazon Vpc Vpn Connection: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_VPN_Connection.svg
        shape: image
        label: "Res Amazon Vpc Vpn Connection"
      }
  
  
  Res Amazon Vpc Vpn Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Amazon_VPC_VPN_Gateway.svg
        shape: image
        label: "Res Amazon Vpc Vpn Gateway"
      }
  
  
  Res Aws App Mesh Mesh: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_App_Mesh_Mesh.svg
        shape: image
        label: "Res Aws App Mesh Mesh"
      }
  
  
  Res Aws App Mesh Virtual Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_App_Mesh_Virtual_Gateway.svg
        shape: image
        label: "Res Aws App Mesh Virtual Gateway"
      }
  
  
  Res Aws App Mesh Virtual Node: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_App_Mesh_Virtual_Node.svg
        shape: image
        label: "Res Aws App Mesh Virtual Node"
      }
  
  
  Res Aws App Mesh Virtual Router: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_App_Mesh_Virtual_Router.svg
        shape: image
        label: "Res Aws App Mesh Virtual Router"
      }
  
  
  Res Aws App Mesh Virtual Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_App_Mesh_Virtual_Service.svg
        shape: image
        label: "Res Aws App Mesh Virtual Service"
      }
  
  
  Res Aws Cloud Map Namespace: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Cloud_Map_Namespace.svg
        shape: image
        label: "Res Aws Cloud Map Namespace"
      }
  
  
  Res Aws Cloud Map Resource: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Cloud_Map_Resource.svg
        shape: image
        label: "Res Aws Cloud Map Resource"
      }
  
  
  Res Aws Cloud Map Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Cloud_Map_Service.svg
        shape: image
        label: "Res Aws Cloud Map Service"
      }
  
  
  Res Aws Cloud Wan Core Network Edge: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Cloud_WAN_Core_Network_Edge.svg
        shape: image
        label: "Res Aws Cloud Wan Core Network Edge"
      }
  
  
  Res Aws Cloud Wan Segment Network: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Cloud_WAN_Segment_Network.svg
        shape: image
        label: "Res Aws Cloud Wan Segment Network"
      }
  
  
  Res Aws Cloud Wan Transit Gateway Route Table Attachment: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Cloud_WAN_Transit_Gateway_Route_Table_Attachment.svg
        shape: image
        label: "Res Aws Cloud Wan Transit Gateway Route Table Attachment"
      }
  
  
  Res Aws Direct Connect Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Direct_Connect_Gateway.svg
        shape: image
        label: "Res Aws Direct Connect Gateway"
      }
  
  
  Res Aws Transit Gateway Attachment: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_AWS_Transit_Gateway_Attachment.svg
        shape: image
        label: "Res Aws Transit Gateway Attachment"
      }
  
  
  Res Elastic Load Balancing Application Load Balancer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Elastic_Load_Balancing_Application_Load_Balancer.svg
        shape: image
        label: "Res Elastic Load Balancing Application Load Balancer"
      }
  
  
  Res Elastic Load Balancing Classic Load Balancer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Elastic_Load_Balancing_Classic_Load_Balancer.svg
        shape: image
        label: "Res Elastic Load Balancing Classic Load Balancer"
      }
  
  
  Res Elastic Load Balancing Gateway Load Balancer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Elastic_Load_Balancing_Gateway_Load_Balancer.svg
        shape: image
        label: "Res Elastic Load Balancing Gateway Load Balancer"
      }
  
  
  Res Elastic Load Balancing Network Load Balancer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Networking-Content-Delivery/Res_Elastic_Load_Balancing_Network_Load_Balancer.svg
        shape: image
        label: "Res Elastic Load Balancing Network Load Balancer"
      }
  
}