classes: {
  
  
  Network 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Globes/Network 2.svg
        shape: image
        label: "Network 2"
      }
  
  
  Network 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Globes/Network 3.svg
        shape: image
        label: "Network 3"
      }
  
  
  Network 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Globes/Network 4.svg
        shape: image
        label: "Network 4"
      }
  
  
  Network 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Globes/Network 5.svg
        shape: image
        label: "Network 5"
      }
  
  
  Planet: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Globes/Planet.svg
        shape: image
        label: "Planet"
      }
  
}