classes: {
  
  icon_service_All_Resources: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_All_Resources.svg
        shape: image
        label: "icon_service_All_Resources"
      }
  
  icon_service_Backlog: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Backlog.svg
        shape: image
        label: "icon_service_Backlog"
      }
  
  icon_service_Biz_Talk: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Biz_Talk.svg
        shape: image
        label: "icon_service_Biz_Talk"
      }
  
  icon_service_Blob_Block: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Blob_Block.svg
        shape: image
        label: "icon_service_Blob_Block"
      }
  
  icon_service_Blob_Page: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Blob_Page.svg
        shape: image
        label: "icon_service_Blob_Page"
      }
  
  icon_service_Branch: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Branch.svg
        shape: image
        label: "icon_service_Branch"
      }
  
  icon_service_Browser: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Browser.svg
        shape: image
        label: "icon_service_Browser"
      }
  
  icon_service_Bug: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Bug.svg
        shape: image
        label: "icon_service_Bug"
      }
  
  icon_service_Builds: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Builds.svg
        shape: image
        label: "icon_service_Builds"
      }
  
  icon_service_Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cache.svg
        shape: image
        label: "icon_service_Cache"
      }
  
  icon_service_Code: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Code.svg
        shape: image
        label: "icon_service_Code"
      }
  
  icon_service_Commit: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Commit.svg
        shape: image
        label: "icon_service_Commit"
      }
  
  icon_service_Controls: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Controls.svg
        shape: image
        label: "icon_service_Controls"
      }
  
  icon_service_Controls_Horizontal: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Controls_Horizontal.svg
        shape: image
        label: "icon_service_Controls_Horizontal"
      }
  
  icon_service_Cost_Alerts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cost_Alerts.svg
        shape: image
        label: "icon_service_Cost_Alerts"
      }
  
  icon_service_Cost_Analysis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cost_Analysis.svg
        shape: image
        label: "icon_service_Cost_Analysis"
      }
  
  icon_service_Cost_Budgets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cost_Budgets.svg
        shape: image
        label: "icon_service_Cost_Budgets"
      }
  
  icon_service_Cost_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cost_Management.svg
        shape: image
        label: "icon_service_Cost_Management"
      }
  
  icon_service_Cost_Management_and_Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cost_Management_and_Billing.svg
        shape: image
        label: "icon_service_Cost_Management_and_Billing"
      }
  
  icon_service_Counter: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Counter.svg
        shape: image
        label: "icon_service_Counter"
      }
  
  icon_service_Cubes: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Cubes.svg
        shape: image
        label: "icon_service_Cubes"
      }
  
  icon_service_Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Dashboard.svg
        shape: image
        label: "icon_service_Dashboard"
      }
  
  icon_service_Dev_Console: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Dev_Console.svg
        shape: image
        label: "icon_service_Dev_Console"
      }
  
  icon_service_Download: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Download.svg
        shape: image
        label: "icon_service_Download"
      }
  
  icon_service_Error: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Error.svg
        shape: image
        label: "icon_service_Error"
      }
  
  icon_service_Extensions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Extensions.svg
        shape: image
        label: "icon_service_Extensions"
      }
  
  icon_service_Feature_Previews: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Feature_Previews.svg
        shape: image
        label: "icon_service_Feature_Previews"
      }
  
  icon_service_File: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_File.svg
        shape: image
        label: "icon_service_File"
      }
  
  icon_service_Files: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Files.svg
        shape: image
        label: "icon_service_Files"
      }
  
  icon_service_Folder_Blank: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Folder_Blank.svg
        shape: image
        label: "icon_service_Folder_Blank"
      }
  
  icon_service_Folder_Website: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Folder_Website.svg
        shape: image
        label: "icon_service_Folder_Website"
      }
  
  icon_service_Free_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Free_Services.svg
        shape: image
        label: "icon_service_Free_Services"
      }
  
  icon_service_FTP: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_FTP.svg
        shape: image
        label: "icon_service_FTP"
      }
  
  icon_service_Gear: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Gear.svg
        shape: image
        label: "icon_service_Gear"
      }
  
  icon_service_Globe_Error: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Globe_Error.svg
        shape: image
        label: "icon_service_Globe_Error"
      }
  
  icon_service_Globe_Success: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Globe_Success.svg
        shape: image
        label: "icon_service_Globe_Success"
      }
  
  icon_service_Globe_Warning: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Globe_Warning.svg
        shape: image
        label: "icon_service_Globe_Warning"
      }
  
  icon_service_Guide: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Guide.svg
        shape: image
        label: "icon_service_Guide"
      }
  
  icon_service_Heart: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Heart.svg
        shape: image
        label: "icon_service_Heart"
      }
  
  icon_service_Help_and_Support: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Help_and_Support.svg
        shape: image
        label: "icon_service_Help_and_Support"
      }
  
  icon_service_Image: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Image.svg
        shape: image
        label: "icon_service_Image"
      }
  
  icon_service_Information: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Information.svg
        shape: image
        label: "icon_service_Information"
      }
  
  icon_service_Input_Output: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Input_Output.svg
        shape: image
        label: "icon_service_Input_Output"
      }
  
  icon_service_Journey_Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Journey_Hub.svg
        shape: image
        label: "icon_service_Journey_Hub"
      }
  
  icon_service_Launch_Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Launch_Portal.svg
        shape: image
        label: "icon_service_Launch_Portal"
      }
  
  icon_service_Learn: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Learn.svg
        shape: image
        label: "icon_service_Learn"
      }
  
  icon_service_Load_Test: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Load_Test.svg
        shape: image
        label: "icon_service_Load_Test"
      }
  
  icon_service_Location: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Location.svg
        shape: image
        label: "icon_service_Location"
      }
  
  icon_service_Log_Streaming: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Log_Streaming.svg
        shape: image
        label: "icon_service_Log_Streaming"
      }
  
  icon_service_Management_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Management_Groups.svg
        shape: image
        label: "icon_service_Management_Groups"
      }
  
  icon_service_Management_Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Management_Portal.svg
        shape: image
        label: "icon_service_Management_Portal"
      }
  
  icon_service_Marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Marketplace.svg
        shape: image
        label: "icon_service_Marketplace"
      }
  
  icon_service_Marketplace_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Marketplace_Management.svg
        shape: image
        label: "icon_service_Marketplace_Management"
      }
  
  icon_service_Media: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Media.svg
        shape: image
        label: "icon_service_Media"
      }
  
  icon_service_Media_File: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Media_File.svg
        shape: image
        label: "icon_service_Media_File"
      }
  
  icon_service_Mobile: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Mobile.svg
        shape: image
        label: "icon_service_Mobile"
      }
  
  icon_service_Mobile_Engagement: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Mobile_Engagement.svg
        shape: image
        label: "icon_service_Mobile_Engagement"
      }
  
  icon_service_Module: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Module.svg
        shape: image
        label: "icon_service_Module"
      }
  
  icon_service_Power: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Power.svg
        shape: image
        label: "icon_service_Power"
      }
  
  icon_service_Powershell: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Powershell.svg
        shape: image
        label: "icon_service_Powershell"
      }
  
  icon_service_Power_Up: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Power_Up.svg
        shape: image
        label: "icon_service_Power_Up"
      }
  
  icon_service_Preview_Features: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Preview_Features.svg
        shape: image
        label: "icon_service_Preview_Features"
      }
  
  icon_service_Process_Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Process_Explorer.svg
        shape: image
        label: "icon_service_Process_Explorer"
      }
  
  icon_service_Production_Ready_Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Production_Ready_Database.svg
        shape: image
        label: "icon_service_Production_Ready_Database"
      }
  
  icon_service_Quickstart_Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Quickstart_Center.svg
        shape: image
        label: "icon_service_Quickstart_Center"
      }
  
  icon_service_Recent: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Recent.svg
        shape: image
        label: "icon_service_Recent"
      }
  
  icon_service_Region_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Region_Management.svg
        shape: image
        label: "icon_service_Region_Management"
      }
  
  icon_service_Reservations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Reservations.svg
        shape: image
        label: "icon_service_Reservations"
      }
  
  icon_service_Resource_Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Resource_Explorer.svg
        shape: image
        label: "icon_service_Resource_Explorer"
      }
  
  icon_service_Resource_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Resource_Groups.svg
        shape: image
        label: "icon_service_Resource_Groups"
      }
  
  icon_service_Resource_Group_List: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Resource_Group_List.svg
        shape: image
        label: "icon_service_Resource_Group_List"
      }
  
  icon_service_Resource_Linked: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Resource_Linked.svg
        shape: image
        label: "icon_service_Resource_Linked"
      }
  
  icon_service_Scheduler: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Scheduler.svg
        shape: image
        label: "icon_service_Scheduler"
      }
  
  icon_service_Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Search.svg
        shape: image
        label: "icon_service_Search"
      }
  
  icon_service_Search_Grid: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Search_Grid.svg
        shape: image
        label: "icon_service_Search_Grid"
      }
  
  icon_service_Server_Farm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Server_Farm.svg
        shape: image
        label: "icon_service_Server_Farm"
      }
  
  icon_service_Service_Health: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Service_Health.svg
        shape: image
        label: "icon_service_Service_Health"
      }
  
  icon_service_SSD: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_SSD.svg
        shape: image
        label: "icon_service_SSD"
      }
  
  icon_service_Storage_Azure_Files: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Storage_Azure_Files.svg
        shape: image
        label: "icon_service_Storage_Azure_Files"
      }
  
  icon_service_Storage_Container: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Storage_Container.svg
        shape: image
        label: "icon_service_Storage_Container"
      }
  
  icon_service_Storage_Queue: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Storage_Queue.svg
        shape: image
        label: "icon_service_Storage_Queue"
      }
  
  icon_service_Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Subscriptions.svg
        shape: image
        label: "icon_service_Subscriptions"
      }
  
  icon_service_Table: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Table.svg
        shape: image
        label: "icon_service_Table"
      }
  
  icon_service_Tag: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Tag.svg
        shape: image
        label: "icon_service_Tag"
      }
  
  icon_service_Tags: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Tags.svg
        shape: image
        label: "icon_service_Tags"
      }
  
  icon_service_Templates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Templates.svg
        shape: image
        label: "icon_service_Templates"
      }
  
  icon_service_TFS_VC_Repository: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_TFS_VC_Repository.svg
        shape: image
        label: "icon_service_TFS_VC_Repository"
      }
  
  icon_service_Toolbox: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Toolbox.svg
        shape: image
        label: "icon_service_Toolbox"
      }
  
  icon_service_Troubleshoot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Troubleshoot.svg
        shape: image
        label: "icon_service_Troubleshoot"
      }
  
  icon_service_Versions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Versions.svg
        shape: image
        label: "icon_service_Versions"
      }
  
  icon_service_Website_Power: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Website_Power.svg
        shape: image
        label: "icon_service_Website_Power"
      }
  
  icon_service_Website_Staging: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Website_Staging.svg
        shape: image
        label: "icon_service_Website_Staging"
      }
  
  icon_service_Web_Slots: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Web_Slots.svg
        shape: image
        label: "icon_service_Web_Slots"
      }
  
  icon_service_Web_Test: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Web_Test.svg
        shape: image
        label: "icon_service_Web_Test"
      }
  
  icon_service_Workbooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Workbooks.svg
        shape: image
        label: "icon_service_Workbooks"
      }
  
  icon_service_Workflow: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/icon_service_Workflow.svg
        shape: image
        label: "icon_service_Workflow"
      }
  
}