classes: {
  
  
  All Resources: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/All_Resources.svg
        shape: image
        label: "All Resources"
      }
  
  
  Backlog: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Backlog.svg
        shape: image
        label: "Backlog"
      }
  
  
  Biz Talk: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Biz_Talk.svg
        shape: image
        label: "Biz Talk"
      }
  
  
  Blob Block: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Blob_Block.svg
        shape: image
        label: "Blob Block"
      }
  
  
  Blob Page: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Blob_Page.svg
        shape: image
        label: "Blob Page"
      }
  
  
  Branch: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Branch.svg
        shape: image
        label: "Branch"
      }
  
  
  Browser: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Browser.svg
        shape: image
        label: "Browser"
      }
  
  
  Bug: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Bug.svg
        shape: image
        label: "Bug"
      }
  
  
  Builds: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Builds.svg
        shape: image
        label: "Builds"
      }
  
  
  Cache: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cache.svg
        shape: image
        label: "Cache"
      }
  
  
  Code: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Code.svg
        shape: image
        label: "Code"
      }
  
  
  Commit: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Commit.svg
        shape: image
        label: "Commit"
      }
  
  
  Controls: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Controls.svg
        shape: image
        label: "Controls"
      }
  
  
  Controls Horizontal: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Controls_Horizontal.svg
        shape: image
        label: "Controls Horizontal"
      }
  
  
  Cost Alerts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cost_Alerts.svg
        shape: image
        label: "Cost Alerts"
      }
  
  
  Cost Analysis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cost_Analysis.svg
        shape: image
        label: "Cost Analysis"
      }
  
  
  Cost Budgets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cost_Budgets.svg
        shape: image
        label: "Cost Budgets"
      }
  
  
  Cost Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cost_Management.svg
        shape: image
        label: "Cost Management"
      }
  
  
  Cost Management And Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cost_Management_and_Billing.svg
        shape: image
        label: "Cost Management And Billing"
      }
  
  
  Counter: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Counter.svg
        shape: image
        label: "Counter"
      }
  
  
  Cubes: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Cubes.svg
        shape: image
        label: "Cubes"
      }
  
  
  Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Dashboard.svg
        shape: image
        label: "Dashboard"
      }
  
  
  Dev Console: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Dev_Console.svg
        shape: image
        label: "Dev Console"
      }
  
  
  Download: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Download.svg
        shape: image
        label: "Download"
      }
  
  
  Error: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Error.svg
        shape: image
        label: "Error"
      }
  
  
  Extensions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Extensions.svg
        shape: image
        label: "Extensions"
      }
  
  
  Feature Previews: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Feature_Previews.svg
        shape: image
        label: "Feature Previews"
      }
  
  
  File: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/File.svg
        shape: image
        label: "File"
      }
  
  
  Files: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Files.svg
        shape: image
        label: "Files"
      }
  
  
  Folder Blank: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Folder_Blank.svg
        shape: image
        label: "Folder Blank"
      }
  
  
  Folder Website: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Folder_Website.svg
        shape: image
        label: "Folder Website"
      }
  
  
  Free Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Free_Services.svg
        shape: image
        label: "Free Services"
      }
  
  
  Ftp: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/FTP.svg
        shape: image
        label: "Ftp"
      }
  
  
  Gear: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Gear.svg
        shape: image
        label: "Gear"
      }
  
  
  Globe Error: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Globe_Error.svg
        shape: image
        label: "Globe Error"
      }
  
  
  Globe Success: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Globe_Success.svg
        shape: image
        label: "Globe Success"
      }
  
  
  Globe Warning: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Globe_Warning.svg
        shape: image
        label: "Globe Warning"
      }
  
  
  Guide: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Guide.svg
        shape: image
        label: "Guide"
      }
  
  
  Heart: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Heart.svg
        shape: image
        label: "Heart"
      }
  
  
  Help And Support: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Help_and_Support.svg
        shape: image
        label: "Help And Support"
      }
  
  
  Image: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Image.svg
        shape: image
        label: "Image"
      }
  
  
  Information: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Information.svg
        shape: image
        label: "Information"
      }
  
  
  Input Output: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Input_Output.svg
        shape: image
        label: "Input Output"
      }
  
  
  Journey Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Journey_Hub.svg
        shape: image
        label: "Journey Hub"
      }
  
  
  Launch Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Launch_Portal.svg
        shape: image
        label: "Launch Portal"
      }
  
  
  Learn: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Learn.svg
        shape: image
        label: "Learn"
      }
  
  
  Load Test: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Load_Test.svg
        shape: image
        label: "Load Test"
      }
  
  
  Location: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Location.svg
        shape: image
        label: "Location"
      }
  
  
  Log Streaming: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Log_Streaming.svg
        shape: image
        label: "Log Streaming"
      }
  
  
  Management Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Management_Groups.svg
        shape: image
        label: "Management Groups"
      }
  
  
  Management Portal: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Management_Portal.svg
        shape: image
        label: "Management Portal"
      }
  
  
  Marketplace: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Marketplace.svg
        shape: image
        label: "Marketplace"
      }
  
  
  Marketplace Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Marketplace_Management.svg
        shape: image
        label: "Marketplace Management"
      }
  
  
  Media: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Media.svg
        shape: image
        label: "Media"
      }
  
  
  Media File: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Media_File.svg
        shape: image
        label: "Media File"
      }
  
  
  Mobile: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Mobile.svg
        shape: image
        label: "Mobile"
      }
  
  
  Mobile Engagement: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Mobile_Engagement.svg
        shape: image
        label: "Mobile Engagement"
      }
  
  
  Module: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Module.svg
        shape: image
        label: "Module"
      }
  
  
  Power: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Power.svg
        shape: image
        label: "Power"
      }
  
  
  Powershell: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Powershell.svg
        shape: image
        label: "Powershell"
      }
  
  
  Power Up: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Power_Up.svg
        shape: image
        label: "Power Up"
      }
  
  
  Preview Features: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Preview_Features.svg
        shape: image
        label: "Preview Features"
      }
  
  
  Process Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Process_Explorer.svg
        shape: image
        label: "Process Explorer"
      }
  
  
  Production Ready Database: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Production_Ready_Database.svg
        shape: image
        label: "Production Ready Database"
      }
  
  
  Quickstart Center: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Quickstart_Center.svg
        shape: image
        label: "Quickstart Center"
      }
  
  
  Recent: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Recent.svg
        shape: image
        label: "Recent"
      }
  
  
  Region Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Region_Management.svg
        shape: image
        label: "Region Management"
      }
  
  
  Reservations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Reservations.svg
        shape: image
        label: "Reservations"
      }
  
  
  Resource Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Resource_Explorer.svg
        shape: image
        label: "Resource Explorer"
      }
  
  
  Resource Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Resource_Groups.svg
        shape: image
        label: "Resource Groups"
      }
  
  
  Resource Group List: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Resource_Group_List.svg
        shape: image
        label: "Resource Group List"
      }
  
  
  Resource Linked: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Resource_Linked.svg
        shape: image
        label: "Resource Linked"
      }
  
  
  Scheduler: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Scheduler.svg
        shape: image
        label: "Scheduler"
      }
  
  
  Search: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Search.svg
        shape: image
        label: "Search"
      }
  
  
  Search Grid: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Search_Grid.svg
        shape: image
        label: "Search Grid"
      }
  
  
  Server Farm: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Server_Farm.svg
        shape: image
        label: "Server Farm"
      }
  
  
  Service Health: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Service_Health.svg
        shape: image
        label: "Service Health"
      }
  
  
  Ssd: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/SSD.svg
        shape: image
        label: "Ssd"
      }
  
  
  Storage Azure Files: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Storage_Azure_Files.svg
        shape: image
        label: "Storage Azure Files"
      }
  
  
  Storage Container: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Storage_Container.svg
        shape: image
        label: "Storage Container"
      }
  
  
  Storage Queue: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Storage_Queue.svg
        shape: image
        label: "Storage Queue"
      }
  
  
  Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Subscriptions.svg
        shape: image
        label: "Subscriptions"
      }
  
  
  Table: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Table.svg
        shape: image
        label: "Table"
      }
  
  
  Tag: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Tag.svg
        shape: image
        label: "Tag"
      }
  
  
  Tags: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Tags.svg
        shape: image
        label: "Tags"
      }
  
  
  Templates: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Templates.svg
        shape: image
        label: "Templates"
      }
  
  
  Tfs Vc Repository: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/TFS_VC_Repository.svg
        shape: image
        label: "Tfs Vc Repository"
      }
  
  
  Toolbox: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Toolbox.svg
        shape: image
        label: "Toolbox"
      }
  
  
  Troubleshoot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Troubleshoot.svg
        shape: image
        label: "Troubleshoot"
      }
  
  
  Versions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Versions.svg
        shape: image
        label: "Versions"
      }
  
  
  Website Power: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Website_Power.svg
        shape: image
        label: "Website Power"
      }
  
  
  Website Staging: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Website_Staging.svg
        shape: image
        label: "Website Staging"
      }
  
  
  Web Slots: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Web_Slots.svg
        shape: image
        label: "Web Slots"
      }
  
  
  Web Test: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Web_Test.svg
        shape: image
        label: "Web Test"
      }
  
  
  Workbooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Workbooks.svg
        shape: image
        label: "Workbooks"
      }
  
  
  Workflow: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/general/Workflow.svg
        shape: image
        label: "Workflow"
      }
  
}