classes: {
  
  
  Res Amazon Devops Guru Insights: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_DevOps_Guru_Insights.svg
        shape: image
        label: "Res Amazon Devops Guru Insights"
      }
  
  
  Res Amazon Rekognition Image: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_Rekognition_Image.svg
        shape: image
        label: "Res Amazon Rekognition Image"
      }
  
  
  Res Amazon Rekognition Video: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_Rekognition_Video.svg
        shape: image
        label: "Res Amazon Rekognition Video"
      }
  
  
  Res Amazon Sagemaker Canvas: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_SageMaker_Canvas.svg
        shape: image
        label: "Res Amazon Sagemaker Canvas"
      }
  
  
  Res Amazon Sagemaker Geospatial Ml: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_SageMaker_Geospatial_ML.svg
        shape: image
        label: "Res Amazon Sagemaker Geospatial Ml"
      }
  
  
  Res Amazon Sagemaker Model: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_SageMaker_Model.svg
        shape: image
        label: "Res Amazon Sagemaker Model"
      }
  
  
  Res Amazon Sagemaker Notebook: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_SageMaker_Notebook.svg
        shape: image
        label: "Res Amazon Sagemaker Notebook"
      }
  
  
  Res Amazon Sagemaker Shadow Testing: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_SageMaker_Shadow_Testing.svg
        shape: image
        label: "Res Amazon Sagemaker Shadow Testing"
      }
  
  
  Res Amazon Sagemaker Train: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_SageMaker_Train.svg
        shape: image
        label: "Res Amazon Sagemaker Train"
      }
  
  
  Res Amazon Textract Analyze Lending: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Machine-Learning/Res_Amazon_Textract_Analyze_Lending.svg
        shape: image
        label: "Res Amazon Textract Analyze Lending"
      }
  
}