classes: {
  
  
  Award: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Award.svg
        shape: image
        label: "Award"
      }
  
  
  Document 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Document 5.svg
        shape: image
        label: "Document 5"
      }
  
  
  Documents 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Documents 1.svg
        shape: image
        label: "Documents 1"
      }
  
  
  Documents 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Documents 2.svg
        shape: image
        label: "Documents 2"
      }
  
  
  Documents 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Documents 3.svg
        shape: image
        label: "Documents 3"
      }
  
  
  Increase 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Increase 3.svg
        shape: image
        label: "Increase 3"
      }
  
  
  Prize: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Prize.svg
        shape: image
        label: "Prize"
      }
  
  
  Sign: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Sign.svg
        shape: image
        label: "Sign"
      }
  
  
  Writing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Documents/Writing.svg
        shape: image
        label: "Writing"
      }
  
}