classes: {
  
  
  Amazon Managed Blockchain: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Blockchain/Amazon_Managed_Blockchain.svg
        shape: image
        label: "Amazon Managed Blockchain"
      }
  
  
  Amazon Quantum Ledger Database: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Blockchain/Amazon_Quantum_Ledger_Database.svg
        shape: image
        label: "Amazon Quantum Ledger Database"
      }
  
}