classes: {
  
  icon_service_Azure_Cosmos_DB: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Azure_Cosmos_DB.svg
        shape: image
        label: "icon_service_Azure_Cosmos_DB"
      }
  
  icon_service_Azure_Databox_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Azure_Databox_Gateway.svg
        shape: image
        label: "icon_service_Azure_Databox_Gateway"
      }
  
  icon_service_Azure_Maps_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Azure_Maps_Accounts.svg
        shape: image
        label: "icon_service_Azure_Maps_Accounts"
      }
  
  icon_service_Azure_Stack: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Azure_Stack.svg
        shape: image
        label: "icon_service_Azure_Stack"
      }
  
  icon_service_Device_Provisioning_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Device_Provisioning_Services.svg
        shape: image
        label: "icon_service_Device_Provisioning_Services"
      }
  
  icon_service_Digital_Twins: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Digital_Twins.svg
        shape: image
        label: "icon_service_Digital_Twins"
      }
  
  icon_service_Event_Grid_Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Event_Grid_Subscriptions.svg
        shape: image
        label: "icon_service_Event_Grid_Subscriptions"
      }
  
  icon_service_Event_Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Event_Hubs.svg
        shape: image
        label: "icon_service_Event_Hubs"
      }
  
  icon_service_Event_Hub_Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Event_Hub_Clusters.svg
        shape: image
        label: "icon_service_Event_Hub_Clusters"
      }
  
  icon_service_Function_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Function_Apps.svg
        shape: image
        label: "icon_service_Function_Apps"
      }
  
  icon_service_Industrial_IoT: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Industrial_IoT.svg
        shape: image
        label: "icon_service_Industrial_IoT"
      }
  
  icon_service_IoT_Central_Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_IoT_Central_Applications.svg
        shape: image
        label: "icon_service_IoT_Central_Applications"
      }
  
  icon_service_IoT_Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_IoT_Edge.svg
        shape: image
        label: "icon_service_IoT_Edge"
      }
  
  icon_service_IoT_Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_IoT_Hub.svg
        shape: image
        label: "icon_service_IoT_Hub"
      }
  
  icon_service_Logic_Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Logic_Apps.svg
        shape: image
        label: "icon_service_Logic_Apps"
      }
  
  icon_service_Machine_Learning_Studio_(Classic)_Web_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Machine_Learning_Studio_(Classic)_Web_Services.svg
        shape: image
        label: "icon_service_Machine_Learning_Studio_(Classic)_Web_Services"
      }
  
  icon_service_Machine_Learning_Studio_Web_Service_Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Machine_Learning_Studio_Web_Service_Plans.svg
        shape: image
        label: "icon_service_Machine_Learning_Studio_Web_Service_Plans"
      }
  
  icon_service_Machine_Learning_Studio_Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Machine_Learning_Studio_Workspaces.svg
        shape: image
        label: "icon_service_Machine_Learning_Studio_Workspaces"
      }
  
  icon_service_Notification_Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Notification_Hubs.svg
        shape: image
        label: "icon_service_Notification_Hubs"
      }
  
  icon_service_Notification_Hub_Namespaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Notification_Hub_Namespaces.svg
        shape: image
        label: "icon_service_Notification_Hub_Namespaces"
      }
  
  icon_service_Stream_Analytics_Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Stream_Analytics_Jobs.svg
        shape: image
        label: "icon_service_Stream_Analytics_Jobs"
      }
  
  icon_service_Time_Series_Data_Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Time_Series_Data_Sets.svg
        shape: image
        label: "icon_service_Time_Series_Data_Sets"
      }
  
  icon_service_Time_Series_Insights_Access_Policies: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Time_Series_Insights_Access_Policies.svg
        shape: image
        label: "icon_service_Time_Series_Insights_Access_Policies"
      }
  
  icon_service_Time_Series_Insights_Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Time_Series_Insights_Environments.svg
        shape: image
        label: "icon_service_Time_Series_Insights_Environments"
      }
  
  icon_service_Time_Series_Insights_Event_Sources: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Time_Series_Insights_Event_Sources.svg
        shape: image
        label: "icon_service_Time_Series_Insights_Event_Sources"
      }
  
  icon_service_Windows_Core_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/icon_service_Windows_Core_Services.svg
        shape: image
        label: "icon_service_Windows_Core_Services"
      }
  
}