classes: {
  
  
  Azure Cosmos Db: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Azure_Cosmos_DB.svg
        shape: image
        label: "Azure Cosmos Db"
      }
  
  
  Azure Databox Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Azure_Databox_Gateway.svg
        shape: image
        label: "Azure Databox Gateway"
      }
  
  
  Azure Maps Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Azure_Maps_Accounts.svg
        shape: image
        label: "Azure Maps Accounts"
      }
  
  
  Azure Stack: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Azure_Stack.svg
        shape: image
        label: "Azure Stack"
      }
  
  
  Device Provisioning Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Device_Provisioning_Services.svg
        shape: image
        label: "Device Provisioning Services"
      }
  
  
  Digital Twins: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Digital_Twins.svg
        shape: image
        label: "Digital Twins"
      }
  
  
  Event Grid Subscriptions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Event_Grid_Subscriptions.svg
        shape: image
        label: "Event Grid Subscriptions"
      }
  
  
  Event Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Event_Hubs.svg
        shape: image
        label: "Event Hubs"
      }
  
  
  Event Hub Clusters: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Event_Hub_Clusters.svg
        shape: image
        label: "Event Hub Clusters"
      }
  
  
  Function Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Function_Apps.svg
        shape: image
        label: "Function Apps"
      }
  
  
  Industrial Iot: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Industrial_IoT.svg
        shape: image
        label: "Industrial Iot"
      }
  
  
  Iot Central Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/IoT_Central_Applications.svg
        shape: image
        label: "Iot Central Applications"
      }
  
  
  Iot Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/IoT_Edge.svg
        shape: image
        label: "Iot Edge"
      }
  
  
  Iot Hub: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/IoT_Hub.svg
        shape: image
        label: "Iot Hub"
      }
  
  
  Logic Apps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Logic_Apps.svg
        shape: image
        label: "Logic Apps"
      }
  
  
  Machine Learning Studio (classic) Web Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Machine_Learning_Studio_(Classic)_Web_Services.svg
        shape: image
        label: "Machine Learning Studio (classic) Web Services"
      }
  
  
  Machine Learning Studio Web Service Plans: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Machine_Learning_Studio_Web_Service_Plans.svg
        shape: image
        label: "Machine Learning Studio Web Service Plans"
      }
  
  
  Machine Learning Studio Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Machine_Learning_Studio_Workspaces.svg
        shape: image
        label: "Machine Learning Studio Workspaces"
      }
  
  
  Notification Hubs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Notification_Hubs.svg
        shape: image
        label: "Notification Hubs"
      }
  
  
  Notification Hub Namespaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Notification_Hub_Namespaces.svg
        shape: image
        label: "Notification Hub Namespaces"
      }
  
  
  Stream Analytics Jobs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Stream_Analytics_Jobs.svg
        shape: image
        label: "Stream Analytics Jobs"
      }
  
  
  Time Series Data Sets: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Time_Series_Data_Sets.svg
        shape: image
        label: "Time Series Data Sets"
      }
  
  
  Time Series Insights Access Policies: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Time_Series_Insights_Access_Policies.svg
        shape: image
        label: "Time Series Insights Access Policies"
      }
  
  
  Time Series Insights Environments: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Time_Series_Insights_Environments.svg
        shape: image
        label: "Time Series Insights Environments"
      }
  
  
  Time Series Insights Event Sources: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Time_Series_Insights_Event_Sources.svg
        shape: image
        label: "Time Series Insights Event Sources"
      }
  
  
  Windows Core Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/iot/Windows_Core_Services.svg
        shape: image
        label: "Windows Core Services"
      }
  
}