classes: {
  
  
  Dollar: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Dollar.svg
        shape: image
        label: "Dollar"
      }
  
  
  Earnings: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Earnings.svg
        shape: image
        label: "Earnings"
      }
  
  
  Euro exchange rate: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Euro exchange rate.svg
        shape: image
        label: "Euro exchange rate"
      }
  
  
  Euro: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Euro.svg
        shape: image
        label: "Euro"
      }
  
  
  Savings 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Savings 2.svg
        shape: image
        label: "Savings 2"
      }
  
  
  Savings: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Savings.svg
        shape: image
        label: "Savings"
      }
  
  
  Shopping 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Shopping 2.svg
        shape: image
        label: "Shopping 2"
      }
  
  
  Shopping 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Money/Shopping 3.svg
        shape: image
        label: "Shopping 3"
      }
  
}