classes: {
  
  icon_service_Keys: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/menu/icon_service_Keys.svg
        shape: image
        label: "icon_service_Keys"
      }
  
}