classes: {
  
  
  Res Amazon-braket Simulator-2 48: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon-Braket_Simulator-2_48.svg
        shape: image
        label: "Res Amazon-braket Simulator-2 48"
      }
  
  
  Res Amazon-braket Simulator-3 48: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon-Braket_Simulator-3_48.svg
        shape: image
        label: "Res Amazon-braket Simulator-3 48"
      }
  
  
  Res Amazon-braket Simulator-4 48: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon-Braket_Simulator-4_48.svg
        shape: image
        label: "Res Amazon-braket Simulator-4 48"
      }
  
  
  Res Amazon Braket Chandelier: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Chandelier.svg
        shape: image
        label: "Res Amazon Braket Chandelier"
      }
  
  
  Res Amazon Braket Chip: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Chip.svg
        shape: image
        label: "Res Amazon Braket Chip"
      }
  
  
  Res Amazon Braket Embedded Simulator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Embedded_Simulator.svg
        shape: image
        label: "Res Amazon Braket Embedded Simulator"
      }
  
  
  Res Amazon Braket Managed Simulator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Managed_Simulator.svg
        shape: image
        label: "Res Amazon Braket Managed Simulator"
      }
  
  
  Res Amazon Braket Noise Simulator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Noise_Simulator.svg
        shape: image
        label: "Res Amazon Braket Noise Simulator"
      }
  
  
  Res Amazon Braket Qpu: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_QPU.svg
        shape: image
        label: "Res Amazon Braket Qpu"
      }
  
  
  Res Amazon Braket Simulator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Simulator.svg
        shape: image
        label: "Res Amazon Braket Simulator"
      }
  
  
  Res Amazon Braket Simulator : {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Simulator_.svg
        shape: image
        label: "Res Amazon Braket Simulator "
      }
  
  
  Res Amazon Braket State Vector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_State_Vector.svg
        shape: image
        label: "Res Amazon Braket State Vector"
      }
  
  
  Res Amazon Braket Tensor Network: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Quantum-Technologies/Res_Amazon_Braket_Tensor_Network.svg
        shape: image
        label: "Res Amazon Braket Tensor Network"
      }
  
}