classes: {
  
  
  Amazon Efs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_EFS.svg
        shape: image
        label: "Amazon Efs"
      }
  
  
  Amazon Elastic Block Store: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_Elastic_Block_Store.svg
        shape: image
        label: "Amazon Elastic Block Store"
      }
  
  
  Amazon File Cache: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_File_Cache.svg
        shape: image
        label: "Amazon File Cache"
      }
  
  
  Amazon Fsx: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_FSx.svg
        shape: image
        label: "Amazon Fsx"
      }
  
  
  Amazon Fsx For Lustre: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_FSx_for_Lustre.svg
        shape: image
        label: "Amazon Fsx For Lustre"
      }
  
  
  Amazon Fsx For Netapp Ontap: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_FSx_for_NetApp_ONTAP.svg
        shape: image
        label: "Amazon Fsx For Netapp Ontap"
      }
  
  
  Amazon Fsx For Openzfs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_FSx_for_OpenZFS.svg
        shape: image
        label: "Amazon Fsx For Openzfs"
      }
  
  
  Amazon Fsx For Wfs: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_FSx_for_WFS.svg
        shape: image
        label: "Amazon Fsx For Wfs"
      }
  
  
  Amazon Simple Storage Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_Simple_Storage_Service.svg
        shape: image
        label: "Amazon Simple Storage Service"
      }
  
  
  Amazon Simple Storage Service Glacier: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_Simple_Storage_Service_Glacier.svg
        shape: image
        label: "Amazon Simple Storage Service Glacier"
      }
  
  
  Amazon S On Outposts: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/Amazon_S_on_Outposts.svg
        shape: image
        label: "Amazon S On Outposts"
      }
  
  
  Aws Backup: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Backup.svg
        shape: image
        label: "Aws Backup"
      }
  
  
  Aws Elastic Disaster Recovery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Elastic_Disaster_Recovery.svg
        shape: image
        label: "Aws Elastic Disaster Recovery"
      }
  
  
  Aws Snowball: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Snowball.svg
        shape: image
        label: "Aws Snowball"
      }
  
  
  Aws Snowball Edge: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Snowball_Edge.svg
        shape: image
        label: "Aws Snowball Edge"
      }
  
  
  Aws Snowcone: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Snowcone.svg
        shape: image
        label: "Aws Snowcone"
      }
  
  
  Aws Snowmobile: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Snowmobile.svg
        shape: image
        label: "Aws Snowmobile"
      }
  
  
  Aws Storage Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Storage/AWS_Storage_Gateway.svg
        shape: image
        label: "Aws Storage Gateway"
      }
  
}