classes: {
  
  icon_service_ABS_Member: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/icon_service_ABS_Member.svg
        shape: image
        label: "icon_service_ABS_Member"
      }
  
  icon_service_Azure_Blockchain_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/icon_service_Azure_Blockchain_Service.svg
        shape: image
        label: "icon_service_Azure_Blockchain_Service"
      }
  
  icon_service_Azure_Token_Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/icon_service_Azure_Token_Service.svg
        shape: image
        label: "icon_service_Azure_Token_Service"
      }
  
  icon_service_Blockchain_Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/icon_service_Blockchain_Applications.svg
        shape: image
        label: "icon_service_Blockchain_Applications"
      }
  
  icon_service_Consortium: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/icon_service_Consortium.svg
        shape: image
        label: "icon_service_Consortium"
      }
  
  icon_service_Outbound_Connection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/icon_service_Outbound_Connection.svg
        shape: image
        label: "icon_service_Outbound_Connection"
      }
  
}