classes: {
  
  
  Abs Member: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/ABS_Member.svg
        shape: image
        label: "Abs Member"
      }
  
  
  Azure Blockchain Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/Azure_Blockchain_Service.svg
        shape: image
        label: "Azure Blockchain Service"
      }
  
  
  Azure Token Service: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/Azure_Token_Service.svg
        shape: image
        label: "Azure Token Service"
      }
  
  
  Blockchain Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/Blockchain_Applications.svg
        shape: image
        label: "Blockchain Applications"
      }
  
  
  Consortium: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/Consortium.svg
        shape: image
        label: "Consortium"
      }
  
  
  Outbound Connection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/blockchain/Outbound_Connection.svg
        shape: image
        label: "Outbound Connection"
      }
  
}