classes: {
  
  
  Building company: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Building Company.svg
        shape: image
        label: "Building company"
      }
  
  
  Company 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Company 2.svg
        shape: image
        label: "Company 2"
      }
  
  
  Company: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Company.svg
        shape: image
        label: "Company"
      }
  
  
  Court: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Court.svg
        shape: image
        label: "Court"
      }
  
  
  Home network: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Home Network.svg
        shape: image
        label: "Home network"
      }
  
  
  Home: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Home.svg
        shape: image
        label: "Home"
      }
  
  
  Warehouse 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Warehouse 2.svg
        shape: image
        label: "Warehouse 2"
      }
  
  
  Warehouse: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Buildings/Warehouse.svg
        shape: image
        label: "Warehouse"
      }
  
}