classes: {
  
  
  Amazon Gamelift: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Games/Amazon_GameLift.svg
        shape: image
        label: "Amazon Gamelift"
      }
  
  
  Amazon Gamesparks: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Games/Amazon_GameSparks.svg
        shape: image
        label: "Amazon Gamesparks"
      }
  
  
  Aws Gamekit: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Games/AWS_GameKit.svg
        shape: image
        label: "Aws Gamekit"
      }
  
  
  Open D Engine: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Games/Open_D_Engine.svg
        shape: image
        label: "Open D Engine"
      }
  
}