classes: {
  
  
  Brainstorm: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Brainstorm.svg
        shape: image
        label: "Brainstorm"
      }
  
  
  Combs: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Combs.svg
        shape: image
        label: "Combs"
      }
  
  
  Connect 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Connect 2.svg
        shape: image
        label: "Connect 2"
      }
  
  
  Connect: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Connect.svg
        shape: image
        label: "Connect"
      }
  
  
  Diwali: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Diwali.svg
        shape: image
        label: "Diwali"
      }
  
  
  Grouping: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Grouping.svg
        shape: image
        label: "Grouping"
      }
  
  
  Idea: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Idea.svg
        shape: image
        label: "Idea"
      }
  
  
  Learning: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Learning.svg
        shape: image
        label: "Learning"
      }
  
  
  Locations: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Locations.svg
        shape: image
        label: "Locations"
      }
  
  
  Locations 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Locations_1.svg
        shape: image
        label: "Locations 1"
      }
  
  
  Magic: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Magic.svg
        shape: image
        label: "Magic"
      }
  
  
  Party: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Party.svg
        shape: image
        label: "Party"
      }
  
  
  Puzzle: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Puzzle.svg
        shape: image
        label: "Puzzle"
      }
  
  
  Quallity: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Quallity.svg
        shape: image
        label: "Quallity"
      }
  
  
  Redo: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Redo.svg
        shape: image
        label: "Redo"
      }
  
  
  Repairment: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Repairment.svg
        shape: image
        label: "Repairment"
      }
  
  
  Rocket: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Rocket.svg
        shape: image
        label: "Rocket"
      }
  
  
  Shoot: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Shoot.svg
        shape: image
        label: "Shoot"
      }
  
  
  Space: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Space.svg
        shape: image
        label: "Space"
      }
  
  
  Stack: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Stack.svg
        shape: image
        label: "Stack"
      }
  
  
  Stars: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Stars.svg
        shape: image
        label: "Stars"
      }
  
  
  Virus: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Absract/Virus.svg
        shape: image
        label: "Virus"
      }
  
}