classes: {
  
  
  Connected Vehicle Platform: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/new icons/Connected_Vehicle_Platform.svg
        shape: image
        label: "Connected Vehicle Platform"
      }
  
  
  Entra Identity: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/new icons/Entra_Identity.svg
        shape: image
        label: "Entra Identity"
      }
  
}