classes: {
  
  
  Accept button: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Arrows Icons/Accept Button.svg
        shape: image
        label: "Accept button"
      }
  
  
  Arrows: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Arrows Icons/Arrows.svg
        shape: image
        label: "Arrows"
      }
  
  
  Chart: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Arrows Icons/Chart.svg
        shape: image
        label: "Chart"
      }
  
  
  Play button: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Arrows Icons/Play Button.svg
        shape: image
        label: "Play button"
      }
  
  
  Quote: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Arrows Icons/Quote.svg
        shape: image
        label: "Quote"
      }
  
  
  Reverse: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Arrows Icons/Reverse.svg
        shape: image
        label: "Reverse"
      }
  
}