classes: {
  
  
  Amazon Cloud Directory: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Cloud_Directory.svg
        shape: image
        label: "Amazon Cloud Directory"
      }
  
  
  Amazon Cognito: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Cognito.svg
        shape: image
        label: "Amazon Cognito"
      }
  
  
  Amazon Detective: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Detective.svg
        shape: image
        label: "Amazon Detective"
      }
  
  
  Amazon Guardduty: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_GuardDuty.svg
        shape: image
        label: "Amazon Guardduty"
      }
  
  
  Amazon Inspector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Inspector.svg
        shape: image
        label: "Amazon Inspector"
      }
  
  
  Amazon Macie: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Macie.svg
        shape: image
        label: "Amazon Macie"
      }
  
  
  Amazon Security Lake: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Security_Lake.svg
        shape: image
        label: "Amazon Security Lake"
      }
  
  
  Amazon Verified Permissions: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/Amazon_Verified_Permissions.svg
        shape: image
        label: "Amazon Verified Permissions"
      }
  
  
  Aws Artifact: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Artifact.svg
        shape: image
        label: "Aws Artifact"
      }
  
  
  Aws Audit Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Audit_Manager.svg
        shape: image
        label: "Aws Audit Manager"
      }
  
  
  Aws Certificate Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Certificate_Manager.svg
        shape: image
        label: "Aws Certificate Manager"
      }
  
  
  Aws Cloudhsm: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_CloudHSM.svg
        shape: image
        label: "Aws Cloudhsm"
      }
  
  
  Aws Directory Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Directory_Service.svg
        shape: image
        label: "Aws Directory Service"
      }
  
  
  Aws Firewall Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Firewall_Manager.svg
        shape: image
        label: "Aws Firewall Manager"
      }
  
  
  Aws Iam Identity Center: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_IAM_Identity_Center.svg
        shape: image
        label: "Aws Iam Identity Center"
      }
  
  
  Aws Identity And Access Management: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Identity_and_Access_Management.svg
        shape: image
        label: "Aws Identity And Access Management"
      }
  
  
  Aws Key Management Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Key_Management_Service.svg
        shape: image
        label: "Aws Key Management Service"
      }
  
  
  Aws Network Firewall: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Network_Firewall.svg
        shape: image
        label: "Aws Network Firewall"
      }
  
  
  Aws Private Certificate Authority: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Private_Certificate_Authority.svg
        shape: image
        label: "Aws Private Certificate Authority"
      }
  
  
  Aws Resource Access Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Resource_Access_Manager.svg
        shape: image
        label: "Aws Resource Access Manager"
      }
  
  
  Aws Secrets Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Secrets_Manager.svg
        shape: image
        label: "Aws Secrets Manager"
      }
  
  
  Aws Security Hub: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Security_Hub.svg
        shape: image
        label: "Aws Security Hub"
      }
  
  
  Aws Shield: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Shield.svg
        shape: image
        label: "Aws Shield"
      }
  
  
  Aws Signer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_Signer.svg
        shape: image
        label: "Aws Signer"
      }
  
  
  Aws Waf: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Security-Identity-Compliance/AWS_WAF.svg
        shape: image
        label: "Aws Waf"
      }
  
}