classes: {
  
  
  24 7: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/24 7.svg
        shape: image
        label: "24 7"
      }
  
  
  Comments: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Comments.svg
        shape: image
        label: "Comments"
      }
  
  
  Conversations: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Conversations.svg
        shape: image
        label: "Conversations"
      }
  
  
  Customers 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Customers 2.svg
        shape: image
        label: "Customers 2"
      }
  
  
  Customers 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Customers 3.svg
        shape: image
        label: "Customers 3"
      }
  
  
  Customers 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Customers 4.svg
        shape: image
        label: "Customers 4"
      }
  
  
  Customers: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Customers.svg
        shape: image
        label: "Customers"
      }
  
  
  Headphones: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Headphones.svg
        shape: image
        label: "Headphones"
      }
  
  
  Locked: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Locked.svg
        shape: image
        label: "Locked"
      }
  
  
  Mail 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Mail 2.svg
        shape: image
        label: "Mail 2"
      }
  
  
  Mail 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Mail 3.svg
        shape: image
        label: "Mail 3"
      }
  
  
  Mail: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Mail.svg
        shape: image
        label: "Mail"
      }
  
  
  Megaphone: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Megaphone.svg
        shape: image
        label: "Megaphone"
      }
  
  
  Opinion: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Opinion.svg
        shape: image
        label: "Opinion"
      }
  
  
  Search: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Search.svg
        shape: image
        label: "Search"
      }
  
  
  Shopping bags: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Shopping Bags.svg
        shape: image
        label: "Shopping bags"
      }
  
  
  Shopping cart 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Shopping Cart 1.svg
        shape: image
        label: "Shopping cart 1"
      }
  
  
  Shopping cart 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Shopping Cart 2.svg
        shape: image
        label: "Shopping cart 2"
      }
  
  
  Shopping cart 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Shopping Cart 3.svg
        shape: image
        label: "Shopping cart 3"
      }
  
  
  Shopping cart 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Shopping Cart 4.svg
        shape: image
        label: "Shopping cart 4"
      }
  
  
  Wallet: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Marketing/Wallet.svg
        shape: image
        label: "Wallet"
      }
  
}