classes: {
  
  
  Res Amazon Ec Ami: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_AMI.svg
        shape: image
        label: "Res Amazon Ec Ami"
      }
  
  
  Res Amazon Ec Auto Scaling: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Auto_Scaling.svg
        shape: image
        label: "Res Amazon Ec Auto Scaling"
      }
  
  
  Res Amazon Ec Aws Microservice Extractor For .net: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_AWS_Microservice_Extractor_for_.NET.svg
        shape: image
        label: "Res Amazon Ec Aws Microservice Extractor For .net"
      }
  
  
  Res Amazon Ec Db Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_DB_Instance.svg
        shape: image
        label: "Res Amazon Ec Db Instance"
      }
  
  
  Res Amazon Ec Elastic Ip Address: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Elastic_IP_Address.svg
        shape: image
        label: "Res Amazon Ec Elastic Ip Address"
      }
  
  
  Res Amazon Ec Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Instance.svg
        shape: image
        label: "Res Amazon Ec Instance"
      }
  
  
  Res Amazon Ec Instances: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Instances.svg
        shape: image
        label: "Res Amazon Ec Instances"
      }
  
  
  Res Amazon Ec Instance With Cloudwatch: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Instance_with_CloudWatch.svg
        shape: image
        label: "Res Amazon Ec Instance With Cloudwatch"
      }
  
  
  Res Amazon Ec Rescue: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Rescue.svg
        shape: image
        label: "Res Amazon Ec Rescue"
      }
  
  
  Res Amazon Ec Spot Instance: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_Amazon_EC_Spot_Instance.svg
        shape: image
        label: "Res Amazon Ec Spot Instance"
      }
  
  
  Res Aws Elastic Beanstalk Application: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_AWS_Elastic_Beanstalk_Application.svg
        shape: image
        label: "Res Aws Elastic Beanstalk Application"
      }
  
  
  Res Aws Elastic Beanstalk Deployment: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_AWS_Elastic_Beanstalk_Deployment.svg
        shape: image
        label: "Res Aws Elastic Beanstalk Deployment"
      }
  
  
  Res Aws Lambda Lambda Function: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Compute/Res_AWS_Lambda_Lambda_Function.svg
        shape: image
        label: "Res Aws Lambda Lambda Function"
      }
  
}