classes: {
  
  icon_service_API_Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_API_Connections.svg
        shape: image
        label: "icon_service_API_Connections"
      }
  
  icon_service_API_Management_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_API_Management_Services.svg
        shape: image
        label: "icon_service_API_Management_Services"
      }
  
  icon_service_Application_Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_Application_Insights.svg
        shape: image
        label: "icon_service_Application_Insights"
      }
  
  icon_service_Azure_DevOps: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_Azure_DevOps.svg
        shape: image
        label: "icon_service_Azure_DevOps"
      }
  
  icon_service_Change_Analysis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_Change_Analysis.svg
        shape: image
        label: "icon_service_Change_Analysis"
      }
  
  icon_service_CloudTest: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_CloudTest.svg
        shape: image
        label: "icon_service_CloudTest"
      }
  
  icon_service_DevOps_Starter: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_DevOps_Starter.svg
        shape: image
        label: "icon_service_DevOps_Starter"
      }
  
  icon_service_DevTest_Labs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_DevTest_Labs.svg
        shape: image
        label: "icon_service_DevTest_Labs"
      }
  
  icon_service_Lab_Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_Lab_Accounts.svg
        shape: image
        label: "icon_service_Lab_Accounts"
      }
  
  icon_service_Lab_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_Lab_Services.svg
        shape: image
        label: "icon_service_Lab_Services"
      }
  
  icon_service_Load_Testing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/icon_service_Load_Testing.svg
        shape: image
        label: "icon_service_Load_Testing"
      }
  
}