classes: {
  
  
  Api Connections: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/API_Connections.svg
        shape: image
        label: "Api Connections"
      }
  
  
  Api Management Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/API_Management_Services.svg
        shape: image
        label: "Api Management Services"
      }
  
  
  Application Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/Application_Insights.svg
        shape: image
        label: "Application Insights"
      }
  
  
  Azure Devops: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/Azure_DevOps.svg
        shape: image
        label: "Azure Devops"
      }
  
  
  Change Analysis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/Change_Analysis.svg
        shape: image
        label: "Change Analysis"
      }
  
  
  Cloudtest: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/CloudTest.svg
        shape: image
        label: "Cloudtest"
      }
  
  
  Devops Starter: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/DevOps_Starter.svg
        shape: image
        label: "Devops Starter"
      }
  
  
  Devtest Labs: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/DevTest_Labs.svg
        shape: image
        label: "Devtest Labs"
      }
  
  
  Lab Accounts: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/Lab_Accounts.svg
        shape: image
        label: "Lab Accounts"
      }
  
  
  Lab Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/Lab_Services.svg
        shape: image
        label: "Lab Services"
      }
  
  
  Load Testing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/devops/Load_Testing.svg
        shape: image
        label: "Load Testing"
      }
  
}