classes: {
  
  
  Res Amazon-elastic-container-service Container-2 48: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon-Elastic-Container-Service_Container-2_48.svg
        shape: image
        label: "Res Amazon-elastic-container-service Container-2 48"
      }
  
  
  Res Amazon-elastic-container-service Container-3 48: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon-Elastic-Container-Service_Container-3_48.svg
        shape: image
        label: "Res Amazon-elastic-container-service Container-3 48"
      }
  
  
  Res Amazon Elastic Container Registry Image: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Registry_Image.svg
        shape: image
        label: "Res Amazon Elastic Container Registry Image"
      }
  
  
  Res Amazon Elastic Container Registry Registry: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Registry_Registry.svg
        shape: image
        label: "Res Amazon Elastic Container Registry Registry"
      }
  
  
  Res Amazon Elastic Container Service Container : {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Service_Container_.svg
        shape: image
        label: "Res Amazon Elastic Container Service Container "
      }
  
  
  Res Amazon Elastic Container Service Copiiot Cli: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Service_CopiIoT_CLI.svg
        shape: image
        label: "Res Amazon Elastic Container Service Copiiot Cli"
      }
  
  
  Res Amazon Elastic Container Service Ecs Service Connect: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Service_ECS_Service_Connect.svg
        shape: image
        label: "Res Amazon Elastic Container Service Ecs Service Connect"
      }
  
  
  Res Amazon Elastic Container Service Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Service_Service.svg
        shape: image
        label: "Res Amazon Elastic Container Service Service"
      }
  
  
  Res Amazon Elastic Container Service Task: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Container_Service_Task.svg
        shape: image
        label: "Res Amazon Elastic Container Service Task"
      }
  
  
  Res Amazon Elastic Kubernetes Service Eks On Outposts: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Containers/Res_Amazon_Elastic_Kubernetes_Service_EKS_on_Outposts.svg
        shape: image
        label: "Res Amazon Elastic Kubernetes Service Eks On Outposts"
      }
  
}