classes: {
  
  
  Amazon Cloudfront: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/Amazon_CloudFront.svg
        shape: image
        label: "Amazon Cloudfront"
      }
  
  
  Amazon Route : {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/Amazon_Route_.svg
        shape: image
        label: "Amazon Route "
      }
  
  
  Amazon Virtual Private Cloud: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/Amazon_Virtual_Private_Cloud.svg
        shape: image
        label: "Amazon Virtual Private Cloud"
      }
  
  
  Amazon Vpc Lattice: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/Amazon_VPC_Lattice.svg
        shape: image
        label: "Amazon Vpc Lattice"
      }
  
  
  Aws App Mesh: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_App_Mesh.svg
        shape: image
        label: "Aws App Mesh"
      }
  
  
  Aws Client Vpn: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Client_VPN.svg
        shape: image
        label: "Aws Client Vpn"
      }
  
  
  Aws Cloud Map: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Cloud_Map.svg
        shape: image
        label: "Aws Cloud Map"
      }
  
  
  Aws Cloud Wan: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Cloud_WAN.svg
        shape: image
        label: "Aws Cloud Wan"
      }
  
  
  Aws Direct Connect: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Direct_Connect.svg
        shape: image
        label: "Aws Direct Connect"
      }
  
  
  Aws Global Accelerator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Global_Accelerator.svg
        shape: image
        label: "Aws Global Accelerator"
      }
  
  
  Aws Privatelink: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_PrivateLink.svg
        shape: image
        label: "Aws Privatelink"
      }
  
  
  Aws Private G: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Private_G.svg
        shape: image
        label: "Aws Private G"
      }
  
  
  Aws Site To Site Vpn: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Site_to_Site_VPN.svg
        shape: image
        label: "Aws Site To Site Vpn"
      }
  
  
  Aws Transit Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Transit_Gateway.svg
        shape: image
        label: "Aws Transit Gateway"
      }
  
  
  Aws Verified Access: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/AWS_Verified_Access.svg
        shape: image
        label: "Aws Verified Access"
      }
  
  
  Elastic Load Balancing: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Networking-Content-Delivery/Elastic_Load_Balancing.svg
        shape: image
        label: "Elastic Load Balancing"
      }
  
}