classes: {
  
  
  Aad Licenses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/AAD_Licenses.svg
        shape: image
        label: "Aad Licenses"
      }
  
  
  Active Directory Connect Health: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Active_Directory_Connect_Health.svg
        shape: image
        label: "Active Directory Connect Health"
      }
  
  
  Administrative Units: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Administrative_Units.svg
        shape: image
        label: "Administrative Units"
      }
  
  
  Api Proxy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/API_Proxy.svg
        shape: image
        label: "Api Proxy"
      }
  
  
  App Registrations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/App_Registrations.svg
        shape: image
        label: "App Registrations"
      }
  
  
  Azure Active Directory: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_Active_Directory.svg
        shape: image
        label: "Azure Active Directory"
      }
  
  
  Azure Ad Bc: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_AD_BC.svg
        shape: image
        label: "Azure Ad Bc"
      }
  
  
  Azure Ad Domain Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_AD_Domain_Services.svg
        shape: image
        label: "Azure Ad Domain Services"
      }
  
  
  Azure Ad Identity Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_AD_Identity_Protection.svg
        shape: image
        label: "Azure Ad Identity Protection"
      }
  
  
  Azure Ad Privilege Identity Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_AD_Privilege_Identity_Management.svg
        shape: image
        label: "Azure Ad Privilege Identity Management"
      }
  
  
  Azure Ad Privleged Identity Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_AD_Privleged_Identity_Management.svg
        shape: image
        label: "Azure Ad Privleged Identity Management"
      }
  
  
  Azure Ad Roles And Administrators: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_AD_Roles_and_Administrators.svg
        shape: image
        label: "Azure Ad Roles And Administrators"
      }
  
  
  Azure Information Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Azure_Information_Protection.svg
        shape: image
        label: "Azure Information Protection"
      }
  
  
  Custom Azure Ad Roles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Custom_Azure_AD_Roles.svg
        shape: image
        label: "Custom Azure Ad Roles"
      }
  
  
  Enterprise Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Enterprise_Applications.svg
        shape: image
        label: "Enterprise Applications"
      }
  
  
  External Identities: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/External_Identities.svg
        shape: image
        label: "External Identities"
      }
  
  
  Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Groups.svg
        shape: image
        label: "Groups"
      }
  
  
  Identity Governance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Identity_Governance.svg
        shape: image
        label: "Identity Governance"
      }
  
  
  Managed Identities: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Managed_Identities.svg
        shape: image
        label: "Managed Identities"
      }
  
  
  Security: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Security.svg
        shape: image
        label: "Security"
      }
  
  
  Tenant Properties: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Tenant_Properties.svg
        shape: image
        label: "Tenant Properties"
      }
  
  
  Users: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Users.svg
        shape: image
        label: "Users"
      }
  
  
  User Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/User_Settings.svg
        shape: image
        label: "User Settings"
      }
  
  
  Verifiable Credentials: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/Verifiable_Credentials.svg
        shape: image
        label: "Verifiable Credentials"
      }
  
}