classes: {
  
  icon_service_AAD_Licenses: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_AAD_Licenses.svg
        shape: image
        label: "icon_service_AAD_Licenses"
      }
  
  icon_service_Active_Directory_Connect_Health: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Active_Directory_Connect_Health.svg
        shape: image
        label: "icon_service_Active_Directory_Connect_Health"
      }
  
  icon_service_Administrative_Units: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Administrative_Units.svg
        shape: image
        label: "icon_service_Administrative_Units"
      }
  
  icon_service_API_Proxy: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_API_Proxy.svg
        shape: image
        label: "icon_service_API_Proxy"
      }
  
  icon_service_App_Registrations: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_App_Registrations.svg
        shape: image
        label: "icon_service_App_Registrations"
      }
  
  icon_service_Azure_Active_Directory: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_Active_Directory.svg
        shape: image
        label: "icon_service_Azure_Active_Directory"
      }
  
  icon_service_Azure_AD_BC: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_AD_BC.svg
        shape: image
        label: "icon_service_Azure_AD_BC"
      }
  
  icon_service_Azure_AD_Domain_Services: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_AD_Domain_Services.svg
        shape: image
        label: "icon_service_Azure_AD_Domain_Services"
      }
  
  icon_service_Azure_AD_Identity_Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_AD_Identity_Protection.svg
        shape: image
        label: "icon_service_Azure_AD_Identity_Protection"
      }
  
  icon_service_Azure_AD_Privilege_Identity_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_AD_Privilege_Identity_Management.svg
        shape: image
        label: "icon_service_Azure_AD_Privilege_Identity_Management"
      }
  
  icon_service_Azure_AD_Privleged_Identity_Management: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_AD_Privleged_Identity_Management.svg
        shape: image
        label: "icon_service_Azure_AD_Privleged_Identity_Management"
      }
  
  icon_service_Azure_AD_Roles_and_Administrators: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_AD_Roles_and_Administrators.svg
        shape: image
        label: "icon_service_Azure_AD_Roles_and_Administrators"
      }
  
  icon_service_Azure_Information_Protection: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Azure_Information_Protection.svg
        shape: image
        label: "icon_service_Azure_Information_Protection"
      }
  
  icon_service_Custom_Azure_AD_Roles: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Custom_Azure_AD_Roles.svg
        shape: image
        label: "icon_service_Custom_Azure_AD_Roles"
      }
  
  icon_service_Enterprise_Applications: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Enterprise_Applications.svg
        shape: image
        label: "icon_service_Enterprise_Applications"
      }
  
  icon_service_External_Identities: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_External_Identities.svg
        shape: image
        label: "icon_service_External_Identities"
      }
  
  icon_service_Groups: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Groups.svg
        shape: image
        label: "icon_service_Groups"
      }
  
  icon_service_Identity_Governance: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Identity_Governance.svg
        shape: image
        label: "icon_service_Identity_Governance"
      }
  
  icon_service_Managed_Identities: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Managed_Identities.svg
        shape: image
        label: "icon_service_Managed_Identities"
      }
  
  icon_service_Security: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Security.svg
        shape: image
        label: "icon_service_Security"
      }
  
  icon_service_Tenant_Properties: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Tenant_Properties.svg
        shape: image
        label: "icon_service_Tenant_Properties"
      }
  
  icon_service_Users: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Users.svg
        shape: image
        label: "icon_service_Users"
      }
  
  icon_service_User_Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_User_Settings.svg
        shape: image
        label: "icon_service_User_Settings"
      }
  
  icon_service_Verifiable_Credentials: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/identity/icon_service_Verifiable_Credentials.svg
        shape: image
        label: "icon_service_Verifiable_Credentials"
      }
  
}