classes: {
  
  
  Amazon Ec: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Amazon_EC.svg
        shape: image
        label: "Amazon Ec"
      }
  
  
  Amazon Ec Auto Scaling: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Amazon_EC_Auto_Scaling.svg
        shape: image
        label: "Amazon Ec Auto Scaling"
      }
  
  
  Amazon Ec Image Builder: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Amazon_EC_Image_Builder.svg
        shape: image
        label: "Amazon Ec Image Builder"
      }
  
  
  Amazon Genomics Cli: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Amazon_Genomics_CLI.svg
        shape: image
        label: "Amazon Genomics Cli"
      }
  
  
  Amazon Lightsail: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Amazon_Lightsail.svg
        shape: image
        label: "Amazon Lightsail"
      }
  
  
  Amazon Lightsail For Research: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Amazon_Lightsail_for_Research.svg
        shape: image
        label: "Amazon Lightsail For Research"
      }
  
  
  Aws App Runner: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_App_Runner.svg
        shape: image
        label: "Aws App Runner"
      }
  
  
  Aws Batch: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Batch.svg
        shape: image
        label: "Aws Batch"
      }
  
  
  Aws Compute Optimizer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Compute_Optimizer.svg
        shape: image
        label: "Aws Compute Optimizer"
      }
  
  
  Aws Elastic Beanstalk: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Elastic_Beanstalk.svg
        shape: image
        label: "Aws Elastic Beanstalk"
      }
  
  
  Aws Lambda: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Lambda.svg
        shape: image
        label: "Aws Lambda"
      }
  
  
  Aws Local Zones: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Local_Zones.svg
        shape: image
        label: "Aws Local Zones"
      }
  
  
  Aws Nitro Enclaves: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Nitro_Enclaves.svg
        shape: image
        label: "Aws Nitro Enclaves"
      }
  
  
  Aws Outposts Family: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Outposts_family.svg
        shape: image
        label: "Aws Outposts Family"
      }
  
  
  Aws Outposts Rack: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Outposts_rack.svg
        shape: image
        label: "Aws Outposts Rack"
      }
  
  
  Aws Outposts Servers: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Outposts_servers.svg
        shape: image
        label: "Aws Outposts Servers"
      }
  
  
  Aws Parallel Cluster: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Parallel_Cluster.svg
        shape: image
        label: "Aws Parallel Cluster"
      }
  
  
  Aws Serverless Application Repository: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Serverless_Application_Repository.svg
        shape: image
        label: "Aws Serverless Application Repository"
      }
  
  
  Aws Simspace Weaver: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_SimSpace_Weaver.svg
        shape: image
        label: "Aws Simspace Weaver"
      }
  
  
  Aws Thinkbox Deadline: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Thinkbox_Deadline.svg
        shape: image
        label: "Aws Thinkbox Deadline"
      }
  
  
  Aws Thinkbox Frost: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Thinkbox_Frost.svg
        shape: image
        label: "Aws Thinkbox Frost"
      }
  
  
  Aws Thinkbox Krakatoa: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Thinkbox_Krakatoa.svg
        shape: image
        label: "Aws Thinkbox Krakatoa"
      }
  
  
  Aws Thinkbox Sequoia: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Thinkbox_Sequoia.svg
        shape: image
        label: "Aws Thinkbox Sequoia"
      }
  
  
  Aws Thinkbox Stoke: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Thinkbox_Stoke.svg
        shape: image
        label: "Aws Thinkbox Stoke"
      }
  
  
  Aws Thinkbox Xmesh: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Thinkbox_XMesh.svg
        shape: image
        label: "Aws Thinkbox Xmesh"
      }
  
  
  Aws Wavelength: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/AWS_Wavelength.svg
        shape: image
        label: "Aws Wavelength"
      }
  
  
  Bottlerocket: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Bottlerocket.svg
        shape: image
        label: "Bottlerocket"
      }
  
  
  Elastic Fabric Adapter: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/Elastic_Fabric_Adapter.svg
        shape: image
        label: "Elastic Fabric Adapter"
      }
  
  
  Nice Dcv: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/NICE_DCV.svg
        shape: image
        label: "Nice Dcv"
      }
  
  
  Nice Enginframe: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/NICE_EnginFrame.svg
        shape: image
        label: "Nice Enginframe"
      }
  
  
  Vmware Cloud On Aws: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Compute/VMware_Cloud_on_AWS.svg
        shape: image
        label: "Vmware Cloud On Aws"
      }
  
}