classes: {
    API Connections: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FAPI%20Connections.svg

      shape: image
      label: "API Connections"
      width: 125
      height: 125
    }
    API Management Services: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAPI%20Management%20Services.svg

      shape: image
      label: "API Management Services"
    }
    Access Review: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FAccess%20Review.svg

      shape: image
      label: "Access Review"
    }
    Active Directory: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FActive%20Directory.svg

      shape: image
      label: "Active Directory"
    }
    Active Directory Connect Health: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FActive%20Directory%20Connect%20Health.svg

      shape: image
      label: "Active Directory Connect Health"
    }
    Activity Log: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FActivity%20Log.svg

      shape: image
      label: "Activity Log"
    }
    Advisor: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FAdvisor.svg

      shape: image
      label: "Advisor"
    }
    Alerts: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FAlerts.svg

      shape: image
      label: "Alerts"
    }
    All Resources: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FAll%20Resources.svg

      shape: image
      label: "All Resources"
    }
    Analysis Services: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FAnalysis%20Services.svg

      shape: image
      label: "Analysis Services"
    }
    App Configuration: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FApp%20Configuration.svg

      shape: image
      label: "App Configuration"
    }
    App Registrations: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FApp%20Registrations.svg

      shape: image
      label: "App Registrations"
    }
    App Service Certificates: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Service%20Certificates.svg

      shape: image
      label: "App Service Certificates"
    }
    App Service Domains: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Service%20Domains.svg

      shape: image
      label: "App Service Domains"
    }
    App Service Environments: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Service%20Environments.svg

      shape: image
      label: "App Service Environments"
    }
    App Service Plans: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Service%20Plans.svg

      shape: image
      label: "App Service Plans"
    }
    App Services: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Services.svg

      shape: image
      label: "App Services"
    }
    Application Gateway: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FApplication%20Gateway.svg

      shape: image
      label: "Application Gateway"
    }
    Application Insights: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FApplication%20Insights.svg

      shape: image
      label: "Application Insights"
    }
    Application Security Groups: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FApplication%20Security%20Groups.svg

      shape: image
      label: "Application Security Groups"
    }
    Archive Storage: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FArchive%20Storage.svg

      shape: image
      label: "Archive Storage"
    }
    Automation Accounts: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FAutomation%20Accounts.svg

      shape: image
      label: "Automation Accounts"
    }
    Availability Sets: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FAvailability%20Sets.svg

      shape: image
      label: "Availability Sets"
    }
    Azure AD B2C: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FAzure%20AD%20B2C.svg

      shape: image
      label: "Azure AD B2C"
    }
    Azure AD Domain Services: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FAzure%20AD%20Domain%20Services.svg

      shape: image
      label: "Azure AD Domain Services"
    }
    Azure AD Identity Protection: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FAzure%20AD%20Identity%20Protection.svg

      shape: image
      label: "Azure AD Identity Protection"
    }
    Azure AD Privileged Identity Management: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FAzure%20AD%20Privileged%20Identity%20Management.svg

      shape: image
      label: "Azure AD Privileged Identity Management"
    }
    Azure API For FHIR: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAzure%20API%20for%20FHIR.svg

      shape: image
      label: "Azure API For FHIR"
    }
    Azure App Service   Mobile: {
      icon: https://icons.terrastruct.com/azure%2FMobile%20Service%20Color%2FAzure%20App%20Service%20-%20Mobile.svg

      shape: image
      label: "Azure App Service   Mobile"
    }
    Azure Artifacts: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20Artifacts.svg

      shape: image
      label: "Azure Artifacts"
    }
    Azure Boards: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20Boards.svg

      shape: image
      label: "Azure Boards"
    }
    Azure Cache For Redis: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Cache%20for%20Redis.svg

      shape: image
      label: "Azure Cache For Redis"
    }
    Azure Cache Plus Redis: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Cache%20plus%20Redis.svg

      shape: image
      label: "Azure Cache Plus Redis"
    }
    Azure Cache Redis Product Icon: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FAzure%20Cache%20Redis%20Product%20icon.svg

      shape: image
      label: "Azure Cache Redis Product Icon"
    }
    Azure Cosmos DB: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Cosmos%20DB.svg

      shape: image
      label: "Azure Cosmos DB"
    }
    Azure Data Catalog: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAzure%20Data%20Catalog.svg

      shape: image
      label: "Azure Data Catalog"
    }
    Azure Data Explorer Clusters: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FAzure%20Data%20Explorer%20Clusters.svg

      shape: image
      label: "Azure Data Explorer Clusters"
    }
    Azure Database Generic: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Database%20%28Generic%29.svg

      shape: image
      label: "Azure Database (Generic"
    }
    Azure Database For MariaDB Servers: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Database%20for%20MariaDB%20servers.svg

      shape: image
      label: "Azure Database For MariaDB Servers"
    }
    Azure Database For MySQL Servers: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Database%20for%20MySQL%20servers.svg

      shape: image
      label: "Azure Database For MySQL Servers"
    }
    Azure Database For PostgreSQL Servers: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20Database%20for%20PostgreSQL%20servers.svg

      shape: image
      label: "Azure Database For PostgreSQL Servers"
    }
    Azure Database Migration Services: {
      icon: https://icons.terrastruct.com/azure%2FMigrate%20Service%20Color%2FAzure%20Database%20Migration%20Services.svg

      shape: image
      label: "Azure Database Migration Services"
    }
    Databricks: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FAzure%20Databricks.svg

      shape: image
      label: "Azure Databricks"
    }
    Azure DevOps: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20DevOps.svg

      shape: image
      label: "Azure DevOps"
    }
    Azure DevTest Labs: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20DevTest%20Labs.svg

      shape: image
      label: "Azure DevTest Labs"
    }
    Azure Digital Twins: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FAzure%20Digital%20Twins.svg

      shape: image
      label: "Azure Digital Twins"
    }
    Azure Firewall: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FAzure%20Firewall.svg

      shape: image
      label: "Azure Firewall"
    }
    Azure HDInsight COLOR: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FAzure%20HDInsight_COLOR.svg

      shape: image
      label: "Azure HDInsight COLOR"
    }
    Azure HockeyApp COLOR: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FAzure%20HockeyApp_COLOR.svg

      shape: image
      label: "Azure HockeyApp COLOR"
    }
    Azure Home: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FAzure%20Home.svg

      shape: image
      label: "Azure Home"
    }
    Azure Information Protection: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FAzure%20Information%20Protection.svg

      shape: image
      label: "Azure Information Protection"
    }
    Azure IoT Hub: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FAzure%20IoT%20Hub.svg

      shape: image
      label: "Azure IoT Hub"
    }
    Azure IoT Hub Security: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FAzure%20IoT%20Hub%20Security.svg

      shape: image
      label: "Azure IoT Hub Security"
    }
    Azure Maps: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FAzure%20Maps.svg

      shape: image
      label: "Azure Maps"
    }
    Azure Media Player: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMedia%2FAzure%20Media%20Player.svg

      shape: image
      label: "Azure Media Player"
    }
    Azure Media Services: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FAzure%20Media%20Services.svg

      shape: image
      label: "Azure Media Services"
    }
    Azure Mobile Engagement: {
      icon: https://icons.terrastruct.com/azure%2FMobile%20Service%20Color%2FAzure%20Mobile%20Engagement.svg

      shape: image
      label: "Azure Mobile Engagement"
    }
    Azure NetApp Files: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FAzure%20NetApp%20files.svg

      shape: image
      label: "Azure NetApp Files"
    }
    Azure OpenShift: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FAzure%20OpenShift.svg

      shape: image
      label: "Azure OpenShift"
    }
    Azure Pipelines: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20Pipelines.svg

      shape: image
      label: "Azure Pipelines"
    }
    Azure Repos: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20Repos.svg

      shape: image
      label: "Azure Repos"
    }
    Azure SQL DataWarehouse: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FAzure%20SQL%20DataWarehouse.svg

      shape: image
      label: "Azure SQL DataWarehouse"
    }
    Azure Search: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FAzure%20Search.svg

      shape: image
      label: "Azure Search"
    }
    Azure Sentinel: {
      icon: https://icons.terrastruct.com/azure%2FSecurity%20Service%20Color%2FAzure%20Sentinel.svg

      shape: image
      label: "Azure Sentinel"
    }
    Azure Service Bus: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAzure%20Service%20Bus.svg

      shape: image
      label: "Azure Service Bus"
    }
    Azure Service Bus Relays: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAzure%20Service%20Bus%20Relays.svg

      shape: image
      label: "Azure Service Bus Relays"
    }
    Azure Sphere: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FAzure%20Sphere.svg

      shape: image
      label: "Azure Sphere"
    }
    Azure StorSimple Device Managers: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAzure%20StorSimple%20Device%20Managers.svg

      shape: image
      label: "Azure StorSimple Device Managers"
    }
    Azure StorSimple Device Managers: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FAzure%20StorSimple%20Device%20Managers.svg

      shape: image
      label: "Azure StorSimple Device Managers"
    }
    Azure Test Plans: {
      icon: https://icons.terrastruct.com/azure%2FDevOps%20Service%20Color%2FAzure%20Test%20Plans.svg

      shape: image
      label: "Azure Test Plans"
    }
    AzureFXTEdgeFiler: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FAzureFXTEdgeFiler.svg

      shape: image
      label: "AzureFXTEdgeFiler"
    }
    Batch AI: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FBatch%20AI.svg

      shape: image
      label: "Batch AI"
    }
    Batch Accounts: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FBatch%20Accounts.svg

      shape: image
      label: "Batch Accounts"
    }
    Blob Storage: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FBlob%20Storage.svg

      shape: image
      label: "Blob Storage"
    }
    Blob Storage: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FBlob%20Storage.svg

      shape: image
      label: "Blob Storage"
    }
    Blueprints: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FBlueprints.svg

      shape: image
      label: "Blueprints"
    }
    Bot Services: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FBot%20Services.svg

      shape: image
      label: "Bot Services"
    }
    CDN Profiles: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FCDN%20Profiles.svg

      shape: image
      label: "CDN Profiles"
    }
    Citrix Virtual Desktops Essentials: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FCitrix%20Virtual%20Desktops%20Essentials.svg

      shape: image
      label: "Citrix Virtual Desktops Essentials"
    }
    Client Apps: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FClient%20Apps.svg

      shape: image
      label: "Client Apps"
    }
    Cloud Cycle: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FCloud_Cycle.svg

      shape: image
      label: "Cloud Cycle"
    }
    Cloud Services: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FCloud%20Services.svg

      shape: image
      label: "Cloud Services"
    }
    Cloud Services Classic: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FCloud%20Services%20%28Classic%29.svg

      shape: image
      label: "Cloud Services Classic"
    }
    CloudSimple Nodes: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FCloudSimple%20Nodes.svg

      shape: image
      label: "CloudSimple Nodes"
    }
    CloudSimple Services: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FCloudSimple%20Services.svg

      shape: image
      label: "CloudSimple Services"
    }
    CloudSimple Virtual Machines: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FCloudSimple%20Virtual%20Machines.svg

      shape: image
      label: "CloudSimple Virtual Machines"
    }
    Cognitive Services: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FCognitive%20Services.svg

      shape: image
      label: "Cognitive Services"
    }
    Conditional Access: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FConditional%20Access.svg

      shape: image
      label: "Conditional Access"
    }
    Connections: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FConnections.svg

      shape: image
      label: "Connections"
    }
    Container Instances: {
      icon: https://icons.terrastruct.com/azure%2FContainer%20Service%20Color%2FContainer%20Instances.svg

      shape: image
      label: "Container Instances"
    }
    Container Registries: {
      icon: https://icons.terrastruct.com/azure%2FContainer%20Service%20Color%2FContainer%20Registries.svg

      shape: image
      label: "Container Registries"
    }
    Content Protection: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMedia%2FContent%20Protection.svg

      shape: image
      label: "Content Protection"
    }
    Controllers: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FControllers.svg

      shape: image
      label: "Controllers"
    }
    Cost Management Billing: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FCost%20Management%20Billing.svg

      shape: image
      label: "Cost Management Billing"
    }
    Customer Lockbox: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FCustomer%20Lockbox.svg

      shape: image
      label: "Customer Lockbox"
    }
    DDOS Protection Plans: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FDDOS%20Protection%20Plans.svg

      shape: image
      label: "DDOS Protection Plans"
    }
    DNS Private Zones: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FDNS%20Private%20Zones.svg

      shape: image
      label: "DNS Private Zones"
    }
    DNS Zones: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FDNS%20Zones.svg

      shape: image
      label: "DNS Zones"
    }
    Data Box: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FData%20Box.svg

      shape: image
      label: "Data Box"
    }
    Data Box Edge Data Box Gateway: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FData%20Box%20Edge%20_%20Data%20Box%20Gateway.svg

      shape: image
      label: "Data Box Edge   Data Box Gateway"
    }
    Data Integration: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FData%20Factories.svg

      shape: image
      label: "Azure Data Factory"
    }
    Data Lake: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FData%20Lake.svg

      shape: image
      label: "Data Lake"
    }
    Data Lake Analytics: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FData%20Lake%20Analytics.svg

      shape: image
      label: "Data Lake Analytics"
    }
    Data Lake Storage: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FData%20Lake%20Storage.svg

      shape: image
      label: ""
    }
    Data Lake Store Gen2: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FData%20Lake%20Store%20Gen1.svg

      shape: image
      label: ""
    }
    Dedicated Event Hub: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FDedicated%20Event%20Hub.svg

      shape: image
      label: "Dedicated Event Hub"
    }
    DeveloperTools: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FDeveloperTools.svg

      shape: image
      label: "DeveloperTools"
    }
    Device Compliance: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FDevice%20Compliance.svg

      shape: image
      label: "Device Compliance"
    }
    Device Config: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FDevice%20Config.svg

      shape: image
      label: "Device Config"
    }
    Device Provisioning Services: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FDevice%20Provisioning%20Services.svg

      shape: image
      label: "Device Provisioning Services"
    }
    Devices Groups: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FDevices%20Groups.svg

      shape: image
      label: "Devices Groups"
    }
    Diagnostic Settings: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FDiagnostic%20Settings.svg

      shape: image
      label: "Diagnostic Settings"
    }
    Disk Snapshots: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FDisk%20Snapshots.svg

      shape: image
      label: "Disk Snapshots"
    }
    Disks: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FDisks.svg

      shape: image
      label: "Disks"
    }
    EBooks: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FeBooks.svg

      shape: image
      label: "EBooks"
    }
    Education: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FEducation.svg

      shape: image
      label: "Education"
    }
    Elastic Database Pools: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FElastic%20Database%20Pools.svg

      shape: image
      label: "Elastic Database Pools"
    }
    Elastic Job Agents: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FElastic%20Job%20Agents.svg

      shape: image
      label: "Elastic Job Agents"
    }
    Enrollment: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FEnrollment.svg

      shape: image
      label: "Enrollment"
    }
    Enterprise Applications: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FEnterprise%20Applications.svg

      shape: image
      label: "Enterprise Applications"
    }
    Event Grid Domains: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FEvent%20Grid%20Domains.svg

      shape: image
      label: "Event Grid Domains"
    }
    Event Grid Subscriptions: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FEvent%20Grid%20Subscriptions.svg

      shape: image
      label: "Event Grid Subscriptions"
    }
    Event Grid Topics: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FEvent%20Grid%20Topics.svg

      shape: image
      label: "Event Grid Topics"
    }
    Event Hub Clusters: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FEvent%20Hub%20Clusters.svg

      shape: image
      label: "Event Hub Clusters"
    }
    Event Hubs: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FEvent%20Hubs.svg

      shape: image
      label: "Event Hubs"
    }
    Exchange On Premises Access: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FExchange%20On-Premises%20Access.svg

      shape: image
      label: "Exchange On Premises Access"
    }
    ExpressRoute Circuits: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FExpressRoute%20Circuits.svg

      shape: image
      label: "ExpressRoute Circuits"
    }
    Free Services: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FFree%20Services.svg

      shape: image
      label: "Free Services"
    }
    Front Doors: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FFront%20Doors.svg

      shape: image
      label: "Front Doors"
    }
    Function Apps: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FFunction%20Apps.svg

      shape: image
      label: "Function Apps"
    }
    General Storage: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FGeneral%20Storage.svg

      shape: image
      label: "General Storage"
    }
    Genomics Accounts: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FGenomics%20Accounts.svg

      shape: image
      label: "Genomics Accounts"
    }
    Guest Assignments: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FGuest%20Assignments.svg

      shape: image
      label: "Guest Assignments"
    }
    HD Insight: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FHD-Insight.svg

      shape: image
      label: "HD Insight"
    }
    HDInsightClusters: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FHDInsightClusters.svg

      shape: image
      label: "HDInsightClusters"
    }
    Help Support: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FHelp%20Support.svg

      shape: image
      label: "Help Support"
    }
    HockeyApp: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FHockeyApp.svg

      shape: image
      label: "HockeyApp"
    }
    Identity Governance: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FIdentity%20governance.svg

      shape: image
      label: "Identity Governance"
    }
    Image Definitions: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FImage%20Definitions.svg

      shape: image
      label: "Image Definitions"
    }
    Image Versions: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FImage%20Versions.svg

      shape: image
      label: "Image Versions"
    }
    Information: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FInformation.svg

      shape: image
      label: "Information"
    }
    Integration Accounts: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FIntegration%20Accounts.svg

      shape: image
      label: "Integration Accounts"
    }
    Integration Service Environments: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FIntegration%20Service%20Environments.svg

      shape: image
      label: "Integration Service Environments"
    }
    Intune App Protection: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FIntune%20App%20Protection.svg

      shape: image
      label: "Intune App Protection"
    }
    IoT Central Applications: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FIoT%20Central%20Applications.svg

      shape: image
      label: "IoT Central Applications"
    }
    Key Vaults: {
      icon: https://icons.terrastruct.com/azure%2FSecurity%20Service%20Color%2FKey%20Vaults.svg

      shape: image
      label: "Key Vaults"
    }
    Kubernetes: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

      shape: image
      label: "Kubernetes"
    }
    Kubernetes Services: {
      icon: https://icons.terrastruct.com/azure%2FContainer%20Service%20Color%2FKubernetes%20Services.svg

      shape: image
      label: "Kubernetes Services"
    }
    Load Balancers: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FLoad%20Balancers.svg

      shape: image
      label: "Load Balancers"
    }
    Local Network Gateways: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FLocal%20Network%20Gateways.svg

      shape: image
      label: "Local Network Gateways"
    }
    Log Analytics Workspaces: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FLog%20Analytics%20Workspaces.svg

      shape: image
      label: "Log Analytics Workspaces"
    }
    Logic Apps: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FLogic%20Apps.svg

      shape: image
      label: "Logic Apps"
    }
    Logic Apps Custom Connector: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FLogic%20Apps%20Custom%20Connector.svg

      shape: image
      label: "Logic Apps Custom Connector"
    }
    Logo DC OS: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FLogo-DC-OS.svg

      shape: image
      label: "Logo DC OS"
    }
    Logo Docker: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FLogo-docker.svg

      shape: image
      label: "Logo Docker"
    }
    Logo Pluralsight Mono: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2Flogo_pluralsight_mono.svg

      shape: image
      label: "Logo Pluralsight Mono"
    }
    Logo Pluralsight Twotone: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2Flogo_pluralsight_twotone.svg

      shape: image
      label: "Logo Pluralsight Twotone"
    }
    Machine Learning Service Workspaces: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FMachine%20Learning%20Service%20Workspaces.svg

      shape: image
      label: "Machine Learning Service Workspaces"
    }
    Machine Learning Studio Web Service Plans: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FMachine%20Learning%20Studio%20Web%20Service%20Plans.svg

      shape: image
      label: "Machine Learning Studio Web Service Plans"
    }
    Machine Learning Studio Web Services: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FMachine%20Learning%20Studio%20Web%20Services.svg

      shape: image
      label: "Machine Learning Studio Web Services"
    }
    Machine Learning Studio Workspaces: {
      icon: https://icons.terrastruct.com/azure%2FAI%20and%20ML%20Service%20Color%2FMachine%20Learning%20Studio%20Workspaces.svg

      shape: image
      label: "Machine Learning Studio Workspaces"
    }
    Managed Applications: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FManaged%20Applications.svg

      shape: image
      label: "Managed Applications"
    }
    Managed Databases: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FManaged%20Databases.svg

      shape: image
      label: "Managed Databases"
    }
    Managed Desktop: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FManaged%20Desktop.svg

      shape: image
      label: "Managed Desktop"
    }
    Managed Identities: {
      icon: https://icons.terrastruct.com/azure%2FIdentity%20Service%20Color%2FManaged%20Identities.svg

      shape: image
      label: "Managed Identities"
    }
    Management Groups: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FManagement%20Groups.svg

      shape: image
      label: "Management Groups"
    }
    Marketplace: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FMarketplace.svg

      shape: image
      label: "Marketplace"
    }
    Media Encoding: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMedia%2FMedia%20Encoding.svg

      shape: image
      label: "Media Encoding"
    }
    Media On Demand: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMedia%2FMedia%20On-Demand.svg

      shape: image
      label: "Media On Demand"
    }
    Mesh Applications: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FMesh%20Applications.svg

      shape: image
      label: "Mesh Applications"
    }
    Metrics: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMetrics.svg

      shape: image
      label: "Metrics"
    }
    Migration Projects: {
      icon: https://icons.terrastruct.com/azure%2FMigrate%20Service%20Color%2FMigration%20Projects.svg

      shape: image
      label: "Migration Projects"
    }
    Monitor: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMonitor.svg

      shape: image
      label: "Monitor"
    }
    Network Interfaces: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FNetwork%20Interfaces.svg

      shape: image
      label: "Network Interfaces"
    }
    Network Security Groups Classic: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FNetwork%20Security%20Groups%20%28Classic%29.svg

      shape: image
      label: "Network Security Groups Classic"
    }
    Network Watcher: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FNetwork%20Watcher.svg

      shape: image
      label: "Network Watcher"
    }
    Network Watcher: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FNetwork%20Watcher.svg

      shape: image
      label: "Network Watcher"
    }
    Non Azure Machine: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FNon-azure-machine.svg

      shape: image
      label: "Non Azure Machine"
    }
    Notification Hub Namespaces: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FNotification%20Hub%20Namespaces.svg

      shape: image
      label: "Notification Hub Namespaces"
    }
    Notification Hubs: {
      icon: https://icons.terrastruct.com/azure%2FMobile%20Service%20Color%2FNotification%20Hubs.svg

      shape: image
      label: "Notification Hubs"
    }
    OS Images Classic: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FOS%20Images%20%28Classic%29.svg

      shape: image
      label: "OS Images Classic"
    }
    On Premises Data Gateways: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FOn-premises%20Data%20Gateways.svg

      shape: image
      label: "On Premises Data Gateways"
    }
    Policy: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FPolicy.svg

      shape: image
      label: "Policy"
    }
    Public IP Addresses: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FPublic%20IP%20Addresses.svg

      shape: image
      label: "Public IP Addresses"
    }
    Queues Storage: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FQueues%20Storage.svg

      shape: image
      label: "Queues Storage"
    }
    Quick Start Center: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FQuick%20Start%20Center.svg

      shape: image
      label: "Quick Start Center"
    }
    Recent: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FRecent.svg

      shape: image
      label: "Recent"
    }
    Recovery Services Vaults: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FRecovery%20Services%20Vaults.svg

      shape: image
      label: "Recovery Services Vaults"
    }
    Recovery Services Vaults: {
      icon: https://icons.terrastruct.com/azure%2FMigrate%20Service%20Color%2FRecovery%20Services%20Vaults.svg

      shape: image
      label: "Recovery Services Vaults"
    }
    Reservations: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FReservations.svg

      shape: image
      label: "Reservations"
    }
    Reserved IP Addresses Classic: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FReserved%20IP%20Addresses%20%28Classic%29.svg

      shape: image
      label: "Reserved IP Addresses Classic"
    }
    Resource: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FResource.svg

      shape: image
      label: "Resource"
    }
    Resource Explorer: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FResource%20Explorer.svg

      shape: image
      label: "Resource Explorer"
    }
    Resource Graph Explorer: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FResource%20Graph%20Explorer.svg

      shape: image
      label: "Resource Graph Explorer"
    }
    Resource Groups: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FResource%20Groups.svg

      shape: image
      label: "Resource Groups"
    }
    Route Filters: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FRoute%20Filters.svg

      shape: image
      label: "Route Filters"
    }
    Route Tables: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FRoute%20Tables.svg

      shape: image
      label: "Route Tables"
    }
    SAP HANA On Azure: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FSAP%20HANA%20on%20Azure.svg

      shape: image
      label: "SAP HANA On Azure"
    }
    Azure SQL Database: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FSQL%20Databases.svg

      shape: image
      label: "Azure SQL Database"
      width: 125
      height: 125
    }
    SQL Managed Instances: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FSQL%20Managed%20Instances.svg

      shape: image
      label: "SQL Managed Instances"
    }
    SQL Server Stretch Databases: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FSQL%20Server%20stretch%20Databases.svg

      shape: image
      label: "SQL Server Stretch Databases"
    }
    SQL Servers: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FSQL%20Servers.svg

      shape: image
      label: "SQL Servers"
    }
    Scheduler Job Collections: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FScheduler%20Job%20Collections.svg

      shape: image
      label: "Scheduler Job Collections"
    }
    Security Baselines: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FSecurity%20Baselines.svg

      shape: image
      label: "Security Baselines"
    }
    Security Center: {
      icon: https://icons.terrastruct.com/azure%2FSecurity%20Service%20Color%2FSecurity%20Center.svg

      shape: image
      label: "Security Center"
    }
    SendGrid Accounts: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FSendGrid%20Accounts.svg

      shape: image
      label: "SendGrid Accounts"
    }
    Service Catalog Managed Application Definitions: {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FService%20Catalog%20Managed%20Application%20Definitions.svg

      shape: image
      label: "Service Catalog Managed Application Definitions"
    }
    Service Endpoint Policies: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FService%20Endpoint%20Policies.svg

      shape: image
      label: "Service Endpoint Policies"
    }
    Service Fabric Clusters: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FService%20Fabric%20Clusters.svg

      shape: image
      label: "Service Fabric Clusters"
    }
    Service Health: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FService%20Health.svg

      shape: image
      label: "Service Health"
    }
    Shared Dashboard: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FShared%20Dashboard.svg

      shape: image
      label: "Shared Dashboard"
    }
    Shared Image Galleries: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FShared%20Image%20Galleries.svg

      shape: image
      label: "Shared Image Galleries"
    }
    SignalR: {
      icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FSignalR.svg

      shape: image
      label: "SignalR"
    }
    Software As A Service (SaaS): {
      icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FSoftware%20as%20a%20Service%20%28SaaS%29.svg

      shape: image
      label: "Software As A Service (SaaS"
    }
    Software Update: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FSoftware%20Update.svg

      shape: image
      label: "Software Update"
    }
    Solutions: {
      icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FSolutions.svg

      shape: image
      label: "Solutions"
    }
    Spatial Anchor: {
      icon: https://icons.terrastruct.com/azure%2FMixed%20Reality%20Service%20Icon%2FSpatial%20Anchor.svg

      shape: image
      label: "Spatial Anchor"
    }
    StackOverflow: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FStackOverflow.svg

      shape: image
      label: "StackOverflow"
    }
    StorSimple Data Managers: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorSimple%20Data%20Managers.svg

      shape: image
      label: "StorSimple Data Managers"
    }
    StorSimple Device Managers: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorSimple%20Device%20Managers.svg

      shape: image
      label: "StorSimple Device Managers"
    }
    Storage Accounts: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorage%20Accounts.svg

      shape: image
      label: "Storage Accounts"
    }
    Storage Accounts Classic: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorage%20Accounts%20%28classic%29.svg

      shape: image
      label: "Storage Accounts Classic"
    }
    Storage Explorer: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorage%20Explorer.svg

      shape: image
      label: "Storage Explorer"
    }
    Storage Sync Services: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FStorage%20Sync%20Services.svg

      shape: image
      label: "Storage Sync Services"
    }
    Stream Analytics Jobs: {
      icon: https://icons.terrastruct.com/azure%2FAnalytics%20Service%20Color%2FStream%20Analytics%20Jobs.svg

      shape: image
      label: "Stream Analytics Jobs"
    }
    Subscriptions: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FSubscriptions.svg

      shape: image
      label: "Subscriptions"
    }
    Support: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FSupport.svg

      shape: image
      label: "Support"
    }
    Support Requests: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FSupport%20Requests.svg

      shape: image
      label: "Support Requests"
    }
    Table Storage: {
      icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FTable%20Storage.svg

      shape: image
      label: "Table Storage"
    }
    Tag: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FTag.svg

      shape: image
      label: "Tag"
    }
    Tags: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FTags.svg

      shape: image
      label: "Tags"
    }
    Templates: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FTemplates.svg

      shape: image
      label: "Templates"
    }
    Tenant Status: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FTenant%20Status.svg

      shape: image
      label: "Tenant Status"
    }
    Time Series Insights Environments: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FTime%20Series%20Insights%20environments.svg

      shape: image
      label: "Time Series Insights Environments"
    }
    Time Series Insights Events Sources: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FTime%20Series%20Insights%20Events%20Sources.svg

      shape: image
      label: "Time Series Insights Events Sources"
    }
    Tools: {
      icon: https://icons.terrastruct.com/azure%2FIntune%20Service%20Color%2FTools.svg

      shape: image
      label: "Tools"
    }
    Traffic Manager Profiles: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FTraffic%20Manager%20Profiles.svg

      shape: image
      label: "Traffic Manager Profiles"
    }
    Two User Icon: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FTwo%20User%20Icon.svg

      shape: image
      label: "Two User Icon"
    }
    User Health Icon: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FUser%20Health%20Icon.svg

      shape: image
      label: "User Health Icon"
    }
    User Icon: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FUser%20Icon.svg

      shape: image
      label: "User Icon"
    }
    User Privacy: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FUser%20Privacy.svg

      shape: image
      label: "User Privacy"
    }
    User Resource: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FUser%20Resource.svg

      shape: image
      label: "User Resource"
    }
    VM: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM.svg

      shape: image
      label: "VM"
    }
    VM Classic: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM%20%28Classic%29.svg

      shape: image
      label: "VM Classic"
    }
    VM Images: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%20Images.svg

      shape: image
      label: "VM Images"
    }
    VM Linux: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM-Linux.svg

      shape: image
      label: "VM Linux"
    }
    VM Linux Non Azure: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM-Linux-non-azure.svg

      shape: image
      label: "VM Linux Non Azure"
    }
    VM Non Azure: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM-non-azure.svg

      shape: image
      label: "VM Non Azure"
    }
    VM Scale Sets: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM%20Scale%20Sets.svg

      shape: image
      label: "VM Scale Sets"
    }
    VM Windows: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM-windows.svg

      shape: image
      label: "VM Windows"
    }
    VM Windows Non Azure: {
      icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FVM%2FVM-windows-non-azure.svg

      shape: image
      label: "VM Windows Non Azure"
    }
    Virtual Clusters: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FVirtual%20Clusters.svg

      shape: image
      label: "Virtual Clusters"
    }
    Virtual Datacenter: {
      icon: https://icons.terrastruct.com/azure%2FDatabases%20Service%20Color%2FVirtual%20Datacenter.svg

      shape: image
      label: "Virtual Datacenter"
    }
    Virtual Network Classic: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FVirtual%20Network%20%28Classic%29.svg

      shape: image
      label: "Virtual Network Classic"
    }
    Virtual Network Gateways: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FVirtual%20Network%20Gateways.svg

      shape: image
      label: "Virtual Network Gateways"
    }
    Virtual Networks: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FVirtual%20Networks.svg

      shape: image
      label: "Virtual Networks"
    }
    Virtual WANs: {
      icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FVirtual%20WANs.svg

      shape: image
      label: "Virtual WANs"
    }
    Web App Firewall: {
      icon: https://icons.terrastruct.com/azure%2FOther%20Category%20Service%20Icon%2FWeb%20App%20Firewall.svg

      shape: image
      label: "Web App Firewall"
    }
    WebAppUmbraco: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FWebAppUmbraco.svg

      shape: image
      label: "WebAppUmbraco"
    }
    WebAppWordPress: {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FWebAppWordPress.svg

      shape: image
      label: "WebAppWordPress"
    }
    What's New: {
      icon: https://icons.terrastruct.com/azure%2FGeneral%20Service%20Icons%2FWhat%27s%20New.svg

      shape: image
      label: "What's New"
    }
    Windows 10 IoT Core Services: {
      icon: https://icons.terrastruct.com/azure%2FInternet%20of%20Things%20Service%20Color%2FWindows%2010%20IoT%20Core%20Services.svg

      shape: image
      label: "Windows 10 IoT Core Services"
    }
}