classes: {
  
  
  Apple: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Apple.svg
        shape: image
        label: "Apple"
      }
  
  
  Cleaning products: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Cleaning Products.svg
        shape: image
        label: "Cleaning products"
      }
  
  
  Cosmetics: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Cosmetics.svg
        shape: image
        label: "Cosmetics"
      }
  
  
  Distance: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Distance.svg
        shape: image
        label: "Distance"
      }
  
  
  Excercises 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Excercises 2.svg
        shape: image
        label: "Excercises 2"
      }
  
  
  Food: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Food.svg
        shape: image
        label: "Food"
      }
  
  
  Football: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Football.svg
        shape: image
        label: "Football"
      }
  
  
  Health 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 2.svg
        shape: image
        label: "Health 2"
      }
  
  
  Health 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 3.svg
        shape: image
        label: "Health 3"
      }
  
  
  Health 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 4.svg
        shape: image
        label: "Health 4"
      }
  
  
  Health 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 5.svg
        shape: image
        label: "Health 5"
      }
  
  
  Health 6: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 6.svg
        shape: image
        label: "Health 6"
      }
  
  
  Health 7: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 7.svg
        shape: image
        label: "Health 7"
      }
  
  
  Health 8: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 8.svg
        shape: image
        label: "Health 8"
      }
  
  
  Health 9: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health 9.svg
        shape: image
        label: "Health 9"
      }
  
  
  Health: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Health.svg
        shape: image
        label: "Health"
      }
  
  
  Mask: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Mask.svg
        shape: image
        label: "Mask"
      }
  
  
  Meditation: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Meditation.svg
        shape: image
        label: "Meditation"
      }
  
  
  Paste: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Paste.svg
        shape: image
        label: "Paste"
      }
  
  
  Pear: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Pear.svg
        shape: image
        label: "Pear"
      }
  
  
  Pills: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Pills.svg
        shape: image
        label: "Pills"
      }
  
  
  Running: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Running.svg
        shape: image
        label: "Running"
      }
  
  
  Soap 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Soap 1.svg
        shape: image
        label: "Soap 1"
      }
  
  
  Soap 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Soap 2.svg
        shape: image
        label: "Soap 2"
      }
  
  
  Strenght: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Strenght.svg
        shape: image
        label: "Strenght"
      }
  
  
  Tidying: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Tidying.svg
        shape: image
        label: "Tidying"
      }
  
  
  Toothbrushes: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Toothbrushes.svg
        shape: image
        label: "Toothbrushes"
      }
  
  
  Towel paper: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Towel Paper.svg
        shape: image
        label: "Towel paper"
      }
  
  
  Washing: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Health/Washing.svg
        shape: image
        label: "Washing"
      }
  
}