classes: {
  
  
  Amazon Cloudwatch: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/Amazon_CloudWatch.svg
        shape: image
        label: "Amazon Cloudwatch"
      }
  
  
  Amazon Managed Grafana: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/Amazon_Managed_Grafana.svg
        shape: image
        label: "Amazon Managed Grafana"
      }
  
  
  Amazon Managed Service For Prometheus: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/Amazon_Managed_Service_for_Prometheus.svg
        shape: image
        label: "Amazon Managed Service For Prometheus"
      }
  
  
  Aws Appconfig: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_AppConfig.svg
        shape: image
        label: "Aws Appconfig"
      }
  
  
  Aws Application Auto Scaling: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Application_Auto_Scaling.svg
        shape: image
        label: "Aws Application Auto Scaling"
      }
  
  
  Aws Auto Scaling: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Auto_Scaling.svg
        shape: image
        label: "Aws Auto Scaling"
      }
  
  
  Aws Backint Agent: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Backint_Agent.svg
        shape: image
        label: "Aws Backint Agent"
      }
  
  
  Aws Chatbot: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Chatbot.svg
        shape: image
        label: "Aws Chatbot"
      }
  
  
  Aws Cloudformation: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_CloudFormation.svg
        shape: image
        label: "Aws Cloudformation"
      }
  
  
  Aws Cloudtrail: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_CloudTrail.svg
        shape: image
        label: "Aws Cloudtrail"
      }
  
  
  Aws Config: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Config.svg
        shape: image
        label: "Aws Config"
      }
  
  
  Aws Control Tower: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Control_Tower.svg
        shape: image
        label: "Aws Control Tower"
      }
  
  
  Aws Distro For Opentelemetry: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Distro_for_OpenTelemetry.svg
        shape: image
        label: "Aws Distro For Opentelemetry"
      }
  
  
  Aws Fault Injection Simulator: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Fault_Injection_Simulator.svg
        shape: image
        label: "Aws Fault Injection Simulator"
      }
  
  
  Aws Health Dashboard: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Health_Dashboard.svg
        shape: image
        label: "Aws Health Dashboard"
      }
  
  
  Aws Launch Wizard: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Launch_Wizard.svg
        shape: image
        label: "Aws Launch Wizard"
      }
  
  
  Aws License Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_License_Manager.svg
        shape: image
        label: "Aws License Manager"
      }
  
  
  Aws Management Console: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Management_Console.svg
        shape: image
        label: "Aws Management Console"
      }
  
  
  Aws Opsworks: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_OpsWorks.svg
        shape: image
        label: "Aws Opsworks"
      }
  
  
  Aws Organizations: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Organizations.svg
        shape: image
        label: "Aws Organizations"
      }
  
  
  Aws Proton: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Proton.svg
        shape: image
        label: "Aws Proton"
      }
  
  
  Aws Resilience Hub: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Resilience_Hub.svg
        shape: image
        label: "Aws Resilience Hub"
      }
  
  
  Aws Resource Explorer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Resource_Explorer.svg
        shape: image
        label: "Aws Resource Explorer"
      }
  
  
  Aws Service Catalog: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Service_Catalog.svg
        shape: image
        label: "Aws Service Catalog"
      }
  
  
  Aws Service Management Connector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Service_Management_Connector.svg
        shape: image
        label: "Aws Service Management Connector"
      }
  
  
  Aws Systems Manager: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Systems_Manager.svg
        shape: image
        label: "Aws Systems Manager"
      }
  
  
  Aws Telco Network Builder: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Telco_Network_Builder.svg
        shape: image
        label: "Aws Telco Network Builder"
      }
  
  
  Aws Trusted Advisor: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Trusted_Advisor.svg
        shape: image
        label: "Aws Trusted Advisor"
      }
  
  
  Aws Well Architected Tool: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Management-Governance/AWS_Well_Architected_Tool.svg
        shape: image
        label: "Aws Well Architected Tool"
      }
  
}