classes: {
  
  icon_service_Azure_Databox_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/icon_service_Azure_Databox_Gateway.svg
        shape: image
        label: "icon_service_Azure_Databox_Gateway"
      }
  
  icon_service_Azure_Migrate: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/icon_service_Azure_Migrate.svg
        shape: image
        label: "icon_service_Azure_Migrate"
      }
  
  icon_service_Azure_Stack_Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/icon_service_Azure_Stack_Edge.svg
        shape: image
        label: "icon_service_Azure_Stack_Edge"
      }
  
  icon_service_Cost_Management_and_Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/icon_service_Cost_Management_and_Billing.svg
        shape: image
        label: "icon_service_Cost_Management_and_Billing"
      }
  
  icon_service_Data_Box: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/icon_service_Data_Box.svg
        shape: image
        label: "icon_service_Data_Box"
      }
  
  icon_service_Recovery_Services_Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/icon_service_Recovery_Services_Vaults.svg
        shape: image
        label: "icon_service_Recovery_Services_Vaults"
      }
  
}