classes: {
  
  
  Azure Databox Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/Azure_Databox_Gateway.svg
        shape: image
        label: "Azure Databox Gateway"
      }
  
  
  Azure Migrate: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/Azure_Migrate.svg
        shape: image
        label: "Azure Migrate"
      }
  
  
  Azure Stack Edge: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/Azure_Stack_Edge.svg
        shape: image
        label: "Azure Stack Edge"
      }
  
  
  Cost Management And Billing: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/Cost_Management_and_Billing.svg
        shape: image
        label: "Cost Management And Billing"
      }
  
  
  Data Box: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/Data_Box.svg
        shape: image
        label: "Data Box"
      }
  
  
  Recovery Services Vaults: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/migrate/Recovery_Services_Vaults.svg
        shape: image
        label: "Recovery Services Vaults"
      }
  
}