classes: {
  
  
  Res Alert  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Alert__Dark.svg
        shape: image
        label: "Res Alert  Dark"
      }
  
  
  Res Authenticated User  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Authenticated_User__Dark.svg
        shape: image
        label: "Res Authenticated User  Dark"
      }
  
  
  Res Aws Management Console  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_AWS_Management_Console__Dark.svg
        shape: image
        label: "Res Aws Management Console  Dark"
      }
  
  
  Res Camera  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Camera__Dark.svg
        shape: image
        label: "Res Camera  Dark"
      }
  
  
  Res Chat  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Chat__Dark.svg
        shape: image
        label: "Res Chat  Dark"
      }
  
  
  Res Client  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Client__Dark.svg
        shape: image
        label: "Res Client  Dark"
      }
  
  
  Res Cold Storage  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Cold_Storage__Dark.svg
        shape: image
        label: "Res Cold Storage  Dark"
      }
  
  
  Res Credentials  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Credentials__Dark.svg
        shape: image
        label: "Res Credentials  Dark"
      }
  
  
  Res Database  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Database__Dark.svg
        shape: image
        label: "Res Database  Dark"
      }
  
  
  Res Data Stream  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Data_Stream__Dark.svg
        shape: image
        label: "Res Data Stream  Dark"
      }
  
  
  Res Data Table  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Data_Table__Dark.svg
        shape: image
        label: "Res Data Table  Dark"
      }
  
  
  Res Disk  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Disk__Dark.svg
        shape: image
        label: "Res Disk  Dark"
      }
  
  
  Res Documents  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Documents__Dark.svg
        shape: image
        label: "Res Documents  Dark"
      }
  
  
  Res Document  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Document__Dark.svg
        shape: image
        label: "Res Document  Dark"
      }
  
  
  Res Email  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Email__Dark.svg
        shape: image
        label: "Res Email  Dark"
      }
  
  
  Res Firewall  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Firewall__Dark.svg
        shape: image
        label: "Res Firewall  Dark"
      }
  
  
  Res Folders  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Folders__Dark.svg
        shape: image
        label: "Res Folders  Dark"
      }
  
  
  Res Folder  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Folder__Dark.svg
        shape: image
        label: "Res Folder  Dark"
      }
  
  
  Res Forums  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Forums__Dark.svg
        shape: image
        label: "Res Forums  Dark"
      }
  
  
  Res Gear  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Gear__Dark.svg
        shape: image
        label: "Res Gear  Dark"
      }
  
  
  Res Generic Application  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Generic_Application__Dark.svg
        shape: image
        label: "Res Generic Application  Dark"
      }
  
  
  Res Git Repository  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Git_Repository__Dark.svg
        shape: image
        label: "Res Git Repository  Dark"
      }
  
  
  Res Globe  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Globe__Dark.svg
        shape: image
        label: "Res Globe  Dark"
      }
  
  
  Res Internet-alt2 48 Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Internet-alt2_48_Dark.svg
        shape: image
        label: "Res Internet-alt2 48 Dark"
      }
  
  
  Res Internet Alt  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Internet_alt__Dark.svg
        shape: image
        label: "Res Internet Alt  Dark"
      }
  
  
  Res Internet  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Internet__Dark.svg
        shape: image
        label: "Res Internet  Dark"
      }
  
  
  Res Json Script  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_JSON_Script__Dark.svg
        shape: image
        label: "Res Json Script  Dark"
      }
  
  
  Res Logs  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Logs__Dark.svg
        shape: image
        label: "Res Logs  Dark"
      }
  
  
  Res Magnifying Glass  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Magnifying_Glass__Dark.svg
        shape: image
        label: "Res Magnifying Glass  Dark"
      }
  
  
  Res Metrics  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Metrics__Dark.svg
        shape: image
        label: "Res Metrics  Dark"
      }
  
  
  Res Mobile Client  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Mobile_client__Dark.svg
        shape: image
        label: "Res Mobile Client  Dark"
      }
  
  
  Res Multimedia  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Multimedia__Dark.svg
        shape: image
        label: "Res Multimedia  Dark"
      }
  
  
  Res Office Building  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Office_building__Dark.svg
        shape: image
        label: "Res Office Building  Dark"
      }
  
  
  Res Programming Language  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Programming_Language__Dark.svg
        shape: image
        label: "Res Programming Language  Dark"
      }
  
  
  Res Question  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Question__Dark.svg
        shape: image
        label: "Res Question  Dark"
      }
  
  
  Res Recover  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Recover__Dark.svg
        shape: image
        label: "Res Recover  Dark"
      }
  
  
  Res Saml Token  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_SAML_token__Dark.svg
        shape: image
        label: "Res Saml Token  Dark"
      }
  
  
  Res Sdk  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_SDK__Dark.svg
        shape: image
        label: "Res Sdk  Dark"
      }
  
  
  Res Servers  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Servers__Dark.svg
        shape: image
        label: "Res Servers  Dark"
      }
  
  
  Res Server  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Server__Dark.svg
        shape: image
        label: "Res Server  Dark"
      }
  
  
  Res Shield  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Shield__Dark.svg
        shape: image
        label: "Res Shield  Dark"
      }
  
  
  Res Source Code  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Source_Code__Dark.svg
        shape: image
        label: "Res Source Code  Dark"
      }
  
  
  Res Ssl Padlock  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_SSL_padlock__Dark.svg
        shape: image
        label: "Res Ssl Padlock  Dark"
      }
  
  
  Res Tape Storage  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Tape_storage__Dark.svg
        shape: image
        label: "Res Tape Storage  Dark"
      }
  
  
  Res Toolkit  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Toolkit__Dark.svg
        shape: image
        label: "Res Toolkit  Dark"
      }
  
  
  Res Users  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_Users__Dark.svg
        shape: image
        label: "Res Users  Dark"
      }
  
  
  Res User  Dark: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_48_Dark/Res_User__Dark.svg
        shape: image
        label: "Res User  Dark"
      }
  
}