classes: {
  
  
  Res Aws Application Discovery Service Aws Agentless Collector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Application_Discovery_Service_AWS_Agentless_Collector.svg
        shape: image
        label: "Res Aws Application Discovery Service Aws Agentless Collector"
      }
  
  
  Res Aws Application Discovery Service Aws Discovery Agent: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Application_Discovery_Service_AWS_Discovery_Agent.svg
        shape: image
        label: "Res Aws Application Discovery Service Aws Discovery Agent"
      }
  
  
  Res Aws Application Discovery Service Migration Evaluator Collector: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Application_Discovery_Service_Migration_Evaluator_Collector.svg
        shape: image
        label: "Res Aws Application Discovery Service Migration Evaluator Collector"
      }
  
  
  Res Aws Datasync Agent: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Datasync_Agent.svg
        shape: image
        label: "Res Aws Datasync Agent"
      }
  
  
  Res Aws Datasync Discovery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_DataSync_Discovery.svg
        shape: image
        label: "Res Aws Datasync Discovery"
      }
  
  
  Res Aws Mainframe Modernization Analyzer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Mainframe_Modernization_Analyzer.svg
        shape: image
        label: "Res Aws Mainframe Modernization Analyzer"
      }
  
  
  Res Aws Mainframe Modernization Compiler: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Mainframe_Modernization_Compiler.svg
        shape: image
        label: "Res Aws Mainframe Modernization Compiler"
      }
  
  
  Res Aws Mainframe Modernization Converter: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Mainframe_Modernization_Converter.svg
        shape: image
        label: "Res Aws Mainframe Modernization Converter"
      }
  
  
  Res Aws Mainframe Modernization Developer: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Mainframe_Modernization_Developer.svg
        shape: image
        label: "Res Aws Mainframe Modernization Developer"
      }
  
  
  Res Aws Mainframe Modernization Runtime: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Mainframe_Modernization_Runtime.svg
        shape: image
        label: "Res Aws Mainframe Modernization Runtime"
      }
  
  
  Res Aws Migration Hub Refactor Spaces Applications: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Migration_Hub_Refactor_Spaces_Applications.svg
        shape: image
        label: "Res Aws Migration Hub Refactor Spaces Applications"
      }
  
  
  Res Aws Migration Hub Refactor Spaces Environments: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Migration_Hub_Refactor_Spaces_Environments.svg
        shape: image
        label: "Res Aws Migration Hub Refactor Spaces Environments"
      }
  
  
  Res Aws Migration Hub Refactor Spaces Services: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Migration_Hub_Refactor_Spaces_Services.svg
        shape: image
        label: "Res Aws Migration Hub Refactor Spaces Services"
      }
  
  
  Res Aws Transfer Family Aws As: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Transfer_Family_AWS_AS.svg
        shape: image
        label: "Res Aws Transfer Family Aws As"
      }
  
  
  Res Aws Transfer Family Aws Ftp: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Transfer_Family_AWS_FTP.svg
        shape: image
        label: "Res Aws Transfer Family Aws Ftp"
      }
  
  
  Res Aws Transfer Family Aws Ftps: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Transfer_Family_AWS_FTPS.svg
        shape: image
        label: "Res Aws Transfer Family Aws Ftps"
      }
  
  
  Res Aws Transfer Family Aws Sftp: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Res_Migration-Transfer/Res_AWS_Transfer_Family_AWS_SFTP.svg
        shape: image
        label: "Res Aws Transfer Family Aws Sftp"
      }
  
}