classes: {
  
  
  Facebook: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Facebook.svg
        shape: image
        label: "Facebook"
      }
  
  
  Instagram: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Instagram.svg
        shape: image
        label: "Instagram"
      }
  
  
  Linkedin: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/LinkedIn.svg
        shape: image
        label: "Linkedin"
      }
  
  
  Social media 1: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 1.svg
        shape: image
        label: "Social media 1"
      }
  
  
  Social media 10: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 10.svg
        shape: image
        label: "Social media 10"
      }
  
  
  Social media 11: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 11.svg
        shape: image
        label: "Social media 11"
      }
  
  
  Social media 2: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 2.svg
        shape: image
        label: "Social media 2"
      }
  
  
  Social media 3: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 3.svg
        shape: image
        label: "Social media 3"
      }
  
  
  Social media 4: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 4.svg
        shape: image
        label: "Social media 4"
      }
  
  
  Social media 5: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 5.svg
        shape: image
        label: "Social media 5"
      }
  
  
  Social media 6: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 6.svg
        shape: image
        label: "Social media 6"
      }
  
  
  Social media 8: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 8.svg
        shape: image
        label: "Social media 8"
      }
  
  
  Social media 9: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Social Media 9.svg
        shape: image
        label: "Social media 9"
      }
  
  
  Twitter: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Twitter.svg
        shape: image
        label: "Twitter"
      }
  
  
  Youtube: {
        icon: https://ppalka-lingaro.github.io/icons/Lingaro/Social Media/Youtube.svg
        shape: image
        label: "Youtube"
      }
  
}