classes: {
  
  icon_service_Activity_Log: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Activity_Log.svg
        shape: image
        label: "icon_service_Activity_Log"
      }
  
  icon_service_Application_Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Application_Insights.svg
        shape: image
        label: "icon_service_Application_Insights"
      }
  
  icon_service_Auto_Scale: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Auto_Scale.svg
        shape: image
        label: "icon_service_Auto_Scale"
      }
  
  icon_service_Azure_Monitors_for_SAP_Solutions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Azure_Monitors_for_SAP_Solutions.svg
        shape: image
        label: "icon_service_Azure_Monitors_for_SAP_Solutions"
      }
  
  icon_service_Azure_Workbooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Azure_Workbooks.svg
        shape: image
        label: "icon_service_Azure_Workbooks"
      }
  
  icon_service_Change_Analysis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Change_Analysis.svg
        shape: image
        label: "icon_service_Change_Analysis"
      }
  
  icon_service_Diagnostics_Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Diagnostics_Settings.svg
        shape: image
        label: "icon_service_Diagnostics_Settings"
      }
  
  icon_service_Log_Analytics_Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Log_Analytics_Workspaces.svg
        shape: image
        label: "icon_service_Log_Analytics_Workspaces"
      }
  
  icon_service_Metrics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Metrics.svg
        shape: image
        label: "icon_service_Metrics"
      }
  
  icon_service_Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Monitor.svg
        shape: image
        label: "icon_service_Monitor"
      }
  
  icon_service_Network_Watcher: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/icon_service_Network_Watcher.svg
        shape: image
        label: "icon_service_Network_Watcher"
      }
  
}