classes: {
  
  
  Activity Log: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Activity_Log.svg
        shape: image
        label: "Activity Log"
      }
  
  
  Application Insights: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Application_Insights.svg
        shape: image
        label: "Application Insights"
      }
  
  
  Auto Scale: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Auto_Scale.svg
        shape: image
        label: "Auto Scale"
      }
  
  
  Azure Monitors For Sap Solutions: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Azure_Monitors_for_SAP_Solutions.svg
        shape: image
        label: "Azure Monitors For Sap Solutions"
      }
  
  
  Azure Workbooks: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Azure_Workbooks.svg
        shape: image
        label: "Azure Workbooks"
      }
  
  
  Change Analysis: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Change_Analysis.svg
        shape: image
        label: "Change Analysis"
      }
  
  
  Diagnostics Settings: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Diagnostics_Settings.svg
        shape: image
        label: "Diagnostics Settings"
      }
  
  
  Log Analytics Workspaces: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Log_Analytics_Workspaces.svg
        shape: image
        label: "Log Analytics Workspaces"
      }
  
  
  Metrics: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Metrics.svg
        shape: image
        label: "Metrics"
      }
  
  
  Monitor: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Monitor.svg
        shape: image
        label: "Monitor"
      }
  
  
  Network Watcher: {
        icon: https://ppalka-lingaro.github.io/icons/Azure Public Service Icons/monitor/Network_Watcher.svg
        shape: image
        label: "Network Watcher"
      }
  
}