classes: {
  
  
  Amazon EFS: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_EFS.svg
        shape: image
        label: "Amazon EFS"
      }
  
  
  Amazon Elastic Block Store: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_Elastic_Block_Store.svg
        shape: image
        label: "Amazon Elastic Block Store"
      }
  
  
  Amazon File Cache: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_File_Cache.svg
        shape: image
        label: "Amazon File Cache"
      }
  
  
  Amazon FSx: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx.svg
        shape: image
        label: "Amazon FSx"
      }
  
  
  Amazon FSx for Lustre: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_Lustre.svg
        shape: image
        label: "Amazon FSx for Lustre"
      }
  
  
  Amazon FSx for NetApp ONTAP: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_NetApp_ONTAP.svg
        shape: image
        label: "Amazon FSx for NetApp ONTAP"
      }
  
  
  Amazon FSx for OpenZFS: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_OpenZFS.svg
        shape: image
        label: "Amazon FSx for OpenZFS"
      }
  
  
  Amazon FSx for WFS: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_WFS.svg
        shape: image
        label: "Amazon FSx for WFS"
      }
  
  
  Amazon Simple Storage Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_Simple_Storage_Service.svg
        shape: image
        label: "Amazon Simple Storage Service"
      }
  
  
  Amazon Simple Storage Service Glacier: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_Simple_Storage_Service_Glacier.svg
        shape: image
        label: "Amazon Simple Storage Service Glacier"
      }
  
  
  Amazon S on Outposts: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_S_on_Outposts.svg
        shape: image
        label: "Amazon S on Outposts"
      }
  
  
  AWS Backup: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Backup.svg
        shape: image
        label: "AWS Backup"
      }
  
  
  AWS Elastic Disaster Recovery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Elastic_Disaster_Recovery.svg
        shape: image
        label: "AWS Elastic Disaster Recovery"
      }
  
  
  AWS Snowball: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowball.svg
        shape: image
        label: "AWS Snowball"
      }
  
  
  AWS Snowball Edge: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowball_Edge.svg
        shape: image
        label: "AWS Snowball Edge"
      }
  
  
  AWS Snowcone: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowcone.svg
        shape: image
        label: "AWS Snowcone"
      }
  
  
  AWS Snowmobile: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowmobile.svg
        shape: image
        label: "AWS Snowmobile"
      }
  
  
  AWS Storage Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Storage_Gateway.svg
        shape: image
        label: "AWS Storage Gateway"
      }
  
}