classes: {
  
  Amazon_EFS: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_EFS.svg
        shape: image
        label: "Amazon_EFS"
      }
  
  Amazon_Elastic_Block_Store: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_Elastic_Block_Store.svg
        shape: image
        label: "Amazon_Elastic_Block_Store"
      }
  
  Amazon_File_Cache: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_File_Cache.svg
        shape: image
        label: "Amazon_File_Cache"
      }
  
  Amazon_FSx: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx.svg
        shape: image
        label: "Amazon_FSx"
      }
  
  Amazon_FSx_for_Lustre: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_Lustre.svg
        shape: image
        label: "Amazon_FSx_for_Lustre"
      }
  
  Amazon_FSx_for_NetApp_ONTAP: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_NetApp_ONTAP.svg
        shape: image
        label: "Amazon_FSx_for_NetApp_ONTAP"
      }
  
  Amazon_FSx_for_OpenZFS: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_OpenZFS.svg
        shape: image
        label: "Amazon_FSx_for_OpenZFS"
      }
  
  Amazon_FSx_for_WFS: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_FSx_for_WFS.svg
        shape: image
        label: "Amazon_FSx_for_WFS"
      }
  
  Amazon_Simple_Storage_Service: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_Simple_Storage_Service.svg
        shape: image
        label: "Amazon_Simple_Storage_Service"
      }
  
  Amazon_Simple_Storage_Service_Glacier: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_Simple_Storage_Service_Glacier.svg
        shape: image
        label: "Amazon_Simple_Storage_Service_Glacier"
      }
  
  Amazon_S_on_Outposts: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/Amazon_S_on_Outposts.svg
        shape: image
        label: "Amazon_S_on_Outposts"
      }
  
  AWS_Backup: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Backup.svg
        shape: image
        label: "AWS_Backup"
      }
  
  AWS_Elastic_Disaster_Recovery: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Elastic_Disaster_Recovery.svg
        shape: image
        label: "AWS_Elastic_Disaster_Recovery"
      }
  
  AWS_Snowball: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowball.svg
        shape: image
        label: "AWS_Snowball"
      }
  
  AWS_Snowball_Edge: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowball_Edge.svg
        shape: image
        label: "AWS_Snowball_Edge"
      }
  
  AWS_Snowcone: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowcone.svg
        shape: image
        label: "AWS_Snowcone"
      }
  
  AWS_Snowmobile: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Snowmobile.svg
        shape: image
        label: "AWS_Snowmobile"
      }
  
  AWS_Storage_Gateway: {
        icon: https://ppalka-lingaro.github.io/icons/AWS asset package/Architecture-Service-Icons/Storage/AWS_Storage_Gateway.svg
        shape: image
        label: "AWS_Storage_Gateway"
      }
  
}